import {pebble,cache,heap} from './storage.mjs';
export const engines={'pebble-engine':pebble,'cache-hotel':cache,'heap-garden':heap};
import {race,receipt,stack} from './computation.mjs';
Object.assign(engines,{'ledger-race':race,'receipt-route':receipt,'stack-kitchen':stack});
import {regex,parser} from './languages.mjs';
Object.assign(engines,{'pattern-tailor':regex,'bracket-workshop':parser});
import {types,proof} from './reasoning.mjs';
Object.assign(engines,{'type-loom':types,'proof-lantern':proof});
import {query,bst,rows} from './structures.mjs';
Object.assign(engines,{'table-confluence':query,'branch-librarian':bst,'row-orchestra':rows});
import {transducer,comparator,petri} from './networks.mjs';
Object.assign(engines,{'state-courier':transducer,'compare-parade':comparator,'token-crucible':petri});
import {lz,align,privacy,quant} from './information.mjs';
Object.assign(engines,{'copy-ribbon':lz,'parallel-manuscripts':align,'private-census':privacy,'tiny-soundbook':quant});
import {agenda,snapshot} from './collective.mjs';
Object.assign(engines,{'agenda-garden':agenda,'causal-camera':snapshot});
import {breed,debt,collector} from './living-systems.mjs';
Object.assign(engines,{'linked-orchard':breed,'clearing-circle':debt,'night-collector':collector});
import {bandit,transit} from './operating.mjs';
Object.assign(engines,{'gathering-grounds':bandit,'loop-transit':transit});
