(() => {
'use strict';
const $=id=>document.getElementById(id), id=new URLSearchParams(location.search).get('game')||'minefield';
const meta=LogicGames.find(g=>g.id===id)||LogicGames[0];
document.title=meta.name+' — Small Hours';$('title').textContent=meta.name+'.';$('mechanic').textContent=meta.mechanic;$('description').textContent=meta.description;$('controls').textContent=meta.controls;$('board').setAttribute('aria-label',meta.name+' puzzle cells');$('room-number').textContent=String(LogicGames.indexOf(meta)+1).padStart(2,'0');document.documentElement.style.setProperty('--accent',meta.accent);
meta.rules.forEach(rule=>{const li=document.createElement('li');li.textContent=rule;$('rules').append(li);});
const record=SmallHours.record('small-hours-logic-'+meta.id,true);
const shuffle=a=>SmallHours.shuffle([...a]), range=n=>Array.from({length:n},(_,i)=>i), clone=o=>JSON.parse(JSON.stringify(o));
let model, selected=1, moves=0, finished=false, history=[], engine;
function message(s){$('message').textContent=s;}
function win(text='Every condition fits. Nicely untangled.'){finished=true;record.save(Math.max(1,moves));$('result-title').textContent='A little clarity.';$('result-copy').textContent=`${text} ${moves} moves.`;$('result').hidden=false;message('Puzzle complete.');$('again').focus({preventScroll:true});}
function lose(text){finished=true;$('result-title').textContent='A new angle awaits.';$('result-copy').textContent=text;$('result').hidden=false;message(text);$('again').focus({preventScroll:true});}
function save(){history.push(clone(model));if(history.length>200)history.shift();moves++;}
function act(fn){if(finished)return;save();fn();render();}
function cell(text,index,fn,cls='',label){const b=document.createElement('button');b.className='cell '+cls;b.textContent=text;b.dataset.index=index;b.setAttribute('aria-label',label||(Number.isFinite(Number(index))?`Cell ${Number(index)+1}: ${text||'empty'}`:`Grid clue ${text||''}`));b.addEventListener('click',()=>{if(!finished)fn();});if(cls.includes('number')||cls.includes('gap')){b.tabIndex=-1;b.setAttribute('aria-disabled','true');}$('board').append(b);return b;}
function grid(n,cls=''){$('board').style.setProperty('--n',n);$('board').className='board '+cls;}
function palette(values){values.forEach(([value,label])=>{const b=document.createElement('button');b.textContent=label;b.dataset.value=value;b.setAttribute('aria-pressed',String(selected===value));b.addEventListener('click',()=>{selected=value;render();});$('palette').append(b);});}
function digits(n=4){palette([[0,'Erase'],...range(n).map(i=>[i+1,String(i+1)])]);}
function extraButton(text,fn){const b=document.createElement('button');b.textContent=text;b.addEventListener('click',()=>{if(!finished)fn();});$('extra').append(b);}
const row=(a,r,n)=>a.slice(r*n,r*n+n), col=(a,c,n)=>range(n).map(r=>a[r*n+c]);
const unique=a=>new Set(a).size===a.length, latin=a=>range(4).every(i=>unique(row(a,i,4))&&unique(col(a,i,4)))&&a.every(x=>x>=1&&x<=4);
const latinAnswer=()=>{const d=shuffle([1,2,3,4]);return [0,1,2,3,2,3,0,1,1,0,3,2,3,2,1,0].map(i=>d[i]);};
const orth=(i,n)=>[i-n,i+n,...(i%n?[i-1]:[]),...(i%n<n-1?[i+1]:[])].filter(j=>j>=0&&j<n*n);
const around=(i,n)=>range(n*n).filter(j=>j!==i&&Math.abs(j%n-i%n)<=1&&Math.abs(Math.floor(j/n)-Math.floor(i/n))<=1);
const engines={};
engines['ninefold']={init(){const answer=latinAnswer(),given=[0,3,5,6,9,10,12,15];return {answer,given,cells:answer.map((v,i)=>given.includes(i)?v:0)};},render(){digits();grid(4,'sudoku');model.cells.forEach((v,i)=>cell(v||'',i,()=>{if(model.given.includes(i)){message('This number is a fixed clue.');return;}act(()=>model.cells[i]=selected);},model.given.includes(i)?'fixed':''));},valid(){return latin(model.cells)&&[0,2,8,10].every(i=>unique([model.cells[i],model.cells[i+1],model.cells[i+4],model.cells[i+5]]));}};
engines['taller-tales']={init(){const answer=latinAnswer();return {answer,cells:answer.map((v,i)=>[0,7,10].includes(i)?v:0),given:[0,7,10],signs:range(16).filter(i=>i%4<3).map(i=>[i,answer[i]<answer[i+1]?'<':'>'])};},render(){digits();grid(4);model.cells.forEach((v,i)=>{const b=cell(v||'',i,()=>{if(model.given.includes(i)){message('A fixed clue stays put.');return;}act(()=>model.cells[i]=selected);},model.given.includes(i)?'fixed':'');const sign=model.signs.find(s=>s[0]===i);if(sign){const s=document.createElement('span');s.className='ineq';s.textContent=sign[1];s.setAttribute('aria-hidden','true');b.append(s);b.setAttribute('aria-label',`Cell ${i+1}, ${v||'empty'}, ${sign[1]==='<'?'less':'greater'} than next cell`);}});},valid(){return latin(model.cells)&&model.signs.every(([i,s])=>s==='<'?model.cells[i]<model.cells[i+1]:model.cells[i]>model.cells[i+1]);}};
const visible=a=>{let max=0,count=0;a.forEach(v=>{if(v>max){count++;max=v;}});return count;};
engines['sky-view']={init(){const answer=latinAnswer();return {answer,cells:Array(16).fill(0),left:range(4).map(r=>visible(row(answer,r,4))),right:range(4).map(r=>visible(row(answer,r,4).reverse())),top:range(4).map(c=>visible(col(answer,c,4))),bottom:range(4).map(c=>visible(col(answer,c,4).reverse()))};},render(){digits();grid(4);$('clues').textContent=`TOP ↓ ${model.top.join(' · ')} | BOTTOM ↑ ${model.bottom.join(' · ')}\nLEFT → ${model.left.join(' · ')} | RIGHT ← ${model.right.join(' · ')}`;$('clues').style.whiteSpace='pre-line';model.cells.forEach((v,i)=>cell(v||'',i,()=>act(()=>model.cells[i]=selected)));},valid(){return latin(model.cells)&&range(4).every(i=>visible(row(model.cells,i,4))===model.left[i]&&visible(row(model.cells,i,4).reverse())===model.right[i]&&visible(col(model.cells,i,4))===model.top[i]&&visible(col(model.cells,i,4).reverse())===model.bottom[i]);}};
engines['equal-measure']={init(){let answer=[0,0,1,1,0,1,0,1,1,0,1,0,1,1,0,0];if(Math.random()<.5)answer=answer.map(x=>1-x);const given=[0,3,6,9,12];return {answer,given,cells:answer.map((v,i)=>given.includes(i)?v:-1)};},render(){grid(4);model.cells.forEach((v,i)=>cell(v<0?'·':v?'☀':'☾',i,()=>{if(model.given.includes(i)){message('This symbol is a fixed clue.');return;}act(()=>model.cells[i]=(model.cells[i]+2)%3-1);},model.given.includes(i)?'fixed':v===1?'on':''));},valid(){if(model.cells.some(x=>x<0))return false;const lines=[...range(4).map(i=>row(model.cells,i,4)),...range(4).map(i=>col(model.cells,i,4))];return lines.every(a=>a.reduce((s,x)=>s+x,0)===2&&a.every((v,i)=>i<2||v!==a[i-1]||v!==a[i-2]))&&unique(lines.slice(0,4).map(a=>a.join('')))&&unique(lines.slice(4).map(a=>a.join('')));}};
const runs=a=>{let out=[],run=0;[...a,0].forEach(x=>{if(x)run++;else if(run){out.push(run);run=0;}});return out.length?out:[0];};
engines['picross-post']={init(){let answer=shuffle([[0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,0,0,1,0,0],[1,1,1,1,1,1,0,0,0,1,1,0,1,0,1,1,0,0,0,1,1,1,1,1,1],[0,0,1,0,0,0,1,1,1,0,1,1,1,1,1,0,0,1,0,0,0,0,1,0,0]])[0];if(Math.random()<.5)answer=answer.slice().reverse();return {answer,cells:Array(25).fill(0)};},render(){grid(6);cell('',-1,()=>{},'gap');range(5).forEach(c=>cell(runs(col(model.answer,c,5)).join('·'),'c'+c,()=>{},'number',`Column ${c+1} runs ${runs(col(model.answer,c,5))}`));range(5).forEach(r=>{cell(runs(row(model.answer,r,5)).join('·'),'r'+r,()=>{},'number',`Row ${r+1} runs ${runs(row(model.answer,r,5))}`);range(5).forEach(c=>{let i=r*5+c;cell(model.cells[i]===2?'×':'',i,()=>act(()=>model.cells[i]=(model.cells[i]+1)%3),model.cells[i]===1?'on':model.cells[i]===2?'marked':'',`Row ${r+1} column ${c+1}, ${model.cells[i]===1?'filled':model.cells[i]===2?'marked empty':'unmarked'}`);});});},valid(){return range(5).every(i=>JSON.stringify(runs(row(model.cells,i,5).map(v=>v===1)))===JSON.stringify(runs(row(model.answer,i,5)))&&JSON.stringify(runs(col(model.cells,i,5).map(v=>v===1)))===JSON.stringify(runs(col(model.answer,i,5))));}};
engines['minefield']={init(){return {mines:[],revealed:[],flags:[],started:false,mode:0};},render(){palette([[0,'Reveal'],[1,'Flag']]);grid(5);range(25).forEach(i=>{const open=model.revealed.includes(i),count=around(i,5).filter(j=>model.mines.includes(j)).length;cell(open?(model.mines.includes(i)?'✹':count||'·'):model.flags.includes(i)?'⚑':'',i,()=>{if(model.revealed.includes(i)){message('That square is already open.');return;}if(selected===1){act(()=>{if(model.flags.includes(i))model.flags=model.flags.filter(x=>x!==i);else model.flags.push(i);});return;}if(model.flags.includes(i)){message('Remove the flag before revealing this square.');return;}act(()=>{if(!model.started){model.mines=shuffle(range(25).filter(j=>j!==i&&!around(i,5).includes(j))).slice(0,4);model.started=true;}const visit=j=>{if(model.revealed.includes(j)||model.flags.includes(j))return;model.revealed.push(j);if(!model.mines.includes(j)&&!around(j,5).some(k=>model.mines.includes(k)))around(j,5).forEach(visit);};visit(i);if(model.mines.includes(i))lose('A mine was uncovered. Try another meadow; your first reveal is safe.');else if(model.revealed.length===21)win('Every safe square is open.');});},open?'fixed':model.flags.includes(i)?'on':'',`Row ${Math.floor(i/5)+1} column ${i%5+1}, ${open?count+' nearby mines':model.flags.includes(i)?'flagged':'covered'}`);});},valid(){return model.revealed.length===21&&!model.revealed.some(i=>model.mines.includes(i));}};
engines['code-cabinet']={init(){return {answer:range(3).map(()=>1+Math.floor(Math.random()*6)),guess:[1,1,1],guesses:[]};},render(){grid(3);model.guess.forEach((v,i)=>cell(String(v),i,()=>act(()=>model.guess[i]=v%6+1),'',`Code position ${i+1}: ${v}. Activate to cycle one through six.`));$('clues').textContent='Tap each code symbol to cycle 1–6. Submit with Check puzzle.';model.guesses.forEach(g=>{const d=document.createElement('div');d.className='feedback';d.textContent=g.values.join(' ')+'   '+('●'.repeat(g.exact))+('○'.repeat(g.near))+'  '+(g.exact+g.near===0?'—':'');d.setAttribute('aria-label',`${g.values.join(', ')}: ${g.exact} exact, ${g.near} misplaced`);$('extra').append(d);});},valid(){const values=[...model.guess],exact=values.filter((v,i)=>v===model.answer[i]).length;let pool=model.answer.filter((v,i)=>v!==values[i]),near=0;values.forEach((v,i)=>{if(v!==model.answer[i]&&pool.includes(v)){near++;pool.splice(pool.indexOf(v),1);}});model.guesses.push({values,exact,near});history=[];moves++;if(exact===3)return true;if(model.guesses.length>=8)lose('The lock rests for now. The code was '+model.answer.join(' · ')+'.');else message(`${exact} exact, ${near} misplaced. ${8-model.guesses.length} guesses remain.`);return false;}};
const permutations=a=>a.length?a.flatMap((v,i)=>permutations(a.filter((_,j)=>i!==j)).map(t=>[v,...t])):[[]];
function seatingFits(a,clues){return clues.every(c=>{const x=a.indexOf(c.a),y=a.indexOf(c.b);return c.type==='center'?x===2:c.type==='inside'?x>0&&x<4:c.type==='left'?x<y:c.type==='apart'?Math.abs(x-y)===2:Math.abs(x-y)===1;});}
engines['seat-at-table']={init(){const answer=shuffle(['Ada','Bo','Cy','Dee','Eli']),candidates=[{type:'center',a:answer[2]},...answer.slice(1,4).map(a=>({type:'inside',a}))];for(let i=0;i<5;i++)for(let j=i+1;j<5;j++){candidates.push({type:'left',a:answer[i],b:answer[j]});if(j-i===2)candidates.push({type:'apart',a:answer[i],b:answer[j]});if(j-i===1)candidates.push({type:'next',a:answer[i],b:answer[j]});}let options=permutations(answer),clues=[];for(const clue of shuffle(candidates)){const next=options.filter(a=>seatingFits(a,[clue]));if(next.length<options.length){clues.push(clue);options=next;}if(options.length===1)break;}return {answer,clues,cells:Array(5).fill('')};},render(){palette(['Ada','Bo','Cy','Dee','Eli'].map(x=>[x,x]));grid(5);const list=document.createElement('ul');model.clues.forEach(c=>{const li=document.createElement('li');li.textContent=c.type==='center'?`${c.a} takes the middle seat.`:c.type==='inside'?`${c.a} is not at either end.`:c.type==='left'?`${c.a} sits somewhere left of ${c.b}.`:c.type==='apart'?`Exactly one person sits between ${c.a} and ${c.b}.`:`${c.a} and ${c.b} sit next to each other.`;list.append(li);});$('clues').append(list);model.cells.forEach((v,i)=>cell(v||i+1,i,()=>{if(typeof selected!=='string'){message('Choose a guest first.');return;}act(()=>{const old=model.cells.indexOf(selected);if(old>=0)model.cells[old]=model.cells[i];model.cells[i]=selected;});},v?'on':''));},valid(){return model.cells.every(v=>['Ada','Bo','Cy','Dee','Eli'].includes(v))&&unique(model.cells)&&seatingFits(model.cells,model.clues);}};
engines['cross-sums']={init(){const digits=shuffle(range(9).map(x=>x+1)),answer=digits;return {answer,cells:Array(9).fill(0),rows:range(3).map(r=>row(answer,r,3).reduce((a,b)=>a+b,0)),cols:range(3).map(c=>col(answer,c,3).reduce((a,b)=>a+b,0))};},render(){digits(9);grid(4);cell('Σ',-1,()=>{},'number');model.cols.forEach((v,i)=>cell(v,'c'+i,()=>{},'number',`Column ${i+1} sum ${v}`));range(3).forEach(r=>{cell(model.rows[r],'r'+r,()=>{},'number',`Row ${r+1} sum ${model.rows[r]}`);range(3).forEach(c=>{const i=r*3+c;cell(model.cells[i]||'',i,()=>act(()=>model.cells[i]=selected));});});},valid(){return model.cells.every(v=>v>=1&&v<=9)&&range(3).every(i=>unique(row(model.cells,i,3))&&unique(col(model.cells,i,3))&&row(model.cells,i,3).reduce((a,b)=>a+b,0)===model.rows[i]&&col(model.cells,i,3).reduce((a,b)=>a+b,0)===model.cols[i]);}};
function connected(nodes,edges){if(!nodes.length)return false;const seen=new Set([nodes[0]]);let changed=true;while(changed){changed=false;edges.forEach(([a,b])=>{if(seen.has(a)&&!seen.has(b)){seen.add(b);changed=true;}if(seen.has(b)&&!seen.has(a)){seen.add(a);changed=true;}});}return nodes.every(n=>seen.has(n));}
engines['bridgewater']={init(){const edges=[];range(9).forEach(i=>{if(i%3<2)edges.push([i,i+1]);if(i<6)edges.push([i,i+3]);});const answer=Array(edges.length).fill(0),seen=new Set([0]);shuffle(range(edges.length)).forEach(()=>{});while(seen.size<9){const options=range(edges.length).filter(k=>seen.has(edges[k][0])!==seen.has(edges[k][1])),k=shuffle(options)[0];answer[k]=1+(Math.random()<.3?1:0);edges[k].forEach(n=>seen.add(n));}return {edges,answer,cells:Array(edges.length).fill(0),totals:range(9).map(i=>edges.reduce((s,e,k)=>s+(e.includes(i)?answer[k]:0),0))};},render(){grid(5);range(25).forEach(p=>{const r=Math.floor(p/5),c=p%5;if(r%2===0&&c%2===0){const island=r/2*3+c/2;cell(model.totals[island],'i'+island,()=>message('Tap the spaces between islands to build bridges.'),'number',`Island ${island+1} requires ${model.totals[island]} bridges`);}else if(r%2&&c%2)cell('','gap'+p,()=>{},'gap');else{const a=r%2?(r-1)/2*3+c/2:r/2*3+(c-1)/2,b=r%2?a+3:a+1,k=model.edges.findIndex(e=>e[0]===a&&e[1]===b),v=model.cells[k];cell(v?(r%2?(v===1?'│':'║'):(v===1?'─':'═')):'·',k,()=>act(()=>model.cells[k]=(v+1)%3),'edge '+(v?'on':''),`Bridge islands ${a+1} and ${b+1}: ${v}`);}});},valid(){return model.totals.every((v,i)=>model.edges.reduce((s,e,k)=>s+(e.includes(i)?model.cells[k]:0),0)===v)&&connected(range(9),model.edges.filter((_,k)=>model.cells[k]>0));}};
function loopEdges(){const out=[];range(4).forEach(r=>range(3).forEach(c=>out.push([r*4+c,r*4+c+1])));range(3).forEach(r=>range(4).forEach(c=>out.push([r*4+c,(r+1)*4+c])));return out;}
function surrounds(r,c,edges){const verts=[r*4+c,r*4+c+1,(r+1)*4+c,(r+1)*4+c+1];return edges.map((e,k)=>verts.includes(e[0])&&verts.includes(e[1])?k:-1).filter(k=>k>=0);}
engines['loop-letter']={init(){const edges=loopEdges(),inside=shuffle([[0,1,2,3,4,5,6,7,8],[0,1,3,4,6,7],[0,1,2,3,4,6,7]])[0],answer=Array(24).fill(0);inside.forEach(i=>surrounds(Math.floor(i/3),i%3,edges).forEach(k=>answer[k]=1-answer[k]));return {edges,answer,cells:Array(24).fill(0),clues:range(9).map(i=>surrounds(Math.floor(i/3),i%3,edges).reduce((s,k)=>s+answer[k],0))};},render(){grid(7,'loop');range(49).forEach(p=>{const r=Math.floor(p/7),c=p%7;if(!(r%2)&&!(c%2))cell('·','v'+p,()=>{},'number');else if(r%2&&c%2)cell(model.clues[(r-1)/2*3+(c-1)/2],'n'+p,()=>{},'number');else{const a=r%2?(r-1)/2*4+c/2:r/2*4+(c-1)/2,b=r%2?a+4:a+1,k=model.edges.findIndex(e=>e[0]===a&&e[1]===b);cell(model.cells[k]?(r%2?'┃':'━'):'·',k,()=>act(()=>model.cells[k]=1-model.cells[k]),'edge '+(model.cells[k]?'on':''),`Edge ${k+1}, ${model.cells[k]?'drawn':'empty'}`);}});},valid(){if(!model.clues.every((v,i)=>surrounds(Math.floor(i/3),i%3,model.edges).reduce((s,k)=>s+model.cells[k],0)===v))return false;const edges=model.edges.filter((_,k)=>model.cells[k]),nodes=[...new Set(edges.flat())];return nodes.length>0&&nodes.every(n=>edges.filter(e=>e.includes(n)).length===2)&&connected(nodes,edges);}};
engines['tent-pitch']={init(){let trees=[0,7,10,21],answer=[1,8,15,22];if(Math.random()<.5){trees=trees.map(i=>24-i);answer=answer.map(i=>24-i);}return {trees,answer,cells:[],rows:range(5).map(r=>answer.filter(i=>Math.floor(i/5)===r).length),cols:range(5).map(c=>answer.filter(i=>i%5===c).length)};},render(){grid(6);cell('',-1,()=>{},'gap');model.cols.forEach((v,c)=>cell(v,'c'+c,()=>{},'number',`Column ${c+1} needs ${v} tents`));range(5).forEach(r=>{cell(model.rows[r],'r'+r,()=>{},'number',`Row ${r+1} needs ${model.rows[r]} tents`);range(5).forEach(c=>{const i=r*5+c,tree=model.trees.includes(i),tent=model.cells.includes(i);cell(tree?'♠':tent?'△':'',i,()=>{if(tree){message('Trees stay rooted. Place a tent beside one.');return;}act(()=>{model.cells=tent?model.cells.filter(x=>x!==i):[...model.cells,i];});},tree?'tree':tent?'on':'',`Row ${r+1} column ${c+1}, ${tree?'tree':tent?'tent':'grass'}`);});});},valid(){const tents=model.cells;if(tents.length!==model.trees.length||tents.some(i=>around(i,5).some(j=>tents.includes(j))))return false;if(!range(5).every(i=>tents.filter(j=>Math.floor(j/5)===i).length===model.rows[i]&&tents.filter(j=>j%5===i).length===model.cols[i]))return false;function match(k,used){if(k===tents.length)return true;return model.trees.some(t=>!used.includes(t)&&orth(t,5).includes(tents[k])&&match(k+1,[...used,t]));}return match(0,[]);}};
engines['pearl-route']={init(){let answer=[[0,1,2,3,4,9],[5,10,15,20,21],[6,7,8,13,18,23,24],[11,12,17,16]];if(Math.random()<.5)answer=answer.map(a=>a.map(i=>24-i));return {answer,ends:answer.map(a=>[a[0],a[a.length-1]]),paths:answer.map(a=>[a[0]])};},render(){palette(range(4).map(i=>[i+1,String.fromCharCode(65+i)]));grid(5);range(25).forEach(i=>{const endpoint=model.ends.findIndex(a=>a.includes(i)),path=model.paths.findIndex(a=>a.includes(i));cell(endpoint>=0?String.fromCharCode(65+endpoint):path>=0?String.fromCharCode(97+path):'',i,()=>{const k=selected-1;if(k<0||k>3)return;const current=model.paths[k],ends=model.ends[k];if(i===ends[0]){act(()=>model.paths[k]=[i]);return;}if(current[current.length-1]===ends[1]){message('This pair is joined. Clear its path to reroute.');return;}if(!orth(current[current.length-1],5).includes(i)||model.paths.some(a=>a.includes(i))||(endpoint>=0&&endpoint!==k)){message('Extend the selected path into a free neighboring square.');return;}act(()=>model.paths[k].push(i));},path>=0?'on':endpoint>=0?'fixed':'',`Cell ${i+1}${endpoint>=0?', endpoint '+String.fromCharCode(65+endpoint):path>=0?', path '+String.fromCharCode(65+path):', empty'}`);});extraButton('Clear selected path',()=>act(()=>model.paths[selected-1]=[model.ends[selected-1][0]]));},valid(){return model.paths.every((p,k)=>p[p.length-1]===model.ends[k][1]);}};
const rotate=v=>((v<<1)&15)|((v>>3)&1);
const pipeGlyph={1:'╵',2:'╶',3:'└',4:'╷',5:'│',6:'┌',7:'├',8:'╴',9:'┘',10:'─',11:'┴',12:'┐',13:'┤',14:'┬',15:'┼'};
engines['tile-weave']={init(){const path=[0,1,2,5,4,3,6,7,8],answer=Array(9).fill(0);for(let j=1;j<path.length;j++){const a=path[j-1],b=path[j],d=b-a;answer[a]|=d===1?2:d===-1?8:d===3?4:1;answer[b]|=d===1?8:d===-1?2:d===3?1:4;}let cells=answer.map(v=>{for(let k=Math.floor(Math.random()*4);k>0;k--)v=rotate(v);return v;});return {answer,cells};},render(){grid(3);model.cells.forEach((v,i)=>cell(pipeGlyph[v],i,()=>act(()=>model.cells[i]=rotate(v)),'pipe',`Pipe ${i+1}, connected directions ${[v&1?'north':'',v&2?'east':'',v&4?'south':'',v&8?'west':''].filter(Boolean).join(', ')}. Activate to rotate.`));},valid(){const edges=[];for(let i=0;i<9;i++){const v=model.cells[i];for(const [bit,delta,opposite] of [[1,-3,4],[2,1,8],[4,3,1],[8,-1,2]]){if(!(v&bit))continue;const j=i+delta;if(j<0||j>=9||((bit===2||bit===8)&&Math.floor(j/3)!==Math.floor(i/3))||!(model.cells[j]&opposite))return false;edges.push([i,j]);}}return connected(range(9),edges);}};
function occupied(cars){const out=Array(36).fill(-1);cars.forEach((car,k)=>range(car.len).forEach(j=>out[car.pos+j*(car.dir==='h'?1:6)]=k));return out;}
function slide(delta){const k=model.active,car=model.cars[k];if(!car)return;const step=car.dir==='h'?1:6,next=car.pos+delta*step,occ=occupied(model.cars);if(next<0||next>=36||(car.dir==='h'&&(Math.floor(next/6)!==Math.floor(car.pos/6)||next%6+car.len>6))||(car.dir==='v'&&Math.floor(next/6)+car.len>6)||range(car.len).some(j=>occ[next+j*step]!==-1&&occ[next+j*step]!==k)){message('That lane is blocked. Move a different car first.');return;}act(()=>{car.pos=next;if(model.cars[0].pos===16)win('The red car has a clear way home.');});}
engines['safe-passage']={init(){return {cars:[{pos:12,len:2,dir:'h'},{pos:2,len:3,dir:'v'},{pos:20,len:2,dir:'h'},{pos:Math.random()<.5?28:29,len:2,dir:'v'}],active:0};},render(){grid(6);const occ=occupied(model.cars);occ.forEach((k,i)=>cell(k<0?'':k===0?'R':String.fromCharCode(65+k),i,()=>{if(k<0){message('Choose a car, then a direction.');return;}model.active=k;render();},k<0?'':`car ${k===0?'red':''} ${model.active===k?'selected':''}`,`Row ${Math.floor(i/6)+1}, column ${i%6+1}, ${k<0?'empty':k===0?'red car':'car '+String.fromCharCode(65+k)}`));const car=model.cars[model.active];$('clues').textContent=`Selected: ${model.active===0?'red car':String.fromCharCode(65+model.active)}. Exit is at the right of row 3.`;extraButton(car.dir==='h'?'← Left':'↑ Up',()=>slide(-1));extraButton(car.dir==='h'?'Right →':'Down ↓',()=>slide(1));},valid(){return model.cars[0].pos===16;}};
function render(){const active=document.activeElement?.dataset?.index,activeValue=document.activeElement?.closest('#palette')?document.activeElement.dataset.value:undefined,activeExtra=document.activeElement?.closest('#extra')?document.activeElement.textContent:undefined;$('board').replaceChildren();$('palette').replaceChildren();$('extra').replaceChildren();$('clues').textContent='';engine.render();$('moves').textContent=moves;$('undo').disabled=finished||!history.length;$('check').disabled=finished;if(active!==undefined){const b=[...$('board').children].find(b=>b.dataset.index===active);if(b)b.focus({preventScroll:true});}else if(activeValue!==undefined){[...$('palette').children].find(b=>b.dataset.value===activeValue)?.focus({preventScroll:true});}else if(activeExtra!==undefined){[...$('extra').children].find(b=>b.textContent===activeExtra)?.focus({preventScroll:true});}}
function restart(){engine=engines[meta.id];model=engine.init();selected=meta.id==='minefield'?0:meta.id==='seat-at-table'?'Ada':1;moves=0;finished=false;history=[];$('result').hidden=true;message('A small puzzle. All the time you need.');render();document.body.dataset.gameId=meta.id;document.body.dataset.gameReady='true';}
$('restart').addEventListener('click',restart);$('again').addEventListener('click',restart);
$('undo').addEventListener('click',()=>{if(finished||!history.length)return;model=history.pop();moves=Math.max(0,moves-1);render();message('Last move undone.');});
$('check').addEventListener('click',()=>{if(finished)return;if(engine.valid())win();else if(!finished&&meta.id!=='code-cabinet')message('Not quite yet. Revisit the clues and try another angle.');render();});
$('board').addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||!e.key.startsWith('Arrow'))return;e.preventDefault();if(finished)return;if(meta.id==='safe-passage'){const car=model.cars[model.active];if((car.dir==='h'&&['ArrowLeft','ArrowRight'].includes(e.key))||(car.dir==='v'&&['ArrowUp','ArrowDown'].includes(e.key)))slide(['ArrowLeft','ArrowUp'].includes(e.key)?-1:1);return;}const cells=[...$('board').children],current=cells.indexOf(document.activeElement),n=Number($('board').style.getPropertyValue('--n')),offset={ArrowLeft:-1,ArrowRight:1,ArrowUp:-n,ArrowDown:n}[e.key];let target=current+offset;while(target>=0&&target<cells.length){if(Math.abs(offset)===1&&Math.floor(target/n)!==Math.floor(current/n))break;const next=cells[target];if(!next.classList.contains('gap')&&!next.classList.contains('number')){next.focus();break;}target+=offset;}});
restart();
})();
