import {range,rng,shuffle,pick,base,win,lose} from './core.mjs';
export const councilLines=[];for(let y=0;y<6;y++)for(let x=0;x<6;x++)for(const[dy,dx]of[[0,1],[1,0],[1,1],[1,-1]]){const line=range(5).map(k=>[(y+k*dy),(x+k*dx)]);if(line.every(([r,c])=>r>=0&&r<6&&c>=0&&c<6))councilLines.push(line.map(([r,c])=>r*6+c));}
export function rotateQuadrant(board,q,direction){const b=[...board],ox=(q%2)*3,oy=Math.floor(q/2)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++){const nx=direction>0?2-y:y,ny=direction>0?x:2-x;b[(oy+ny)*6+ox+nx]=board[(oy+y)*6+ox+x];}return b;}
export const councilWinner=(board,who)=>councilLines.some(line=>line.every(i=>board[i]===who));
export function councilMoves(board,who){const moves=[];for(let i=0;i<36;i++)if(!board[i])for(let q=0;q<4;q++)for(const d of [-1,1]){const b=[...board];b[i]=who;moves.push({i,q,d,board:rotateQuadrant(b,q,d)});}return moves;}
function evaluate(board,who){let score=0;for(const line of councilLines){const own=line.filter(i=>board[i]===who).length,other=line.filter(i=>board[i]===-who).length;if(!other)score+=[0,1,5,25,220,100000][own];if(!own)score-=[0,2,8,40,600,200000][other];}return score;}
export function houseMove(board){const moves=councilMoves(board,-1);return moves.sort((a,b)=>{const av=councilWinner(a.board,-1)&&!councilWinner(a.board,1)?1e9:evaluate(a.board,-1),bv=councilWinner(b.board,-1)&&!councilWinner(b.board,1)?1e9:evaluate(b.board,-1);return bv-av||a.i-b.i||a.q-b.q||a.d-b.d})[0];}
function councilInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):2;for(let trial=0;trial<1000;trial++){const line=mode==='finite'?[[0,1,2,3,4],[1,2,3,4,5],[2,8,14,20,26]][d]:pick(councilLines,r),missing=mode==='finite'?[4,1,2][d]:pick(line,r),quarter=mode==='finite'?d%4:Math.floor(r()*4),direction=r()<.5?-1:1;let board=range(36).map(()=>0);for(const i of line)if(i!==missing)board[i]=1;if(line.filter(i=>i!==missing&&Math.floor(i/6/3)*2+Math.floor(i%6/3)===quarter).length<2)continue;board=rotateQuadrant(board,quarter,-direction);if(councilLines.some(line=>line.filter(i=>board[i]===1).length>=4))continue;const marker=range(36).map(i=>i===missing?2:0),reserved=rotateQuadrant(marker,quarter,-direction).indexOf(2),opponents=shuffle(range(36).filter(i=>board[i]===0&&i!==reserved),r).slice(0,4);opponents.forEach(i=>board[i]=-1);if(councilWinner(board,-1))continue;/* The constructed target is discarded; tests recover their own turn witness. */return base({board,phase:'place',turns:0,last:null,note:'Tactical duel from the displayed balanced4-versus4 opening. Place one stone, then rotate ANY3×3 quadrant90°; both colors move with it. A sole line of five AFTER rotation wins. House then makes a complete placement+rotation turn.'});}throw Error('Could not create nonterminal tactical opening');}
function settle(s,house=false){const player=councilWinner(s.board,1),opponent=councilWinner(s.board,-1);if(player&&opponent){lose(s,'Both colors have five: this duel is a draw; the campaign needs a sole winning line.');return true}if(player){win(s,'Your placement-plus-rotation creates the sole five-stone line.');s.score+=Math.max(0,200-s.turns*10);return true}if(opponent){lose(s,'The house formed the sole five-stone line after a complete turn.');return true}if(s.board.every(Boolean)){lose(s,'The full board is a draw; reset to seek a sole winning line.');return true}return false;}
const council={stages:3,init:councilInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('place:')&&s.phase==='place'){const i=+a.split(':')[1];if(s.board[i])return;s.board[i]=1;s.phase='rotate';s.edits++;s.note='Placement made. Rotate one quadrant; alignment is evaluated only after the required rotation.';}else if(a.startsWith('rotate:')&&s.phase==='rotate'){const[,q,d]=a.split(':').map(Number);s.board=rotateQuadrant(s.board,q,d);s.turns++;s.edits++;if(settle(s))return;const m=houseMove(s.board);if(!m){lose(s,'No house placement remains; draw.');return}s.board=m.board;s.last={i:m.i,q:m.q,d:m.d};if(settle(s,true))return;s.phase='place';s.note=`House placed at row${Math.floor(m.i/6)+1}, column${m.i%6+1}, then turned quadrant ${m.q+1} ${m.d>0?'clockwise':'counterclockwise'}. Your complete turn next.`;}},render(ui,s){ui.p(`Turn ${s.turns+1} · ${s.phase==='place'?'place your stone':'mandatory quadrant rotation'}. You● / house○. Quadrants1(top left),2(top right),3(bottom left),4(bottom right). Each study begins from a seeded balanced tactical opening.`);ui.grid(6,'Six by six rotating-quadrant council board');s.board.forEach((v,i)=>{const b=ui.button('place:'+i,v===1?'●':v===-1?'○':'·',s.phase!=='place'||v!==0);b.setAttribute('aria-label',`Row${Math.floor(i/6)+1} column${i%6+1}: ${v===1?'your stone':v===-1?'house stone':'empty'}`);b.style.borderRight=i%6===2?'3px solid #a6864e':'';b.style.borderBottom=Math.floor(i/6)===2?'3px solid #a6864e':'';});ui.grid(2,'Turn one entire quadrant',{compact:true});range(4).forEach(q=>{ui.button(`rotate:${q}:-1`,`Quadrant ${q+1} ↺`,s.phase!=='rotate');ui.button(`rotate:${q}:1`,`Quadrant ${q+1} ↻`,s.phase!=='rotate')});ui.p('House policy: take an immediate sole five if possible; otherwise maximize its printed-board line opportunities while heavily penalizing your open four-stone threats. Ties use lower placement, quadrant, then counterclockwise.');}};
export const councilEngines={'turning-council':council};
