import {range,sum,letter,rng,shuffle,pick,base,win,lose,audit,graph,integer,certify} from './core.mjs';

const gametes=g=>g===0?[0]:g===2?[1]:[0,1];
export function inheritancePossible(a,b,c){return gametes(a).some(x=>gametes(b).some(y=>x+y===c))}
function heritageInit({stage,seed,mode}){
 const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(stage,2);
 if(d===0)return base({n:3,parents:[null,null,[0,1]],traits:[true,true,false],known:{},values:[-1,-1,-1],note:'The recessive child has aa. Each dominant-trait parent must transmit one a allele; infer their two-copy genotypes.'});
 const n=d===1?6:8;
 for(let trial=0;trial<2000;trial++){
  const parents=range(n).map(()=>null);parents[2]=[0,1];parents[3]=[0,1];parents[5]=[2,4];if(d===2){parents[6]=[3,4];parents[7]=[5,6];}
  if(mode==='endless')for(let i=3;i<n;i++)if(r()<.55)parents[i]=shuffle(range(i),r).slice(0,2);
  const hidden=[];for(let i=0;i<n;i++)hidden.push(parents[i]?pick(gametes(hidden[parents[i][0]]),r)+pick(gametes(hidden[parents[i][1]]),r):Math.floor(r()*3));
  const known=Object.fromEntries(shuffle(range(n),r).slice(0,2).map(i=>[i,hidden[i]]));
  // A recessive descendant with two visibly dominant unknown parents ensures
  // each generated family contains actual carrier deduction, not all-aa/all-AA filling.
  if(!parents.some((p,i)=>p&&hidden[i]===0&&hidden[p[0]]>0&&hidden[p[1]]>0&&known[p[0]]===undefined&&known[p[1]]===undefined))continue;
  return base({n,parents,traits:hidden.map(v=>v>0),known,values:range(n).map(i=>known[i]??-1),note:'Every child inherits one copy from each listed parent. Dominant trait means AA or Aa; recessive means aa. Known genotype clues are fixed; any globally compatible inference is accepted.'});
 }
 throw Error('Could not construct an evidence-bearing family');
}
export function heritageError(s){if(s.values.some(v=>v<0))return 'Infer every unknown genotype.';for(let i=0;i<s.n;i++){if((s.values[i]>0)!==s.traits[i])return `Person ${i+1} has the wrong visible trait.`;if(s.known[i]!==undefined&&s.values[i]!==s.known[i])return 'A known genotype was changed.';if(s.parents[i]&&!inheritancePossible(s.values[s.parents[i][0]],s.values[s.parents[i][1]],s.values[i]))return `Person ${i+1} cannot inherit that genotype from the two assigned parents.`;}return null;}
const heritage={stages:3,init:heritageInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('person:')){const i=+a.split(':')[1];if(s.known[i]!==undefined)return;s.values[i]=(s.values[i]+2)%4-1;s.edits++;}else if(a==='check')audit(s,heritageError(s),'Every fixed family transmission and visible trait agrees.');},render(ui,s){ui.p('A is dominant; a is recessive. AA transmits A, aa transmits a, Aa can transmit either. Infer this fictional family’s single inherited trait.');graph(ui,'pedigree',range(s.n),s.parents.flatMap((p,i)=>p?p.map(v=>[v,i]):[]),{labels:range(s.n).map(i=>String(i+1)),marks:s.values.map(v=>v<0?'?':['aa','Aa','AA'][v]),directed:true});ui.table(['Person','Parents','Visible trait','Known genotype'],range(s.n).map(i=>[i+1,s.parents[i]?.map(v=>v+1).join(' + ')||'founder',s.traits[i]?'dominant':'recessive',s.known[i]===undefined?'infer':['aa','Aa','AA'][s.known[i]]]));ui.grid(3,'Cycle unknown family genotypes',{compact:true});s.values.forEach((v,i)=>ui.button('person:'+i,`Person ${i+1}: ${v<0?'?':['aa','Aa','AA'][v]}`,s.known[i]!==undefined));certify(ui,'Certify all transmissions');}};

export function posterior(prior,likelihood,positive){const weights=prior.map((v,i)=>v*(positive?likelihood[i]:1-likelihood[i])),total=sum(weights);return weights.map(v=>v/total)}
export function responseRisk(s,action){return sum(s.belief.map((v,i)=>v*s.losses[action][i]))+s.paid;}
function posteriorInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):2;for(let trial=0;trial<2000;trial++){const weights=range(3).map(()=>1+Math.floor(r()*4)),prior=weights.map(v=>v/sum(weights)),losses=range(3).map(a=>range(3).map(i=>a===i?0:4+Math.floor(r()*(d===2?17:7)))),probes=range(3+d%2).map(i=>({name:'Probe'+(i+1),cost:.08+Math.floor(r()*4)*.04,likelihood:shuffle([.12+.04*Math.floor(r()*3),.45+.05*Math.floor(r()*3),.82+.03*Math.floor(r()*3)],r),result:r()<.5}));let b=posterior(prior,probes[0].likelihood,probes[0].result);b=posterior(b,probes[1].likelihood,probes[1].result);const risks=losses.map(row=>sum(row.map((v,i)=>v*b[i]))),bestResponse=risks.indexOf(Math.min(...risks)),mostProbable=b.indexOf(Math.max(...b));if(d===2&&bestResponse===mostProbable)continue;const paid=probes[0].cost+probes[1].cost,ceiling=Math.min(...risks)+paid+.12,initial=Math.min(...losses.map(row=>sum(row.map((v,i)=>v*prior[i]))));if(ceiling>=initial-.2)continue;return base({prior,belief:[...prior],losses,probes,used:[],paid:0,ceiling,budget:d===0?.48:d===1?.52:.44,history:[],note:'Probe outcomes are sealed until purchased. All likelihoods are strictly positive, so no class is eliminated. Stop with a response whose posterior expected loss PLUS paid probe costs meets the contract.'});}throw Error('Could not construct a feasible expected-loss contract');}
const bayes={stages:3,undo:false,init:posteriorInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('probe:')){const i=+a.split(':')[1],p=s.probes[i];if(s.used.includes(i))return;if(s.paid+p.cost>s.budget+1e-9){lose(s,'Investigation cost exceeds the printed budget.');return}s.used.push(i);s.paid+=p.cost;s.belief=posterior(s.belief,p.likelihood,p.result);s.history.push(`${p.name}: ${p.result?'positive':'negative'}; paid${p.cost.toFixed(2)}`);s.edits++;s.note='Weights multiplied by the displayed result likelihood and renormalized. Every class still has positive probability.';}else if(a.startsWith('respond:')){const i=+a.split(':')[1],risk=responseRisk(s,i);if(risk>s.ceiling+1e-9)lose(s,`Response ${i+1} expected loss plus paid costs = ${risk.toFixed(3)}, above contract${s.ceiling.toFixed(3)}.`);else{win(s,`Response ${i+1} stopped at total expected loss${risk.toFixed(3)}≤${s.ceiling.toFixed(3)}.`);s.score+=Math.round((s.ceiling-risk)*1000);}}},render(ui,s){ui.p(`Contract: expected response loss + paid probe costs ≤${s.ceiling.toFixed(3)}. Paid${s.paid.toFixed(2)}; investigation budget ${s.budget.toFixed(2)}. Scoring uses these printed model probabilities and expected losses.`);ui.table(['Class','Prior','Current posterior'],range(3).map(i=>['Class'+(i+1),s.prior[i].toFixed(4),s.belief[i].toFixed(4)]));ui.table(['Probe','Cost',...range(3).map(i=>'P(positive|class'+(i+1)+')')],s.probes.map(p=>[p.name,p.cost.toFixed(2),...p.likelihood.map(v=>v.toFixed(2))]));ui.p('A negative result uses1−P(positive|class). The probes are conditionally independent in this puzzle model.');ui.group('Purchase a previously unused observation');s.probes.forEach((p,i)=>ui.button('probe:'+i,'Buy '+p.name,s.used.includes(i)));ui.table(['Response',...range(3).map(i=>'Loss if class'+(i+1)),'Current expected loss + paid'],s.losses.map((row,a)=>['Response'+(a+1),...row,responseRisk(s,a).toFixed(3)]));ui.group('Stop investigating and commit response');range(3).forEach(i=>ui.button('respond:'+i,'Stop with response'+(i+1)));ui.p('Observed transcript: '+(s.history.join(' · ')||'no purchases yet'));}};

export function lieSuccessor(s,question,answer){return s.discrepancies.map((v,i)=>Math.min(2,v+Number(s.codes[i][question]!==answer)))}
export function adversarialAnswer(s,question){const possibilities=[0,1].map(answer=>{const next=lieSuccessor(s,question,answer),live=next.filter(v=>v<=1).length,unused=next.filter(v=>v===0).length;return{answer,next,live,unused}}).filter(v=>v.live>0);return possibilities.sort((a,b)=>b.live-a.live||b.unused-a.unused||a.answer-b.answer)[0];}
function lieInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):2,cols=mode==='endless'?4+stage%2:2+d,n=4+d*2,codes=shuffle(range(1<<cols),r).slice(0,n).map(mask=>range(cols).map(i=>(mask>>i)&1));return base({n,cols,codes,discrepancies:range(n).map(()=>0),budget:cols*3,history:[],note:'The archive answers adversarially, but the entire transcript must remain compatible with some fixed object and at most ONE lie. Track each object’s disagreements. Repeating a question is legal.'});}
const lie={stages:3,init:lieInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('ask:')){if(s.edits>=s.budget){lose(s,'No questions remain; certainty was not established.');return}const q=+a.split(':')[1],chosen=adversarialAnswer(s,q);s.discrepancies=chosen.next;s.history.push({q,answer:chosen.answer});s.edits++;s.note=`Property ${q+1}: ${chosen.answer?'yes':'no'}. All remaining objects disagree with at most one answer;${s.budget-s.edits} questions remain.`;}else if(a.startsWith('identify:')){const i=+a.split(':')[1],live=range(s.n).filter(v=>s.discrepancies[v]<=1);if(live.length!==1||live[0]!==i)lose(s,`The transcript still permits ${live.map(v=>'object'+(v+1)).join(', ')}. Identification needs one globally consistent object.`);else win(s,'One object survives every at-most-one-lie explanation of the complete transcript.');}},render(ui,s){ui.p(`Questions ${s.edits}/${s.budget}. Disagreements0: lie unused;1: lie already used;2: incompatible. The answerer chooses a globally compatible answer preserving as many candidates as possible; ties preserve unused-lie candidates, then answer no.`);ui.table(['Object',...range(s.cols).map(i=>'Property'+(i+1)),'Disagreements'],s.codes.map((row,i)=>['Object'+(i+1),...row.map(v=>v?'yes':'no'),s.discrepancies[i]===2?'discarded':s.discrepancies[i]]));ui.group('Ask one repeatable property question');range(s.cols).forEach(q=>ui.button('ask:'+q,'Ask property'+(q+1),s.edits>=s.budget));ui.grid(3,'Commit certain object identity',{compact:true});range(s.n).forEach(i=>ui.button('identify:'+i,'Identify object'+(i+1)));ui.table(['Question','Adversarial answer'],s.history.map(v=>[v.q+1,v.answer?'yes':'no']));}};

export function invariantAdmits(inequalities,x,y){return inequalities.every(([a,b,c])=>a*x+b*y<=c)}
export function enabledTransition(t,x,y){const main=t.guard==='y-below'?y<t.bound:t.guard==='x-positive'?x>0:t.guard==='x-below'?x<t.bound:false;return main&&(t.minX===undefined||x>=t.minX)}
export function invariantError(s){for(const[x,y]of s.initial)if(!invariantAdmits(s.inequalities,x,y))return `Initial state(${x},${y}) is excluded.`;for(const[x,y]of s.bad)if(invariantAdmits(s.inequalities,x,y))return `Forbidden state(${x},${y}) is admitted.`;for(let x=0;x<=s.maxX;x++)for(let y=0;y<=s.maxY;y++)if(invariantAdmits(s.inequalities,x,y))for(const t of s.transitions)if(enabledTransition(t,x,y)){const nx=x+t.dx,ny=y+t.dy;if(nx<0||nx>s.maxX||ny<0||ny>s.maxY)return `Admitted state(${x},${y}) uses ${t.name} to leave the declared domain at(${nx},${ny}).`;if(!invariantAdmits(s.inequalities,nx,ny))return `Admitted state(${x},${y}) uses ${t.name} to reach excluded state(${nx},${ny}), even if its source is unreachable from the initials.`;}return null;}
function invariantInit({stage,seed,mode}){
 const r=rng(seed),d=mode==='finite'?Math.min(stage,2):2,k=mode==='endless'?1+Math.floor(r()*2):d===2?2:1,offset=d?Math.floor(r()*(mode==='endless'?3:2)):0,cap=2+Math.floor(r()*(mode==='endless'?3:2)),maxX=k*cap+offset+2,maxY=cap+2;
 const initial=mode==='endless'?shuffle(range(maxX+1).flatMap(x=>range(cap+1).filter(y=>x-k*y<=offset).map(y=>[x,y])),r).slice(0,2+Math.floor(r()*3)):[[offset,0],[k+offset,1]],bad=[[k+offset+1,1],...range(maxX+1).map(x=>[x,cap+1])];
 const transitions=[{name:'Advance',guard:'y-below',bound:cap,dx:k,dy:1},{name:'Retreat',guard:'x-positive',bound:0,dx:-1,dy:0}];
 if(d===2)transitions.push({name:'Slant',guard:'y-below',bound:cap,dx:k-1,dy:1});
 if(mode==='endless'){
  const deltas=shuffle([[0,1],[k,2],[2*k,2],[k-1,2],[-1,1],[-1,2],[0,2]],r).slice(0,1+Math.floor(r()*3));
  for(const[dx,dy]of deltas)transitions.push({name:'Update'+transitions.length,guard:'y-below',bound:cap+1-dy,dx,dy,...(dx<0?{minX:-dx}:{})});
  const extraBad=shuffle(range(maxX+1).flatMap(x=>range(cap+1).filter(y=>x-k*y>offset).map(y=>[x,y])),r).slice(0,1+Math.floor(r()*3));bad.push(...extraBad);
 }
 return base({maxX,maxY,initial,bad,transitions,inequalities:[[1,0,maxX],[0,1,maxY]],selected:0,boundLimit:maxX+maxY,note:'Synthesize TWO half-plane inequalities. They must include every initial state, exclude every forbidden state, and preserve every enabled transition from EVERY admitted integer state, including unreachable ones.'});
}
const invariant={stages:3,init:invariantInit,act(s,a){if(s.outcome!=='playing')return;const[k,v,delta]=a.split(':');if(k==='inequality')s.selected=+v;else if(k==='coefficient'){const i=+v,next=s.inequalities[s.selected][i]+ +delta,min=i===2?-s.boundLimit:-2,max=i===2?s.boundLimit:2;if(next<min||next>max)return;s.inequalities[s.selected][i]=next;s.edits++;}else if(a==='check')audit(s,invariantError(s),'The region is inductive across the full declared finite domain and separates initial/forbidden states.');},render(ui,s){ui.p(`Declared state domain: ALL integer pairs0≤x≤${s.maxX},0≤y≤${s.maxY}. Every enabled successor must also stay in this domain; an outgoing edge is a failure, never silently cropped.`);ui.table(['Initial states'],s.initial.map(v=>[v.join(',')]));ui.table(['Forbidden states'],s.bad.map(v=>[v.join(',')]));ui.table(['Transition','Enabled when','Successor'],s.transitions.map(t=>[t.name,(t.guard==='y-below'?`y<${t.bound}`:t.guard==='x-positive'?'x>0':`x<${t.bound}`)+(t.minX===undefined?'':` AND x≥${t.minX}`),`(x${t.dx<0?'': '+'}${t.dx},y+${t.dy})`]));ui.canvas('invariant-grid',620,360,ctx=>{ctx.fillStyle='#f2f5ec';ctx.fillRect(0,0,620,360);for(let x=0;x<=s.maxX;x++)for(let y=0;y<=s.maxY;y++){const px=50+x*520/s.maxX,py=315-y*260/s.maxY,admitted=invariantAdmits(s.inequalities,x,y);ctx.fillStyle=admitted?'#b9d0b7':'#e1e7dc';ctx.beginPath();ctx.arc(px,py,11,0,Math.PI*2);ctx.fill();if(s.bad.some(v=>v[0]===x&&v[1]===y)){ctx.strokeStyle='#ad5860';ctx.lineWidth=3;ctx.stroke()}if(s.initial.some(v=>v[0]===x&&v[1]===y)){ctx.strokeStyle='#bb8538';ctx.lineWidth=4;ctx.stroke()}ctx.fillStyle='#244335';ctx.font='10px system-ui';ctx.textAlign='center';ctx.fillText(`${x},${y}`,px,py+24)}});ui.group('Select one inequality');s.inequalities.forEach((v,i)=>ui.button('inequality:'+i,`${i+1}: ${v[0]}x + ${v[1]}y ≤ ${v[2]}`,false,s.selected===i));for(let i=0;i<3;i++)integer(ui,'coefficient:'+i,['x coefficient','y coefficient','right-hand bound'][i],s.inequalities[s.selected][i],i===2?-s.boundLimit:-2,i===2?s.boundLimit:2);ui.p('Green points are admitted; red rings forbidden; gold rings initial. Both inequalities must hold simultaneously.');certify(ui,'Certify initiation, safety AND closure');}};

export const evidenceEngines={'heritage-house':heritage,'posterior-post':bayes,'one-lie-archive':lie,'invariant-gallery':invariant};
