import {range,sum,letter,rng,shuffle,pick,edge,key,hasEdge,uniqueEdges,base,win,lose,audit,spent,graph,matrix,certify} from './core.mjs';

export function contractGraph(s,a,b){
 const keep=Math.min(a,b),remove=Math.max(a,b),i=s.bags.findIndex(v=>v.id===keep),j=s.bags.findIndex(v=>v.id===remove);
 if(i<0||j<0||!hasEdge(s.edges,a,b))return 'Contraction needs two currently adjacent bags.';
 if(s.bags[i].anchor!==null&&s.bags[j].anchor!==null)return 'Two protected target anchors cannot share a bag.';
 s.bags[i].members=[...s.bags[i].members,...s.bags[j].members].sort((a,b)=>a-b);s.bags[i].anchor??=s.bags[j].anchor;s.bags.splice(j,1);
 s.edges=uniqueEdges(s.edges.map(([x,y])=>[x===remove?keep:x,y===remove?keep:y]));return null;
}
export function minorError(s){
 if(s.bags.length!==s.targetN)return `There are ${s.bags.length} bags; the target has ${s.targetN}.`;
 if(s.bags.some(b=>b.anchor===null))return 'Every final bag must contain one protected target anchor.';
 const actual=uniqueEdges(s.edges.map(([a,b])=>[s.bags.find(v=>v.id===a).anchor,s.bags.find(v=>v.id===b).anchor]));
 for(let a=0;a<s.targetN;a++)for(let b=a+1;b<s.targetN;b++)if(hasEdge(actual,a,b)!==hasEdge(s.target,a,b))return `Target edge ${letter(a)}–${letter(b)} is ${hasEdge(s.target,a,b)?'missing':'unwanted'}.`;
 return null;
}
function minorInit({stage,seed,mode}){
 const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(2,stage),targetN=3+d;
 let target=range(targetN-1).map(i=>[i,i+1]);if(d>0)target.push([0,targetN-1]);if(d===2)target.push([0,2]);if(mode==='endless'){target=range(targetN-1).map(i=>[i,i+1]);for(let a=0;a<targetN;a++)for(let b=a+2;b<targetN;b++)if(r()<.38)target.push([a,b]);}
 let edges=uniqueEdges(target),n=targetN;const extra=2+d;
 for(let k=0;k<extra;k++){if(k%2===0){const [a,b]=pick(edges,r);edges=edges.filter(e=>key(...e)!==key(a,b));edges.push(edge(a,n),edge(n,b));}else edges.push(edge(Math.floor(r()*n),n));n++;}
 const chords=shuffle(range(n).flatMap(a=>range(n).filter(b=>b>a&&!hasEdge(edges,a,b)).map(b=>[a,b])),r).slice(0,1+d);
 return base({targetN,target:uniqueEdges(target),bags:range(n).map(id=>({id,members:[id],anchor:id<targetN?id:null})),edges:uniqueEdges([...edges,...chords]),selected:[],budget:extra+chords.length+1,note:'Protected A/B/… anchors must remain in different bags. Contract only adjacent bags; delete extra edges. Match every target edge and absent edge.'});
}
const minor={stages:3,init:minorInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('node:')){const id=+a.split(':')[1];s.selected=s.selected.includes(id)?s.selected.filter(v=>v!==id):[...s.selected.slice(-1),id];s.note='Select two bags to contract their connecting edge.';}else if(a==='contract'){if(s.selected.length!==2){s.note='Select two bags first.';return}const error=contractGraph(s,...s.selected);if(error){s.note=error;return}s.selected=[];spent(s,'Incident edges redirected; loops and parallel duplicates removed.');}else if(a.startsWith('delete:')){const[a1,b]=a.slice(7).split(',').map(Number);if(!hasEdge(s.edges,a1,b))return;s.edges=s.edges.filter(e=>key(...e)!==key(a1,b));spent(s,`Deleted edge ${a1+1}–${b+1}.`);}else if(a==='check')audit(s,minorError(s),'The contracted network has exactly the target relation.');},render(ui,s){ui.p(`Edits ${s.edits}/${s.budget}. Bag members are original source vertex numbers; letters are protected target anchors.`);ui.h('Target');ui.p('Target edges: '+s.target.map(([a,b])=>letter(a)+'–'+letter(b)).join(',')+'. Every unlisted pair must be absent.');graph(ui,'minor-target',range(s.targetN),s.target);ui.h('Current contracted network');graph(ui,'minor-current',s.bags.map(b=>b.id),s.edges,{labels:s.bags.map(b=>b.anchor===null?'•'+(b.id+1):letter(b.anchor)),selected:s.selected});ui.grid(3,'Choose vertex bags',{compact:true});for(const b of s.bags)ui.button('node:'+b.id,`${b.anchor===null?'unmarked':letter(b.anchor)} {${b.members.map(v=>v+1).join(',')}}`,false,s.selected.includes(b.id));ui.group('Contraction');ui.button('contract','Contract selected adjacent bags',s.selected.length!==2);ui.grid(3,'Delete current edges',{compact:true});for(const[a,b]of s.edges)ui.button('delete:'+key(a,b),`Delete ${a+1}–${b+1}`);certify(ui);}};

export function isomorphismError(s){if(s.mapping.includes(-1))return 'Map every left vertex.';if(new Set(s.mapping).size!==s.n)return 'Destinations must be a bijection.';for(let a=0;a<s.n;a++){if(s.leftMarks[a]!==s.rightMarks[s.mapping[a]])return `Vertex ${letter(a)} has the wrong mark.`;for(let b=a+1;b<s.n;b++)if(hasEdge(s.left,a,b)!==hasEdge(s.right,s.mapping[a],s.mapping[b]))return `${letter(a)}–${letter(b)} has ${hasEdge(s.left,a,b)?'a missing adjacency':'an unwanted adjacency'} under this mapping.`;}return null;}
function isoInit({stage,seed,mode}){const r=rng(seed),n=mode==='finite'?5+Math.min(stage,2):6+(stage%3),permutation=shuffle(range(n),r);let left=range(n-1).map(i=>[i,i+1]);if(stage>0)left.push([0,n-1]);for(let a=0;a<n;a++)for(let b=a+2;b<n;b++)if(r()<.22)left.push([a,b]);left=uniqueEdges(left);const leftMarks=range(n).map(i=>stage===0?i%3:Math.floor(r()*2)),rightMarks=range(n).map(()=>0);leftMarks.forEach((v,i)=>rightMarks[permutation[i]]=v);return base({n,left,right:uniqueEdges(left.map(([a,b])=>[permutation[a],permutation[b]])),leftMarks,rightMarks,mapping:range(n).map(()=>-1),selected:0,note:'Match marks, edges AND absent edges. Choosing an occupied destination swaps assignments, keeping a bijection.'});}
const twin={stages:3,init:isoInit,act(s,a){if(s.outcome!=='playing')return;const [kind,index]=a.split(':');if(kind==='left')s.selected=+index;else if(kind==='right'){const j=+index,owner=s.mapping.indexOf(j),old=s.mapping[s.selected];s.mapping[s.selected]=j;if(owner>=0&&owner!==s.selected)s.mapping[owner]=old;s.edits++;s.note=`Mapped ${letter(s.selected)} to ${letter(j)}′.`;}else if(a==='clear'){s.mapping[s.selected]=-1;s.edits++;}else if(a==='check')audit(s,isomorphismError(s),'Every edge, nonedge and mark is preserved by the bijection.');},render(ui,s){ui.h('Left network');graph(ui,'iso-left',range(s.n),s.left,{marks:s.leftMarks.map(v=>'mark'+v),selected:[s.selected]});ui.h('Right network');graph(ui,'iso-right',range(s.n),s.right,{labels:range(s.n).map(i=>letter(i)+'′'),marks:s.rightMarks.map(v=>'mark'+v)});ui.grid(4,'Select left vertex',{compact:true});range(s.n).forEach(i=>ui.button('left:'+i,`${letter(i)} → ${s.mapping[i]<0?'?':letter(s.mapping[i])+'′'}`,false,s.selected===i));ui.grid(4,'Assign right vertex',{compact:true});range(s.n).forEach(i=>ui.button('right:'+i,`${letter(i)}′ · mark${s.rightMarks[i]}`,false,s.mapping[s.selected]===i));ui.group();ui.button('clear','Clear selected mapping');ui.table(['Left','Neighbors','Mark'],range(s.n).map(i=>[letter(i),range(s.n).filter(j=>hasEdge(s.left,i,j)).map(letter).join(','),s.leftMarks[i]]));ui.table(['Right','Neighbors','Mark'],range(s.n).map(i=>[letter(i)+'′',range(s.n).filter(j=>hasEdge(s.right,i,j)).map(j=>letter(j)+'′').join(','),s.rightMarks[i]]));certify(ui);}};

export function eliminationStep(vertices,edges,v){const neighbors=vertices.filter(w=>hasEdge(edges,v,w)),added=[];for(let i=0;i<neighbors.length;i++)for(let j=i+1;j<neighbors.length;j++)if(!hasEdge(edges,neighbors[i],neighbors[j]))added.push(edge(neighbors[i],neighbors[j]));return{neighbors,added,edges:uniqueEdges([...edges,...added].filter(([a,b])=>a!==v&&b!==v)),vertices:vertices.filter(w=>w!==v)}}
function fillInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(stage,2),n=5+d;let edges=range(n-1).map(i=>[i,i+1]);if(d>=1)edges.push([0,n-1]);if(d===2){edges=[[0,1],[0,2],[1,2],[1,3],[2,3],[2,4],[3,4],[3,5],[4,5],[4,6],[5,6]];}const p=shuffle(range(n),r);edges=uniqueEdges(edges.map(([a,b])=>[p[a],p[b]]));if(mode==='endless'&&d===2){edges=[[p[0],p[1]],[p[0],p[2]],[p[1],p[2]]];for(let v=3;v<n;v++){const[a,b]=pick(edges,r);edges.push(edge(p[v],a),edge(p[v],b));}edges=uniqueEdges(edges);}
 return base({vertices:range(n),edges,order:[],selected:0,widthCap:d===0?1:2,fillCap:d===0?0:d===1?n-3:0,fill:0,maxWidth:0,note:'Eliminating a vertex connects every pair of its current neighbors, then removes it. Preview the new clique before committing.'});}
const fill={stages:3,init:fillInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('select:'))s.selected=+a.split(':')[1];else if(a==='eliminate'){if(!s.vertices.includes(s.selected))return;const t=eliminationStep(s.vertices,s.edges,s.selected);s.edits++;s.fill+=t.added.length;s.maxWidth=Math.max(s.maxWidth,t.neighbors.length);s.order.push(s.selected);s.vertices=t.vertices;s.edges=t.edges;if(s.maxWidth>s.widthCap)lose(s,`Elimination had ${t.neighbors.length} neighbors, exceeding width ${s.widthCap}.`);else if(s.fill>s.fillCap)lose(s,`Created ${s.fill} fill edges, exceeding allowance ${s.fillCap}.`);else if(!s.vertices.length)win(s,'Every vertex eliminated within both width and fill limits.');else{s.selected=s.vertices[0];s.note=`Removed ${letter(s.order.at(-1))}; ${t.added.length} fill edges created.`;}}},render(ui,s){ui.p(`Maximum neighbors ${s.maxWidth}/${s.widthCap} · fill edges ${s.fill}/${s.fillCap}. Eliminated: ${s.order.map(letter).join(' → ')||'none'}.`);graph(ui,'fill-graph',s.vertices,s.edges,{labels:s.vertices.map(letter),selected:[s.selected]});ui.grid(4,'Select vertex',{compact:true});s.vertices.forEach(v=>ui.button('select:'+v,letter(v),false,s.selected===v));if(s.vertices.includes(s.selected)){const t=eliminationStep(s.vertices,s.edges,s.selected);ui.p(`${letter(s.selected)} neighbors: ${t.neighbors.map(letter).join(',')||'none'}. Would create ${t.added.map(([a,b])=>letter(a)+'–'+letter(b)).join(',')||'no new edges'}.`)}ui.group();ui.button('eliminate','Commit selected elimination',!s.vertices.length);}};

export function augmentCandidates(s){const p=s.path;if(!p.length)return range(s.n).filter(i=>!s.match.some(([a])=>a===i));const v=p.at(-1);if(p.length%2===1)return range(s.n).filter(j=>hasEdge(s.edges,v,s.n+j)&&!s.match.some(([a,b])=>a===v&&b===j)&&!p.includes(s.n+j)).map(j=>s.n+j);const matched=s.match.find(([,b])=>b===v-s.n);return matched&&!p.includes(matched[0])?[matched[0]]:[];}
export function flipAugment(s){if(s.path.length<2||s.path.length%2||s.match.some(([,b])=>b===s.path.at(-1)-s.n))return 'Finish at an unmatched right vertex.';const add=[],remove=[];for(let i=0;i<s.path.length-1;i++){const a=i%2?s.path[i+1]:s.path[i],b=(i%2?s.path[i]:s.path[i+1])-s.n;(i%2?remove:add).push([a,b]);}s.match=[...s.match.filter(([a,b])=>!remove.some(([x,y])=>x===a&&y===b)),...add].sort((a,b)=>a[0]-b[0]);s.path=[];return null;}
function augmentInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(2,stage),n=4+d,lp=shuffle(range(n),r),rp=shuffle(range(n),r);let pairs=range(n).map(i=>[i,i]);for(let i=1;i<n;i++)pairs.push([i,i-1]);if(d===2)pairs.push([0,n-1]);if(mode==='endless')for(let a=0;a<n;a++)for(let b=0;b<n;b++)if(r()<.18)pairs.push([a,b]);let match=range(n-1).map(i=>[i,i+1]);pairs.push(...match);if(d===2)match=match.slice(0,n-2);return base({n,edges:uniqueEdges(pairs.map(([a,b])=>[lp[a],n+rp[b]])),match:match.map(([a,b])=>[lp[a],rp[b]]),path:[],budget:n*3+5,target:n,note:'Start at a free left vertex. Walk unmatched edge right, then its matched edge left. Finish at a free right vertex and flip the whole path.'});}
const augment={stages:3,init:augmentInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('walk:')){const v=+a.split(':')[1];if(!augmentCandidates(s).includes(v)){s.note='That step does not alternate unmatched/matched edges.';return}s.path.push(v);spent(s,`Path: ${s.path.map(v=>(v<s.n?'L':'R')+(v%s.n+1)).join(' → ')}.`);}else if(a==='cancel'){s.path=[];s.note='Path cleared; spent traversal moves remain spent.';}else if(a==='flip'){const error=flipAugment(s);if(error){s.note=error;return}if(s.match.length===s.target)win(s,'The alternating flips delivered a complete matching.');else s.note='Matching increased by exactly one. Choose another free left start.';}},render(ui,s){ui.p(`Matched ${s.match.length}/${s.target} · traversals ${s.edits}/${s.budget}. Solid listed pairs are currently matched.`);graph(ui,'augment-graph',range(s.n*2),s.edges,{labels:range(s.n*2).map(v=>(v<s.n?'L':'R')+(v%s.n+1)),selected:s.path,bipartite:true});ui.table(['Current left','Current right'],s.match.map(([a,b])=>['L'+(a+1),'R'+(b+1)]));ui.p('Path: '+(s.path.map(v=>(v<s.n?'L':'R')+(v%s.n+1)).join(' → ')||'not started'));const choices=augmentCandidates(s);ui.grid(3,'Legal next path vertex',{compact:true});range(s.n*2).forEach(v=>ui.button('walk:'+v,(v<s.n?'L':'R')+(v%s.n+1),!choices.includes(v),s.path.includes(v)));ui.group();ui.button('flip','Flip complete augmenting path');ui.button('cancel','Cancel path');ui.table(['Left','Permitted recipients'],range(s.n).map(i=>['L'+(i+1),range(s.n).filter(j=>hasEdge(s.edges,i,s.n+j)).map(j=>'R'+(j+1)).join(',')]));}};

export function heapError(heap){for(let i=1;i<heap.length;i++)if(heap[Math.floor((i-1)/2)]>heap[i])return `Parent slot ${Math.floor((i-1)/2)+1} exceeds child slot ${i+1}.`;return null;}
function heapInit({stage,seed,mode}){const r=rng(seed),n=mode==='finite'?5+Math.min(stage,2)*2:7+stage%3,values=shuffle(range(n).map(i=>i*2+1+Math.floor(r()*2)),r);return base({heap:values,output:[],selected:0,budget:Math.ceil(n*Math.log2(n))+n,note:'Exchange only a parent and its child. Extract is safe only when EVERY current parent is no larger than its children. Root removal brings the last leaf to slot1.'});}
const heap={stages:3,init:heapInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('slot:')){const i=+a.split(':')[1];if(i<0||i>=s.heap.length)return;s.selected=i;s.note=`Slot ${i+1} selected; use an explicit parent/child swap control.`;}else if(a.startsWith('swap:')){const i=+a.split(':')[1],j=s.selected;if(i<0||i>=s.heap.length||i===j)return;if(i>0&&Math.floor((i-1)/2)===j||j>0&&Math.floor((j-1)/2)===i){[s.heap[i],s.heap[j]]=[s.heap[j],s.heap[i]];s.selected=i;spent(s,'Exchanged adjacent tree slots; inspect the full heap before extracting.');}else s.note='Only a parent and its direct child can exchange.';}else if(a==='extract'){const error=heapError(s.heap);if(error){lose(s,'Unsafe extraction: '+error);return}const root=s.heap[0],last=s.heap.pop();s.output.push(root);if(s.heap.length)s.heap[0]=last;s.selected=0;if(!s.heap.length)win(s,'Every shrinking root was extracted in increasing order.');else s.note=`Extracted ${root}; last leaf${last} moved to root. Repair the entire heap again.`;}},render(ui,s){ui.p(`Parent/child exchanges ${s.edits}/${s.budget} · extracted ${s.output.join(' → ')||'none'}. Every slot is a tree position, not a fixed value.`);ui.canvas('heap-tree',620,360,ctx=>{ctx.fillStyle='#f2f5ec';ctx.fillRect(0,0,620,360);const pos=s.heap.map((_,i)=>{const depth=Math.floor(Math.log2(i+1)),first=(1<<depth)-1,width=1<<depth;return[(i-first+.5)*620/width,50+depth*90]});ctx.strokeStyle='#718579';for(let i=1;i<s.heap.length;i++){ctx.beginPath();ctx.moveTo(...pos[Math.floor((i-1)/2)]);ctx.lineTo(...pos[i]);ctx.stroke()}s.heap.forEach((v,i)=>{ctx.fillStyle=i===s.selected?'#e7c174':'#dfe9da';ctx.beginPath();ctx.arc(...pos[i],24,0,Math.PI*2);ctx.fill();ctx.fillStyle='#203f33';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(String(v),pos[i][0],pos[i][1]+6);ctx.font='12px system-ui';ctx.fillText('slot'+(i+1),pos[i][0],pos[i][1]+40)})});ui.grid(4,'Select heap slot',{compact:true});s.heap.forEach((v,i)=>ui.button('slot:'+i,`Slot ${i+1}: ${v}`,false,s.selected===i));ui.group('Explicit parent/child exchanges');if(s.selected>0)ui.button('swap:'+Math.floor((s.selected-1)/2),'Swap with parent');for(const i of [2*s.selected+1,2*s.selected+2])if(i<s.heap.length)ui.button('swap:'+i,'Swap with '+(i%2?'left':'right')+' child');ui.table(['Slot','Value','Parent','Children'],s.heap.map((v,i)=>[i+1,v,i?Math.floor((i-1)/2)+1:'root',[i*2+2,i*2+3].filter(j=>j<=s.heap.length).join(',')||'leaf']));ui.group();ui.button('extract','Extract current minimum root');ui.p('Current heap audit: '+(heapError(s.heap)||'all parent/child inequalities hold')+'.');}};

export const graphEngines={'minor-museum':minor,'twin-graph':twin,'fill-in-station':fill,'alternating-couriers':augment,'heap-foundry':heap};
