import {range,sum,letter,rng,shuffle,pick,base,audit,win,lose,graph,certify} from './core.mjs';

const atom=p=>({op:'atom',p}),not=f=>({op:'not',f}),know=(who,f)=>({op:'know',who,f});
export function knowledgeTruth(formula,world,worlds,active){
 if(formula.op==='atom')return !!worlds[world][formula.p];
 if(formula.op==='not')return !knowledgeTruth(formula.f,world,worlds,active);
 if(formula.op==='and')return knowledgeTruth(formula.a,world,worlds,active)&&knowledgeTruth(formula.b,world,worlds,active);
 if(formula.op==='know'){const observation=worlds[world][formula.who];return active.filter(i=>worlds[i][formula.who]===observation).every(i=>knowledgeTruth(formula.f,i,worlds,active));}
 throw Error('Unknown epistemic operator');
}
export function knowledgeText(f){if(f.op==='atom')return f.p;if(f.op==='not')return `not (${knowledgeText(f.f)})`;if(f.op==='and')return `(${knowledgeText(f.a)}) and (${knowledgeText(f.b)})`;return `${f.who==='A'?'Ada':'Bo'} knows (${knowledgeText(f.f)})`;}
function knowledgeInit({stage,seed,mode}){
 const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(stage,2),n=8+d*2,steps=1+d;
 const candidates=[not(know('A',atom('P'))),know('A',atom('P')),know('B',atom('Q')),not(know('B',atom('Q'))),know('A',not(atom('P'))),know('B',not(atom('Q'))),not(know('A',know('B',atom('Q')))),know('A',know('B',atom('Q'))),not(know('B',know('A',atom('P')))),know('B',know('A',atom('P')))];
 for(let trial=0;trial<4000;trial++){
  const worlds=range(n).map(i=>({A:Math.floor(r()*(2+d)),B:Math.floor(r()*(3+d)),P:r()<.5,Q:r()<.5}));let active=range(n);const announcements=[];
  for(let k=0;k<steps;k++){const choices=candidates.filter(f=>{if(d===0&&f!==candidates[0])return false;if(d>0&&k===steps-1&&f.op!=='know'&&f.f?.op!=='know')return false;const survivors=active.filter(i=>knowledgeTruth(f,i,worlds,active));return survivors.length>0&&survivors.length<active.length});if(!choices.length)break;const f=pick(choices,r);announcements.push(f);active=active.filter(i=>knowledgeTruth(f,i,worlds,active));}
  const newKnowledge=active.some(w=>['A','B'].some(who=>['P','Q'].some(p=>knowledgeTruth(know(who,atom(p)),w,worlds,active)&&!knowledgeTruth(know(who,atom(p)),w,worlds,range(n)))));
  if((d<2||newKnowledge)&&announcements.length===steps&&(!d||announcements.some(f=>(f.op==='know'&&f.f.op==='know')||(f.op==='not'&&f.f?.f?.op==='know'))))return base({worlds,active:range(n),announcements,step:0,retained:[],note:'An announcement is evaluated in EVERY currently active world at once. Retain exactly the worlds where it is true, then update all observers’ groups.'});
 }throw Error('Could not construct a nontrivial public-announcement transcript');
}
const knowledge={stages:3,init:knowledgeInit,act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('world:')){const i=+a.split(':')[1];if(!s.active.includes(i))return;s.retained=s.retained.includes(i)?s.retained.filter(v=>v!==i):[...s.retained,i];s.edits++;}else if(a==='apply'){const f=s.announcements[s.step],expected=s.active.filter(i=>knowledgeTruth(f,i,s.worlds,s.active)),wrong=s.active.find(i=>expected.includes(i)!==s.retained.includes(i));if(wrong!==undefined){const w=s.worlds[wrong];audit(s,`World ${wrong+1} should be ${expected.includes(wrong)?'retained':'removed'}. Ada group${w.A+1}, Bo group${w.B+1}; evaluate the displayed claim in the CURRENT groups.`);return}s.active=expected;s.retained=[];s.step++;if(s.step===s.announcements.length)win(s,'Every public announcement filtered simultaneously; the final knowledge groups are correct.');else s.note='Announcement public. Removed worlds no longer belong to anyone’s information group; evaluate the next claim afresh.';}},render(ui,s){ui.p(`Announcement ${Math.min(s.step+1,s.announcements.length)}/${s.announcements.length}: ${knowledgeText(s.announcements[Math.min(s.step,s.announcements.length-1)])}.`);ui.p('Ada knows a claim at a world iff it is true at every ACTIVE world with the same Ada observation. Bo uses Bo observations. “Not knows” does not mean “knows not”.');ui.table(['World','Ada observation','Bo observation','P','Q','Publicly active'],s.worlds.map((w,i)=>[i+1,w.A+1,w.B+1,w.P?'true':'false',w.Q?'true':'false',s.active.includes(i)?'yes':'removed']));ui.grid(3,'Choose retained worlds',{compact:true});s.worlds.forEach((w,i)=>ui.button('world:'+i,`World ${i+1} ${s.retained.includes(i)?'retain':'remove'}`,!s.active.includes(i),s.retained.includes(i)));for(const who of ['A','B'])ui.table([who==='A'?'Ada current group':'Bo current group','Active worlds'],[...new Set(s.active.map(i=>s.worlds[i][who]))].sort().map(g=>[g+1,s.active.filter(i=>s.worlds[i][who]===g).map(i=>i+1).join(',')]));ui.group();ui.button('apply','Apply simultaneous public announcement');}};

export function modalTruth(f,w,s){const successors=s.arrows.filter(([a])=>a===w).map(([,b])=>b);if(f.op==='atom')return !!s.values[w][f.p];if(f.op==='not')return !modalTruth(f.f,w,s);if(f.op==='or')return modalTruth(f.a,w,s)||modalTruth(f.b,w,s);if(f.op==='and')return modalTruth(f.a,w,s)&&modalTruth(f.b,w,s);if(f.op==='box')return successors.every(v=>modalTruth(f.f,v,s));if(f.op==='diamond')return successors.some(v=>modalTruth(f.f,v,s));throw Error('Unknown modal operator')}
export function modalText(f){if(f.op==='atom')return f.p;if(f.op==='not')return `¬${modalText(f.f)}`;if(f.op==='or'||f.op==='and')return `(${modalText(f.a)}${f.op==='or'?' ∨ ':' ∧ '}${modalText(f.b)})`;return (f.op==='box'?'□':'◇')+'('+modalText(f.f)+')';}
const box=f=>({op:'box',f}),diamond=f=>({op:'diamond',f});
function modalInit({stage}){const P=atom('P'),Q=atom('Q'),studies=[{premises:[diamond(P)],conclusion:box(P),n:3},{premises:[box({op:'or',a:P,b:Q}),diamond({op:'or',a:P,b:Q})],conclusion:{op:'or',a:box(P),b:box(Q)},n:3},{premises:[box(diamond(P)),diamond(atom('Q'))],conclusion:diamond(box(P)),n:4}],d=studies[Math.min(stage,2)];return base({...d,arrows:[],values:range(d.n).map(()=>({P:false,Q:false})),from:0,to:1,note:'Construct a counterexample at root 1. All premises must be true and the conclusion false. Arrows are directed; □ with no successor is true, ◇ with no successor is false.'});}
const modal={stages:3,init:modalInit,act(s,a){if(s.outcome!=='playing')return;const[k,v,p]=a.split(':');if(k==='from')s.from=+v;else if(k==='to')s.to=+v;else if(k==='value'){s.values[+v][p]=!s.values[+v][p];s.edits++;}else if(a==='arrow'){if(s.from===s.to){s.note='These finite studies use arrows between different worlds; choose a different destination.';return}const i=s.arrows.findIndex(([a,b])=>a===s.from&&b===s.to);if(i<0)s.arrows.push([s.from,s.to]);else s.arrows.splice(i,1);s.edits++;}else if(a==='check'){const i=s.premises.findIndex(f=>!modalTruth(f,0,s));audit(s,i>=0?`Premise ${i+1} is false at root 1.`:modalTruth(s.conclusion,0,s)?'The conclusion is still true at root 1; this is not a counterexample.':null,'Premises true, conclusion false: your modal model refutes the inference.');}},render(ui,s){ui.p('Root is world 1. Premises: '+s.premises.map(modalText).join(' AND ')+'. Conclusion to refute: '+modalText(s.conclusion)+'.');ui.p('□F: every arrow destination satisfies F (true with no arrows). ◇F: at least one arrow destination satisfies F. Nested operators begin again at that destination. No self-arrows in this campaign.');graph(ui,'modal-frame',range(s.n),s.arrows,{labels:range(s.n).map(i=>String(i+1)),marks:s.values.map(v=>'P'+(v.P?'✓':'×')+' Q'+(v.Q?'✓':'×')),directed:true,selected:[0]});ui.grid(3,'Select arrow source',{compact:true});range(s.n).forEach(i=>ui.button('from:'+i,'From world'+(i+1),false,s.from===i));ui.grid(3,'Select arrow destination',{compact:true});range(s.n).forEach(i=>ui.button('to:'+i,'To world'+(i+1),false,s.to===i));ui.group();ui.button('arrow','Toggle selected directed arrow',s.from===s.to);ui.grid(3,'Change world propositions',{compact:true});range(s.n).forEach(i=>['P','Q'].forEach(p=>ui.button(`value:${i}:${p}`,`World ${i+1} ${p}: ${s.values[i][p]?'true':'false'}`,false,s.values[i][p])));ui.table(['World',...s.premises.map((_,i)=>'Premise'+(i+1)),'Conclusion'],range(s.n).map(i=>[i+1,...s.premises.map(f=>modalTruth(f,i,s)?'true':'false'),modalTruth(s.conclusion,i,s)?'true':'false']));certify(ui,'Certify counterexample at root 1');}};

export function reducedDiagram(table,order){const n=order.length,nodes=[],intern=new Map();function build(depth,mask,bits){if(depth===n)return table[bits]?1:0;const variable=order[depth],low=build(depth+1,mask|(1<<variable),bits&~(1<<variable)),high=build(depth+1,mask|(1<<variable),bits|(1<<variable));if(low===high)return low;const key=[variable,low,high].join(',');if(intern.has(key))return intern.get(key);const id=nodes.length+2;nodes.push({id,variable,low,high,depth});intern.set(key,id);return id}const root=build(0,0,0);return{root,nodes,count:nodes.length};}
function diagramInit({stage,seed,mode}){const r=rng(seed),n=mode==='finite'?3+Math.min(stage,2):4+stage%2;for(let trial=0;trial<200;trial++){const vars=shuffle(range(n),r),selector=vars[0],a=vars[1],b=vars[2],extra=vars.slice(3),neg=range(n).map(()=>r()<.5),op=range(3).map(()=>r()<.5);const table=range(1<<n).map(bits=>{const v=i=>Boolean((bits>>i)&1)!==neg[i],branch=side=>{let out=v(side?a:b);for(let k=0;k<extra.length;k++)if(k%2===Number(side))out=op[k]?out&&v(extra[k]):out||v(extra[k]);return out};return Number(v(selector)?branch(true):branch(false))}),good=[selector,...vars.slice(1)],bad=[...vars.slice(1),selector],budget=reducedDiagram(table,good).count;if(reducedDiagram(table,bad).count<=budget)continue;return base({n,table,order:shuffle(range(n),r),budget,note:'One global variable order applies to every branch. Equal low/high children remove a test; identical (variable,low,high) triples share ONE node. Meet the nonterminal-node budget.'});}throw Error('Could not construct an order-sensitive BDD');}
const diagram={stages:3,init:diagramInit,act(s,a){if(s.outcome!=='playing')return;const[k,v]=a.split(':');if(k==='up'||k==='down'){const i=s.order.indexOf(+v),j=i+(k==='up'?-1:1);if(j<0||j>=s.n)return;[s.order[i],s.order[j]]=[s.order[j],s.order[i]];s.edits++;}else if(a==='check')audit(s,reducedDiagram(s.table,s.order).count>s.budget?`The reduced DAG uses ${reducedDiagram(s.table,s.order).count} nonterminal nodes, above budget ${s.budget}.`:null,'The shared reduced decision diagram meets the node budget.');},render(ui,s){const d=reducedDiagram(s.table,s.order);ui.p(`Variable order ${s.order.map(letter).join(' → ')} · unique nonterminal nodes ${d.count}/${s.budget}. Terminals0/1 do not count. Shared child IDs denote one DAG node.`);ui.grid(3,'Reorder global variables',{compact:true});s.order.forEach((v,i)=>{ui.button('up:'+v,letter(v)+' earlier',i===0);ui.button('down:'+v,letter(v)+' later',i===s.n-1)});ui.canvas('bdd-dag',620,390,ctx=>{ctx.fillStyle='#f2f5ec';ctx.fillRect(0,0,620,390);const rows=range(s.n).map(k=>d.nodes.filter(v=>v.depth===k)),pos=new Map([[0,[210,365]],[1,[410,365]]]);rows.forEach((row,depth)=>row.forEach((v,i)=>pos.set(v.id,[(i+.5)*620/row.length,35+depth*300/s.n])));for(const v of d.nodes)for(const [dest,bit]of[[v.low,0],[v.high,1]]){ctx.strokeStyle=bit?'#a16f31':'#718579';ctx.setLineDash(bit?[]:[4,4]);ctx.beginPath();ctx.moveTo(...pos.get(v.id));ctx.lineTo(...pos.get(dest));ctx.stroke()}ctx.setLineDash([]);for(const [id,p]of pos){ctx.fillStyle=id===d.root?'#e7c174':'#dfe9da';ctx.beginPath();ctx.arc(...p,17,0,Math.PI*2);ctx.fill();ctx.fillStyle='#203f33';ctx.font='bold 12px system-ui';ctx.textAlign='center';ctx.fillText(id<2?String(id):letter(d.nodes.find(v=>v.id===id).variable)+'#'+id,p[0],p[1]+4)}});ui.table(['Node','Variable','Low(0)','High(1)'],d.nodes.map(v=>[v.id,letter(v.variable),v.low,v.high]));ui.p('Root node: '+d.root+'. Dashed edges select0; solid edges select1.');ui.table([...range(s.n).map(letter),'Output'],s.table.map((v,bits)=>[...range(s.n).map(i=>(bits>>i)&1),v]));certify(ui,'Certify reduced-node budget');}};

function witnessInit({stage,seed,mode}){const r=rng(seed),d=mode==='finite'?Math.min(stage,2):Math.min(stage,2),n=3+(mode==='endless'&&stage%3===0?1:0),R=range(n).map(()=>range(n).map(()=>r()<.4)),S=range(n).map(()=>range(n).map(()=>r()<.35));if(d===0){R.forEach(row=>row[Math.floor(r()*n)]=true);}else if(d===1){const universal=Math.floor(r()*n);R.forEach(row=>row[universal]=true);}else{R.forEach(row=>row[Math.floor(r()*n)]=true);S.forEach(row=>row[Math.floor(r()*n)]=true);}return base({n,d,R,S,choices:range(d===1?1:n).map(()=>-1),later:range(n*n).map(()=>-1),selected:0,laterSelected:0,note:d===0?'For each x choose a y with R(x,y). Different x may use different y.':d===1?'Choose ONE y before x is known. That same y must satisfy R(x,y) for every x.':'For each x choose y. Keep that y fixed for every later z; choose w after z so R(x,y), S(y,w), and w≠z all hold.',});}
export function witnessError(s){if(s.choices.some(v=>v<0))return 'Choose every required earlier witness.';for(let x=0;x<s.n;x++){const y=s.choices[s.d===1?0:x];if(!s.R[x][y])return `Universal branch x${x+1}: R(x,y${y+1}) fails.`;if(s.d===2)for(let z=0;z<s.n;z++){const w=s.later[x*s.n+z];if(w<0)return `Choose a later w for x${x+1}, z${z+1}.`;if(!s.S[y][w]||w===z)return `Branch x${x+1}, z${z+1} needs S(y${y+1},w) and w≠z.`;}}return null;}
const witness={stages:3,init(args){const s=witnessInit(args);if(s.d===2){const r=rng(args.seed^0xc0f3e23);s.S.forEach(row=>shuffle(range(s.n),r).slice(0,2).forEach(i=>row[i]=true));}return s;},act(s,a){if(s.outcome!=='playing')return;const[k,v]=a.split(':');if(k==='branch')s.selected=+v;else if(k==='later-branch')s.laterSelected=+v;else if(k==='choose'){s.choices[s.selected]=+v;s.edits++;s.note='Earlier witness fixed for all following universal branches.';}else if(k==='later'){s.later[s.laterSelected]=+v;s.edits++;}else if(a==='check')audit(s,witnessError(s),'Every universal branch has a witness with the permitted dependencies.');},render(ui,s){ui.p(s.d===0?'Formula: ∀x ∃y R(x,y).':s.d===1?'Formula: ∃y ∀x R(x,y).':'Formula: ∀x ∃y ∀z ∃w [R(x,y) AND S(y,w) AND w≠z].');ui.p('Domain values1…'+s.n+'. Choices made before a universal variable may not depend on that variable. All branches are checked, not just the selected one.');ui.table(['R(x,y)',...range(s.n).map(i=>'y'+(i+1))],s.R.map((row,x)=>['x'+(x+1),...row.map(v=>v?'yes':'no')]));if(s.d===2)ui.table(['S(y,w)',...range(s.n).map(i=>'w'+(i+1))],s.S.map((row,y)=>['y'+(y+1),...row.map(v=>v?'yes':'no')]));ui.grid(3,'Select earlier decision context',{compact:true});s.choices.forEach((v,i)=>ui.button('branch:'+i,`${s.d===1?'Before every x':'x'+(i+1)}: y${v<0?'?':v+1}`,false,s.selected===i));ui.group('Choose permitted earlier y');range(s.n).forEach(v=>ui.button('choose:'+v,'y'+(v+1),false,s.choices[s.selected]===v));if(s.d===2){ui.grid(3,'Select later universal branch',{compact:true});s.later.forEach((v,i)=>ui.button('later-branch:'+i,`x${Math.floor(i/s.n)+1},z${i%s.n+1}: w${v<0?'?':v+1}`,false,s.laterSelected===i));ui.group('Choose later w');range(s.n).forEach(v=>ui.button('later:'+v,'w'+(v+1),false,s.later[s.laterSelected]===v));}certify(ui,'Check EVERY universal branch');}};

export const semanticEngines={'knowledge-circle':knowledge,'modal-witness':modal,'diagram-order':diagram,'witness-table':witness};
