/* Twenty independent puzzle engines. Shared helpers only render controls and graph diagrams. */
(() => {
'use strict';
const range=n=>Array.from({length:n},(_,i)=>i),clone=o=>JSON.parse(JSON.stringify(o)),shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;},pick=a=>a[Math.floor(Math.random()*a.length)],same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),sum=a=>a.reduce((a,b)=>a+b,0);
const adj=(p,n)=>[p-n,p+n,...(p%n?[p-1]:[]),...(p%n<n-1?[p+1]:[])].filter(i=>i>=0&&i<n*n);
const connected=(nodes,edges)=>{if(!nodes.length)return [];const found=new Set([nodes[0]]),todo=[nodes[0]];while(todo.length){const a=todo.shift();edges.forEach(([x,y])=>{const b=x===a?y:y===a?x:null;if(b!==null&&nodes.includes(b)&&!found.has(b)){found.add(b);todo.push(b);}});}return [...found];};
const gridEdges=n=>range(n*n).flatMap(i=>adj(i,n).filter(j=>j>i).map(j=>[i,j]));
const direction={U:[0,-1],R:[1,0],D:[0,1],L:[-1,0]},opposite={U:'D',D:'U',L:'R',R:'L'};
const step=(p,d,n,walls)=>{const [dx,dy]=direction[d],x=p%n+dx,y=Math.floor(p/n)+dy,q=y*n+x;return x<0||x>=n||y<0||y>=n||walls.includes(q)?p:q;};
function arrows(c,fn){[['U','↑ Up'],['L','← Left'],['D','↓ Down'],['R','Right →']].forEach(([d,label])=>c.extra(label,()=>fn(d),'dir-'+d));}
function graph(c,n,edges,nodeLabels){
 const m=c.m,ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),make=(tag,attrs,text)=>{const el=document.createElementNS(ns,tag);Object.entries(attrs).forEach(([k,v])=>el.setAttribute(k,v));if(text!==undefined)el.textContent=text;return el;};
 svg.setAttribute('viewBox','0 0 460 280');svg.setAttribute('role','img');svg.setAttribute('aria-label','Live network overview. Offline relays show X, inks show numbers, selected tree links are bold, and water channels show directed flow. All details are also listed in the controls below.');
 if(m.flow){const defs=make('defs',{}),marker=make('marker',{id:'flow-arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});marker.append(make('path',{d:'M0 0 L10 5 L0 10 z',fill:'#315e50'}));defs.append(marker);svg.append(defs);}
 const pos=range(n).map(i=>[230+185*Math.cos(i*2*Math.PI/n-Math.PI/2),140+108*Math.sin(i*2*Math.PI/n-Math.PI/2)]);
 edges.forEach(([a,b,w],i)=>{const[x,y]=pos[a],[u,v]=pos[b],dist=Math.hypot(u-x,v-y),dx=(u-x)/dist*20,dy=(v-y)/dist*20,offline=m.off&&(m.off.includes(a)||m.off.includes(b)),chosen=m.picked?.includes(i),active=m.flow?m.flow[i]>0:chosen;
 const attrs={x1:x+dx,y1:y+dy,x2:u-dx,y2:v-dy,stroke:offline?'#bac8c0':active?'#315e50':'#91ada1','stroke-width':m.flow?1.5+m.flow[i]:chosen?5:2,opacity:offline?.45:m.picked&&!chosen?.5:1};if(offline||m.flow&&!active)attrs['stroke-dasharray']='4 4';if(m.flow)attrs['marker-end']='url(#flow-arrow)';svg.append(make('line',attrs));if(w!==undefined)svg.append(make('text',{x:(x+u)/2,y:(y+v)/2,'text-anchor':'middle',stroke:'#fafaf3','stroke-width':4,'paint-order':'stroke'},w));});
 pos.forEach(([x,y],i)=>{const off=m.off?.includes(i),ink=m.colors?.[i];svg.append(make('circle',{cx:x,cy:y,r:19,fill:off?'#324f46':ink?['','#e5bc78','#a9d1c6','#cec0e5'][ink]:'#e0e8d9',stroke:'#5e7b6b','stroke-width':1}));const t=make('text',{x,y:y+5,'text-anchor':'middle'},off?'×':(nodeLabels?.[i]??String.fromCharCode(65+i))+(ink?'·'+ink:''));if(off)t.style.fill='white';svg.append(t);});c.board.append(svg);
}
const letter=i=>String.fromCharCode(65+i),E={};
// Generation is bounded; fallback invariants are covered by finite-state regression tests.
function relayCut(n,edges,limit){
 for(let size=0;size<=limit;size++)for(const set of subsets(n-2,size)){
  const off=set.map(i=>i+1),nodes=range(n).filter(i=>!off.includes(i));
  if(!connected(nodes,edges).includes(n-1))return size;
 }
 return limit+1;
}
function relayModel(stage){
 const n=8+stage*2,budget=stage+1;
 for(let attempt=0;attempt<500;attempt++){
  const edges=range(n).flatMap(a=>range(n).filter(b=>b>a&&Math.random()<(.25+stage*.055)).map(b=>[a,b]));
  const degree=range(n).map(a=>edges.filter(e=>e.includes(a)).length);
  if(degree[0]<=budget||degree[n-1]<=budget||degree.some(d=>d<2)||connected(range(n),edges).length!==n)continue;
  if(relayCut(n,edges,budget)!==budget)continue;
  return{n,edges,budget,off:[],sources:[0],sinks:[n-1],generation:'random graph; verified minimum cut'};
 }
 // A family of disjoint channels with a shared cut; terminals have more neighbors than budget.
 const left=range(budget+1).map(i=>i+1),cut=range(budget).map(i=>budget+2+i),right=range(budget+1).map(i=>2*budget+2+i),N=3*budget+4;
 let edges=[...left.map(i=>[0,i]),...right.map(i=>[i,N-1])];
 cut.forEach((c,i)=>edges.push([left[i],c],[c,right[i]],[left.at(-1),c],[c,right.at(-1)]));
 const rename=[0,...shuffle(range(N-2).map(i=>i+1)),N-1];edges=edges.map(e=>e.map(i=>rename[i]));
 if(relayCut(N,edges,budget)!==budget)throw Error('Invalid relay fallback');
 return{n:N,edges,budget,off:[],sources:[0],sinks:[N-1],generation:'validated channel fallback'};
}
function riverModel(stage){
 const n=6+stage,minDelivery=3+stage;
 for(let attempt=0;attempt<500;attempt++){
  const edges=range(n).flatMap(a=>range(n).filter(b=>b>a&&!(a===0&&b===n-1)&&(b===a+1||Math.random()<.38)).map(b=>[a,b,1+Math.floor(Math.random()*(4+stage))]));
  const source=edges.filter(e=>e[0]===0),sink=edges.filter(e=>e[1]===n-1),target=maxflow(n,edges);
  if(source.length<2||sink.length<2||target<minDelivery||target>=sum(source.map(e=>e[2]))||target>=sum(sink.map(e=>e[2])))continue;
  return{n,edges,flow:edges.map(()=>0),target,generation:'random branching network; verified internal bottleneck'};
 }
 const cap=stage+2,edges=[[0,1,cap+2],[0,2,cap+1],[1,2,1],[1,3,cap],[2,3,1],[2,4,1],[3,4,1],[3,5,cap+2],[4,5,cap+2]],target=maxflow(6,edges);
 return{n:6,edges,flow:edges.map(()=>0),target,generation:'validated internal-bottleneck fallback'};
}
function gardenNext(bits,n){
 let next=0;
 for(let i=0;i<n;i++){
  const live=bits>>i&1,neighbors=(bits>>((i+n-1)%n)&1)+(bits>>((i+1)%n)&1);
  if(live?neighbors===1:neighbors===2)next|=1<<i;
 }
 return next;
}
function gardenReach(initial,n,days){
 let states=new Map([[initial,{cost:0,first:0}]]);
 for(let day=0;day<days;day++){
  const next=new Map();
  for(const[bits,record]of states)for(let edit=-1;edit<n;edit++){
   const result=gardenNext(edit<0?bits:bits^(1<<edit),n),cost=record.cost+(edit>=0),first=day===0?1<<(edit+1):record.first,old=next.get(result);
   if(!old||cost<old.cost)next.set(result,{cost,first});else if(cost===old.cost)old.first|=first;
  }
  states=next;
 }
 return states;
}
function gardenModel(stage){
 const n=7+stage,days=3+stage,budget=2+stage,allFirst=(1<<(n+1))-1;
 for(let attempt=0;attempt<100;attempt++){
  // Final deterministic attempt is a separately validated fallback, never an unchecked target.
  const initial=attempt===99?[112,223,234][stage]:1+Math.floor(Math.random()*((1<<n)-2));
  const options=[...gardenReach(initial,n,days)].filter(([bits,r])=>bits>0&&bits<(1<<n)-1&&r.cost===budget&&r.first!==allFirst);
  if(!options.length)continue;
  const[target,proof]=pick(options);
  return{n,days,budget,initial,cells:initial,target,day:0,used:0,pending:-1,timeline:[{day:0,cells:initial,edit:-1}],minimumInterventions:proof.cost,viableFirstChoices:proof.first};
 }
 throw Error('No calibrated garden found');
}
function ferryDistance(n,conflicts,capacity){
 const final=(1<<n)-1,queue=[[0,0,0]],seen=new Set(['0,0']);
 for(let k=0;k<queue.length;k++){
  const[bits,boat,d]=queue[k];if(bits===final)return d;
  const available=range(n).filter(i=>(bits>>i&1)===boat),loads=[[],...range(capacity).flatMap(k=>subsets(available.length,k+1).map(s=>s.map(i=>available[i])))];
  for(const load of loads){
   const next=bits^sum(load.map(i=>1<<i)),side=1-boat,key=next+','+side;
   if(seen.has(key)||conflicts.some(([a,b])=>(next>>a&1)===(next>>b&1)&&(next>>a&1)!==side))continue;
   seen.add(key);queue.push([next,side,d+1]);
  }
 }
 return -1;
}
function ferryModel(stage){
 const n=[5,6,8][stage],capacity=[2,2,3][stage],par=[7,9,11][stage],names=shuffle(['Fox','Goose','Grain','Lynx','Hare','Herbs','Finch','Seeds','Moth','Silk','Beetle']).slice(0,n);
 const fallback=[[[0,1],[0,4],[1,4],[3,4]],[[0,2],[0,3],[0,4],[0,5],[1,5],[2,5],[3,5]],[[0,2],[0,4],[0,6],[0,7],[1,4],[2,6],[4,5],[4,6],[4,7],[6,7]]][stage];
 for(let attempt=0;attempt<400;attempt++){
  const conflicts=attempt===399?fallback:range(n).flatMap(a=>range(n).filter(b=>b>a&&Math.random()<(.3+stage*.02)).map(b=>[a,b]));
  if(ferryDistance(n,conflicts,capacity)!==par)continue;
  return{names,conflicts,capacity,banks:names.map(()=>0),boat:0,cargo:[],trips:0,par,generation:attempt===399?'validated fallback':'random compatibility graph'};
 }
 throw Error('Invalid ferry fallback');
}

E['mutual-match']={init(stage){const n=4+stage,left=range(n).map(()=>shuffle(range(n))),right=range(n).map(()=>shuffle(range(n)));return{n,left,right,pairs:Array(n).fill(-1),chosen:0};},render(c){const m=c.m;c.clue('Preferences run best → worst. A courier and route form a blocking pair only when BOTH prefer each other to their current assignment.');c.cards();range(m.n).forEach(i=>c.palette(`Courier ${letter(i)}`,()=>c.select('chosen',i),'courier-'+i,m.chosen===i));range(m.n).forEach(i=>c.button(`Courier ${letter(i)}\nWants: ${m.left[i].map(x=>x+1).join(' › ')}\nPartner: ${m.pairs[i]<0?'unassigned':'Route '+(m.pairs[i]+1)}`, 'worker-'+i,()=>c.select('chosen',i),'small'+(m.chosen===i?' on':'')));range(m.n).forEach(j=>c.button(`Route ${j+1}\nWants: ${m.right[j].map(letter).join(' › ')}\nCourier: ${m.pairs.includes(j)?letter(m.pairs.indexOf(j)):'none'}`, 'route-'+j,()=>c.act(()=>{const old=m.pairs.indexOf(j),previous=m.pairs[m.chosen];if(old>=0)m.pairs[old]=previous;m.pairs[m.chosen]=j;}),'small'));},check(m){if(m.pairs.includes(-1))return'Every courier needs a route before we can check stability.';for(let a=0;a<m.n;a++)for(let b=0;b<m.n;b++){const other=m.pairs.indexOf(b);if(m.left[a].indexOf(b)<m.left[a].indexOf(m.pairs[a])&&m.right[b].indexOf(a)<m.right[b].indexOf(other))return`Blocking pair: courier ${letter(a)} and route ${b+1} each prefer one another over their current partner.`;}return null;}};
const iceMove=(m,p,d)=>{const trail=[];let q;while((q=step(p,d,m.n,m.walls))!==p){p=q;trail.push(p);}return{p,trail};};
E['ice-station']={init(stage){const n=6;let m;for(;;){const walls=shuffle(range(n*n).slice(1)).slice(0,8+stage*2),visited=new Set([0]),queue=[0];while(queue.length){const p=queue.shift();Object.keys(direction).forEach(d=>{const q=iceMove({n,walls},p,d).p;if(!visited.has(q)){visited.add(q);queue.push(q);}});}if(visited.size<10+stage*2)continue;const stops=[...visited].filter(x=>x!==0),goals=shuffle(stops).slice(0,3+stage),dock=pick(stops),q=[[0,0,0]],seen=new Set(['0,0']);let par=-1;for(let k=0;k<q.length;k++){const[p,mask,depth]=q[k];if(p===dock&&mask===(1<<goals.length)-1){par=depth;break;}Object.keys(direction).forEach(d=>{const next=iceMove({n,walls},p,d);let bits=mask;next.trail.forEach(i=>{const j=goals.indexOf(i);if(j>=0)bits|=1<<j;});const key=next.p+','+bits;if(!seen.has(key)){seen.add(key);q.push([next.p,bits,depth+1]);}});}if(par<6+stage*2)continue;m={n,walls,p:0,goals,got:[],dock,slides:0,par,reachableStops:visited.size};break;}return m;},render(c){const m=c.m;c.clue(`Seals ${m.got.length}/${m.goals.length} · Dock ${Math.floor(m.dock/m.n)+1},${m.dock%m.n+1} · Whole slides ${m.slides} · shortest route ${m.par}. A seal is collected even if you slide past it.`);c.grid(m.n);range(m.n*m.n).forEach(i=>c.button(m.walls.includes(i)?'▦':i===m.p?'●':m.goals.includes(i)&&!m.got.includes(i)?'✦':i===m.dock?'◎':'·','cell-'+i,()=>c.say('Use the four direction buttons to make a complete slide.'),m.walls.includes(i)?'wall':i===m.dock?'goal':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}: ${m.walls.includes(i)?'wall':i===m.p?'skater':m.goals.includes(i)&&!m.got.includes(i)?'uncollected seal':i===m.dock?'dock':'ice'}`));arrows(c,d=>this.move(c,d));},move(c,d){const m=c.m,{p,trail}=iceMove(m,m.p,d);if(p===m.p)return c.say('A wall is immediately ahead; no slide was spent.');c.act(()=>{m.p=p;m.slides++;m.got=[...new Set([...m.got,...trail.filter(x=>m.goals.includes(x))])];});},check(m){return m.goals.some(x=>!m.got.includes(x))?'Some seals remain. Look for a stopping point that opens their row or column.':m.p!==m.dock?'All seals collected. Now stop exactly at the dock.':null;}};
const roll=(o,d)=>{const[t,b,n,s,w,e]=o;return d==='U'?[s,n,t,b,w,e]:d==='D'?[n,s,b,t,w,e]:d==='L'?[e,w,n,s,t,b]:[w,e,n,s,b,t];};
E['cube-seal']={init(stage){const n=4,walls=[[],[5],[5,10]][stage],start=0,orientation=[1,6,2,5,3,4];let p=start,o=[...orientation],seals=[];for(let k=0;k<3+stage;k++){const previous=[p,o[1]];do{for(let j=0;j<4+stage;j++){const ds=Object.keys(direction).filter(d=>step(p,d,n,walls)!==p),d=pick(ds);p=step(p,d,n,walls);o=roll(o,d);}}while(p===previous[0]&&o[1]===previous[1]);seals.push([p,o[1]]);}return{n,walls,p:start,o:orientation,seals,done:0};},render(c){const m=c.m;c.clue(`Cube compass: TOP ${m.o[0]} · BOTTOM ${m.o[1]} · NORTH ${m.o[2]} · SOUTH ${m.o[3]} · WEST ${m.o[4]} · EAST ${m.o[5]}\nSeals in order (row, column → required bottom): ${m.seals.map(([p,v],i)=>`${i<m.done?'✓ ':''}${Math.floor(p/m.n)+1},${p%m.n+1} → bottom ${v}`).join(' | ')}`);c.grid(m.n);range(m.n*m.n).forEach(i=>{const seal=m.seals[m.done];c.button(m.walls.includes(i)?'▦':i===m.p?`${m.o[0]} ↑`:seal&&i===seal[0]?`${seal[1]} ↓`:'·','cell-'+i,()=>c.say('Roll using direction controls; the compass describes every face.'),m.walls.includes(i)?'wall':seal&&i===seal[0]?'goal':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}: ${i===m.p?'cube with top '+m.o[0]:m.walls.includes(i)?'wall':seal&&i===seal[0]?'seal needs bottom '+seal[1]:'floor'}`);});arrows(c,d=>this.move(c,d));},move(c,d){const m=c.m,p=step(m.p,d,m.n,m.walls);if(p===m.p)return c.say('That side is blocked. The cube did not rotate.');c.act(()=>{m.p=p;m.o=roll(m.o,d);const goal=m.seals[m.done];if(goal&&p===goal[0]&&m.o[1]===goal[1]){m.done++;c.say('Seal stamped. The next socket is ready.');}});},check(m){return m.done===m.seals.length?null:`${m.seals.length-m.done} seal(s) remain. Position and bottom face must agree.`;}};
const knight=(a,b,n)=>Math.abs(a%n-b%n)*Math.abs(Math.floor(a/n)-Math.floor(b/n))===2;
E['knight-exchange']={init(stage){const n=4,goal=Array(16).fill(0),positions=[[0,1,14,15],[0,3,12,15],[0,1,2,13,14,15]][stage];positions.forEach((p,i)=>goal[p]=i<positions.length/2?1:2);let cells,previous;do{cells=goal.slice();previous='';for(let k=0;k<14+stage*8;k++){const moves=cells.flatMap((v,a)=>v?range(16).filter(b=>!cells[b]&&knight(a,b,n)&&`${a},${b}`!==previous).map(b=>[a,b]):[]),[a,b]=pick(moves);cells[b]=cells[a];cells[a]=0;previous=`${b},${a}`;}}while(same(cells,goal));return{n,cells,goal,selected:-1};},render(c){const m=c.m;c.clue('Birds: A amber / B blue. Nests are printed under each square. A knight jumps (2,1); intervening pieces do not block it.');c.grid(m.n);range(16).forEach(i=>c.button(`${m.cells[i]?m.cells[i]===1?'A':'B':'·'}${m.goal[i]?' / '+(m.goal[i]===1?'A':'B'):''}`,'cell-'+i,()=>{if(m.cells[i])return c.select('selected',i);if(m.selected<0)return c.say('Choose a bird first.');if(!knight(m.selected,i,m.n))return c.say('That is not an L-shaped knight jump.');c.act(()=>{m.cells[i]=m.cells[m.selected];m.cells[m.selected]=0;m.selected=i;});},(m.selected===i?'on ':m.goal[i]?'goal ':'')+(m.cells[i]?'piece':''),`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}, ${m.cells[i]?'bird '+(m.cells[i]===1?'A':'B'):'empty'}${m.goal[i]?', nest '+(m.goal[i]===1?'A':'B'):''}`));},check(m){return same(m.cells,m.goal)?null:'Every A and B bird must occupy a nest of its own letter.';}};
E['map-inks']={init(stage){const n=7+stage,answer=shuffle(range(n).map(i=>i%3)),edges=[],add=(a,b)=>{const e=[a,b].sort((x,y)=>x-y);if(!edges.some(([x,y])=>x===e[0]&&y===e[1]))edges.push(e);},triangle=range(3).map(v=>answer.indexOf(v));triangle.forEach((a,i)=>add(a,triangle[(i+1)%3]));const linked=new Set(triangle);shuffle(range(n)).forEach(a=>{if(!linked.has(a)){add(a,pick([...linked].filter(b=>answer[b]!==answer[a])));linked.add(a);}});range(n).forEach(a=>range(n).filter(b=>b>a&&answer[a]!==answer[b]&&Math.random()<.35).forEach(b=>add(a,b)));return{n,edges,colors:Array(n).fill(0),ink:1};},render(c){const m=c.m;c.clue('Borders: '+m.edges.map(([a,b])=>`${letter(a)}—${letter(b)}`).join(' · '));c.cards();graph(c,m.n,m.edges);['Erase','1 Amber','2 Teal','3 Plum'].forEach((name,i)=>c.palette(name,()=>c.select('ink',i),'ink-'+i,m.ink===i));range(m.n).forEach(i=>c.button(`District ${letter(i)}\nInk ${m.colors[i]||'unset'}`,'node-'+i,()=>c.act(()=>m.colors[i]=m.ink),m.colors[i]?'on':''));},check(m){if(m.colors.some(x=>!x))return'Give every district an ink.';const edge=m.edges.find(([a,b])=>m.colors[a]===m.colors[b]);return edge?`Border conflict: ${letter(edge[0])} and ${letter(edge[1])} both use ink ${m.colors[edge[0]]}.`:null;}};
E['circuit-break']={init(stage){return relayModel(stage);},render(c){const m=c.m;c.clue(`Disable at most ${m.budget} relays. Offline ${m.off.length}/${m.budget}. Transmitter ${letter(0)} → archive ${letter(m.n-1)}.\nWires: ${m.edges.map(([a,b])=>`${letter(a)}—${letter(b)}`).join(' · ')}`);c.cards();graph(c,m.n,m.edges);range(m.n).forEach(i=>c.button(`${letter(i)} ${i===0?'TRANSMITTER':i===m.n-1?'ARCHIVE':m.off.includes(i)?'OFFLINE':'relay online'}`,'node-'+i,()=>{if(i===0||i===m.n-1)return c.say('Terminals cannot be removed. Find a relay cut.');c.act(()=>m.off=m.off.includes(i)?m.off.filter(x=>x!==i):[...m.off,i]);},i===0||i===m.n-1?'fixed':m.off.includes(i)?'marked':''));},check(m){if(m.off.length>m.budget)return`Too many relays offline: ${m.off.length}, budget ${m.budget}.`;const reached=connected(range(m.n).filter(i=>!m.off.includes(i)),m.edges);return reached.includes(m.n-1)?'The archive still hears the transmitter through the remaining relay network.':null;}};
function mst(n,edges){const parent=range(n),root=a=>parent[a]===a?a:(parent[a]=root(parent[a]));let cost=0;[...edges].sort((a,b)=>a[2]-b[2]).forEach(([a,b,w])=>{a=root(a);b=root(b);if(a!==b){parent[a]=b;cost+=w;}});return cost;}
E['copper-tree']={init(stage){const n=6+stage,edges=range(n).flatMap(a=>range(n).filter(b=>b>a&&(b===a+1||Math.random()<.4)).map(b=>[a,b,1+Math.floor(Math.random()*9)]));return{n,edges,picked:[],budget:mst(n,edges)};},render(c){const m=c.m;c.clue(`Copper ${sum(m.picked.map(i=>m.edges[i][2]))}/${m.budget}. Connect all ${m.n} villages with ${m.n-1} links and no loop.`);c.cards();graph(c,m.n,m.edges);m.edges.forEach(([a,b,w],i)=>c.button(`${letter(a)}—${letter(b)} · ${w} copper`,'edge-'+i,()=>c.act(()=>m.picked=m.picked.includes(i)?m.picked.filter(x=>x!==i):[...m.picked,i]),m.picked.includes(i)?'on':''));},check(m){const edges=m.picked.map(i=>m.edges[i]),reached=connected(range(m.n),edges);if(reached.length<m.n)return`The village of ${letter(range(m.n).find(i=>!reached.includes(i)))} is disconnected.`;if(edges.length!==m.n-1)return'The network contains a loop. A connected tree has exactly one fewer link than villages.';const cost=sum(edges.map(e=>e[2]));return cost>m.budget?`Connected, but ${cost-m.budget} copper over the minimum budget.`:null;}};
function maxflow(n,edges){const cap=range(n).map(()=>Array(n).fill(0));edges.forEach(([a,b,w])=>cap[a][b]=w);let total=0;for(;;){const prev=Array(n).fill(-1),q=[0];prev[0]=0;while(q.length&&prev[n-1]<0){const a=q.shift();range(n).forEach(b=>{if(prev[b]<0&&cap[a][b]>0){prev[b]=a;q.push(b);}});}if(prev[n-1]<0)break;let flow=Infinity;for(let b=n-1;b!==0;b=prev[b])flow=Math.min(flow,cap[prev[b]][b]);for(let b=n-1;b!==0;b=prev[b]){cap[prev[b]][b]-=flow;cap[b][prev[b]]+=flow;}total+=flow;}return total;}
E['river-capacity']={init(stage){return riverModel(stage);},render(c){const m=c.m,names=['S',...range(m.n-2).map(letter),'T'],bal=Array(m.n).fill(0);m.edges.forEach(([a,b],i)=>{bal[a]-=m.flow[i];bal[b]+=m.flow[i];});c.clue(`Deliver ${m.target} units to T. Current arrival: ${bal[m.n-1]}. Basin balance (in minus out): ${range(m.n).slice(1,-1).map(i=>`${names[i]} ${bal[i]}`).join(' · ')}`);c.cards();graph(c,m.n,m.edges.map(([a,b,w],i)=>[a,b,m.flow[i]+'/'+w]),names);m.edges.forEach(([a,b,cap],i)=>c.button(`${names[a]} → ${names[b]}\nFlow ${m.flow[i]} / capacity ${cap}`,'edge-'+i,()=>c.act(()=>m.flow[i]=(m.flow[i]+1)%(cap+1)),'small'+(m.flow[i]?' on':'')));},check(m){const bal=Array(m.n).fill(0);m.edges.forEach(([a,b],i)=>{bal[a]-=m.flow[i];bal[b]+=m.flow[i];});const bad=range(m.n).slice(1,-1).find(i=>bal[i]!==0);return bad!==undefined?`Basin ${letter(bad-1)} has ${Math.abs(bal[bad])} more units ${bal[bad]>0?'in than out':'out than in'}.`:bal[m.n-1]!==m.target?`Conserved, but delivery is ${bal[m.n-1]}; the harbor needs ${m.target}.`:null;}};
const claim=(r,v)=>r.op==='same'?v[r.a]===v[r.b]:r.op==='different'?v[r.a]!==v[r.b]:r.op==='both'?v[r.a]&&v[r.b]:r.op==='either'?v[r.a]||v[r.b]:!v[r.a];
E['honest-company']={init(stage){const n=5+stage;let claims;do{const answer=range(n).map(()=>Math.random()<.5),used=new Set();claims=range(n).map(i=>{let r,key;do{r={a:Math.floor(Math.random()*n),b:Math.floor(Math.random()*n),op:pick(['same','different','both','either','not'])};key=r.op+':'+(r.op==='not'?r.a:[r.a,r.b].sort().join(','));}while(r.a===r.b||used.has(key)||Boolean(claim(r,answer))!==answer[i]);used.add(key);return r;});}while(range(1<<n).filter(bits=>{const v=range(n).map(i=>Boolean(bits>>i&1));return claims.every((r,i)=>Boolean(claim(r,v))===v[i]);}).length!==1);return{n,claims,values:Array(n).fill(-1)};},render(c){const m=c.m;c.clue('H = honest; L = liar; ? = undecided. Every speaker’s assigned nature must agree with the truth of their whole statement.');c.cards();m.claims.forEach((r,i)=>{const a=letter(r.a),b=letter(r.b),s=r.op==='same'?`${a} and ${b} have the same nature.`:r.op==='different'?`${a} and ${b} have different natures.`:r.op==='both'?`${a} and ${b} are both honest.`:r.op==='either'?`At least one of ${a} and ${b} is honest.`:`${a} is a liar.`;c.button(`${letter(i)} says: “${s}”\nAssign: ${m.values[i]<0?'?':m.values[i]?'H':'L'}`,'speaker-'+i,()=>c.act(()=>m.values[i]=m.values[i]===-1?1:m.values[i]===1?0:-1),'small'+(m.values[i]>=0?' on':''));});},check(m){if(m.values.includes(-1))return'Assign every speaker either H or L.';const wrong=m.claims.findIndex((r,i)=>Boolean(claim(r,m.values))!==Boolean(m.values[i]));return wrong<0?null:`Speaker ${letter(wrong)} is marked ${m.values[wrong]?'honest but says something false':'lying but says something true'}.`;}};
const gateNames=['AND','OR','XOR','NAND','NOR'],gate=(type,a,b)=>type===0?a&b:type===1?a|b:type===2?a^b:type===3?1-(a&b):1-(a|b);
function outputs(m,gates){return range(8).map(i=>{const v=[i>>2&1,i>>1&1,i&1];m.wires.forEach(([a,b],j)=>v.push(gate(gates[j],v[a],v[b])));return v.at(-1);});}
E['gate-foundry']={init(stage){const wires=[[[0,1],[1,2],[3,4]],[[0,1],[1,2],[0,4],[3,5]],[[0,1],[1,2],[0,4],[2,3],[5,6]]][stage];let m,target;do{m={wires,gates:wires.map(()=>0)};target=outputs(m,wires.map(()=>Math.floor(Math.random()*5)));}while(target.every(x=>x===target[0])||same(target,outputs(m,m.gates)));return{...m,target};},render(c){const m=c.m,current=outputs(m,m.gates),name=i=>i<3?['A','B','C'][i]:'G'+(i-2);c.clue('A B C → target / your output\n'+range(8).map(i=>`${i>>2&1} ${i>>1&1} ${i&1} → ${m.target[i]} / ${current[i]} ${m.target[i]===current[i]?'✓':'×'}`).join('\n'));c.cards();m.wires.forEach(([a,b],i)=>c.button(`G${i+1} = ${name(a)} ${gateNames[m.gates[i]]} ${name(b)}\nTap to cycle gate`,'gate-'+i,()=>c.act(()=>m.gates[i]=(m.gates[i]+1)%5),'small'));c.extra('Gate reference',()=>c.say('AND: both 1. OR: either 1. XOR: exactly one 1. NAND: opposite of AND. NOR: opposite of OR.'),'reference');},check(m){const got=outputs(m,m.gates),bad=got.findIndex((x,i)=>x!==m.target[i]);return bad<0?null:`Input ${bad>>2&1}${bad>>1&1}${bad&1} produces ${got[bad]}, but needs ${m.target[bad]}.`;}};
const occurrences=(s,from)=>range(s.length).filter(i=>s.slice(i,i+from.length)===from),rewrite=(s,rule,i)=>s.slice(0,i)+rule[1]+s.slice(i+rule[0].length);
E['rewrite-press']={init(stage){const rules=[[['AB','BA'],['AA','B'],['B','AA'],['BA','C'],['C','AB']],[['AB','C'],['CA','AC'],['CC','B'],['B','CA'],['AC','BA']],[['AB','BC'],['BC','CA'],['AA','B'],['CC','A'],['B','AB']]][stage],start=['AABA','ABACA','AABB'][stage],queue=[[start,0]],seen=new Set([start]),choices=[];while(queue.length&&seen.size<14000){const [s,d]=queue.shift();if(d>=4+stage)choices.push([s,d]);if(d>=6+stage)continue;rules.forEach(r=>occurrences(s,r[0]).forEach(i=>{const t=rewrite(s,r,i);if(t.length<=10&&!seen.has(t)){seen.add(t);queue.push([t,d+1]);}}));}const[target,budget]=pick(choices);return{rules,start,ribbon:start,target,budget,used:0,rule:0};},render(c){const m=c.m;c.clue(`Target: ${m.target}\nRibbon: ${m.ribbon}\nRewrites ${m.used}/${m.budget}. Selected rule ${m.rules[m.rule].join(' → ')}.`);c.cards();m.rules.forEach((r,i)=>c.palette(r.join(' → '),()=>c.select('rule',i),'rule-'+i,m.rule===i));range(m.ribbon.length).forEach(i=>c.button(`${m.ribbon[i]}\nPosition ${i+1}`,'char-'+i,()=>{const r=m.rules[m.rule];if(!occurrences(m.ribbon,r[0]).includes(i))return c.say(`Rule needs ${r[0]} beginning at the selected position.`);if(m.used>=m.budget)return c.say('Rewrite budget spent. Undo or reset this study to try another route.');if(m.ribbon.length-r[0].length+r[1].length>12)return c.say('The ribbon tray holds at most twelve symbols.');c.act(()=>{m.ribbon=rewrite(m.ribbon,r,i);m.used++;});},occurrences(m.ribbon,m.rules[m.rule][0]).includes(i)?'on small':'small'));},check(m){return m.ribbon===m.target?null:`The ribbon is ${m.ribbon}; the target is ${m.target}. ${m.budget-m.used} rewrites remain.`;}};
const twinStep=(m,a,b,d)=>[step(a,d,m.n,m.wallsA),step(b,opposite[d],m.n,m.wallsB)];
E['twin-steps']={init(stage){const n=4+stage,wallsA=shuffle(range(n*n).slice(1)).slice(0,stage+3),wallsB=shuffle(range(n*n).slice(0,-1)).slice(0,stage+4),a=0,b=n*n-1,q=[[a,b,0]],seen=new Set([a+','+b]);let far=q[0];while(q.length){const state=q.shift();if(state[2]>far[2])far=state;Object.keys(direction).forEach(d=>{const[x,y]=twinStep({n,wallsA,wallsB},state[0],state[1],d),key=x+','+y;if(!seen.has(key)){seen.add(key);q.push([x,y,state[2]+1]);}});}if(far[2]<n)return this.init(stage);return{n,wallsA,wallsB,a,b,goalA:far[0],goalB:far[1],par:far[2]};},render(c){const m=c.m;c.clue('Amber follows your direction; blue moves opposite. A blocked walker waits while the other continues. Both docks must be occupied together.');c.grid(m.n);[['Amber',m.a,m.goalA,m.wallsA],['Blue',m.b,m.goalB,m.wallsB]].forEach(([name,p,g,walls],k)=>{c.heading(name+' maze');range(m.n*m.n).forEach(i=>c.button(walls.includes(i)?'▦':i===p?k?'B':'A':i===g?'◎':'·','maze-'+k+'-'+i,()=>c.say('Use a direction control to move both walkers.'),walls.includes(i)?'wall':i===g?'goal':'',`${name}, row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}, ${walls.includes(i)?'wall':i===p?'walker':i===g?'dock':'floor'}`));});arrows(c,d=>this.move(c,d));},move(c,d){const m=c.m,[a,b]=twinStep(m,m.a,m.b,d);if(a===m.a&&b===m.b)return c.say('Both walkers are blocked. No move was spent.');c.act(()=>{m.a=a;m.b=b;});},check(m){return m.a===m.goalA&&m.b===m.goalB?null:`${m.a===m.goalA?'Amber is docked.':'Amber needs its dock.'} ${m.b===m.goalB?'Blue is docked.':'Blue needs its dock.'}`;}};
const gardenDescription=(bits,n)=>range(n).map(i=>`Cell ${i+1}: ${bits>>i&1?'live':'empty'}`).join(' · ');
E['seed-tomorrow']={
 init(stage){return gardenModel(stage);},
 render(c){
  const m=c.m,edited=m.pending<0?m.cells:m.cells^(1<<m.pending),preview=gardenNext(edited,m.n);
  c.clue(`Day ${m.day}/${m.days} · Interventions ${m.used}/${m.budget}. One plant OR prune per day; waiting costs none. Ends wrap.\n`+
   `FINAL TARGET: ${gardenDescription(m.target,m.n)}\nCURRENT: ${gardenDescription(m.cells,m.n)}\n`+
   (m.day<m.days?`Pending: ${m.pending<0?'wait; no intervention':`${m.cells>>m.pending&1?'prune':'plant'} cell ${m.pending+1}`}. NEXT DAY PREVIEW: ${gardenDescription(preview,m.n)}`:'The final day has arrived. Check the target, or Undo a day to revise your plan.'));
  c.cards();
  range(m.n).forEach(i=>c.button(`Cell ${i+1}: ${m.cells>>i&1?'live':'empty'}\nTarget: ${m.target>>i&1?'live':'empty'}${m.pending===i?'\nSelected intervention':''}`,'seed-'+i,()=>{
   if(m.day===m.days)return c.say('No days remain. Undo a day or reset the study.');
   if(m.pending!==i&&m.used>=m.budget)return c.say('Intervention budget spent. You may wait and advance, Undo a day, or reset.');
   c.select('pending',m.pending===i?-1:i);
  },m.pending===i?'on small':'small',`Cell ${i+1}, currently ${m.cells>>i&1?'live':'empty'}, final target ${m.target>>i&1?'live':'empty'}${m.pending===i?', selected to '+(m.cells>>i&1?'prune':'plant'):''}`));
  c.extra('Wait: clear selection',()=>c.select('pending',-1),'wait');
  c.extra('Advance one day',()=>{
   if(m.day===m.days)return c.say('All days have elapsed. Check the target or Undo a day.');
   if(m.pending>=0&&m.used>=m.budget)return c.say('No interventions remain. Choose Wait before advancing.');
   c.act(()=>{const edit=m.pending;m.cells=gardenNext(edit<0?m.cells:m.cells^(1<<edit),m.n);m.used+=edit>=0?1:0;m.day++;m.timeline.push({day:m.day,cells:m.cells,edit});m.pending=-1;});
   c.say(`Day ${m.day} has grown. ${m.days-m.day} day(s) and ${m.budget-m.used} intervention(s) remain.`);
  },'advance');
  c.heading('Growth rule — all cells update together after the intervention');
  c.heading('Left / current / right → next state');
  range(8).forEach(bits=>{const left=bits>>2&1,live=bits>>1&1,right=bits&1,next=live?(left+right===1):(left+right===2);c.heading(`${left?'live':'empty'} / ${live?'live':'empty'} / ${right?'live':'empty'} → ${next?'live':'empty'}`);});
  c.heading('Day history');m.timeline.forEach(t=>c.heading(`Day ${t.day}${t.day?` (after ${t.edit<0?'waiting':'intervention at cell '+(t.edit+1)})`:''}: ${gardenDescription(t.cells,m.n)}`));
 },
 check(m){if(m.day<m.days)return `Advance through all ${m.days} days before checking the final garden.`;return m.cells===m.target?null:'The final garden differs from the target. Undo one or more days to change the timing of your interventions.';}
};
function projections(cells){const out=[Array(9).fill(0),Array(9).fill(0),Array(9).fill(0)];cells.forEach((v,i)=>{const x=i%3,y=Math.floor(i/3)%3,z=Math.floor(i/9);out[0][z*3+y]+=v;out[1][z*3+x]+=v;out[2][y*3+x]+=v;});return out;}
E['voxel-post']={init(stage){let answer;do{answer=range(27).map(()=>Math.random()<(.28+stage*.1)?1:0);}while(!answer.some(Boolean));return{cells:Array(27).fill(0),target:projections(answer)};},render(c){const m=c.m,p=projections(m.cells);c.clue(['X view (each layer: north → south)','Y view (each layer: west → east)','Z view (each row: west → east)'].map((name,k)=>name+'\n'+range(3).map(r=>range(3).map(x=>`${p[k][r*3+x]}/${m.target[k][r*3+x]}`).join('  ')).join('\n')).join('\n\n')+'\nEach entry is current / required.');c.grid(3);range(27).forEach(i=>{if(i%9===0)c.heading(`Layer ${Math.floor(i/9)+1} (${i===0?'bottom':i===9?'middle':'top'})`);c.button(m.cells[i]?'■':'·','voxel-'+i,()=>c.act(()=>m.cells[i]=1-m.cells[i]),m.cells[i]?'on':'',`Layer ${Math.floor(i/9)+1}, row ${Math.floor(i/3)%3+1}, column ${i%3+1}: ${m.cells[i]?'block':'empty'}`);});},check(m){const p=projections(m.cells);for(let k=0;k<3;k++)for(let i=0;i<9;i++)if(p[k][i]!==m.target[k][i])return`${['X','Y','Z'][k]} projection, line ${i+1}: ${p[k][i]} blocks, needs ${m.target[k][i]}.`;return null;}};
E['hitori-harbor']={init(stage){const n=5,base=shuffle([1,2,3,4,5]),cells=range(n*n).map(i=>base[(Math.floor(i/n)+i%n)%n]);let shaded;do{shaded=[];shuffle(range(n*n)).forEach(i=>{if(shaded.length<5+stage&&!adj(i,n).some(j=>shaded.includes(j)))shaded.push(i);});}while(connected(range(n*n).filter(i=>!shaded.includes(i)),gridEdges(n)).length!==n*n-shaded.length);shaded.forEach(i=>{const options=range(n*n).filter(j=>j!==i&&!shaded.includes(j)&&(Math.floor(j/n)===Math.floor(i/n)||j%n===i%n));cells[i]=cells[pick(options)];});return{n,cells,shaded:[]};},render(c){const m=c.m;c.clue('Shade to remove numbers. Remaining cells must connect orthogonally; diagonals do not connect. Shaded cells cannot share an edge.');c.grid(m.n);m.cells.forEach((v,i)=>c.button(m.shaded.includes(i)?'× '+v:String(v),'cell-'+i,()=>c.act(()=>m.shaded=m.shaded.includes(i)?m.shaded.filter(x=>x!==i):[...m.shaded,i]),m.shaded.includes(i)?'marked':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}, number ${v}, ${m.shaded.includes(i)?'shaded':'unshaded'}`));},check(m){const white=range(m.n*m.n).filter(i=>!m.shaded.includes(i));const touch=m.shaded.find(i=>adj(i,m.n).some(j=>m.shaded.includes(j)));if(touch!==undefined)return`Shaded cells touch beside row ${Math.floor(touch/m.n)+1}, column ${touch%m.n+1}.`;if(connected(white,gridEdges(m.n)).length!==white.length)return'The unshaded town has split into separate parts.';for(let r=0;r<m.n;r++)for(const axis of ['row','column']){const line=white.filter(i=>axis==='row'?Math.floor(i/m.n)===r:i%m.n===r),values=line.map(i=>m.cells[i]);if(new Set(values).size!==values.length)return`Repeated unshaded number in ${axis} ${r+1}.`;}return null;}};
function components(nodes,n){const result=[],remaining=new Set(nodes);while(remaining.size){const start=[...remaining][0],q=[start],group=[];remaining.delete(start);while(q.length){const p=q.shift();group.push(p);adj(p,n).forEach(j=>{if(remaining.has(j)){remaining.delete(j);q.push(j);}});}result.push(group);}return result;}
function seaSquare(sea,n){return range(n*n).find(i=>i%n<n-1&&i<n*(n-1)&&[i,i+1,i+n,i+n+1].every(j=>sea.includes(j)));}
E['island-census']={init(stage){const n=5;let land,sea,groups;do{land=range(25).filter(()=>Math.random()<(.43+stage*.015));sea=range(25).filter(i=>!land.includes(i));groups=components(land,n);}while(!sea.length||components(sea,n).length!==1||seaSquare(sea,n)!==undefined||groups.length<3||groups.some(g=>g.length>7)||groups.length>7);const clues=groups.map(g=>[pick(g),g.length]);return{n,clues,cells:range(25).map(i=>clues.some(c=>c[0]===i)?1:0)};},render(c){const m=c.m;c.clue('○ unknown · LAND · ≈ sea. Each lighthouse number counts its whole island. Every unnumbered cell must be explicitly marked land or sea.');c.grid(m.n);m.cells.forEach((v,i)=>{const clue=m.clues.find(c=>c[0]===i);c.button(clue?String(clue[1]):v===0?'○':v===1?'LAND':'≈','cell-'+i,()=>{if(clue)return c.say('A lighthouse is fixed land. Its number is the total island area.');c.act(()=>m.cells[i]=(m.cells[i]+1)%3);},clue?'fixed':v===1?'on':v===2?'marked':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}, ${clue?'lighthouse '+clue[1]:v===0?'unknown':v===1?'land':'sea'}`);});},check(m){if(m.cells.includes(0))return'Mark every unknown cell as land or sea.';const land=range(25).filter(i=>m.cells[i]===1),sea=range(25).filter(i=>m.cells[i]===2);for(const group of components(land,m.n)){const clues=m.clues.filter(c=>group.includes(c[0]));if(clues.length!==1)return`An island has ${clues.length} lighthouses; it needs exactly one.`;if(group.length!==clues[0][1])return`Lighthouse ${clues[0][1]} has ${group.length} land cells; it needs exactly ${clues[0][1]}.`;}if(components(sea,m.n).length!==1)return'The sea must form one connected region.';const square=seaSquare(sea,m.n);return square===undefined?null:`A 2 by 2 sea square begins at row ${Math.floor(square/m.n)+1}, column ${square%m.n+1}.`;}};
const rectangle=(a,b,n)=>{const x1=Math.min(a%n,b%n),x2=Math.max(a%n,b%n),y1=Math.min(Math.floor(a/n),Math.floor(b/n)),y2=Math.max(Math.floor(a/n),Math.floor(b/n));return range(n*n).filter(i=>i%n>=x1&&i%n<=x2&&Math.floor(i/n)>=y1&&Math.floor(i/n)<=y2);};
E['parcel-survey']={init(stage){const n=stage===2?6:5,rects=[[0,0,n,n]];while(rects.length<6+stage*2){const options=rects.map((r,i)=>[r,i]).filter(([r])=>r[2]*r[3]>=4&&(r[2]>1||r[3]>1));if(!options.length)break;const[r,i]=pick(options),vertical=r[2]>1&&(r[3]===1||Math.random()<.5),cut=1+Math.floor(Math.random()*((vertical?r[2]:r[3])-1));rects.splice(i,1,...(vertical?[[r[0],r[1],cut,r[3]],[r[0]+cut,r[1],r[2]-cut,r[3]]]:[[r[0],r[1],r[2],cut],[r[0],r[1]+cut,r[2],r[3]-cut]]));}const clues=rects.map(([x,y,w,h])=>[(y+Math.floor(Math.random()*h))*n+x+Math.floor(Math.random()*w),w*h]);return{n,clues,rects:[],anchor:-1};},render(c){const m=c.m;c.clue(`Covered ${sum(m.rects.map(r=>r.length))}/${m.n*m.n}. ${m.anchor<0?'Choose the first corner of a rectangle.':`First corner: row ${Math.floor(m.anchor/m.n)+1}, column ${m.anchor%m.n+1}. Choose the opposite corner.`}`);c.grid(m.n);range(m.n*m.n).forEach(i=>{const clue=m.clues.find(c=>c[0]===i),region=m.rects.findIndex(r=>r.includes(i));c.button((clue?String(clue[1]):'·')+(region>=0?' '+letter(region):''),'cell-'+i,()=>{if(region>=0){c.act(()=>{m.rects.splice(region,1);m.anchor=-1;});return;}if(m.anchor<0)return c.select('anchor',i);const r=rectangle(m.anchor,i,m.n),clues=m.clues.filter(c=>r.includes(c[0]));if(r.some(j=>m.rects.some(other=>other.includes(j))))return c.say('That rectangle overlaps a finished parcel. Choose a different corner.');if(clues.length!==1)return c.say(`That rectangle contains ${clues.length} stakes; it needs exactly one.`);if(r.length!==clues[0][1])return c.say(`Area ${r.length} does not match stake ${clues[0][1]}. Choose a different corner.`);c.act(()=>{m.rects.push(r);m.anchor=-1;});},m.anchor===i?'marked':region>=0?'on':clue?'fixed':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}${clue?', stake area '+clue[1]:''}${region>=0?', parcel '+letter(region):', uncovered'}`);});c.extra('Cancel corner',()=>c.select('anchor',-1),'cancel');},check(m){return sum(m.rects.map(r=>r.length))===m.n*m.n?null:'Some ground is still uncovered. Every cell needs exactly one parcel.';}};
function cycle(n,edges){const state=Array(n).fill(0),trail=[];let found=null;const visit=a=>{state[a]=1;trail.push(a);for(const[x,b]of edges){if(x!==a)continue;if(state[b]===1){found=[...trail.slice(trail.indexOf(b)),b];return true;}if(state[b]===0&&visit(b))return true;}trail.pop();state[a]=2;return false;};for(let i=0;i<n;i++)if(state[i]===0&&visit(i))return found;return null;}
const subsets=(n,k)=>{const result=[],walk=(a,start)=>{if(a.length===k){result.push(a);return;}for(let i=start;i<n;i++)walk([...a,i],i+1);};walk([],0);return result;};
E['arrow-audit']={init(stage){const n=5+stage,order=shuffle(range(n)),edges=[];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)if(b===a+1||Math.random()<.45)edges.push([order[a],order[b]]);let initial,budget;do{const rev=shuffle(range(edges.length)).slice(0,2+stage);initial=edges.map((e,i)=>rev.includes(i)?[e[1],e[0]]:[...e]);budget=0;while(budget<4&&cycle(n,initial)&&!subsets(initial.length,budget).some(set=>!cycle(n,initial.map((e,i)=>set.includes(i)?[e[1],e[0]]:e))))budget++;}while(!cycle(n,initial)||budget>3);return{n,edges:initial,flipped:[],budget};},render(c){const m=c.m;c.clue(`Reversals ${m.flipped.length}/${m.budget}. Every task must admit an order with all arrows pointing forward. No task labels imply a correct order.`);c.cards();m.edges.forEach(([a,b],i)=>{const rev=m.flipped.includes(i);c.button(`${letter(rev?b:a)} → ${letter(rev?a:b)}${rev?' · reversed':''}`,'edge-'+i,()=>c.act(()=>m.flipped=rev?m.flipped.filter(x=>x!==i):[...m.flipped,i]),rev?'on':'');});},check(m){if(m.flipped.length>m.budget)return`Over the reversal budget by ${m.flipped.length-m.budget}.`;const loop=cycle(m.n,m.edges.map((e,i)=>m.flipped.includes(i)?[e[1],e[0]]:e));return loop?'Circular promises: '+loop.map(letter).join(' → '):null;}};
function parity(a,n){return[...range(n).map(r=>sum(a.slice(r*n,r*n+n))%2),...range(n).map(c=>sum(range(n).map(r=>a[r*n+c]))%2),...range(n).map(d=>sum(range(n).map(r=>a[r*n+(d-r+n)%n]))%2)];}
E['parity-repair']={init(stage){const n=4+stage,original=range(n*n).map(()=>Math.random()<.5?1:0),target=parity(original,n),bad=shuffle(range(n*n)).slice(0,stage===0?2:3),received=original.map((v,i)=>bad.includes(i)?1-v:v);return{n,target,received,cells:received.slice(),budget:bad.length};},render(c){const m=c.m,p=parity(m.cells,m.n),edited=m.cells.filter((v,i)=>v!==m.received[i]).length;c.clue(`Changed bits ${edited}/${m.budget}. Every entry shows current / expected parity (0 even, 1 odd).\nRows: ${range(m.n).map(i=>`${p[i]}/${m.target[i]}`).join(' · ')}\nColumns: ${range(m.n).map(i=>`${p[m.n+i]}/${m.target[m.n+i]}`).join(' · ')}\nDiagonals: ${range(m.n).map(i=>`${p[2*m.n+i]}/${m.target[2*m.n+i]}`).join(' · ')}\nWrapping diagonal d contains cells where (row + column − 2) modulo ${m.n} equals d; diagonals are numbered 0 to ${m.n-1}.`);c.grid(m.n);m.cells.forEach((v,i)=>c.button(`${v}${v!==m.received[i]?' *':''}`,'bit-'+i,()=>c.act(()=>m.cells[i]=1-m.cells[i]),v!==m.received[i]?'on':'',`Row ${Math.floor(i/m.n)+1}, column ${i%m.n+1}: bit ${v}; received ${m.received[i]}; diagonal ${(Math.floor(i/m.n)+i%m.n)%m.n}`));},check(m){const changed=m.cells.filter((v,i)=>v!==m.received[i]).length;if(changed>m.budget)return`${changed} bits changed; the budget is ${m.budget}.`;const p=parity(m.cells,m.n),bad=p.findIndex((v,i)=>v!==m.target[i]);return bad<0?null:`${bad<m.n?'Row '+(bad+1):bad<2*m.n?'Column '+(bad-m.n+1):'Diagonal '+(bad-2*m.n)} checksum still disagrees.`;}};
function ferrySafe(m,banks,boat){return m.conflicts.find(([a,b])=>banks[a]===banks[b]&&banks[a]!==boat);}
E['safety-ferry']={init(stage){return ferryModel(stage);},render(c){const m=c.m;c.clue(`Ferry on ${m.boat?'far':'near'} bank · capacity ${m.capacity} · crossings ${m.trips} · shortest safe journey ${m.par}\nNever leave together without you: ${m.conflicts.map(([a,b])=>`${m.names[a]} + ${m.names[b]}`).join(' | ')}\nNear bank: ${m.names.filter((_,i)=>!m.banks[i]).join(', ')||'empty'}\nFar bank: ${m.names.filter((_,i)=>m.banks[i]).join(', ')||'empty'}`);c.cards();m.names.forEach((name,i)=>c.button(`${name}\n${m.banks[i]?'Far':'Near'} bank${m.cargo.includes(i)?' · aboard':''}`,'cargo-'+i,()=>{if(m.banks[i]!==m.boat)return c.say('That cargo is on the opposite bank. Sail back first.');if(!m.cargo.includes(i)&&m.cargo.length>=m.capacity)return c.say(`The ferry carries at most ${m.capacity}. Unselect a passenger first.`);c.select('cargo',m.cargo.includes(i)?m.cargo.filter(x=>x!==i):[...m.cargo,i]);},m.cargo.includes(i)?'on small':'small'));c.extra('Sail across',()=>{const banks=m.banks.map((b,i)=>m.cargo.includes(i)?1-b:b),boat=1-m.boat,bad=ferrySafe(m,banks,boat);if(bad)return c.say(`Unsafe crossing: ${m.names[bad[0]]} and ${m.names[bad[1]]} would be left together without you.`);c.act(()=>{m.banks=banks;m.boat=boat;m.cargo=[];m.trips++;});},'sail');},check(m){return m.banks.every(Boolean)?null:`${m.banks.filter(v=>!v).length} passenger(s) remain on the near bank.`;}};
window.PuzzleEngines=E;
})();
