(() => {
'use strict';
const $=id=>document.getElementById(id),requested=new URLSearchParams(location.search).get('game'),meta=PuzzleGames.find(g=>g.id===requested)||PuzzleGames[0],engine=PuzzleEngines[meta.id];
document.title=meta.name+' — Small Hours';$('title').textContent=meta.name;$('description').textContent=meta.description;$('mechanic').textContent=meta.mechanic;$('controls').textContent=meta.controls;document.documentElement.style.setProperty('--accent',meta.accent);meta.rules.forEach(rule=>{const li=document.createElement('li');li.textContent=rule;$('rules').append(li);});
let model,initial,stage=0,moves=0,checks=0,history=[],started=false,complete=false,journey=false;
const clone=x=>JSON.parse(JSON.stringify(x));
function say(text){$('status').textContent=text;}
function act(fn){if(!started||complete)return;history.push(clone(model));fn();moves++;render();}
function select(key,value){if(!started||complete)return;model[key]=value;render();}
function button(parent,text,key,fn,cls='',label){const b=document.createElement('button');b.textContent=text;b.dataset.key=key;b.className=cls;b.setAttribute('aria-label',label||text.replace(/\n/g,', '));if(cls.includes('on')||cls.includes('selected'))b.setAttribute('aria-pressed','true');b.addEventListener('click',()=>{if(!complete)fn();});parent.append(b);return b;}
const context=()=>({m:model,board:$('board'),act,select,say,clue:text=>$('clues').textContent=text,grid:n=>{$('board').className='grid';$('board').style.setProperty('--n',n);},cards:()=>{$('board').className='cards';},button:(text,key,fn,cls,label)=>button($('board'),text,key,fn,cls,label),palette:(text,fn,key,pressed)=>button($('palette'),text,key,fn,pressed?'selected':''),extra:(text,fn,key)=>button($('extra'),text,key,fn),heading:text=>{const el=document.createElement('div');el.className='layer-title';el.textContent=text;$('board').append(el);}});
function render(){const focused=document.activeElement?.dataset?.key;$('clues').textContent='';$('board').replaceChildren();$('palette').replaceChildren();$('extra').replaceChildren();engine.render(context());$('study').textContent=`${stage+1} / 3`;$('moves').textContent=moves;$('checks').textContent=checks;$('undo').disabled=complete||!history.length;$('check').disabled=complete;$('reset').disabled=complete;$('board').querySelectorAll('button').forEach(b=>b.disabled=complete);$('palette').querySelectorAll('button').forEach(b=>b.disabled=complete);$('extra').querySelectorAll('button').forEach(b=>b.disabled=complete);if(focused&&!complete){const el=[...document.querySelectorAll('[data-key]')].find(el=>el.dataset.key===focused);if(el)el.focus({preventScroll:true});else $('check').focus({preventScroll:true});}}
function study(){model=engine.init(stage);initial=clone(model);history=[];complete=false;$('result').hidden=true;say(`Study ${stage+1}: ${meta.description}`);render();}
function restart(){stage=0;moves=0;checks=0;started=false;complete=false;journey=false;history=[];$('play').hidden=true;$('start').hidden=false;$('result').hidden=true;$('study').textContent='1 / 3';$('moves').textContent='0';$('checks').textContent='0';document.body.dataset.outcome='ready';say('Three studies. All the time you need.');}
$('start').addEventListener('click',()=>{if(started)return;started=true;$('start').hidden=true;$('play').hidden=false;document.body.dataset.outcome='playing';study();$('board').querySelector('button')?.focus({preventScroll:true});});
$('restart').addEventListener('click',()=>{restart();$('start').focus({preventScroll:true});});
$('reset').addEventListener('click',()=>{if(complete)return;model=clone(initial);history=[];say('Same study, fresh approach. Earlier studies are kept.');render();});
$('undo').addEventListener('click',()=>{if(complete||!history.length)return;model=history.pop();moves=Math.max(0,moves-1);say('Last edit undone.');render();});
$('check').addEventListener('click',()=>{if(!started||complete)return;checks++;const error=engine.check(model);if(error){say(error);render();return;}complete=true;journey=stage===2;$('result').hidden=false;$('result-title').textContent=journey?'A little clarity.':'Study complete.';$('result-copy').textContent=journey?`Three distinct studies solved in ${moves} edits and ${checks} checks.`:'Every condition agrees. The next study asks a little more.';$('next').textContent=journey?'Begin a new journey':'Next study →';document.body.dataset.outcome=journey?'win':'study';say(journey?'Journey complete. All three studies solved.':`Study ${stage+1} complete.`);render();$('next').focus({preventScroll:true});});
$('next').addEventListener('click',()=>{if(journey){restart();$('start').focus();}else{stage++;document.body.dataset.outcome='playing';study();$('board').querySelector('button')?.focus({preventScroll:true});}});
document.addEventListener('keydown',e=>{if(!started||complete||e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,select,textarea'))return;const d={ArrowUp:'U',ArrowDown:'D',ArrowLeft:'L',ArrowRight:'R'}[e.key];if(d&&engine.move&&$('play').contains(document.activeElement)){e.preventDefault();engine.move(context(),d);}});
restart();document.body.dataset.gameId=meta.id;document.body.dataset.gameReady='true';
})();
