const {chromium}=require('playwright');const fs=require('fs');const path=require('path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');const manifest=JSON.parse(fs.readFileSync(path.join(root,'arcade-room/games.json')));const source=fs.readFileSync(path.join(root,'arcade-room/room.js'),'utf8');const base=process.env.BASE_URL||'http://127.0.0.1:8790';const coverage=process.env.RESUME&&fs.existsSync(path.join(__dirname,'../coverage/arcade-room.json'))?JSON.parse(fs.readFileSync(path.join(__dirname,'../coverage/arcade-room.json'))).games:[];const errors=[];let browser;
const snapshot=p=>p.evaluate(()=>window.__arcade());const time=(p,ms)=>p.clock.runFor(ms);
async function key(p,k){await p.keyboard.press(k);}
async function setHeld(p,keys){const old=await p.evaluate(()=>window.__keys||[]);for(const k of old)if(!keys.includes(k))await p.keyboard.up(k);for(const k of keys)if(!old.includes(k))await p.keyboard.down(k);await p.evaluate(keys=>{window.__keys=keys},keys);}
async function pointer(p,x,y,release=false){const box=await p.locator('canvas').boundingBox();await p.mouse.move(box.x+x*box.width/480,box.y+y*box.height/440);if(release){await p.mouse.down();await p.mouse.up();}else{await p.mouse.down();await p.mouse.up();}}
async function aim(p,origin,angle,power){const box=await p.locator('canvas').boundingBox();await p.mouse.move(box.x+origin.x*box.width/480,box.y+origin.y*box.height/440);await p.mouse.down();await p.mouse.move(box.x+(origin.x+Math.cos(angle)*power*210)*box.width/480,box.y+(origin.y+Math.sin(angle)*power*210)*box.height/440);await p.mouse.up();}
async function settle(p,limit=18000){for(let i=0;i<limit/200;i++){await time(p,200);const s=await snapshot(p);if(s.mode==='ended'||!s.d.moving)return s;}throw Error('did not settle');}
function golfSim(s,angle,power){let b={...s.ball,vx:Math.cos(angle)*power*480,vy:Math.sin(angle)*power*480},dt=.016;let closest=1e9;for(let i=0;i<650;i++){let ox=b.x,oy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;for(const[axis,vel,min,max]of [['x','vx',36,444],['y','vy',36,404]])if(b[axis]<min||b[axis]>max){b[axis]=Math.max(min,Math.min(max,b[axis]));b[vel]*=-.7;}for(const w of s.walls)if(b.x+8>w.x&&b.x-8<w.x+w.w&&b.y+8>w.y&&b.y-8<w.y+w.h){if(ox+8<=w.x||ox-8>=w.x+w.w){b.x=ox;b.vx*=-.7;}else{b.y=oy;b.vy*=-.7;}}b.vx*=Math.pow(.25,dt);b.vy*=Math.pow(.25,dt);let distance=Math.hypot(b.x-s.cup.x,b.y-s.cup.y);if(Math.hypot(b.vx,b.vy)<190){closest=Math.min(closest,distance);if(distance<10)return{win:true,distance};}if(Math.hypot(b.vx,b.vy)<7)break;}return{win:false,distance:closest};}
const solvers={
'velvet-snake':async p=>{for(let turn=0;turn<800;turn++){let s=await snapshot(p);if(s.mode==='ended')return s;let d=s.d,start=d.snake[0],queue=[[start,[]]],seen=new Set([`${start.x},${start.y}`]),path=null,dirs=[['ArrowUp',0,-1],['ArrowRight',1,0],['ArrowDown',0,1],['ArrowLeft',-1,0]];while(queue.length){let[n,steps]=queue.shift();if(n.x===d.berry.x&&n.y===d.berry.y){path=steps;break;}for(let[k,dx,dy]of dirs){let x=n.x+dx,y=n.y+dy,id=`${x},${y}`;if(x<0||x>=17||y<0||y>=15||seen.has(id)||d.snake.slice(0,-1).some(b=>b.x===x&&b.y===y))continue;seen.add(id);queue.push([{x,y},[...steps,k]]);}}if(!path?.length)throw Error('snake BFS trapped');await key(p,path[0]);await time(p,Math.ceil((Math.max(.105,.185-d.count*.005)-d.tick)*1000)+4);}throw Error('snake timeout');},
'rally-club':async p=>{for(let i=0;i<2800;i++){let s=await snapshot(p);if(s.mode==='ended')return s;const b=s.d.ball;await pointer(p,70,Math.max(66,Math.min(374,b.y+(b.y>220?-34:34))));await time(p,48);}throw Error('rally timeout');},
'paper-links':async p=>{for(let n=0;n<12;n++){let s=await snapshot(p);if(s.mode==='ended')return s;let best={distance:Infinity},shot;for(let deg=-180;deg<180;deg+=2){for(let pow=.2;pow<=1.001;pow+=.025){let r=golfSim(s.d,deg*Math.PI/180,pow);if(r.distance<best.distance){best=r;shot={angle:deg*Math.PI/180,power:pow};}if(r.win)break;}if(best.win)break;}assert(shot);await aim(p,s.d.ball,shot.angle,shot.power);await settle(p);}return snapshot(p);},
'moon-basket':async p=>{let selected;for(let a=-1.45;a<-.2;a+=.015){for(let power=.2;power<=1;power+=.01){let x=87,y=350,vx=Math.cos(a)*power*560,vy=Math.sin(a)*power*560,old;for(let i=0;i<500;i++){old=y;vy+=270*.016;x+=vx*.016;y+=vy*.016;if(vy>0&&old<180&&y>=180&&Math.abs(x-356)<12){selected={a,power};break;}if(y>425)break;}if(selected)break;}if(selected)break;}assert(selected);for(let n=0;n<3;n++){await aim(p,{x:87,y:350},selected.a,selected.power);await settle(p);}return snapshot(p);},
'quiet-curl':async p=>{for(let i=0;i<3;i++){await aim(p,{x:240,y:365},-Math.PI/2+(i-1)*.07,.565);await settle(p);}return snapshot(p);},
'kite-flight':async p=>{for(let i=0;i<650;i++){let s=await snapshot(p);if(s.mode==='ended')return s;let next=s.d.gates.find(g=>g.x>80),target=next?next.y:220;await setHeld(p,s.d.y+s.d.vy*.35>target?['Space']:[]);await time(p,48);}throw Error('kite timeout');},
'soft-landing':async p=>{for(let i=0;i<500;i++){let s=await snapshot(p);if(s.mode==='ended')return s;await setHeld(p,s.d.vy>29?['Space']:[]);await time(p,32);}throw Error('lander timeout');},
'star-tow':async p=>{for(let i=0;i<1400;i++){let s=await snapshot(p);if(s.mode==='ended')return s;let d=s.d,target=d.cargo?{x:240,y:220}:d.pods[0],dx=target.x-d.x,dy=target.y-d.y,distance=Math.hypot(dx,dy);let desired=Math.atan2(dy-d.vy*.55,dx-d.vx*.55),err=Math.atan2(Math.sin(desired-d.angle),Math.cos(desired-d.angle)),keys=[];if(Math.abs(err)>.07)keys.push(err>0?'ArrowRight':'ArrowLeft');if(distance<65||Math.abs(err)>.8)keys.push('ArrowDown');if(Math.abs(err)<.4&&distance>18)keys.push('Space');await setHeld(p,keys);await time(p,48);}throw Error('tow timeout');},
'garden-guard':async p=>{for(let i=0;i<200;i++){let s=await snapshot(p);if(s.mode==='ended')return s;for(let j=0;j<9;j++)if(s.d.cells[j]?.type==='pest')await key(p,'Digit'+(j+1));await time(p,160);}throw Error('garden timeout');},
'beat-post':async p=>{for(let i=0;i<400;i++){let s=await snapshot(p);if(s.mode==='ended')return s;for(const n of s.d.notes)if(!n.done&&Math.abs(n.time-s.elapsed)<.05)await key(p,['ArrowLeft','ArrowDown','ArrowRight'][n.lane]);await time(p,48);}return snapshot(p);},
'pinball-pocket':async p=>{await setHeld(p,['ArrowLeft','ArrowRight']);for(let i=0;i<1000;i++){let s=await snapshot(p);if(s.mode==='ended')return s;if(s.d.waiting){await setHeld(p,[s.d.balls%2?'ArrowLeft':'ArrowRight']);await key(p,'Space');await setHeld(p,['ArrowLeft','ArrowRight']);}await time(p,100);}throw Error('pinball timeout');},
'rope-skip':async p=>{for(let i=0;i<850;i++){let s=await snapshot(p);if(s.mode==='ended')return s;if(s.d.next<.31&&s.d.height===0)await key(p,'Space');await time(p,40);}throw Error('rope timeout');},
'balance-beam':async p=>{for(let i=0;i<650;i++){let s=await snapshot(p);if(s.mode==='ended')return s;let target=s.d.x*.9+s.d.v*2+s.d.breeze*.3;await setHeld(p,Math.abs(target)>2?[target>0?'ArrowLeft':'ArrowRight']:[]);await time(p,48);}return snapshot(p);},

'harbor-catch':async p=>{for(let i=0;i<500;i++){let s=await snapshot(p);if(s.mode==='ended')return s;let d=s.d;if(d.phase==='idle'){await setHeld(p,[]);const f=d.fish[0],t=(f.y-72)/110;let target=f.x+f.vx*t;while(target<35||target>445)target=target<35?70-target:890-target;await pointer(p,target,60);await setHeld(p,['Space']);}else if(d.phase==='reel')await setHeld(p,[]);await time(p,80);}throw Error('fishing timeout');},

// Bowl shots use a forward physics search, including equal-mass collision and pockets.
 'table-bowls':async p=>{for(let turn=0;turn<8;turn++){let s=await snapshot(p);if(s.mode==='ended')return s;let shot=bestBowl(s.d);await aim(p,s.d.balls.find(b=>b.cue),shot.a,shot.power);await settle(p);}return snapshot(p);}
};
function bowlSim(d,a,power){let balls=d.balls.map(b=>({...b})),cue=balls.find(b=>b.cue),score=0,best=1e9;cue.vx=Math.cos(a)*power*540;cue.vy=Math.sin(a)*power*540;for(let k=0;k<550;k++){for(let b of [...balls]){b.x+=b.vx*.016;b.y+=b.vy*.016;if(d.pockets.some(p=>Math.hypot(b.x-p.x,b.y-p.y)<22)){if(b.cue){b.x=240;b.y=340;b.vx=b.vy=0;}else{balls.splice(balls.indexOf(b),1);score++;}continue;}for(let[ax,v,min,max]of[['x','vx',42+b.r,438-b.r],['y','vy',42+b.r,398-b.r]])if(b[ax]<min||b[ax]>max){b[ax]=Math.max(min,Math.min(max,b[ax]));b[v]*=-.8;}b.vx*=Math.pow(.24,.016);b.vy*=Math.pow(.24,.016);if(Math.hypot(b.vx,b.vy)<5)b.vx=b.vy=0;}for(let i=0;i<balls.length;i++)for(let j=i+1;j<balls.length;j++){let b=balls[i],c=balls[j],dx=c.x-b.x,dy=c.y-b.y,len=Math.hypot(dx,dy),r=b.r+c.r;if(len<r&&len>0){dx/=len;dy/=len;let o=(r-len)/2;b.x-=dx*o;b.y-=dy*o;c.x+=dx*o;c.y+=dy*o;let v=(b.vx-c.vx)*dx+(b.vy-c.vy)*dy;if(v>0){let z=v*.975;b.vx-=dx*z;b.vy-=dy*z;c.vx+=dx*z;c.vy+=dy*z;}}}if(balls.every(b=>Math.hypot(b.vx,b.vy)<5))break;}const remaining=balls.filter(b=>!b.cue);if(!remaining.length)return score*10000;for(let b of remaining)best=Math.min(best,...d.pockets.map(p=>Math.hypot(b.x-p.x,b.y-p.y)));return score*10000-best;}
function bestBowl(d){let best=-Infinity,shot={a:0,power:.7};for(let deg=-180;deg<180;deg+=2)for(let power=.3;power<=1.001;power+=.07){const a=deg*Math.PI/180,r=bowlSim(d,a,power);if(r>best){best=r;shot={a,power};}}const center={...shot};for(let off=-2;off<=2;off+=.2)for(let pw=Math.max(.18,center.power-.07);pw<=Math.min(1,center.power+.07);pw+=.01){let a=center.a+off*Math.PI/180,r=bowlSim(d,a,pw);if(r>best){best=r;shot={a,power:pw};}}return shot;}
// Regression: a final pocket leaves no object for the distance heuristic.
// It must score as a success, rather than retaining the 1e9 distance sentinel.
const finalBowlFixture={balls:[{x:240,y:150,vx:0,vy:0,r:10,cue:true},{x:240,y:80,vx:0,vy:0,r:12}],pockets:[{x:240,y:42}]};
assert.equal(bowlSim(finalBowlFixture,-Math.PI/2,.3),10000,'Final object pocket receives its full solver reward');
assert.ok(bowlSim(finalBowlFixture,Math.PI/2,.3)<0,'A shot leaving the object on the table ranks below a pocket');
async function golfBudgetRound(p){
 await p.locator('#restart').click();await p.locator('#start').click();
 for(let i=0;i<9;i++){let s=await snapshot(p);await aim(p,s.d.ball,Math.PI/2,.18);await settle(p);}
 let s=await snapshot(p);await aim(p,s.d.ball,-Math.PI/2,.8);await settle(p);s=await snapshot(p);await aim(p,s.d.ball,Math.PI,.18);await settle(p);s=await snapshot(p);
 assert.equal(s.d.strokes,11);assert.equal(s.d.level,0);let shot,best=Infinity;
 for(let deg=-180;deg<180;deg+=1)for(let pow=.18;pow<=1.001;pow+=.01){const r=golfSim(s.d,deg*Math.PI/180,pow);if(r.win&&r.distance<best){best=r.distance;shot={a:deg*Math.PI/180,power:pow};}}
 assert(shot,'No actual-input12th-stroke cutoff route');await aim(p,s.d.ball,shot.a,shot.power);await settle(p);const end=await snapshot(p);assert.equal(end.d.strokes,12);assert.equal(end.d.level,1);assert.equal(end.mode,'ended');assert.equal(await p.locator('#result-title').textContent(),'One more little try?');await p.locator('canvas').focus();await key(p,'Space');assert.equal((await snapshot(p)).d.strokes,12);return true;
}
async function lossRound(p,id){
  await p.locator('#restart').click();await p.locator('#start').click();
  if(['paper-links','moon-basket','quiet-curl','table-bowls'].includes(id)){
    for(let n=0;n<13;n++){const s=await snapshot(p);if(s.mode==='ended')break;const origin=id==='paper-links'?s.d.ball:id==='moon-basket'?{x:87,y:350}:id==='quiet-curl'?{x:240,y:365}:s.d.balls.find(b=>b.cue);await aim(p,origin,id==='moon-basket'?-.2:id==='quiet-curl'?-Math.PI/2:Math.PI/2,.18);await settle(p);}
  }else if(id==='harbor-catch'){for(let n=0;n<500;n++){let s=await snapshot(p);if(s.mode==='ended')break;if(s.d.phase==='idle'){await setHeld(p,[]);await pointer(p,40,60);await key(p,'Space');}await time(p,200);}}else if(id==='pinball-pocket'){
    for(let n=0;n<400;n++){let s=await snapshot(p);if(s.mode==='ended')break;if(s.d.waiting)await key(p,'Space');await time(p,250);}
  }else await time(p,85000);
  const s=await snapshot(p);if(s.mode!=='ended')console.log('INCOMPLETE LOSS',id,JSON.stringify(s));assert.equal(s.mode,'ended',id+' loss round did not end');return {score:s.score,won:(await p.locator('#result-title').textContent())==='A little victory.'};
}
(async()=>{
 browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});
 let ids=process.env.GAMES?process.env.GAMES.split(','):manifest.map(m=>m.id);
 for(const id of ids){
  const item={id,passed:false,completed:false,restart:false,mobile:false,checks:[],limitations:['Chromium only; mobile is emulated, not a physical device.','Winning routes use solver-directed real keyboard/pointer input, virtual time and a read-only test-response state probe. No production test hooks.']};
  for(const mobile of [false,true]){
   const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1360,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:mobile?'reduce':'no-preference'});
   await context.addInitScript(({blocked})=>{let seed=7127;Math.random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};if(blocked){Storage.prototype.getItem=function(){throw new Error('blocked read')};Storage.prototype.setItem=function(){throw new Error('blocked write')};}}, {blocked:mobile});
   const p=await context.newPage();p.on('pageerror',e=>errors.push({id,mobile,error:e.message}));
   await p.route('**/arcade-room/room.js',route=>route.fulfill({contentType:'application/javascript',body:source.replace("reset();document.body.dataset.gameId", "window.__arcade=()=>JSON.parse(JSON.stringify({mode,d,elapsed,score}));reset();document.body.dataset.gameId")}));
   await p.clock.install({time:new Date('2026-01-01')});await p.clock.pauseAt(new Date('2026-01-01T00:00:01Z'));
   await p.goto(`${base}/mini-games/arcade-room/?game=${id}`);await p.waitForSelector('body[data-game-ready="true"]');assert.equal(await p.getAttribute('body','data-game-id'),id);
   if(mobile){await p.locator('#start').tap();const inputs=p.locator('#inputs button');if(await inputs.count())await inputs.first().tap();else{const box=await p.locator('canvas').boundingBox();await p.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);}await time(p,80);await p.locator('#restart').tap();}
   await p.locator('#start').click();const result=await solvers[id](p);await setHeld(p,[]);const won=(await p.locator('#result-title').textContent())==='A little victory.';
   console.log(id,mobile?'mobile':'desktop',result.mode,result.score,await p.locator('#result-copy').textContent());assert.equal(result.mode,'ended',id+' did not complete');assert(won,id+' winning route failed');
   await p.screenshot({path:`/tmp/arcade-${id}-${mobile?'mobile':'desktop'}.png`,fullPage:true});
   if(mobile){assert.match(await p.locator('#storage-note').textContent(),/unavailable/);assert.notEqual(await p.locator('#best').textContent(),'—');item.mobile=true;item.mobileScore=result.score;}else{item.desktopScore=result.score;item.lossRound=await lossRound(p,id);if(id==='paper-links')item.stroke12HoleCutoff=await golfBudgetRound(p);}
   for(let i=0;i<3;i++){await p.locator('#restart').click();assert.equal((await snapshot(p)).mode,'ready');await p.locator('#start').click();await time(p,100);}
   await key(p,'p');let before=await snapshot(p);await time(p,10000);assert.deepEqual(await snapshot(p),before);await p.locator('#pause').click();assert.equal(await p.evaluate(()=>document.activeElement.id),'game');if(id==='rope-skip'){await key(p,'Space');assert((await snapshot(p)).d.height>0,'Space must jump after button Resume');}await p.evaluate(()=>dispatchEvent(new Event('blur')));assert.equal((await snapshot(p)).mode,'paused');
   await p.locator('#pause').click();await p.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});assert.equal((await snapshot(p)).mode,'paused');
   assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(mobile){await p.setViewportSize({width:320,height:740});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));for(const b of await p.locator('#inputs button').all()){const box=await b.boundingBox();assert(box.height>=44);}}
   if(!mobile){await p.reload();await p.waitForSelector('body[data-game-ready="true"]');assert.notEqual(await p.locator('#best').textContent(),'—');}
   await p.locator('.back').click();assert.match(p.url(),/mini-games\/$/);await context.close();
  }
  Object.assign(item,{passed:true,completed:true,restart:true,desktop:true});item.checks=['Full winning rounds desktop and mobile','Desktop alternate completion/loss','Three restarts on each viewport','P keyboard pause, frozen clock, blur and visibility pause','390px and320px layout,44px controls','Mobile touch controls smoke and reduced motion','Blocked storage fallback/mobile session best','Saved best survives desktop reload','Return to catalog'];const prior=coverage.findIndex(g=>g.id===id);if(prior>=0)coverage.splice(prior,1);coverage.push(item);
  fs.mkdirSync(path.join(__dirname,'../coverage'),{recursive:true});if(!process.env.NO_COVERAGE)fs.writeFileSync(path.join(__dirname,'../coverage/arcade-room.json'),JSON.stringify({family:'arcade-room',errors,games:coverage},null,2)+'\n');
 }
 await browser.close();assert.deepEqual(errors,[]);console.log('All arcade rounds and edge checks passed.');
})().catch(async e=>{console.error(e);await browser?.close();process.exit(1)});
