/* Source-informed full campaigns through native keyboard and touch controls.
 * Hidden model orders inform bag/applicant/Dutch routes; no runtime state mutation.
 * Optional modes use the public URL replay seed. Not unaided mastery or physical-device evidence. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),BASE=process.env.BASE_URL||'http://127.0.0.1:8790',file=path.join(ROOT,'coverage/commons-room.json');
const files=()=>fs.readdirSync(path.join(ROOT,'commons-room')).sort().map(n=>'commons-room/'+n).concat(fs.readdirSync(path.join(ROOT,'journey')).sort().map(n=>'journey/'+n),['tests/commons-room.cjs','tests/commons-room-rules.mjs','tests/commons-room-plans.mjs','tests/commons-room-paths.json','tests/commons-room-variants.json']);
function hash(){let h=crypto.createHash('sha256');for(const f of files())h.update(f+'\0').update(fs.readFileSync(path.join(ROOT,f)));return h.digest('hex')}
let report={suite:'commons-room',passed:false,testedAt:new Date().toISOString(),cases:[],limits:['Pure-model legal plans replay through real browser controls. Bag order, applicants and private Dutch reservations inform some plans; these prove reachable outcomes, not unaided play or fair human success probability.','Every desktop gameplay control uses native keyboard focus/Enter; every mobile gameplay action uses touchscreen taps. Mode selection is setup via the native select API before the game begins.','Chromium desktop and emulated touch at390/320px; not a physical-phone, other-engine or screen-reader study.','Late-stage optional-mode checks are pure-model generation constraints, not full browser completion at stage10003. Independent ordinary-input review is separate.']};
const save=()=>fs.writeFileSync(file,JSON.stringify(report,null,2)+'\n');
(async()=>{save();let sourceHash=hash();const{engines}=await import('../commons-room/engines.mjs'),{legalActions,copy}=await import('../commons-room/core.mjs'),{checks,generation}=await import('./commons-room-rules.mjs');
const games=JSON.parse(fs.readFileSync(path.join(ROOT,'commons-room/games.json'))),plans=JSON.parse(fs.readFileSync(path.join(__dirname,'commons-room-paths.json'))),variants=JSON.parse(fs.readFileSync(path.join(__dirname,'commons-room-variants.json')));
assert.equal(games.length,20);assert.equal(Object.keys(engines).length,20);assert.equal(Object.keys(plans).length,20);assert.equal(Object.keys(variants).length,20);
for(const g of games){assert.equal(g.stages,3);assert.ok(checks[g.id]?.length);for(let stage=0;stage<3;stage++){let s=engines[g.id].init({stage,seed:1,mode:'finite'});for(const k of plans[g.id][stage]){assert.ok(legalActions(engines[g.id],s).includes(k));engines[g.id].act(s,k)}assert.equal(s.outcome,'win',g.id+' full finite model study');assert.ok(Number.isFinite(s.score)&&s.score>=0)}let s=engines[g.id].init({stage:0,seed:1,mode:'finite'});for(const k of variants[g.id].loss)engines[g.id].act(s,k);assert.equal(s.outcome,'loss',g.id+' model natural failure');if(g.endless.supported){assert.equal(variants[g.id].optional.length,2);assert.ok(variants[g.id].optionalLoss?.length)}}
report.modelRules={games:20,checks,generation};
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
try{for(const mobile of[false,true]){let context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:960},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
const activate=async selector=>{let b=page.locator(selector).first();assert.equal(await b.isEnabled(),true,selector+' enabled');if(mobile)await b.tap();else{await b.focus();await b.press('Enter')}};const action=k=>activate(`[data-action="${k}"]`);
for(const g of games){console.log((mobile?'touch ':'keyboard ')+g.id);let e=engines[g.id],v=variants[g.id];await page.goto(BASE+'/mini-games/'+g.url+'&seed='+v.seed);await page.waitForSelector('body[data-game-ready="true"]');assert.equal(await page.locator('h1').innerText(),g.name);assert.equal(await page.locator('body').getAttribute('data-game-id'),g.id);assert.equal(await page.locator('#rules li').count(),g.rules.length);await activate('#start');let opening=await page.locator('#board').innerText();
let s=e.init({stage:0,seed:1,mode:'finite'}),change=legalActions(e,s).find(k=>{let q=copy(s);e.act(q,k);return JSON.stringify(q)!==JSON.stringify(s)});assert.ok(change);await action(change);assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');if(await page.locator('#undo').isEnabled()){await activate('#undo');assert.equal(await page.locator('#board').innerText(),opening,'Undo restores complete opening')}await activate('#restart');assert.equal(await page.locator('#board').innerText(),opening,'Restart restores authored opening');
for(const k of v.loss)await action(k);assert.equal(await page.locator('body').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('#board button:not(:disabled)').count(),0,'Terminal controls disabled');await activate('#reset');assert.equal(await page.locator('#board').innerText(),opening,'Reset recovers natural failure');
for(let stage=0;stage<3;stage++){for(const k of plans[g.id][stage])await action(k);assert.equal(await page.locator('body').getAttribute('data-outcome'),stage===2?'win':'study-win',g.id+' study'+stage+' UI win');assert.equal(await page.locator('#board button:not(:disabled)').count(),0);if(stage<2)await activate('#next')}
assert.equal(await page.locator('body').getAttribute('data-outcome'),'win');assert.ok(Number(await page.locator('#score').innerText())>0);await activate('#again');assert.equal(await page.locator('#board').innerText(),opening,'Play again restores campaign');assert.equal(await page.locator('#score').innerText(),'0');
let optionalMode={supported:false};if(g.endless.supported){await page.locator('#mode').selectOption('endless');await activate('#start');let initialModels=[];let bank=0;for(let stage=0;stage<2;stage++){let seed=(v.seed+Math.imul(stage+1,0x9e3779b9))>>>0,model=e.init({stage,seed,mode:'endless'});delete model.rng;delete model.stage;delete model.note;initialModels.push(JSON.stringify(model));for(const k of v.optional[stage])await action(k);assert.equal(await page.locator('body').getAttribute('data-outcome'),'study-win');let total=Number(await page.locator('#score').innerText());assert.ok(total>bank,'Score accumulates completed optional challenges');bank=total;await activate('#next');assert.equal(Number(await page.locator('#score').innerText()),bank,'Next challenge banks score once')}
assert.notEqual(initialModels[0],initialModels[1],'Fresh seeded optional models');assert.equal(await page.locator('#undo').isEnabled(),false,'Optional score cannot be farmed with Undo');assert.equal(await page.locator('#reset').isEnabled(),false,'Optional reset disabled');for(const k of v.optionalLoss)await action(k);assert.equal(await page.locator('body').getAttribute('data-outcome'),'loss');await activate('#again');assert.equal(await page.locator('body').getAttribute('data-outcome'),'playing');assert.equal(await page.locator('#score').innerText(),'0');await activate('#end-run');assert.equal(await page.locator('body').getAttribute('data-outcome'),'win','Player may bank and end optional run');assert.match(await page.locator('#result-title').innerText(),/banked/i);await activate('#again');assert.equal(await page.locator('#score').innerText(),'0');optionalMode={supported:true,kind:g.endless.kind,completedChallenges:2,freshChallenges:true,scoreAccumulated:true,terminalRecovery:true,playerEndRun:true,lateStageProperties:true,lateStageScope:'pure-model generation properties including stage10003, not late-stage browser wins',lateStageMethod:'20 pure-model seed/stage samples including stage10003; no late-stage browser win claim',replaySeed:v.seed,gameplayInputs:mobile?'touchscreen':'native keyboard'};
}else assert.equal(await page.locator('#endless-option').evaluate(option=>option.disabled),true);
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),g.id+' viewport fits');if(mobile){await page.setViewportSize({width:320,height:740});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),g.id+'320px fits');await page.setViewportSize({width:390,height:844})}assert.deepEqual(errors,[]);
if(['spore-council','socket-skirmish','orderbook-wharf','seasonal-ledger','maturity-garden'].includes(g.id)){let out=path.join(ROOT,'coverage/commons-room-previews');fs.mkdirSync(out,{recursive:true});await page.screenshot({path:path.join(out,g.id+'-'+(mobile?'touch':'desktop')+'.png'),fullPage:true})}
report.cases.push({id:g.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',restart:true,touchOnly:mobile,inputMethod:mobile?'Touchscreen taps for all finite/optional gameplay; native mode-selector setup before Begin':'Native focus and Enter for all finite/optional gameplay controls',winActions:plans[g.id].reduce((n,p)=>n+p.length,0),lossActions:v.loss.length,finiteStudiesCompleted:3,optionalMode,edgeCases:['Per-game nontrivial rule regression: '+checks[g.id].join('; '),'Natural losing UI path and Reset recovery','Three actual finite-study wins','Undo restores complete opening; Restart and Play again reset campaign and score','Terminal native controls disable','No page errors; responsive bounds including320px on touch profile'],ordinaryInput:'Source-informed legal full paths; independent ordinary-input review is separate'});save();
}await context.close()}
let bytes=[];for(const f of files().filter(f=>f.startsWith('commons-room/')||f.startsWith('journey/'))){let response=await fetch(BASE+'/mini-games/'+f);assert.equal(response.status,200);let served=Buffer.from(await response.arrayBuffer()),local=fs.readFileSync(path.join(ROOT,f));assert.deepEqual(served,local,'Served runtime matches local '+f);bytes.push(f)}report.servedAssets=bytes;assert.equal(hash(),sourceHash,'Runtime/tests changed during suite; rerun required');report.sourceHash=sourceHash;report.passed=report.cases.length===40;assert.equal(report.passed,true);save();console.log(JSON.stringify({passed:report.passed,cases:report.cases.length,optionalCases:report.cases.filter(c=>c.optionalMode.supported).length}));
}finally{await browser.close()}})().catch(e=>{report.passed=false;report.error=e.stack;save();console.error(e);process.exitCode=1});
