/* Independent public-clue solvers drive real native inputs with public seed replay. No browser model hooks or state writes. */
const {chromium}=require('playwright'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const games=require('../constraint-room/games.json'),root=path.resolve(__dirname,'..'),out=path.join(root,'coverage/constraint-room.json'),base=process.env.BASE_URL||'http://127.0.0.1:8790';
const range=n=>Array.from({length:n},(_,i)=>i),seed=12345,stageSeed=stage=>(seed+Math.imul(stage+1,0x9e3779b9))>>>0;
function sourceHash(){const files=[...fs.readdirSync(path.join(root,'constraint-room')).map(f=>'constraint-room/'+f),...fs.readdirSync(path.join(root,'journey')).map(f=>'journey/'+f),...fs.readdirSync(__dirname).filter(f=>f.startsWith('constraint-')).map(f=>'tests/'+f)].sort(),h=crypto.createHash('sha256');for(const f of files)h.update(f+'\0').update(fs.readFileSync(path.join(root,f))).update('\0');return h.digest('hex')}
const report={family:'constraint-room',passed:false,cases:[],sourceHash:sourceHash(),limits:['All40 primary paths use source-derived deterministic replay models and independently written solvers over public clues; they establish reachable rule-valid outcomes, not unaided human difficulty.','No browser model read/write probes, answer injection, or writable runtime hook. Gameplay is actual native button input.','Mobile paths use Chromium emulated touchscreen taps. No physical device or screen-reader user study.','Generator sampling and known rule regressions do not exhaust every possible seed or action sequence.']};
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');
(async()=>{const {engines}=await import('../constraint-room/engines.mjs'),{plan,failurePlan}=await import('./constraint-room-solvers.mjs'),{runRegressions}=await import('./constraint-room-regressions.mjs');report.modelRegressions=runRegressions();
function wrongPlan(id,initial){if(['once-through','cyclic-courtyard'].includes(id))return failurePlan(id,initial);const actions=plan(id,initial),s=structuredClone(initial),e=engines[id];actions.forEach(a=>e.act(s,a));assert.equal(s.outcome,'playing');let candidates=[];
if(id==='lamp-ward')candidates=range(s.cells.length).filter(i=>!s.walls.includes(i)&&s.cells[i]!==1).map(i=>['cell:'+i]);
else if(id==='star-charter')candidates=range(s.cells.length).filter(i=>s.cells[i]!==1).map(i=>['cell:'+i]);
else if(id==='region-census')candidates=range(s.cells.length).filter(i=>!s.givens[i]).map(i=>['size:'+(s.cells[i]===1?2:1),'cell:'+i]);
else if(id==='magnet-ledger')candidates=range(s.slots.length).map(k=>['slot:'+k]);
else if(id==='thermometer-hall')candidates=s.tubes.map((t,k)=>[`tube:${k}:${(s.lengths[k]+1)%(t.length+1)}`]);
else if(id==='compass-estate')candidates=s.arms.flatMap((a,k)=>a.flatMap((v,d)=>v?[['hub:'+k,'retract:'+d]]:[]));
else if(id==='four-forms')candidates=range(s.cells.length).filter(i=>s.cells[i]!==1).map(i=>['cell:'+i]);
else if(id==='domino-register')candidates=[['cell:0']];
else if(id==='diagonal-grove')candidates=range(s.cells.length).map(i=>['cell:'+i]);
else if(id==='shade-detour'){const k=s.links.findIndex(Boolean),[a,b]=s.edges[k];candidates=[['mode:route','cell:'+a,'cell:'+b]]}
else if(id==='seam-quilt')candidates=s.placed.map((k,i)=>['tile:'+k,'rotate','cell:'+i]);
else if(id==='exclusive-print')candidates=s.chosen.flatMap((v,k)=>v?[['plate:'+k]]:[]);
else candidates=range(s.cells.length).filter(i=>!(s.clues&&s.clues[i]!==undefined&&['mosaic-ring','sight-garden'].includes(id))&&!(s.fixed&&s.fixed[i]!==undefined)).map(i=>Array(s.cells[i]===1?1:2).fill('cell:'+i));
for(const wrong of candidates){const t=structuredClone(s);wrong.forEach(a=>e.act(t,a));e.act(t,'check');if(t.outcome==='loss')return [...actions,...wrong,'check']}throw Error('No meaningful wrong study for '+id)}
const properties=[];for(const game of games){const e=engines[game.id],fingerprints=new Set;for(let k=0;k<40;k++){const stage=k%4===3?100:k%3,s=e.init({stage,seed:(987654+Math.imul(k+1,3935559001))>>>0,mode:k%4===3?'endless':'finite'});assert.equal(s.outcome,'playing');assert.deepEqual(s,e.init({stage,seed:(987654+Math.imul(k+1,3935559001))>>>0,mode:k%4===3?'endless':'finite'}),'same seed reproduces');fingerprints.add(JSON.stringify(s));if(k<12){const p=plan(game.id,s);for(const a of p)e.act(s,a);if(s.outcome==='playing')e.act(s,'check');assert.equal(s.outcome,'win',game.id+' generator sample '+k+' '+s.note);assert.ok(Number.isFinite(s.score)&&s.score>0)}}assert.ok(fingerprints.size>=35,game.id+' fresh generated studies');properties.push({id:game.id,sampledSeeds:40,solverWins:12,includesStage100:true,distinctInitialStates:fingerprints.size})}report.generation=properties;save();
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});for(const game of games.filter(g=>!process.env.GAME_IDS||process.env.GAME_IDS.split(',').includes(g.id))){const page=await context.newPage(),errors=[],edgeCases=[],winActions=[],lossActions=[];page.on('pageerror',e=>errors.push(e.message));const click=async sel=>{if(mobile)await page.locator(sel).first().tap();else await page.locator(sel).first().click()},action=async a=>click('[data-action="'+a+'"]'),run=async a=>{for(const k of a)await action(k)},initial=(stage,mode='finite')=>engines[game.id].init({stage,seed:stageSeed(stage),mode}),outcome=()=>page.locator('body').getAttribute('data-outcome');
await page.goto(base+'/mini-games/'+game.url+'&seed='+seed);await page.waitForFunction(()=>document.body.dataset.gameReady==='true');await click('#start');assert.match(await page.locator('#seed-note').innerText(),/12345/);
if(!mobile){const b=page.locator('#board button:not(:disabled)').first();await b.focus();await page.keyboard.press('Space');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');edgeCases.push('Space activates a native mechanic control and focus survives rendering');await click('#reset')}
const losing=wrongPlan(game.id,initial(0));await run(losing);lossActions.push(...losing);assert.equal(await outcome(),'loss',game.id+' meaningful invalid state');assert.ok((await page.locator('#status').innerText()).length>25);edgeCases.push('A complete deliberately corrupted solution or stranded route produces an explained loss');await click('#undo');assert.equal(await outcome(),'playing','Undo recovers loss');edgeCases.push('Undo restores playing after failed Check or final losing move');await click('#reset');assert.equal(await page.locator('#score').innerText(),'0');
// Game-specific impossible-action guards, through real controls.
if(game.id==='lamp-ward'){const s=initial(0);assert.equal(await page.locator('[data-action="cell:'+s.walls[0]+'"]').isDisabled(),true);edgeCases.push('Numbered wall cannot become a lamp')}
if(game.id==='region-census'){const s=initial(0);assert.equal(await page.locator('[data-action="cell:'+Object.keys(s.givens)[0]+'"]').isDisabled(),true);edgeCases.push('Given region label is immutable')}
if(game.id==='fleet-blueprint'){const s=initial(0);assert.equal(await page.locator('[data-action="cell:'+Object.keys(s.fixed)[0]+'"]').isDisabled(),true);edgeCases.push('Fixed hull/water clue cannot change')}
if(game.id==='domino-register'){await action('cell:0');await action('cell:'+ (initial(0).n*2-1));assert.match(await page.locator('#status').innerText(),/share an edge/);edgeCases.push('Non-neighbor domino pairing is refused');await click('#reset')}
if(game.id==='compass-estate'){const s=initial(0),h=s.hubs[0][0],q=range(s.n*s.n).find(i=>!s.hubs.some(x=>x[0]===i)&&i%s.n!==h%s.n&&Math.floor(i/s.n)!==Math.floor(h/s.n));if(q!==undefined){await action('cell:'+q);assert.match(await page.locator('#status').innerText(),/same row or column/);edgeCases.push('Bent diagonal estate arm is refused');await click('#reset')}}
for(let stage=0;stage<3;stage++){const s=initial(stage),p=plan(game.id,s);assert.ok(p.length);await run(p);winActions.push({mode:'finite',stage,actions:p});if(await outcome()==='playing'){await action('check');winActions.at(-1).actions.push('check')}assert.equal(await outcome(),stage<2?'study-win':'win',game.id+' chapter '+stage+' '+await page.locator('#status').innerText());if(stage<2)await click('#next')}
assert.equal(await page.locator('#next').isHidden(),true);assert.ok(Number(await page.locator('#score').innerText())>=3000);edgeCases.push('Every one of three finite studies wins through native inputs and completed controls lock');await click('#restart');assert.equal(await outcome(),'playing');assert.equal(await page.locator('#score').innerText(),'0');assert.equal(await page.locator('body').getAttribute('data-stage'),'0');edgeCases.push('Restart resets campaign stage, score, result and replay board');
await page.locator('#mode').selectOption('endless');await click('#start');for(let stage=0;stage<2;stage++){const p=plan(game.id,initial(stage,'endless'));await run(p);if(await outcome()==='playing'){await action('check');p.push('check')}assert.equal(await outcome(),'study-win');winActions.push({mode:'endless',stage,actions:p});await click('#next')}const banked=Number(await page.locator('#score').innerText());assert.ok(banked>=2000);assert.equal(await page.locator('#reset').isDisabled(),true);assert.equal(await page.locator('#undo').isDisabled(),true);edgeCases.push('Two independently generated endless studies win and score accumulates; Reset/Undo cannot replay points');
const endlessFail=wrongPlan(game.id,initial(2,'endless'));await run(endlessFail);assert.equal(await outcome(),'loss');lossActions.push(...endlessFail);assert.equal(Number(await page.locator('#score').innerText()),banked);edgeCases.push('A later endless failure preserves earned score and ends that stream');await click('#restart');assert.equal(await outcome(),'playing');assert.equal(await page.locator('#score').innerText(),'0');await click('#end-run');assert.equal(await outcome(),'win');assert.match(await page.locator('#result-title').innerText(),/banked/i);edgeCases.push('A fresh endless run restarts at zero and explicit bank ends it');
for(const width of mobile?[320,390]:[1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),game.id+' overflow at '+width)}assert.deepEqual(errors,[]);report.cases.push({id:game.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',restart:true,touchOnly:mobile,inputMethod:mobile?'Chromium emulated touchscreen taps for every gameplay, loss, recovery, progression and restart action; native mode selectOption changes playback mode':'Native mouse clicks plus ordinary keyboard Space activation; native mode selectOption changes playback mode',edgeCases,winActions,lossActions,finiteStudiesCompleted:3,endlessStudiesCompleted:2,optionalMode:{supported:true,kind:'challenge-stream',completedChallenges:2,sourceSeed:seed,freshChallenges:true,scoreAccumulated:true,terminalRecovery:true,playerEndRun:true,lateStageProperties:true,lateStageScope:'Pure model sampling and solver completion at stage100; browser stages0–2 only.',lateStagePropertyMethod:'Pure model seed sampling and rule-valid solver completion at stage100; browser inputs cover stages0–2.'},errors});save();console.log('PASS',game.id,mobile?'mobile-touch':'desktop');await page.close()}await context.close()}assert.equal(report.cases.length,(process.env.GAME_IDS?process.env.GAME_IDS.split(',').length:20)*2);report.scope=process.env.GAME_IDS?'explicit subset':'all20 games, desktop and mobile-touch';report.passed=true;report.sourceUnchanged=sourceHash()===report.sourceHash;assert.equal(report.sourceUnchanged,true,'source changed during execution');save()}finally{await browser.close()}})().catch(e=>{report.passed=false;report.failure=String(e.stack||e);save();console.error(e);process.exitCode=1});
