'use strict';
const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const games=require('../construct-room/games.json'),fixtures=require('./construct-fixtures.json'),base=process.env.BASE_URL||'http://127.0.0.1:8781',out=path.join(__dirname,'../coverage/construct-room.json');
const report={family:'construct-room',passed:false,cases:[],sourceHash:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../construct-room/engines.js'))).update(fs.readFileSync(path.join(__dirname,'../construct-room/room.js'))).digest('hex'),limits:['Source-authored and solver-generated fixture routes replayed solely through public DOM controls. Not independent ordinary-play evidence.','No state injection, source interception or runtime mutation. Read-only visible button labels guide face swaps.','Chromium desktop and emulated touch; no physical device or actual screen-reader certification.']};
const save=()=>fs.writeFileSync(out,JSON.stringify(report,null,2));
(async()=>{save();const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{for(const mobile of[false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},hasTouch:mobile,isMobile:mobile,reducedMotion:'reduce'});for(const game of games.filter(g=>!process.env.GAME_IDS||process.env.GAME_IDS.split(',').includes(g.id))){assert.ok(fixtures[game.id],'Missing winning fixture '+game.id);const page=await context.newPage(),errors=[],edge=[];page.on('pageerror',e=>errors.push(e.message));const click=async s=>{await page.locator(s)[mobile?'tap':'click']()},key=async k=>click(`[data-key="${k}"]`);await page.goto(base+'/mini-games/'+game.url);await page.waitForSelector('body[data-game-ready="true"]');await click('#start');await click('#check');assert.equal(await page.locator('#result').isHidden(),true);edge.push('initial incomplete certificate rejected');if(!mobile){const b=page.locator('#board button:not(:disabled),#extra button:not(:disabled)').first();await b.focus();await page.keyboard.press('Space');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');edge.push('native focused Space action retains usable focus');await click('#reset')}
if(game.id==='falling-orchard'){for(const[x,y]of fixtures[game.id][0].greedy){await key('cell-'+(y*5+x));await key('remove')}assert.equal(await page.locator('body').getAttribute('data-result'),'lost');await click('#undo');assert.equal(await page.locator('body').getAttribute('data-result'),'playing');edge.push('greedy removal reaches natural singleton dead-end; Undo recovers')}
if(game.id==='turn-the-stack'){for(let i=0;i<7;i++){await key('prefix-1');await key('flip')}assert.equal(await page.locator('body').getAttribute('data-result'),'lost');await click('#undo');assert.equal(await page.locator('body').getAttribute('data-result'),'playing');edge.push('real flip allowance failure and recovery')}
if(game.id==='one-last-marble'){await key('marble-0');await key('fling-1');assert.match(await page.locator('#status').innerText(),/no distant target/);edge.push('launch without target refuses without consuming a marble')}
if(game.id==='letter-conservatory'){await key('letter-0');await key('word-submit');assert.match(await page.locator('#status').innerText(),/not in/);assert.match(await page.locator('#clues').innerText(),/Committed 0\/4/);edge.push('invalid word refuses without spending a word slot')}
if(game.id==='compass-house'){await key('build');assert.match(await page.locator('#status').innerText(),/Choose two/);edge.push('degenerate construction refuses with exact requirement')}
if(game.id==='fair-portions'){await key('cut');assert.match(await page.locator('#status').innerText(),/positive areas/);edge.push('boundary-tangent cut rejected without material loss')}
if(game.id==='corner-cabinet'){const before=await page.locator('#board').innerText();for(let i=0;i<4;i++)await key('turn-1');assert.equal(await page.locator('#board').innerText(),before);await click('#check');assert.equal(await page.locator('#result').isHidden(),true);edge.push('four face turns restore exact visible state; still-unsolved cube rejected')}
if(game.id==='unfair-circle'){await key('face-0');await key('face-17');await click('#check');assert.equal(await page.locator('#result').isHidden(),true);await click('#undo');edge.push('unequal means rejected; face swap undo restores shared inventory')}
if(game.id==='unfolding-house'){for(let i=0;i<6;i++)await key('seam-'+i);await click('#check');assert.match(await page.locator('#status').innerText(),/five seams/);edge.push('cyclic/excess hinge candidate rejected')}
if(game.id==='gentle-unknot'){await key('braid-cancel');assert.match(await page.locator('#status').innerText(),/not an inverse pair/);await key('braid-add');await key('braid-cancel');edge.push('illegal topology cancellation refused; inverse pair insertion and cancellation preserve braid')}
if(game.id==='bonding-room'){await key('bond-cell-0');await key('bond-dir-0');assert.equal(await page.locator('body').getAttribute('data-result'),'lost');await click('#undo');edge.push('wrong irreversible valence bond fails naturally; Undo restores atoms')}
if(game.id==='rooms-in-motion'){await key('insert-0');const before=await page.locator('#board').innerText();await key('insert-1');assert.match(await page.locator('#status').innerText(),/reverse/);assert.equal(await page.locator('#board').innerText(),before);edge.push('immediate reverse insertion rejected atomically')}
if(game.id==='pocket-photograph'){await key('photo-mode-frame');await key('photo-cell-28');await key('capture');assert.match(await page.locator('#status').innerText(),/avatar/);await key('photo-cell-0');await key('capture');await key('photo-cell-24');await key('paste');await key('photo-cell-0');await key('capture');await key('photo-cell-24');await key('paste');assert.equal(await page.locator('body').getAttribute('data-result'),'lost');await click('#undo');edge.push('avatar capture refused; destructive wall prints exhaust cameras and strand the route; Undo recovers held photo')}
await click('#reset');for(let stage=0;stage<3;stage++){const f=fixtures[game.id][stage];
if(game.id==='words-that-move'&&stage===1){await key('world-dir-1');await key('world-dir-2');assert.equal(await page.locator('body').getAttribute('data-result'),'lost');await click('#undo');await click('#reset');edge.push('breaking every YOU rule produces recoverable no-control failure')}
if(game.id==='unfolding-house'){for(const i of f.hinges)await key('seam-'+i);if(f.rotate)await key('rotate-net')}
if(game.id==='gentle-unknot'){for(const [type,i]of f.path){if(type==='slide'||type==='cancel')await key('cross-'+i);await key('braid-'+type)}}
if(game.id==='bonding-room'){for(const [atom,d]of f){const b=page.locator('#board button').filter({hasText:new RegExp('^'+'ABCD'[atom]+' ')});await b[mobile?'tap':'click']();await key('bond-dir-'+d)}}
if(game.id==='words-that-move')for(const d of f)await key('world-dir-'+d);
if(game.id==='rooms-in-motion')for(const k of f.actions)await key(k);
if(game.id==='pocket-photograph')for(const k of f)await key(k);
if(game.id==='falling-orchard')for(const[x,y]of f.solution){await key('cell-'+(y*5+x));await key('remove')};if(game.id==='turn-the-stack')for(const k of f.path){await key('prefix-'+k);await key('flip')};if(game.id==='one-last-marble')for(const[p,d]of f.path){await key('marble-'+p);await key('fling-'+d)};if(game.id==='letter-conservatory')for(const[w,p]of f.solution){for(const i of p)await key('letter-'+i);await key('word-submit')};if(game.id==='corner-cabinet')for(const[face,dir]of [...f].reverse()){await key('cube-'+face);await key('turn-'+(-dir))};if(game.id==='unfair-circle'){const target=f.flat();for(let i=0;i<18;i++){const values=[];for(let j=0;j<18;j++)values.push(Number((await page.locator(`[data-key="face-${j}"]`).innerText()).split(': ')[1]));if(values[i]===target[i])continue;const j=values.findIndex((v,j)=>j>i&&v===target[i]);assert.ok(j>=0);await key('face-'+i);await key('face-'+j)}}if(game.id==='compass-house')for(const k of f)await key(k);if(game.id==='fair-portions'){let ends={a:[0,0],b:[12,0]};for(const[p,a,b]of f){await key('piece-'+p);for(const[end,target]of[['a',a],['b',b]])for(let axis=0;axis<2;axis++)while(ends[end][axis]!==target[axis]){const delta=Math.sign(target[axis]-ends[end][axis]);await key(end+'-'+axis+'-'+delta);ends[end][axis]+=delta}await key('cut')}}await click('#check');assert.equal(await page.locator('#result').isVisible(),true,game.id+' study '+stage+': '+await page.locator('#status').innerText());if(stage<2)await click('#next')}
assert.equal(await page.locator('body').getAttribute('data-result'),'won');assert.equal(await page.locator('#check').isDisabled(),true);await click('#restart');assert.equal(await page.locator('#study').innerText(),'1 / 3');assert.equal(await page.locator('#moves').innerText(),'0');assert.equal(await page.locator('#checks').innerText(),'0');assert.equal(await page.locator('#result').isHidden(),true);for(const width of mobile?[320,390]:[1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),game.id+' overflow '+width)}assert.deepEqual(errors,[]);edge.push('three real studies won; completed certificate locked; full restart restores counters');report.cases.push({id:game.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',restart:true,studiesCompleted:3,edgeCases:edge,inputMethod:mobile?'Touchscreen taps only; source-authored and solver-guided public-control routes':'Native keyboard Space smoke plus mouse clicks; source-authored and solver-guided public-control routes',touchOnly:mobile,completionType:'source-informed public UI replay',errors});save();console.log('PASS',game.id,mobile?'mobile-touch':'desktop');await page.close()}await context.close()}report.passed=true;report.scope=process.env.GAME_IDS?'explicit requested subset':'full manifest';save()}finally{await browser.close()}})().catch(e=>{report.passed=false;report.failure=String(e.stack||e);save();console.error(e);process.exitCode=1});
