/* UI solvers use rendered evidence only. No injected production hooks, state reads or state writes.
   These certify rule/terminal reachability, not independent human difficulty or physical-device usability. */
const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs');const path=require('node:path');const games=require('../discovery-room/games.json');const base=process.env.BASE_URL||'http://127.0.0.1:8790';let page,mobile,edges=[];
const text=()=>page.locator('#board').innerText();const meter=()=>page.locator('#meter').innerText();
async function click(name){const l=page.getByRole('button',{name,exact:true});mobile?await l.tap():await l.click()}
async function nth(sel,i){const l=page.locator(sel).nth(i);mobile?await l.tap():await l.click()}
async function fill(name,v){await page.getByRole('spinbutton',{name,exact:true}).fill(''+v);await page.getByRole('spinbutton',{name,exact:true}).press('Tab')}
const nums=s=>(s.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number);
async function mark(i){await nth('.grid button.cell',i)}
const solvers={};
function ray(atoms,port){let x,y,dx,dy;if(port<6){x=port;y=-1;dx=0;dy=1}else if(port<12){x=6;y=port-6;dx=-1;dy=0}else if(port<18){x=17-port;y=6;dx=0;dy=-1}else{x=-1;y=23-port;dx=1;dy=0}let first=true;const has=(x,y)=>x>=0&&x<6&&y>=0&&y<6&&atoms.includes(y*6+x);for(let k=0;k<100;k++){const ax=x+dx,ay=y+dy;if(has(ax,ay))return'absorbed';const l=has(ax+dy,ay-dx),r=has(ax-dy,ay+dx);if(l&&r||first&&(l||r))return'reflected';if(l)[dx,dy]=[-dy,dx];else if(r)[dx,dy]=[dy,-dx];else{x=ax;y=ay;if(x<0)return'port '+(24-y);if(x>5)return'port '+(7+y);if(y<0)return'port '+(x+1);if(y>5)return'port '+(18-x)}first=false}return'loop'}
solvers['ray-archive']=async()=>{for(let stage=0;stage<2;stage++){let candidates=[];const interior=Array.from({length:16},(_,i)=>(1+(i/4|0))*6+1+i%4);for(let a=0;a<16;a++)for(let b=a+1;b<16;b++)for(let c=b+1;c<16;c++)candidates.push([interior[a],interior[b],interior[c]]);for(let n=0;candidates.length>1&&n<12;n++){let best=0,score=Infinity;for(let p=0;p<24;p++){const groups={};for(const a of candidates){const r=ray(a,p);groups[r]=(groups[r]||0)+1}const s=Math.max(...Object.values(groups));if(s<score){score=s;best=p}}await click('Ray '+(best+1));const answer=(await page.locator('.log p').first().innerText()).split(' → ')[1];candidates=candidates.filter(a=>ray(a,best)===answer)}assert.equal(candidates.length,1);await click('Mark atoms');for(const i of candidates[0])await mark(i);await click('Certify atoms')}edges.push('Incomplete atom certification leaves round active')};
solvers['false-weight']=async()=>{for(let stage=0;stage<3;stage++){const n=stage===2?6:9;let pans=Array(n).fill(0);for(let turn=0;turn<3;turn++){const labels=await page.getByRole('button',{name:/^Accuse coin/}).allTextContents(),hyp=labels.map(s=>[nums(s)[0]-1,s.includes('heavy')?1:-1]);if(hyp.length===1){await click(labels[0]);break}let best,score=Infinity;for(let code=1;code<3**n;code++){let v=code,a=[];for(let i=0;i<n;i++){a.push(v%3);v=v/3|0}if(a.filter(x=>x===1).length!==a.filter(x=>x===2).length)continue;const groups=[0,0,0];for(const[c,s]of hyp)groups[(a[c]===0?0:s*(a[c]===1?1:-1))+1]++;const m=Math.max(...groups);if(m<score){score=m;best=a}}for(let i=0;i<n;i++)for(let k=0;k<(best[i]-pans[i]+3)%3;k++)await mark(i);pans=best;await click('Weigh pans');if(turn===2){const ls=await page.getByRole('button',{name:/^Accuse coin/}).allTextContents();assert.equal(ls.length,1);await click(ls[0])}}}edges.push('Balanced-pan hypothesis elimination; three different counterfeit cases')};
solvers['three-of-a-kind']=async()=>{for(let s=0;s<6;s++){const cards=(await page.locator('.grid button').allTextContents()).map(v=>[v.includes('○')?0:v.includes('□')?1:2,nums(v)[0]-1,v.includes('open')?0:v.includes('striped')?1:2]);let found;for(let i=0;i<12;i++)for(let j=i+1;j<12;j++)for(let k=j+1;k<12;k++)if([0,1,2].every(x=>(cards[i][x]+cards[j][x]+cards[k][x])%3===0))found=[i,j,k];assert.ok(found);for(const i of found)await mark(i);await click('Claim triple')}edges.push('Six changing tableaux solved with all-three-property validation')};
solvers['second-look']=async()=>{for(let s=0;s<3;s++){const a=await page.locator('.grid button').allTextContents();await click('Switch scene');const b=await page.locator('.grid button').allTextContents();const diff=a.map((v,i)=>v!==b[i]?i:-1).filter(i=>i>=0);assert.equal(diff.length,3);for(const i of diff)await mark(i);await click('Submit three changes')}edges.push('Three visual scenes compared through view switches only')};
solvers['fog-journal']=async()=>{for(let s=0;s<2;s++){const visited=new Set(),path=[];let found=false;async function dfs(pos){visited.add(pos);const t=await text();if(pos===24){found=true;return true}const line=t.split('\n').find(x=>x.startsWith('Visible passages:'));for(const [name,delta,back]of [['North',-5,'South'],['East',1,'West'],['South',5,'North'],['West',-1,'East']]){if(!line.includes(name)||visited.has(pos+delta))continue;await click(name);path.push(back);if(await dfs(pos+delta))return true;await click(back);path.pop()}return false}await dfs(0);assert.ok(found);for(const back of path.reverse())await click(back)}edges.push('Mapped unknown mazes using visible exits, collected artifacts and retraced route')};
solvers['prefix-press']=async()=>{for(let s=0;s<3;s++){while(await page.getByRole('button',{name:/ · weight /}).count()>1){const ns=await page.getByRole('button',{name:/ · weight /}).allTextContents();const order=ns.map((v,i)=>({v,i,w:nums(v).at(-1)})).sort((a,b)=>a.w-b.w);await click(order[0].v);await click(order[1].v);await click('Merge selected trees')}const rows=await page.locator('table tr').allTextContents();const codes={};for(const row of rows.slice(1)){const m=row.match(/^([A-Z])([01]+)$/);codes[m[1]]=m[2]}const msg=(await text()).match(/Encode dispatch: ([A-Z]+)/)[1];for(const bit of msg.split('').map(x=>codes[x]).join(''))await click('Bit '+bit);await click('Transmit')}edges.push('Optimal tree and independently encoded dispatch for each alphabet')};
solvers['transit-observatory']=async()=>{for(let s=0;s<3;s++){for(let n=0;n<7;n++){const labels=await page.getByRole('button',{name:/^Claim period/}).allTextContents(),cs=labels.map(nums);if(cs.length===1){await click(labels[0]);break}let best=0,score=Infinity;for(let t=0;t<60;t++){const yes=cs.filter(([p,q])=>t%p===q).length,v=Math.max(yes,cs.length-yes);if(v<score){score=v;best=t}}await fill('Observation time',best);await click('Observe transit')}}edges.push('Adaptive public-hypothesis temporal sampling, uniqueness required')};
const predicates=[v=>v[0]<v[1]&&v[1]<v[2],v=>v[0]===v[2],v=>v.reduce((a,b)=>a+b,0)%2===0,v=>new Set(v).size===2,v=>v[1]>v[0]&&v[1]>v[2],v=>v.reduce((a,b)=>a+b,0)>=8],ruleNames=['strictly increasing','first equals third','sum is even','exactly two equal','middle is largest','sum at least eight'];
solvers['specimen-rule']=async()=>{for(let s=0;s<2;s++){let final;for(let n=0;n<9;n++){const labels=await page.getByRole('button',{name:/^Claim /}).allTextContents(),ids=labels.map(v=>ruleNames.indexOf(v.slice(6)));if(ids.length===1){final=ids[0];await click(labels[0]);break}let best,score=Infinity;for(let a=1;a<=4;a++)for(let b=1;b<=4;b++)for(let c=1;c<=4;c++){const v=[a,b,c],yes=ids.filter(i=>predicates[i](v)).length,m=Math.max(yes,ids.length-yes);if(m<score){score=m;best=v}}for(let i=0;i<3;i++)await fill('Specimen '+(i+1),best[i]);await click('Test specimen')}const lines=(await text()).split('\n').filter(x=>/^Specimen \d:/.test(x));assert.equal(lines.length,4);for(let i=0;i<4;i++)await click((predicates[final](nums(lines[i]).slice(1))?'Accept':'Reject')+' specimen '+(i+1));await click('Submit predictions')}edges.push('Constructed distinguishing experiments and classified unseen specimens')};
solvers['causal-lab']=async()=>{const wires=[['A','C'],['B','C'],['A','D'],['C','E'],['D','E'],['B','F'],['E','F']];function result(f,a,b,force){const v={A:a,B:b};for(const n of ['C','D','E','F'])v[n]=n===force?false:wires.some(([from,to],i)=>i!==f&&to===n&&v[from]);return ['C','D','E','F'].map(n=>+!!v[n]).join('')}for(let s=0;s<3;s++){let input=[false,false];for(let n=0;n<7;n++){const labels=await page.getByRole('button',{name:/^Diagnose /}).allTextContents(),ids=labels.map(t=>wires.findIndex(w=>t==='Diagnose '+w.join(' → ')));if(ids.length===1){await click(labels[0]);break}let best,score=Infinity;for(let a=0;a<2;a++)for(let b=0;b<2;b++)for(const f of ['none','C','D','E']){const g={};ids.forEach(i=>{const r=result(i,a,b,f);g[r]=(g[r]||0)+1});const m=Math.max(...Object.values(g));if(m<score){score=m;best=[a,b,f]}}for(let i=0;i<2;i++)if(!!best[i]!==input[i]){await click(`Input ${['A','B'][i]}: ${input[i]?'ON':'OFF'}`);input[i]=!input[i]}await page.getByLabel('Force lamp off').selectOption(best[2]);await click('Measure lamps')}}edges.push('Interventions distinguish every surviving wire hypothesis')};
solvers['parallax-post']=async()=>{for(let s=0;s<4;s++){const t=await text(),target=t.match(/Photograph ONLY landmarks ([A-Z]) and ([A-Z])/)[1];await click('Camera baseline 2');const left=await page.getByRole('button',{name:/^Left landmark/}).all(),right=await page.getByRole('button',{name:/^Right landmark/}).all();const ls=await Promise.all(left.map(x=>x.getAttribute('aria-label'))),rs=await Promise.all(right.map(x=>x.getAttribute('aria-label')));let targetDepth;for(let i=0;i<ls.length;i++){const lx=nums(ls[i])[0],shape=ls[i].split(', ')[1],candidates=rs.map((v,j)=>({v,j,x:nums(v)[0]})).filter(r=>r.v.split(', ')[1]===shape&&(lx-r.x)/2>=1&&(lx-r.x)/2<=4);assert.equal(candidates.length,1);if(String.fromCharCode(65+i)===target)targetDepth=(lx-candidates[0].x)/2;await click(ls[i]);await click(candidates[0].v)}await click('Focus depth '+targetDepth);await click('Expose plate')}edges.push('Active stereo correspondence reconstruction with changed camera baseline')};
solvers['wave-desk']=async()=>{for(let s=0;s<3;s++){const rows=await page.locator('table tr').all();const data=[];for(const r of rows.slice(1))data.push((await r.locator('td').allTextContents()).map(Number));let found;for(let a=-3;a<=3;a++)for(let b=-3;b<=3;b++)for(let c=-3;c<=3;c++)if(data.every(r=>a*r[1]+b*r[2]+c*r[3]===r[4]))found=[a,b,c];assert.ok(found);for(let k=0;k<3;k++)for(let n=0;n<Math.abs(found[k]);n++)await click((found[k]>0?'Increase ':'Decrease ')+String.fromCharCode(65+k));await click('Certify signal')}edges.push('Signed synthesis solved against all eight visible samples')};
solvers['twenty-questions']=async()=>{const names=['striped','round','large','warm','nocturnal'];function depth(cs){if(cs.length<2)return 0;let best=99;for(let k=0;k<5;k++){const yes=cs.filter(i=>(i>>k)&1),no=cs.filter(i=>!((i>>k)&1));if(yes.length&&no.length)best=Math.min(best,1+Math.max(depth(yes),depth(no)))}return best}for(let s=0;s<4;s++){for(let n=0;n<4;n++){const labels=await page.getByRole('button',{name:/^Identify /}).allTextContents(),cs=labels.map(v=>nums(v)[0]);if(cs.length===1){await click(labels[0]);break}let best=-1,score=99;for(let k=0;k<5;k++){const yes=cs.filter(i=>(i>>k)&1),no=cs.filter(i=>!((i>>k)&1));if(yes.length&&no.length){const d=Math.max(depth(yes),depth(no));if(d<score){score=d;best=k}}}assert.ok(best>=0);await click('Ask '+names[best])}}edges.push('Optimal adaptive questions for correlated trait catalogs under shared budget')};
solvers['scent-trail']=async()=>{for(let s=0;s<3;s++){let candidates=Array.from({length:49},(_,i)=>i),steps=0;while(candidates.length>1&&steps<20){await click('Scan scent');steps++;const info=await page.locator('.log p').first().innerText(),[x,y,d]=nums(info),[dx,dy]=info.includes('north')?[0,-1]:info.includes('east')?[1,0]:info.includes('south')?[0,1]:[-1,0];candidates=candidates.filter(i=>Math.abs(x-(i%7+dx))+Math.abs(y-((i/7|0)+dy))===d);if(candidates.length>1){const info=await text(),[px,py]=nums(info.match(/Rover at \([^)]*\)/)[0]),wind=info.match(/cell (north|east|south|west)/)[1],[wx,wy]=wind==='north'?[0,-1]:wind==='east'?[1,0]:wind==='south'?[0,1]:[-1,0];let best=null,score=-1;for(let sy=0;sy<7;sy++)for(let sx=0;sx<7;sx++){const groups={};for(const c of candidates){const r=Math.abs(sx-(c%7+wx))+Math.abs(sy-((c/7|0)+wy));groups[r]=(groups[r]||0)+1}const gain=(candidates.length-Math.max(...Object.values(groups)))/(1+Math.abs(px-sx)+Math.abs(py-sy));if(gain>score){score=gain;best=[sx,sy]}}let [cx,cy]=[px,py];while(cx!==best[0]){await click(cx<best[0]?'East':'West');cx+=Math.sign(best[0]-cx);steps++}while(cy!==best[1]){await click(cy<best[1]?'South':'North');cy+=Math.sign(best[1]-cy);steps++}}}assert.equal(candidates.length,1);let [x,y]=nums((await text()).match(/Rover at \([^)]*\)/)[0]);const tx=candidates[0]%7,ty=candidates[0]/7|0;while(x!==tx){await click(x<tx?'East':'West');x+=Math.sign(tx-x)}while(y!==ty){await click(y<ty?'South':'North');y+=Math.sign(ty-y)}await click('Collect beacon')}edges.push('Plume position inferred from logged wind-corrected distances')};
solvers['fossil-brush']=async()=>{for(let stage=0;stage<2;stage++){const counts=nums((await text()).split('\n').find(x=>x.startsWith('Sonar row'))).slice(0,6);for(let r=0;r<6;r++)if(counts[r]){const labels=await page.locator('.grid button').allTextContents();let start=-1;for(let c=0;c<4;c++)if([0,1,2].every(k=>labels[r*6+c+k].endsWith('depth 2')))start=c;assert.ok(start>=0);await click('Chisel three');await mark(r*6+start);await click('Brush');for(let c=0;c<6;c++){const i=r*6+c;let label=await page.locator('.grid button').nth(i).innerText();while(label.includes('depth')){await mark(i);label=await page.locator('.grid button').nth(i).innerText()}}}assert.match(await meter(),/integrity 10/);await click('Submit excavation')}edges.push('Safe broad cuts are required to fit action budget; finishing precision brush preserves integrity')};
solvers['archive-edit']=async()=>{for(let stage=0;stage<3;stage++){const rows=await page.locator('table tr').all(),base=[],target=[],fields=[];for(const r of rows.slice(1)){const c=await r.locator('td').allTextContents();fields.push(c[0]);base.push(c[1]);target.push(c[3])}const paragraphs=await page.locator('.commit-card>p').allTextContents();const commits=paragraphs.map(t=>{const name=t.split(':')[0],requires=t.match(/Requires: (\w+)/)[1],changes=t.split(': ').slice(1).join(': ').split('. Requires')[0].split('; ').map(v=>{const [f,x]=v.split(' → ');return[fields.indexOf(f),x]});return{name,requires,changes}});let solution;function dfs(state,used){if(state.every((v,i)=>v===target[i])){solution=used;return true}if(used.length===3)return false;for(const c of commits){if(used.includes(c.name)||c.requires!=='none'&&!used.includes(c.requires))continue;const next=state.slice();for(const [f,v]of c.changes)if(next[f]===base[f]||next[f]!==target[f])next[f]=v;if(dfs(next,used.concat(c.name)))return true}return false}assert.ok(dfs(base,[]),'No visible commit plan');for(const name of solution){await click('Cherry-pick '+name);while(await page.getByRole('button',{name:'Keep current',exact:true}).count()){const t=await text(),m=t.match(/Merge conflict in (\w+): current (\w+) vs incoming (\w+)/),required=target[fields.indexOf(m[1])];await click(m[3]===required?'Use incoming':'Keep current')}}await click('Publish release')}edges.push('Solved visible dependent patch subset/order under three-pick budget and both conflict choices')};
solvers['lens-library']=async()=>{for(let s=0;s<4;s++){await click('Send calibration [4,0,0,0,0,0]');const t=await text(),cal=nums(t.split('\n').find(x=>x.startsWith('Calibration output'))),k=cal[1]===1?2:cal[1]===2?0:1;const target=nums(t.split('\n').find(x=>x.startsWith('Observed blurred')));const blur=v=>v.map((x,i)=>k===0?(x+v[(i+5)%6])/2:k===1?(x+v[(i+1)%6])/2:(v[(i+5)%6]+2*x+v[(i+1)%6])/4);const sourceLines=t.split('\n').filter(x=>/^Source \d:/.test(x));let found=-1;for(const line of sourceLines){const ns=nums(line),v=blur(ns.slice(1));if(v.every((x,i)=>x===target[i]))found=ns[0]}assert.ok(found>0);await click(`Restore source ${found} with ${['L','R','B'][k]}`)}edges.push('Calibration kernel plus forward reconstruction identifies source')};
solvers['invisible-ink']=async()=>{for(let stage=0;stage<3;stage++){const counts=nums((await text()).split('\n').find(x=>x.startsWith('Manifest')));let candidates=[];for(const channel of ['UV','Heat','Pressure']){await click(channel);for(let r=0;r<3;r++)if(counts[r]){let labels=await page.locator('.grid button').allTextContents();let row=labels.slice(r*3,r*3+3).map((v,k)=>v.split(' ').at(-1).includes('0')?-1:r*3+k).filter(i=>i>=0);if(row.length>counts[r])await click('Scan row '+(r+1))}}const labels=await page.locator('.grid button').allTextContents();for(let r=0;r<3;r++)if(counts[r]){const row=labels.slice(r*3,r*3+3).map((v,k)=>v.split(' ').at(-1).includes('0')?-1:r*3+k).filter(i=>i>=0);assert.equal(row.length,counts[r]);candidates.push(...row)}assert.equal(candidates.length,2);for(const i of candidates)await mark(i);await click('Certify two parcels')}edges.push('Adaptive strip exposures stop when manifest and negative evidence identify remaining genuine parcels')};
solvers['clockmaker-cabinet']=async()=>{for(const n of ['Desk · a loose handle peeks out','Visit Greenhouse','Potting bench · loose joined blades','handle','blades','shears','Vines · something brass beneath','Put selected item away','Read sundial','Visit Workshop','brass key','Cabinet · brass keyhole','Visit Clock tower','Small drawer','gear','Clockwork · gear slot and winding socket','winding key','Clockwork · gear slot and winding socket','Set hour 3','Visit Workshop','Put selected item away','exit key','Front door · needs the clock’s key'])await click(n);edges.push('Causal item combination, fixture repair, winding, setting and escape chain')};
solvers['track-exchange']=async()=>{async function walk(dirs){for(const d of dirs)await click(d)}await click('Control Ada');await walk(['South','South']);await click('Pick up object');await walk(['East','East']);await click('Control Bo');await walk(['South','South','West','West','West','West']);await click('Pick up object');await walk(['East','East']);await click('Transfer at hatch');await walk(['East','East','South','South']);await click('Unlock and escape');await click('Control Ada');await walk(['East','South','South','East']);await click('Unlock and escape');edges.push('Key-gate chokepoint and water crossing precede simultaneous hatch exchange and both escapes')};
solvers['folded-world']=async()=>{const dirs=['North','East','South','West'];for(let n=0;n<18;n++){if(await page.locator('#status').getAttribute('data-outcome')==='win')break;const t=await text(),room=Number(t.match(/Room (\d+): local/)[1]),north=t.match(/local door (North|East|South|West) points/)[1],mirrored=t.includes('MIRRORED frame'),goal=t.includes('Next destination: Atrium')?0:Number(t.match(/Next destination: seal in room (\d+)/)[1]);const rows=await page.locator('table tr').all(),graph=[];for(const r of rows.slice(1))graph.push((await r.locator('td').allTextContents()).map(Number).slice(1));const q=[[room,[]]],seen=new Set([room]);let route;while(q.length){const [u,path]=q.shift();if(u===goal){route=path;break}graph[u].forEach((v,d)=>{if(!seen.has(v)){seen.add(v);q.push([v,path.concat(d)])}})}const local=(dirs.indexOf(north)+(mirrored?-route[0]:route[0])+4)%4;await click('Local '+dirs[local])}edges.push('Plans atlas routes and converts both rotated and reflected local frames')};
async function edgeCheck(id){const before=await meter();const same=async()=>assert.equal(await meter(),before);switch(id){
case 'ray-archive': await click('Certify atoms');await same();assert.match(await page.locator('#status').innerText(),/exactly three/);break;
case 'false-weight': await click('Weigh pans');await same();assert.match(await page.locator('#status').innerText(),/same nonzero/);break;
case 'three-of-a-kind': await click('Claim triple');await same();assert.match(await page.locator('#status').innerText(),/exactly three/);break;
case 'second-look': await click('Submit three changes');await same();assert.match(await page.locator('#status').innerText(),/exactly three/);break;
case 'fog-journal': await click('North');await same();assert.match(await page.locator('#status').innerText(),/wall/);break;
case 'prefix-press': await click('Merge selected trees');await same();assert.match(await page.locator('#status').innerText(),/two available/);break;
case 'transit-observatory':for(let i=0;i<6;i++)await click('Observe transit');assert.equal(await page.locator('.log p').count(),6);await click('Observe transit');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('.log p').count(),6);break;
case 'specimen-rule':for(let i=0;i<8;i++)await click('Test specimen');assert.equal(await page.locator('.log p').count(),8);await click('Test specimen');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('.log p').count(),8);break;
case 'causal-lab':for(let i=0;i<6;i++)await click('Measure lamps');assert.equal(await page.locator('.log p').count(),6);await click('Measure lamps');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('.log p').count(),6);break;
case 'parallax-post':await click('Expose plate');await same();assert.match(await page.locator('#status').innerText(),/all five/);break;
case 'wave-desk':await click('Decrease A');await click('Increase A');await same();break;
case 'twenty-questions':for(let i=0;i<12;i++)await click('Ask striped');await click('Ask striped');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('.log p').count(),13);break;
case 'scent-trail':for(let i=0;i<3;i++)await click('North');const m=await meter();await click('North');assert.equal(await meter(),m);assert.match(await page.locator('#status').innerText(),/boundary/);break;
case 'fossil-brush':await click('Chisel three');await mark(5);await same();assert.match(await page.locator('#status').innerText(),/three cells/);break;
case 'archive-edit':await click('Publish release');assert.match(await meter(),/2 review credits/);assert.match(await page.locator('#status').innerText(),/does not meet/);break;
case 'lens-library':for(let i=0;i<6;i++)await click('Send calibration [4,0,0,0,0,0]');await click('Send calibration [4,0,0,0,0,0]');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');break;
case 'invisible-ink':await click('Certify two parcels');await same();assert.match(await page.locator('#status').innerText(),/exactly two/);break;
case 'clockmaker-cabinet':for(let i=0;i<6;i++)await click('Front door · needs the clock’s key');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'loss');break;
case 'track-exchange':await click('Transfer at hatch');await same();assert.match(await page.locator('#status').innerText(),/Both explorers/);await click('South');await click('South');const gateMeter=await meter();await click('East');assert.equal(await meter(),gateMeter);assert.match(await page.locator('#status').innerText(),/iron gate requires/);break;
case 'folded-world':await click('Local North');assert.match(await meter(),/17 steps/);assert.equal(await page.locator('.log p').count(),1);break;
}edges.push('Asserted invalid-action guard or resource-exhaustion loss before restart');await click('Restart');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'playing')}
(async()=>{const coverage={passed:false,cases:[],limits:['Completion uses source-independent automated solvers operating visible DOM through UI inputs; not a claim of ordinary human play quality.','Mobile viewport is Chromium touch emulation, not a physical phone. Numeric fields/selects use mixed input; no screenreader testing.']};const dest=path.join(__dirname,'../coverage/discovery-room.json');fs.writeFileSync(dest,JSON.stringify(coverage,null,2));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{for(const profile of ['desktop','mobile-touch']){mobile=profile==='mobile-touch';const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:'reduce'});page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));for(const g of games){edges=[];await page.goto(base+'/mini-games/'+g.url);await page.waitForSelector('body[data-game-ready=true]');await click('Begin study');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'playing');await edgeCheck(g.id);await solvers[g.id]();assert.equal(await page.locator('#status').getAttribute('data-outcome'),'win',g.id+': '+await page.locator('#status').innerText());assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,g.id+' horizontal overflow');await click('Restart');assert.equal(await page.locator('#status').getAttribute('data-outcome'),'playing');assert.equal(await page.locator('#start').isVisible(),false);assert.deepEqual(errors,[]);const mixed=['transit-observatory','specimen-rule','causal-lab'].includes(g.id);coverage.cases.push({id:g.id,profile,passed:true,outcome:'win',restart:true,edgeCases:edges.concat('Restart clears terminal outcome'),touchOnly:mobile&&!mixed,inputMethod:mobile?(mixed?'Touch buttons plus programmatic native field fill/select':'Touchscreen tap on all gameplay buttons'):'Pointer clicks plus native field fill/select',verification:'solver-driven UI, visible evidence only'});fs.writeFileSync(dest,JSON.stringify(coverage,null,2));console.log(profile,g.id,'PASS')}await context.close()}coverage.passed=true;fs.writeFileSync(dest,JSON.stringify(coverage,null,2))}finally{await browser.close()}})().catch(e=>{console.error(e);process.exitCode=1});
