const {chromium}=require('playwright');const assert=require('node:assert/strict');const fs=require('node:fs'),path=require('node:path');
const studies=[{start:[16,24,12,8],ratios:[[1,2],[1,2]],locked:[],minimum:4},{start:[12,30,24,16,8,18],ratios:[[2,3],[1,2],[4,5]],locked:[0],minimum:10},{start:[30,18,36,12,8,24],ratios:[[2,3],[3,2],[3,5]],locked:[],minimum:12}];
function route(study,goal=a=>study.ratios.every(([n,d],i)=>a[i*2]*d===a[i*2+1]*n)){const q=[{a:study.start,path:[]}],seen=new Set([study.start.join()]);for(let j=0;j<q.length;j++){const {a,path}=q[j];if(goal(a))return path;for(let i=0;i<a.length-1;i++){if(study.locked.includes(i)||study.locked.includes(i+1))continue;const b=[...a];[b[i],b[i+1]]=[b[i+1],b[i]];if(!seen.has(b.join())){seen.add(b.join());q.push({a:b,path:[...path,i]});}}}throw Error('unsolvable study');}
const completeActions=studies.flatMap((s,i)=>[...route(s).flatMap(n=>['gear:'+n,'gear:'+(n+1)]),'geartest',...(i<2?['gearnext']:[])]);
module.exports={completeActions,studies,route};
async function run(){const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});const checks=[];for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:960},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});if(mobile)await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('blocked')};Storage.prototype.setItem=()=>{throw Error('blocked')};});const p=await context.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));const base=process.env.BASE_URL||'http://127.0.0.1:8793';await p.goto(base+'/mini-games/spatial-room/?game=gear-train');await p.waitForSelector('body[data-game-ready=true]');assert.match(await p.locator('#rules').textContent(),/Bolted sockets cannot move/);assert.match(await p.locator('#rules').textContent(),/Finish all three/);const click=async a=>mobile?p.locator(`[data-action="${a}"]`).tap():p.locator(`[data-action="${a}"]`).click();const apply=async moves=>{for(const i of moves){await click('gear:'+i);await click('gear:'+(i+1));}};const board=()=>p.locator('[data-action^="gear:"]').evaluateAll(bs=>bs.map(b=>Number(b.getAttribute('aria-label').match(/, (\d+) teeth/)[1])));
assert.deepEqual(await board(),studies[0].start);await click('geartest');assert.match(await p.locator('#message').textContent(),/Not yet/);assert.equal(await p.locator('#result').isHidden(),true);
await click('gear:0');await click('gear:2');assert.equal(await p.locator('#moves').textContent(),'0');assert.deepEqual(await board(),studies[0].start);assert.match(await p.locator('#message').textContent(),/Only neighbors/);await click('gear:0');await click('gearundo');assert.equal(await p.locator('#moves').textContent(),'0');
await p.locator('[data-action="gear:0"]').focus();await p.keyboard.press('Enter');await p.locator('[data-action="gear:1"]').focus();await p.keyboard.press('Space');assert.equal(await p.locator('#moves').textContent(),'1');assert.equal(await p.locator('#result').isHidden(),true);await click('gearundo');assert.deepEqual(await board(),studies[0].start);
// A correct total reduction is insufficient when individual meshes are wrong.
await apply(route(studies[0],a=>a.join()==='8,24,12,16'));await click('geartest');assert.match(await p.locator('#message').textContent(),/every individual mesh/i);assert.equal(await p.locator('[data-action="gearnext"]').count(),0);await click('gearretry');assert.deepEqual(await board(),studies[0].start);assert.equal(await p.locator('#moves').textContent(),'0');
await apply(route(studies[0]));await click('geartest');await click('gearnext');await click('gear:0');assert.match(await p.locator('#message').textContent(),/bolted/);assert.deepEqual(await board(),studies[1].start);await p.locator('#restart').click();assert.deepEqual(await board(),studies[0].start);assert.equal(await p.locator('#moves').textContent(),'0');
for(let i=0;i<studies.length;i++){const steps=route(studies[i]);assert.equal(steps.length,studies[i].minimum);await apply(steps);assert.equal(await p.locator('#result').isHidden(),true,'assembly alone does not skip certification');await click('geartest');if(i<2){assert.equal(await p.locator('#result').isHidden(),true);await click('gearnext');assert.deepEqual(await board(),studies[i+1].start);}}
assert.equal(await p.locator('#result').isVisible(),true);assert.equal(await p.locator('#moves').textContent(),'26');assert.equal(await p.locator('#best').textContent(),'26');if(mobile)assert.match(await p.locator('#storage-note').textContent(),/unavailable/);await p.screenshot({path:`/tmp/gear-depth-${mobile?'mobile':'desktop'}.png`,fullPage:true});await p.locator('#again').click();assert.deepEqual(await board(),studies[0].start);for(let n=0;n<3;n++){await click('gear:0');await click('gear:1');await p.locator('#restart').click();assert.deepEqual(await board(),studies[0].start);assert.equal(await p.locator('#moves').textContent(),'0');}if(!mobile){await p.reload();assert.equal(await p.locator('#best').textContent(),'26');}await p.setViewportSize({width:320,height:800});assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await p.goto(base+'/mini-games/spatial-room/?game=rover-script');await click('command:F');await click('run');assert.match(await p.locator('#message').textContent(),/Command 1.*blocked from row 5, column 1/);assert.equal(await p.locator('#result').isHidden(),true);assert.match(await p.locator('#board').textContent(),/Program: 1\/30 commands · Run attempts: 1/);assert.deepEqual(errors,[]);checks.push({mobile,completedStudies:3,minimumSwaps:[4,10,12],fullRoundSwaps:26,ordinaryFirstSwapNotWin:true,productOnlyRejected:true,illegalNonNeighbor:true,lockedSocket:true,undo:true,stageReset:true,midProgressRestart:true,repeatedRestart:true,keyboard:true,reducedMotion:mobile,storage:mobile?'blocked fallback':'persisted record',overflow320:false,roverBlockedCommandFeedback:true,consoleErrors:[]});await context.close();console.log('Gear depth',mobile?'mobile':'desktop','passed');}await browser.close();fs.writeFileSync(path.join(__dirname,'../coverage/gear-depth.json'),JSON.stringify({passed:true,checks,limits:['Chromium desktop and emulated mobile only.','Three authored studies; adjacent-swap shortest solutions independently enumerated by BFS.','No production state injection or response probes.']},null,2)+'\n');}
if(require.main===module)run().catch(e=>{console.error(e);process.exit(1)});
