/* Real browser lifecycle regression using test-only engines. This is NOT game evidence. */
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {chromium,webkit}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BASE_URL||'http://127.0.0.1:8790';
const realTime={id:'clock-fixture',name:'Clock fixture',description:'Test-only clock',rules:['Hold the input.','Play three studies.','Restart at any point.'],controls:'Native controls.',endless:{supported:false,reason:'Test fixture'}};
const puzzle={...realTime,id:'journey-fixture',name:'Journey fixture',endless:{supported:true,design:'Test-only fresh seeded chapters.'}};
const authoredEngine=`{stages:3,init:({stage,seed,mode})=>({stage,seed,mode,n:0,aim:5,score:0,outcome:'playing',note:'Make two moves to complete this test study.'}),act(s,a){if(a.startsWith('aim:'))s.aim=Number(a.split(':')[1]);if(a==='move'){s.n++;s.score+=10;s.note='Move '+s.n;if(s.n===2){s.outcome='win';s.note='Study complete.'}}else if(a==='fail'){s.outcome='loss';s.note='Test failure.'}},render(c,s){c.p('Visible seed '+s.seed+' / moves '+s.n);c.button('move','Make move');c.button('fail','Fail study');c.range('aim','Aim',{min:0,max:10,step:1,value:s.aim})}}`;
const clockEngine=`{stages:3,realtime:true,undo:false,init:({stage,seed,mode})=>({stage,seed,mode,time:0,held:false,score:0,outcome:'playing',note:'Test clock running.'}),act(s,a){if(a==='down:thrust')s.held=true;if(a==='up:thrust')s.held=false},pause(s){s.held=false},tick(s,dt){s.time+=dt;s.score+=s.held?dt*10:0},render(c,s){c.live('Elapsed',s=>s.time.toFixed(2));c.live('Input',s=>s.held?'held':'released');c.hold('thrust','Hold thrust');c.canvas('clock',200,100,(ctx,s)=>{ctx.clearRect(0,0,200,100);ctx.fillRect(s.time%180,25,10,10)})}}`;
function pageHTML(){const template=fs.readFileSync(path.join(root,'field-room/index.html'),'utf8');return template.replace('<script type="module" src="room.mjs"></script>',`<script type="module">import {mountRoom} from '../journey/journey.mjs';const games=${JSON.stringify([puzzle,realTime])};const engines={'journey-fixture':${authoredEngine},'clock-fixture':${clockEngine}};mountRoom({games,engines,title:'TEST ONLY'});</script>`)}
const sourceNames=['journey/journey.mjs','journey/journey.css','field-room/index.html','tests/journey.cjs'];
function sourceFiles(){return sourceNames.map(f=>({path:'mini-games/'+f,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')}))}
function sourceHash(){const h=crypto.createHash('sha256');for(const f of sourceNames)h.update(f+'\0').update(fs.readFileSync(path.join(root,f)));return h.digest('hex')}
(async()=>{
 const tested=sourceHash(),filesBefore=sourceFiles(),engine=process.env.BROWSER_ENGINE||'chromium',browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,...(engine==='chromium'?{executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']}:{})});
 const cases=[];try{
 for(const mobile of [false,true]){
  const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'}),page=await context.newPage(),errors=[];
  page.on('pageerror',e=>errors.push(e.message));await page.route('**/mini-games/journey-test/**',route=>route.fulfill({contentType:'text/html',body:pageHTML()}));
  const act=async selector=>{const b=page.locator(selector);if(mobile)await b.tap();else{await b.focus();await b.press('Enter')}};
  await page.goto(base+'/mini-games/journey-test/?game=journey-fixture&seed=42');await page.waitForSelector('body[data-game-ready=true]');assert.match(await page.locator('#seed-note').innerText(),/Run seed 42/);
  await act('#start');const original=await page.locator('#board').innerText();await act('[data-action=move]');assert.equal(await page.locator('#score').innerText(),'10');await act('#undo');assert.equal(await page.locator('#board').innerText(),original);assert.equal(await page.locator('#score').innerText(),'0');
  await act('[data-action=move]');await act('#reset');assert.equal(await page.locator('#board').innerText(),original);assert.equal(await page.locator('#score').innerText(),'0');
  await act('[data-action=fail]');assert.equal(await page.locator('body').getAttribute('data-outcome'),'loss');assert.equal(await page.locator('#board button:not(:disabled)').count(),0);await act('#undo');assert.equal(await page.locator('body').getAttribute('data-outcome'),'playing');
  await act('#restart');assert.equal(await page.locator('#board').innerText(),original);if(!mobile){await page.locator('[data-action=aim]').focus();await page.keyboard.press('ArrowRight');await page.keyboard.press('ArrowRight');assert.equal(await page.locator('[data-action=aim]').inputValue(),'7');assert.equal(await page.locator('[data-action=aim]').evaluate(e=>e===document.activeElement),true);await act('#reset')}
  for(let n=0;n<3;n++){await act('[data-action=move]');await act('[data-action=move]');assert.equal(await page.locator('#score').innerText(),String((n+1)*20));assert.equal(await page.locator('body').getAttribute('data-outcome'),n<2?'study-win':'win');if(n<2){await act('#next');assert.equal(await page.locator('#score').innerText(),String((n+1)*20))}}
  assert.equal(await page.locator('#best').innerText(),'60');assert.equal(await page.locator('#next').isVisible(),false);await act('#again');assert.equal(await page.locator('#score').innerText(),'0');assert.equal(await page.locator('#best').innerText(),'60');
  await page.locator('#mode').selectOption('endless');await act('#start');assert.equal(await page.locator('#reset').isEnabled(),false);assert.equal(await page.locator('#undo').isEnabled(),false);
  await act('[data-action=move]');await act('[data-action=move]');await act('#next');const second=await page.locator('#board').innerText();assert.notEqual(second,original);assert.equal(await page.locator('#score').innerText(),'20');await act('[data-action=move]');await act('#end-run');assert.equal(await page.locator('#score').innerText(),'30');assert.equal(await page.locator('#best').innerText(),'30');assert.equal(await page.locator('#board button:not(:disabled)').count(),0);
  await act('#restart');assert.equal(await page.locator('#score').innerText(),'0');assert.equal(await page.locator('#best').innerText(),'30');await page.locator('#mode').selectOption('finite');assert.equal(await page.locator('#best').innerText(),'60');
  await page.goto(base+'/mini-games/journey-test/?game=absent');assert.equal(await page.locator('body').getAttribute('data-outcome'),'unavailable');assert.equal(await page.locator('#start').isVisible(),false);assert.match(await page.locator('#title').innerText(),/unavailable/);
  await page.goto(base+'/mini-games/journey-test/?game=clock-fixture&seed=42');await page.clock.install();await act('#start');await page.clock.runFor(500);const elapsed=()=>page.locator('.live-readout').first().innerText();await act('#pause');const before=await elapsed();await page.clock.runFor(1000);assert.equal(await elapsed(),before,'Pause freezes active time');await act('#pause');await page.clock.runFor(400);assert.notEqual(await elapsed(),before);assert.equal(await page.locator('#endless-option').evaluate(e=>e.disabled),true);
  if(!mobile){await page.locator('[data-action=thrust]').focus();await page.keyboard.down('Space');await page.clock.runFor(300);assert.match(await page.locator('.live-readout').nth(1).innerText(),/held/);await page.keyboard.up('Space');assert.match(await page.locator('.live-readout').nth(1).innerText(),/released/)}else{const box=await page.locator('[data-action=thrust]').boundingBox();await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);assert.match(await page.locator('.live-readout').nth(1).innerText(),/released/)}
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const frozen=await elapsed();await page.clock.runFor(700);assert.equal(await elapsed(),frozen,'Blur freezes active time');await act('#restart');assert.ok(Number((await elapsed()).split(': ')[1])<.1);assert.match(await page.locator('.live-readout').nth(1).innerText(),/released/);
  await page.setViewportSize({width:320,height:740});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);
  cases.push({profile:mobile?'mobile-touch':'desktop',passed:true,scope:'Test-only engines verify lifecycle, finite/endless score banking, exact-seed replay, failure/undo, resets, unavailable links, real-time pause/blur/held-input clearing and 320px layout.'});await context.close();
 }
 for(const failure of ['read','write']){const context=await browser.newContext(),page=await context.newPage();await page.route('**/mini-games/journey-test/**',route=>route.fulfill({contentType:'text/html',body:pageHTML()}));await page.addInitScript(mode=>{if(mode==='read')Object.defineProperty(window,'localStorage',{get(){throw Error('blocked')}});else Storage.prototype.setItem=function(){throw Error('quota')}},failure);await page.goto(base+'/mini-games/journey-test/?game=journey-fixture&seed=42');await page.locator('#start').click();await page.locator('[data-action=move]').click();await page.locator('[data-action=move]').click();assert.equal(await page.locator('#best').innerText(),'20');assert.match(await page.locator('#storage-note').innerText(),/memory/);await page.locator('#restart').click();assert.equal(await page.locator('#best').innerText(),'20');cases.push({profile:'storage-'+failure,passed:true});await context.close()}
 assert.equal(sourceHash(),tested);assert.deepEqual(sourceFiles(),filesBefore);const report={passed:true,sourceHash:tested,sourceFiles:filesBefore,sourceUnchanged:true,verifiedAt:new Date().toISOString(),engine,browserVersion:browser.version(),cases,limits:['Synthetic game engines are test-only and do not attest any playable-game rules or difficulty.','Touch is browser emulation, not a physical device.']};fs.writeFileSync(path.join(root,'coverage/journey-'+engine+'.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
