/* Guided full UI reachability; independent ordinary-play reviews are separate artifacts. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),room=path.join(root,'parlour-room'),manifest=JSON.parse(fs.readFileSync(path.join(room,'games.json')));
const fixtures={};for(const f of ['parlour-paths.json','parlour-b02-b05-paths.json','parlour-b13-guided-paths.json']){const file=path.join(__dirname,'fixtures',f);if(fs.existsSync(file))for(const [id,variants] of Object.entries(JSON.parse(fs.readFileSync(file))))fixtures[id]={...fixtures[id],...variants};}
const selected=process.env.GAME_IDS?.split(','),games=manifest.filter(g=>!selected||selected.includes(g.id));
const report={suite:'parlour-room',passed:false,scope:selected?'partial':'complete',classification:'Guided reproducibility through actual UI; source-planned routes may use hidden information. Not independent ordinary play.',cases:[],failures:[]};
const save=()=>fs.writeFileSync(path.join(root,'coverage','parlour-room.json'),JSON.stringify(report,null,2)+'\n');
(async()=>{for(const helper of ['parlour-rules.mjs','parlour-b02-b05-rules.mjs','parlour-market-estate-properties.cjs','parlour-startup.cjs'])require('node:child_process').execFileSync(process.execPath,[path.join(__dirname,helper)],{stdio:'inherit'});const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});try{
 const queue=[...games];async function runGame(g){const cases=fixtures[g.id];if(!cases?.main||!cases?.failure||!cases?.secondary||cases.main.seed===cases.secondary.seed){report.failures.push(g.id+': missing main win, natural loss or distinct secondary deal fixture');save();return;}
 const engine=(await import(path.join(room,g.module+'.mjs'))).default;
 for(const [variant,f] of Object.entries(cases)){if(!['main','failure','secondary'].includes(variant))continue;
 const hash=crypto.createHash('sha256').update(fs.readFileSync(path.join(room,g.module+'.mjs'))).digest('hex');
 try{assert.equal(f.sourceSha256,hash,'Fixture source hash changed');const s={id:g.id,seed:f.seed,rng:f.seed,done:false,log:[]};engine.init(s);for(const code of f.path){assert(!s.done,'Path continues after terminal');assert(engine.actions(s).some(a=>a.code===code),'Illegal model action '+code);engine.move(s,code);assert(!/\b(?:undefined|NaN)\b/.test(JSON.stringify(engine.view(s))),'Invalid rendered state');}assert(s.done);assert.equal(s.outcome,f.outcome);assert.equal(f.outcome,variant==='failure'?'loss':'win');}catch(e){report.failures.push(`${g.id}/${variant}: ${e.message}`);save();continue;}
 for(const mobile of[false,true]){const profile=mobile?'mobile-touch':'desktop',context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},isMobile:mobile,hasTouch:mobile}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 try{await page.goto((process.env.BASE_URL||'http://127.0.0.1:8781')+'/mini-games/parlour-room/?game='+g.id);await page.locator('body[data-game-ready="true"]').waitFor();assert.equal(await page.locator('h1').innerText(),g.name);assert((await page.locator('#rules').innerText()).length>50);
 let activation=0;const use=async loc=>{assert(await loc.isVisible());assert(await loc.isEnabled());if(mobile){await loc.scrollIntoViewIfNeeded();await loc.tap();}else{await loc.focus();await page.keyboard.press(activation++%2?'Space':'Enter');}};
 await use(page.locator('#start'));for(let seed=731;seed<f.seed;seed+=7919)await use(page.locator('#new-deal'));assert((await page.locator('#deal').innerText()).includes(String(f.seed)));const initial=await page.locator('#scoreboard').innerText();
 for(const code of f.path){let loc=page.locator('[data-action]').filter({visible:true});loc=page.locator(`[data-action=${JSON.stringify(code)}]`).filter({visible:true}).first();const large=page.locator(`[data-board-action=${JSON.stringify(code)}]`).first();if(mobile&&await large.count()){if(!await large.isVisible())await use(page.locator('#large-controls summary'));loc=large;}await use(loc);}
 await page.locator('body[data-completed="true"]').waitFor();assert.equal(await page.locator('body').getAttribute('data-outcome'),f.outcome);assert((await page.locator('#result-title').innerText()).length>8);assert.equal(await page.locator('[data-action]').count(),0,'Terminal actions removed');await use(page.locator('#again'));assert.equal(await page.locator('body').getAttribute('data-completed'),'false');assert.equal(await page.locator('#scoreboard').innerText(),initial);assert.equal(await page.locator('#status').getAttribute('role'),'status');
 if(mobile){await page.setViewportSize({width:320,height:740});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'320px overflow');}assert.deepEqual(errors,[]);
 report.cases.push({id:g.id,designId:g.designId,profile,variant,passed:true,outcome:f.outcome,restart:true,sourceSha256:hash,seed:f.seed,actions:f.path.length,inputMethod:mobile?'touchscreen.tap':'native focused button Enter/Space',touchOnly:mobile,edgeCases:['full terminal outcome','terminal controls removed','same-deal restart restores initial score','no page errors',...(mobile?['320px no horizontal overflow']:[])],classification:f.classification});console.log('PASS',g.id,variant,profile,f.path.length);
 }catch(e){report.failures.push(`${g.id}/${variant}/${profile}: ${e.stack}`);console.log('FAIL',g.id,variant,profile,e.message);}finally{await context.close();save();}
 }
 }
 }
 await Promise.all(Array.from({length:3},async()=>{while(queue.length)await runGame(queue.shift());}));
 report.passed=!selected&&report.failures.length===0&&manifest.every(g=>['desktop','mobile-touch'].every(p=>['main','failure','secondary'].every(v=>report.cases.some(c=>c.id===g.id&&c.profile===p&&c.variant===v&&c.outcome===(v==='failure'?'loss':'win')))));save();if(report.failures.length)process.exitCode=1;
}finally{await browser.close();}})().catch(e=>{report.failures.push(e.stack);save();console.error(e);process.exitCode=1;});
