/* Read-only solver probes guide real DOM inputs. No state writes or shipped hooks. */
const {chromium}=require('playwright');const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const games=require('../puzzle-lab/games.json'),out=path.join(__dirname,'../coverage/puzzle-lab.json'),base=process.env.BASE_URL||'http://127.0.0.1:8790';
const range=n=>Array.from({length:n},(_,i)=>i),sum=a=>a.reduce((a,b)=>a+b,0),same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),dirs={U:[0,-1],R:[1,0],D:[0,1],L:[-1,0]},opp={U:'D',D:'U',L:'R',R:'L'};
const adj=(p,n)=>[p-n,p+n,...(p%n?[p-1]:[]),...(p%n<n-1?[p+1]:[])].filter(i=>i>=0&&i<n*n),step=(p,d,n,walls)=>{const[x,y]=dirs[d],a=p%n+x,b=Math.floor(p/n)+y,q=b*n+a;return a<0||a>=n||b<0||b>=n||walls.includes(q)?p:q;};
function bfs(start,goal,next,key=x=>JSON.stringify(x),limit=1000000){const q=[start],keys=new Map([[key(start),0]]),prev=[[-1,null]];let end=-1;for(let i=0;i<q.length;i++){if(goal(q[i])){end=i;break;}for(const[action,state]of next(q[i])){const k=key(state);if(!keys.has(k)){keys.set(k,q.length);prev.push([i,action]);q.push(state);}}if(q.length>limit)throw Error('Solver state limit');}assert.ok(end>=0,'reachable solution');const actions=[];while(prev[end][0]>=0){actions.push(prev[end][1]);end=prev[end][0];}return actions.reverse();}
const subsets=(n,k)=>{const a=[],walk=(v,s)=>{if(v.length===k){a.push(v);return;}for(let i=s;i<n;i++)walk([...v,i],i+1);};walk([],0);return a;};
function connected(nodes,edges){if(!nodes.length)return false;const seen=new Set([nodes[0]]),q=[nodes[0]];while(q.length){const a=q.shift();edges.forEach(([u,v])=>{const b=u===a?v:v===a?u:-1;if(nodes.includes(b)&&!seen.has(b)){seen.add(b);q.push(b);}});}return seen.size===nodes.length;}
const gridEdges=n=>range(n*n).flatMap(i=>adj(i,n).filter(j=>j>i).map(j=>[i,j]));
function acyclic(n,edges){const indeg=Array(n).fill(0);edges.forEach(e=>indeg[e[1]]++);const q=range(n).filter(i=>!indeg[i]);for(let i=0;i<q.length;i++)edges.filter(e=>e[0]===q[i]).forEach(e=>{if(!--indeg[e[1]])q.push(e[1]);});return q.length===n;}
const roll=(o,d)=>{const[t,b,n,s,w,e]=o;return d==='U'?[s,n,t,b,w,e]:d==='D'?[n,s,b,t,w,e]:d==='L'?[e,w,n,s,t,b]:[w,e,n,s,b,t];};
function parity(a,n){return[...range(n).map(r=>sum(a.slice(r*n,r*n+n))%2),...range(n).map(c=>sum(range(n).map(r=>a[r*n+c]))%2),...range(n).map(d=>sum(range(n).map(r=>a[r*n+(d-r+n)%n]))%2)];}
const solvers={};
solvers['mutual-match']=m=>{const free=range(m.n),next=Array(m.n).fill(0),partners=Array(m.n).fill(-1);while(free.length){const a=free.shift(),b=m.left[a][next[a]++],old=partners[b];if(old<0||m.right[b].indexOf(a)<m.right[b].indexOf(old)){partners[b]=a;if(old>=0)free.push(old);}else free.push(a);}return partners.flatMap((a,b)=>['courier-'+a,'route-'+b]);};
solvers['ice-station']=m=>bfs([m.p,0],([p,b])=>p===m.dock&&b===(1<<m.goals.length)-1,([p,b])=>Object.keys(dirs).map(d=>{let t=p,q,mask=b;while((q=step(t,d,m.n,m.walls))!==t){t=q;const i=m.goals.indexOf(t);if(i>=0)mask|=1<<i;}return['dir-'+d,[t,mask]];}));
solvers['cube-seal']=m=>{let p=m.p,o=m.o,result=[];for(const[target,face]of m.seals){const moves=bfs([p,o],([q,r])=>q===target&&r[1]===face,([q,r])=>Object.keys(dirs).filter(d=>step(q,d,m.n,m.walls)!==q).map(d=>[d,[step(q,d,m.n,m.walls),roll(r,d)]]));for(const d of moves){p=step(p,d,m.n,m.walls);o=roll(o,d);result.push('dir-'+d);}}return result;};
solvers['knight-exchange']=m=>bfs(m.cells,a=>same(a,m.goal),a=>a.flatMap((v,i)=>v?range(a.length).filter(j=>!a[j]&&Math.abs(i%m.n-j%m.n)*Math.abs(Math.floor(i/m.n)-Math.floor(j/m.n))===2).map(j=>{const t=a.slice();t[j]=v;t[i]=0;return[[i,j],t];}):[]),a=>a.join('')).flatMap(([a,b])=>['cell-'+a,'cell-'+b]);
solvers['map-inks']=m=>{const a=Array(m.n).fill(0);function solve(i){if(i===m.n)return true;for(let v=1;v<=3;v++){a[i]=v;if(m.edges.every(([x,y])=>!a[x]||!a[y]||a[x]!==a[y])&&solve(i+1))return true;}a[i]=0;return false;}assert.ok(solve(0));return a.flatMap((v,i)=>['ink-'+v,'node-'+i]);};
solvers['circuit-break']=m=>{for(let k=0;k<=m.budget;k++)for(const s of subsets(m.n-2,k).map(a=>a.map(i=>i+1))){const nodes=range(m.n).filter(i=>!s.includes(i)),seen=new Set([0]),q=[0];for(let i=0;i<q.length;i++)m.edges.forEach(([u,v])=>{const b=u===q[i]?v:v===q[i]?u:-1;if(nodes.includes(b)&&!seen.has(b)){seen.add(b);q.push(b);}});if(!seen.has(m.n-1))return s.map(i=>'node-'+i);}throw Error('cut unsolvable');};
solvers['copper-tree']=m=>{const parent=range(m.n),root=a=>parent[a]===a?a:(parent[a]=root(parent[a])),result=[];m.edges.map((e,i)=>[...e,i]).sort((a,b)=>a[2]-b[2]).forEach(([a,b,w,i])=>{a=root(a);b=root(b);if(a!==b){parent[a]=b;result.push('edge-'+i);}});return result;};
solvers['river-capacity']=m=>{const cap=range(m.n).map(()=>Array(m.n).fill(0));m.edges.forEach(([a,b,w])=>cap[a][b]=w);for(;;){const prev=Array(m.n).fill(-1),q=[0];prev[0]=0;for(let i=0;i<q.length&&prev[m.n-1]<0;i++)range(m.n).forEach(b=>{if(prev[b]<0&&cap[q[i]][b]>0){prev[b]=q[i];q.push(b);}});if(prev[m.n-1]<0)break;let flow=Infinity;for(let b=m.n-1;b;b=prev[b])flow=Math.min(flow,cap[prev[b]][b]);for(let b=m.n-1;b;b=prev[b]){cap[prev[b]][b]-=flow;cap[b][prev[b]]+=flow;}}return m.edges.flatMap(([a,b,w],i)=>Array(w-cap[a][b]).fill('edge-'+i));};
solvers['honest-company']=m=>{const claim=(r,v)=>r.op==='same'?v[r.a]===v[r.b]:r.op==='different'?v[r.a]!==v[r.b]:r.op==='both'?v[r.a]&&v[r.b]:r.op==='either'?v[r.a]||v[r.b]:!v[r.a];for(let bits=0;bits<1<<m.n;bits++){const a=range(m.n).map(i=>bits>>i&1);if(m.claims.every((r,i)=>Boolean(claim(r,a))===Boolean(a[i])))return a.flatMap((v,i)=>Array(v?1:2).fill('speaker-'+i));}throw Error('truth unsolvable');};
solvers['gate-foundry']=m=>{const gate=(t,a,b)=>t===0?a&b:t===1?a|b:t===2?a^b:t===3?1-(a&b):1-(a|b);for(let bits=0;bits<5**m.wires.length;bits++){let n=bits;const gates=m.wires.map(()=>{const v=n%5;n=Math.floor(n/5);return v;}),got=range(8).map(i=>{const v=[i>>2&1,i>>1&1,i&1];m.wires.forEach(([a,b],j)=>v.push(gate(gates[j],v[a],v[b])));return v.at(-1);});if(same(got,m.target))return gates.flatMap((v,i)=>Array(v).fill('gate-'+i));}throw Error('gate unsolvable');};
solvers['rewrite-press']=m=>bfs(m.ribbon,a=>a===m.target,a=>m.rules.flatMap(([from,to],r)=>range(a.length).filter(i=>a.slice(i,i+from.length)===from).map(i=>[[r,i],a.slice(0,i)+to+a.slice(i+from.length)]).filter(([,s])=>s.length<=12)),a=>a,200000).flatMap(([r,i])=>['rule-'+r,'char-'+i]);
solvers['twin-steps']=m=>bfs([m.a,m.b],([a,b])=>a===m.goalA&&b===m.goalB,([a,b])=>Object.keys(dirs).map(d=>['dir-'+d,[step(a,d,m.n,m.wallsA),step(b,opp[d],m.n,m.wallsB)]]));
solvers['seed-tomorrow']=m=>{for(let bits=0;bits<1<<m.n;bits++){let a=range(m.n).map(i=>bits>>i&1);for(let d=0;d<m.days;d++)a=a.map((_,i)=>a[(i+m.n-1)%m.n]^a[(i+1)%m.n]);if(same(a,m.target))return range(m.n).filter(i=>bits>>i&1).map(i=>'seed-'+i);}throw Error('seed unsolvable');};
solvers['voxel-post']=m=>{const ids=range(27).map(i=>{const x=i%3,y=Math.floor(i/3)%3,z=Math.floor(i/9);return[z*3+y,9+z*3+x,18+y*3+x];}),remaining=Array(27).fill(3),want=m.target.flat(),a=Array(27).fill(0);function solve(i){if(i===27)return want.every(v=>v===0);const keys=ids[i];keys.forEach(k=>remaining[k]--);for(const v of [0,1]){keys.forEach(k=>want[k]-=v);a[i]=v;if(keys.every(k=>want[k]>=0&&want[k]<=remaining[k])&&solve(i+1))return true;keys.forEach(k=>want[k]+=v);}keys.forEach(k=>remaining[k]++);return false;}assert.ok(solve(0),'voxel solvable');return a.flatMap((v,i)=>v?['voxel-'+i]:[]);};
solvers['hitori-harbor']=m=>{const n=m.n,edges=gridEdges(n),pairs=range(n*n).flatMap(i=>range(n*n).filter(j=>j>i&&m.cells[i]===m.cells[j]&&(i%n===j%n||Math.floor(i/n)===Math.floor(j/n))).map(j=>[i,j]));function solve(shade){const pair=pairs.find(([a,b])=>!shade.includes(a)&&!shade.includes(b));if(!pair)return connected(range(n*n).filter(i=>!shade.includes(i)),edges)?shade:null;for(const i of pair)if(!adj(i,n).some(j=>shade.includes(j))){const result=solve([...shade,i]);if(result)return result;}return null;}const shade=solve([]);assert.ok(shade,'hitori solvable');return shade.map(i=>'cell-'+i);};
solvers['island-census']=m=>{const n=m.n,all=range(n*n),clues=m.clues.map(([i])=>i),candidates=m.clues.map(([anchor,size])=>{let sets=[[anchor]],seen=new Set;for(let k=1;k<size;k++){const next=[];sets.forEach(s=>s.flatMap(i=>adj(i,n)).forEach(j=>{if(s.includes(j)||clues.includes(j)||adj(j,n).some(x=>clues.includes(x)&&x!==anchor))return;const t=[...s,j].sort((a,b)=>a-b),key=t.join(',');if(!seen.has(key)){seen.add(key);next.push(t);}}));sets=next;}return sets;});const order=range(clues.length).sort((a,b)=>candidates[a].length-candidates[b].length);function solve(k,land){if(k===order.length){const sea=all.filter(i=>!land.includes(i));return connected(sea,gridEdges(n))&&!all.some(i=>i%n<n-1&&i<n*(n-1)&&[i,i+1,i+n,i+n+1].every(j=>sea.includes(j)))?land:null;}for(const s of candidates[order[k]])if(s.every(i=>!land.includes(i)&&!adj(i,n).some(j=>land.includes(j)))){const answer=solve(k+1,[...land,...s]);if(answer)return answer;}return null;}const land=solve(0,[]);assert.ok(land,'islands solvable');return all.filter(i=>!clues.includes(i)).flatMap(i=>Array(land.includes(i)?1:2).fill('cell-'+i));};
solvers['parcel-survey']=m=>{const n=m.n,options=m.clues.map(([anchor,area])=>{const out=[];for(let h=1;h<=n;h++)if(area%h===0){const w=area/h;if(w>n)continue;for(let y=0;y+h<=n;y++)for(let x=0;x+w<=n;x++){const cells=range(n*n).filter(i=>i%n>=x&&i%n<x+w&&Math.floor(i/n)>=y&&Math.floor(i/n)<y+h);if(cells.includes(anchor)&&m.clues.filter(([i])=>cells.includes(i)).length===1)out.push({cells,corners:[y*n+x,(y+h-1)*n+x+w-1]});}}return out;});const order=range(options.length).sort((a,b)=>options[a].length-options[b].length);function solve(k,used,result){if(k===order.length)return result;for(const rect of options[order[k]])if(rect.cells.every(i=>!used.includes(i))){const r=solve(k+1,[...used,...rect.cells],[...result,rect]);if(r)return r;}return null;}const result=solve(0,[],[]);assert.ok(result);return result.flatMap(r=>r.corners.map(i=>'cell-'+i));};
solvers['arrow-audit']=m=>{for(let k=0;k<=m.budget;k++)for(const set of subsets(m.edges.length,k))if(acyclic(m.n,m.edges.map((e,i)=>set.includes(i)?[e[1],e[0]]:e)))return set.map(i=>'edge-'+i);throw Error('cycle unsolvable');};
solvers['parity-repair']=m=>{for(let k=0;k<=m.budget;k++)for(const set of subsets(m.n*m.n,k)){const a=m.received.map((v,i)=>set.includes(i)?1-v:v);if(same(parity(a,m.n),m.target))return set.map(i=>'bit-'+i);}throw Error('parity unsolvable');};
solvers['safety-ferry']=m=>bfs([0,0],([bits])=>bits===(1<<m.names.length)-1,([bits,boat])=>{const at=range(m.names.length).filter(i=>(bits>>i&1)===boat),sets=[[],...range(m.capacity).flatMap(k=>subsets(at.length,k+1).map(s=>s.map(i=>at[i])))];return sets.map(s=>{const next=bits^sum(s.map(i=>1<<i)),b=1-boat;return[s,[next,b]];}).filter(([, [bits,b]])=>!m.conflicts.some(([a,c])=>(bits>>a&1)===(bits>>c&1)&&(bits>>a&1)!==b));}).flatMap(set=>[...set.map(i=>'cargo-'+i),'sail']);
const report={family:'puzzle-lab',passed:false,cases:[],sourceHash:crypto.createHash('sha256').update(fs.readFileSync(path.join(__dirname,'../puzzle-lab/engines.js'))).update(fs.readFileSync(path.join(__dirname,'../puzzle-lab/room.js'))).digest('hex'),limits:['Completion is solver-guided reachability through real UI inputs, based on read-only state snapshots injected only in tests.','Ordinary-input checks cover explicit invalid actions, keyboard focus and restart; they do not establish human difficulty or independent solve quality.','Mobile-touch uses Chromium touch emulation. No physical phone or actual screenreader test.','Three studies per game; random instances may admit multiple valid solutions. No claim of exhaustive play-space testing.']};
function save(){fs.writeFileSync(out,JSON.stringify(report,null,2)+'\n');}
(async()=>{save();const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});try{for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});for(const game of games.filter(g=>!process.env.GAME_IDS||process.env.GAME_IDS.split(',').includes(g.id))){const page=await context.newPage(),errors=[],edges=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/puzzle-lab/room.js',async route=>{const response=await route.fetch();let text=await response.text();assert.ok(text.includes('restart();document.body.dataset.gameId'));text=text.replace('restart();document.body.dataset.gameId','window.__readPuzzle=()=>JSON.parse(JSON.stringify(model));restart();document.body.dataset.gameId');await route.fulfill({response,body:text});});const snap=()=>page.evaluate(()=>window.__readPuzzle());const click=async selector=>{if(mobile)await page.locator(selector).tap();else await page.locator(selector).click();};const key=k=>click(`[data-key="${k}"]`);await page.goto(base+'/mini-games/'+game.url);await page.waitForFunction(()=>document.body.dataset.gameReady==='true');await click('#start');await click('#check');assert.notEqual(await page.locator('body').getAttribute('data-outcome'),'win');assert.equal(await page.locator('#result').isHidden(),true,'empty study rejected');edges.push('initial incomplete study rejected');
if(!mobile){const button=page.locator('#board button').first();await button.focus();await page.keyboard.press('Space');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY','keyboard focus survives action');edges.push('keyboard activation retains visible control focus');await click('#reset');}
// Deliberate, game-specific wrong input before the three-study completion.
let m=await snap();switch(game.id){
case 'ice-station':case 'cube-seal':await key('dir-U');assert.deepEqual(await snap(),m);edges.push('blocked move leaves position and orientation unchanged');break;
case 'knight-exchange':{const a=m.cells.findIndex(Boolean),b=range(16).find(i=>!m.cells[i]&&Math.abs(a%4-i%4)*Math.abs(Math.floor(a/4)-Math.floor(i/4))!==2);await key('cell-'+a);await key('cell-'+b);assert.deepEqual((await snap()).cells,m.cells);edges.push('non-knight jump rejected');break;}
case 'circuit-break':await key('node-0');assert.deepEqual(await snap(),m);edges.push('transmitter cannot be disabled');break;
case 'parcel-survey':await key('cell-0');await key('cell-'+(m.n*m.n-1));assert.equal((await snap()).rects.length,0);edges.push('rectangle containing multiple stakes rejected');break;
case 'safety-ferry':await key('sail');assert.deepEqual(await snap(),m);assert.match(await page.locator('#status').innerText(),/Unsafe/);edges.push('unsafe unattended bank crossing refused');break;
case 'rewrite-press':{const i=range(m.ribbon.length).find(i=>m.ribbon.slice(i,i+m.rules[0][0].length)!==m.rules[0][0]);await key('char-'+i);assert.deepEqual(await snap(),m);edges.push('rule applied at nonmatching substring rejected');break;}
case 'map-inks':for(let i=0;i<m.n;i++)await key('node-'+i);await click('#check');assert.match(await page.locator('#status').innerText(),/Border conflict/);edges.push('adjacent identical colors rejected');break;
case 'river-capacity':await key('edge-0');await click('#check');assert.match(await page.locator('#status').innerText(),/Basin/);edges.push('unconserved intermediate flow rejected');break;
case 'hitori-harbor':await key('cell-0');await key('cell-1');await click('#check');assert.match(await page.locator('#status').innerText(),/touch/);edges.push('adjacent shaded cells rejected');break;
case 'island-census':await key('cell-'+m.clues[0][0]);assert.deepEqual(await snap(),m);edges.push('fixed lighthouse remains land');break;
case 'parity-repair':for(let i=0;i<=m.budget;i++)await key('bit-'+i);await click('#check');assert.match(await page.locator('#status').innerText(),/budget/);edges.push('excess repaired bits rejected');break;
case 'arrow-audit':for(let i=0;i<=m.budget;i++)await key('edge-'+i);await click('#check');assert.match(await page.locator('#status').innerText(),/budget/);edges.push('excess reversed arrows rejected');break;
case 'mutual-match':await key('route-0');assert.equal((await snap()).pairs[0],0);await click('#undo');assert.deepEqual((await snap()).pairs,m.pairs);edges.push('pair assignment undo restores unassigned courier');break;
case 'gate-foundry':case 'seed-tomorrow':case 'voxel-post':case 'honest-company':await page.locator('#board button').first()[mobile?'tap':'click']();assert.notDeepEqual(await snap(),m);await click('#undo');assert.deepEqual(await snap(),m);await click('#check');assert.equal(await page.locator('#result').isHidden(),true);edges.push('legal edit undo restores original model and failed check');break;
default:await page.locator('#board button').first()[mobile?'tap':'click']();await click('#check');assert.equal(await page.locator('#result').isHidden(),true);edges.push('partial edited candidate rejected');}
await click('#reset');for(let stage=0;stage<3;stage++){m=await snap();if(game.id==='ice-station'){assert.ok(m.reachableStops>=10+stage*2);assert.ok(m.par>=6+stage*2);if(stage===0)edges.push('every ice study has substantial reachable interior stops and verified minimum route depth');}if(game.id==='twin-steps')assert.ok(m.par>=m.n);if(game.id==='knight-exchange')assert.ok(!same(m.cells,m.goal));if(game.id==='voxel-post')assert.ok(m.target.flat().some(Boolean));const actions=solvers[game.id](m);assert.ok(actions.length,'nonempty solution');for(const k of actions)await key(k);await click('#check');assert.equal(await page.locator('#result').isVisible(),true,game.id+' stage '+stage+' '+await page.locator('#status').innerText());if(stage<2){assert.equal(await page.locator('body').getAttribute('data-outcome'),'study');await click('#next');}}
assert.equal(await page.locator('body').getAttribute('data-outcome'),'win');assert.equal(await page.locator('#study').innerText(),'3 / 3');assert.equal(await page.locator('#check').isDisabled(),true);edges.push('all three studies complete and completed study locked');await click('#restart');assert.equal(await page.locator('#start').isVisible(),true);assert.equal(await page.locator('#moves').innerText(),'0');assert.equal(await page.locator('#checks').innerText(),'0');assert.equal(await page.locator('#result').isHidden(),true);await click('#start');assert.equal(await page.locator('#study').innerText(),'1 / 3');assert.equal(await page.locator('body').getAttribute('data-outcome'),'playing');for(const width of mobile?[320,390]:[1440]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),game.id+' overflow '+width);}assert.deepEqual(errors,[]);report.cases.push({id:game.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',restart:true,studiesCompleted:3,edgeCases:edges,inputMethod:mobile?'Touchscreen taps only; solver-guided legal UI inputs':'Mouse clicks plus ordinary keyboard Space action; solver-guided legal UI inputs',touchOnly:mobile,completionType:'read-only solver probe guided UI',errors});save();console.log('PASS',game.id,mobile?'mobile-touch':'desktop');await page.close();}await context.close();}assert.equal(report.cases.length,games.length*2,'full manifest required before passed');report.passed=true;save();}finally{await browser.close();}})().catch(error=>{report.passed=false;report.failure=String(error.stack||error);save();console.error(error);process.exitCode=1;});
