/* Source-derived author plans; actual native controls, no hidden browser hooks. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),base=process.env.BASE_URL||'http://127.0.0.1:8790',games=JSON.parse(fs.readFileSync(path.join(root,'relation-room/games.json'))),fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'relation-room-paths.json')));
const hash=()=>{const files=['relation-room','journey'].flatMap(d=>fs.readdirSync(path.join(root,d)).filter(f=>fs.statSync(path.join(root,d,f)).isFile()).map(f=>d+'/'+f)).concat(fs.readdirSync(__dirname).filter(f=>f.startsWith('relation-room')).map(f=>'tests/'+f)).sort(),h=crypto.createHash('sha256');for(const f of files)h.update(f+'\0').update(fs.readFileSync(path.join(root,f))).update('\0');return{sha256:h.digest('hex'),files}};
const symbols=['sun','moon','leaf','wave','star','kite'];
const specificNames={
 'minor-museum':'Protected adjacent target anchors cannot contract into one bag',
 'twin-graph':'Occupied isomorphism destinations swap assignments without duplicate ownership',
 'interval-museum':'Native endpoint bounds and reversed-endpoint audit are enforced',
 'knowledge-circle':'Each successful announcement removes public worlds and rebuilds current groups',
 'modal-witness':'Reverse accessibility arrow cannot witness a root Diamond premise',
 'polygon-passport':'Side gluing merges endpoint classes and removing the gluing restores them',
 'hairpin-studio':'Adjacent positions fail the actual minimum-loop-gap rule',
 'letter-carries':'A complete digit assignment with a leading zero fails certification',
 'fill-in-station':'A destructive high-degree elimination loses under the induced-width cap',
 'alternating-couriers':'A matched right endpoint forces its partner as the next alternating step',
 'recursive-rings':'Detaching ring1 unlocks ring3 only while its preceding ring2 remains attached',
 'ordered-echo':'Recall collects visible pulses before hiding; a wrong next symbol ends the attempt',
 'heritage-house':'A complete family assignment with a wrong visible trait fails certification',
 'posterior-post':'Purchased probe is charged once and remains disabled; positive likelihood classes remain represented',
 'heap-foundry':'Selecting a leaf does not exchange values; only explicit parent-child swaps mutate the heap',
 'diagram-order':'An independently chosen over-budget reduced variable order fails its full-node audit',
 'turning-council':'Placement waits for rotation; a nonwinning full turn elicits one legal complete house reply',
 'witness-table':'All printed universal branches are checked with the permitted earlier/later witness contexts',
 'one-lie-archive':'The same property can be asked repeatedly; transcript disagreements update globally',
 'invariant-gallery':'A region containing initials and excluding forbidden states still fails on an admitted unreachable transition'
};
(async()=>{
 const model=await import(path.join(__dirname,'relation-room-plans.mjs')),before=hash(),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']}),report={passed:false,startedAt:new Date().toISOString(),sourceHash:before.sha256,sourceFiles:before.files,scope:fixture.scope,method:'Source-derived independent legal plans drive rendered native buttons. Recall captures public cues before hiding; sealed Posterior observations are used by test-only author planning. No writable browser state hooks or hidden browser-state access.',limits:['Author legal-witness plans drive native controls; this does not establish unaided player difficulty or ordinary source-blind completion.','Browser completion covers all three finite studies and the first two optional studies; stages7/100/100000 at six dispersed replay seeds use independent pure-model legal witnesses, not late-stage browser completion.','Chromium desktop and320px emulated touchscreen profiles; no physical-device, cross-browser or screen-reader claim.','Posterior test planning reads sealed source outcomes; Echo pure models use source sequences while browser play collects only rendered pulses before hiding. No hidden browser-state inspection or writable browser hooks.'],cases:[]};
 const save=()=>fs.writeFileSync(path.join(root,'coverage/relation-room.json'),JSON.stringify(report,null,2)+'\n');
 try{
 for(const mobile of [false,true]){
  const context=await browser.newContext({viewport:mobile?{width:320,height:800}:{width:1280,height:900},hasTouch:mobile,isMobile:mobile}),page=await context.newPage();context.setDefaultTimeout(8000);let errors=[];page.on('pageerror',e=>errors.push(e.message));
  const activate=async(selector,keyboard=false)=>{const control=page.locator(selector).first();assert(await control.isEnabled(),'Enabled native control: '+selector);if(mobile)await control.tap();else if(keyboard){await control.focus();await page.keyboard.press('Space');assert(await page.evaluate(()=>document.activeElement!==document.body),'Focus survived native Space');}else await control.click();};
  const outcome=()=>page.locator('body').getAttribute('data-outcome'),stage=()=>page.locator('body').getAttribute('data-stage');
  const layout=async()=>{assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'No horizontal page overflow');};
  const actions=async(pathActions)=>{for(const a of pathActions){await activate('[data-action="'+a+'"]');assert((await page.locator('#status').innerText()).trim(),'Actionable status');}};
  const recall=async(wrong=false)=>{const pulses=[];while(await page.locator('[data-action="next-pulse"]').count()){const cue=(await page.locator('#board p').allTextContents()).find(v=>v.startsWith('Visible pulse: '));assert(cue);pulses.push(symbols.indexOf(cue.slice('Visible pulse: '.length)));assert(pulses.at(-1)>=0);await activate('[data-action="next-pulse"]');assert(await page.locator('#undo').isDisabled(),'Recall cannot rewind covered pulses');}assert(!(await page.locator('#board').innerText()).includes('Visible pulse:'),'Covered cues removed from rendered state');if(wrong){await activate('[data-action="symbol:'+((pulses[0]+1)%model.initial('ordered-echo',Number(await stage()),fixture.runSeed,await page.locator('#mode').inputValue()).alphabet)+'"]');return pulses;}for(const v of pulses)await activate('[data-action="symbol:'+v+'"]');return pulses;};
  for(const g of games){
   errors=[];const record=fixture.records.find(v=>v.id===g.id),item={id:g.id,profile:mobile?'mobile-touch':'desktop',passed:false,outcome:null,restart:false,touchOnly:mobile,inputMethod:mobile?'Actual touchscreen taps for every engine and shell gameplay action; native mode selectOption used only for mode navigation':'Native mouse clicks plus actual keyboard Space activation of opening control; native mode selectOption navigation',edgeCases:[],winActions:[],lossActions:[],finiteStudiesCompleted:0,endlessStudiesCompleted:0,optionalMode:{supported:g.endless.supported},errors};report.cases.push(item);
   await page.goto(base+'/mini-games/'+g.url+'&seed='+fixture.runSeed);await page.waitForSelector('body[data-game-ready=true]');assert.equal(await page.locator('body').getAttribute('data-game-id'),g.id);await activate('#start');assert.equal(await outcome(),'playing');await layout();
   const openingBefore=await page.locator('#board').innerHTML();await activate(g.smoke.actionSelector,!mobile);assert.notEqual(await page.locator('#board').innerHTML(),openingBefore,'Opening changes actual rendered field');await activate('#reset');
   // Rule-specific ordinary control checks, followed by recovery.
   const s=model.initial(g.id,0);
   if(g.id==='minor-museum'){const [a,b]=s.edges.find(([a,b])=>a<s.targetN&&b<s.targetN);await actions(['node:'+a,'node:'+b,'contract']);assert.match(await page.locator('#status').innerText(),/protected/);}
   else if(g.id==='twin-graph'){await actions(['left:0','right:0','left:1','right:0']);assert.match(await page.locator('[data-action="left:0"]').innerText(),/\?/);assert.match(await page.locator('[data-action="left:1"]').innerText(),/A/);}
   else if(g.id==='interval-museum'){assert(await page.locator('[data-action="endpoint:0:-1"]').isDisabled());if(!mobile){await page.locator('[data-action="left"]').press('End');assert.equal(await page.locator('[data-action="left"]').inputValue(),String(s.limit));await actions(['check']);assert.match(await page.locator('#status').innerText(),/ordered endpoints/);}else{await actions(Array.from({length:s.limit},()=> 'endpoint:0:1'));await actions(['check']);assert.match(await page.locator('#status').innerText(),/ordered endpoints/);}}
   else if(g.id==='modal-witness'){await actions(['from:1','to:0','arrow','value:1:P','check']);assert.match(await page.locator('#status').innerText(),/Premise 1 is false/);}
   else if(g.id==='polygon-passport'){const before=await page.locator('#board').innerText();await actions(['side:0','side:2','pair']);const after=await page.locator('#board').innerText();assert.notEqual(before,after);await actions(['unpair']);assert((await page.locator('#board').innerText()).includes('{1} {2} {3} {4}'));}
   else if(g.id==='hairpin-studio'){await actions(['site:0','site:1','bond']);assert.match(await page.locator('#status').innerText(),/unpaired.*inside a bond/);}
   else if(g.id==='alternating-couriers'){const free=Array.from({length:s.n},(_,i)=>i).find(i=>!s.match.some(([a])=>a===i)),recipient=s.match.find(([a,b])=>s.edges.some(([x,y])=>x===free&&y===s.n+b));assert(recipient);await actions(['walk:'+free,'walk:'+(s.n+recipient[1])]);assert(await page.locator('[data-action="walk:'+recipient[0]+'"]').isEnabled());assert.equal(await page.locator('[data-action^="walk:"]:not(:disabled)').count(),1);}
   else if(g.id==='recursive-rings'){assert(await page.locator('[data-action="ring:2"]').isDisabled());await actions(['ring:0']);assert(await page.locator('[data-action="ring:2"]').isEnabled());}
   else if(g.id==='posterior-post'){await actions(['probe:0']);assert(await page.locator('#undo').isDisabled(),'Paid evidence cannot be rewound');assert(await page.locator('[data-action="probe:0"]').isDisabled());const rows=await page.locator('#board table').first().locator('tbody tr td:last-child').allTextContents();assert(rows.length===3&&rows.every(v=>Number(v)>0));}
   else if(g.id==='heap-foundry'){const before=await page.locator('#board table').innerText();await actions(['slot:'+(s.heap.length-1)]);assert.equal(await page.locator('#board table').innerText(),before);assert.equal(await page.locator('[data-action^="swap:"]').count(),1);}
   else if(g.id==='turning-council'){const e=(await import(path.join(root,'relation-room/council.mjs'))).councilEngines[g.id];let pathReply;for(let i=0;i<36&&!pathReply;i++)if(!s.board[i])for(let q=0;q<4&&!pathReply;q++)for(const d of [-1,1]){const t=structuredClone(s);e.act(t,'place:'+i);e.act(t,`rotate:${q}:${d}`);if(t.outcome==='playing'){pathReply=['place:'+i,`rotate:${q}:${d}`];break;}}assert(pathReply);await actions([pathReply[0]]);assert.equal(await outcome(),'playing');assert(await page.locator('[data-action^="place:"]').first().isDisabled());await actions([pathReply[1]]);assert.match(await page.locator('#status').innerText(),/House placed/);const text=await page.locator('[data-action^="place:"]').allTextContents();assert.equal(text.filter(v=>v==='●').length,5);assert.equal(text.filter(v=>v==='○').length,5);}
   else if(g.id==='one-lie-archive'){await actions(['ask:0']);assert(await page.locator('[data-action="ask:0"]').isEnabled());await actions(['ask:0']);assert.equal(await page.locator('#board table').last().locator('tr').count(),3);}
   await activate('#reset');
   for(let chapter=0;chapter<3;chapter++){
    assert.equal(await stage(),String(chapter));
    if(chapter===record.lossStage){if(g.id==='ordered-echo')await recall(true);else await actions(record.loss);assert.equal(await outcome(),'loss',g.id+' explained natural failure');assert((await page.locator('#status').innerText()).length>30);if(g.id==='letter-carries')assert.match(await page.locator('#status').innerText(),/leading/);if(g.id==='heritage-house')assert.match(await page.locator('#status').innerText(),/visible trait/);if(g.id==='invariant-gallery')assert.match(await page.locator('#status').innerText(),/unreachable/);item.lossActions.push({mode:'finite',stage:chapter,actions:g.id==='ordered-echo'?'visible cues then deliberately wrong first recall':record.loss});await activate('#reset');assert.equal(await outcome(),'playing');}
    const before=await page.locator('#board').innerText();if(g.id==='ordered-echo'){const pulses=await recall(false);item.winActions.push({mode:'finite',stage:chapter,observedPulses:pulses,inputScope:'Visible pulse read before each hide; recalled only after all cues covered'});}else{await actions(record.finite[chapter]);item.winActions.push({mode:'finite',stage:chapter,actions:record.finite[chapter]});}
    assert.equal(await outcome(),chapter===2?'win':'study-win',g.id+' chapter'+chapter);assert.equal(await page.locator('#board button:not(:disabled)').count(),0,'Terminal game controls locked');item.finiteStudiesCompleted++;await layout();
    if(g.id==='knowledge-circle')assert.notEqual(await page.locator('#board').innerText(),before,'Actual announcements changed worlds/groups');
    if(chapter<2)await activate('#next');
   }
   item.outcome='win';item.edgeCases.push(specificNames[g.id],'All three finite studies completed through native controls','Explained natural failure, Reset recovery and correct replay completed','Terminal engine controls are disabled');
   await activate('#restart');assert.equal(await outcome(),'playing');assert.equal(await stage(),'0');assert.equal(await page.locator('#score').innerText(),'0');item.restart=true;
   if(g.endless.supported){
    await page.locator('#mode').selectOption('endless');await activate('#start');const fields=[];let accumulated=0;
    for(let chapter=0;chapter<2;chapter++){assert.equal(await stage(),String(chapter));fields.push(await page.locator('#board').innerText());if(g.id==='ordered-echo'){const pulses=await recall(false);item.winActions.push({mode:'endless',stage:chapter,observedPulses:pulses});}else{await actions(record.optional[chapter]);item.winActions.push({mode:'endless',stage:chapter,actions:record.optional[chapter]});}assert.equal(await outcome(),'study-win');const score=Number(await page.locator('#score').innerText());assert(score>accumulated);accumulated=score;item.endlessStudiesCompleted++;await activate('#next');assert.equal(Number(await page.locator('#score').innerText()),accumulated);}
    assert.notEqual(fields[0],fields[1],'Fresh generated challenge content');assert(await page.locator('#reset').isDisabled());assert(await page.locator('#undo').isDisabled());await activate('#end-run');assert.equal(await outcome(),'win');assert.equal(Number(await page.locator('#score').innerText()),accumulated);assert.match(await page.locator('#status').innerText(),/banked/);await activate('#restart');assert.equal(await outcome(),'playing');assert.equal(await page.locator('#score').innerText(),'0');
    // A separate optional natural failure and actual restart; tactical loss uses
    // a later seeded duel, reached by two full native winning turns.
    if(g.id==='turning-council'){for(let chapter=0;chapter<2;chapter++){await actions(record.optional[chapter]);await activate('#next');}const t=model.initial(g.id,2,fixture.runSeed,'endless');let loss;try{loss=model.lossPlan(g.id,t);}catch{loss=null}if(loss){await actions(loss);assert.equal(await outcome(),'loss');item.lossActions.push({mode:'endless',stage:2,actions:loss});await activate('#restart');}else item.edgeCases.push('Optional terminal recovery observed through Bank; natural tactical loss executed in finite study3 only');}
    else{if(g.id==='ordered-echo')await recall(true);else await actions(model.lossPlan(g.id,model.initial(g.id,0,fixture.runSeed,'endless')));assert.equal(await outcome(),'loss');await activate('#restart');assert.equal(await outcome(),'playing');}
    item.optionalMode={supported:true,kind:g.endless.kind||'challenge-stream',completedChallenges:2,sourceSeed:fixture.runSeed,freshChallenges:true,scoreAccumulated:true,terminalRecovery:true,playerEndRun:true,lateStageProperties:fixture.lateModelEvidence.filter(v=>v.id===g.id).length===18,lateStageScope:'Pure model independent legal-witness completion at stages7/100/100000 across six dispersed public run seeds; actual browser finite0–2 and optional0–1, plus separately disclosed failure scope.'};item.edgeCases.push('Two fresh optional studies completed and accumulated score banked','Optional Reset/Undo disabled; Bank/restart cannot mint score');
   }else{assert(await page.locator('#endless-option').evaluate(el=>el.disabled));item.optionalMode={supported:false};item.edgeCases.push('Unsupported procedural mode disabled with accurate finite-only explanation');}
   await layout();assert.deepEqual(errors,[]);item.errors=[...errors];item.passed=true;save();console.log(JSON.stringify({id:g.id,profile:item.profile,finite:3,optional:item.endlessStudiesCompleted,passed:true}));
  }
  await context.close();
 }
 const after=hash();report.sourceUnchanged=before.sha256===after.sha256;report.sourceHashAfter=after.sha256;report.finishedAt=new Date().toISOString();assert(report.sourceUnchanged,'Runtime/test source changed during the browser run');assert.equal(report.cases.length,40);report.passed=true;save();console.log(JSON.stringify({passed:true,cases:40,finiteStudies:120,optionalStudies:68,sourceHash:before.sha256}));
 }catch(error){report.error=String(error.stack||error);report.finishedAt=new Date().toISOString();report.sourceHashAfter=hash().sha256;report.sourceUnchanged=report.sourceHash===report.sourceHashAfter;save();throw error;}finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1});
