/* Source-informed reachability and rule regression evidence, not unaided solving.
   All gameplay actions are real native keyboard controls or touchscreen taps.
   The native selectOption API is used only to configure endless-mode setup. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const{chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),BASE=process.env.BASE_URL||'http://127.0.0.1:8790',RUN_SEED=1337;
const reportPath=path.join(ROOT,'coverage/signal-lab.json'),fixturePath=path.join(__dirname,'signal-lab-paths.json');
const report={passed:false,cases:[],generationProperties:[],limits:['Source-informed test plans use hidden model data where applicable; this is reachability and regression evidence, not unaided solving.','Chromium keyboard and emulated touchscreen inputs, not physical-device or screen-reader certification.','Mode setup uses native selectOption; every mobile gameplay action, failure and recovery uses touchscreen taps, including real native slider tracks.']};
function save(){fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n')}
function sourceFiles(){return['signal-lab','journey'].flatMap(dir=>fs.readdirSync(path.join(ROOT,dir)).sort().filter(n=>!n.endsWith('.md')).map(n=>dir+'/'+n)).concat(['tests/signal-lab.cjs','tests/signal-lab-plans.mjs','tests/signal-lab-regressions.mjs','tests/signal-lab-paths.json'])}
function hash(files){const h=crypto.createHash('sha256');for(const f of files)h.update(f+'\0').update(fs.readFileSync(path.join(ROOT,f)));return h.digest('hex')}
(async()=>{save();const{engines}=await import('../signal-lab/engines.mjs'),{winPlan,lossPlan,replay,stageSeed,rendered}=await import('./signal-lab-plans.mjs'),{regressions}=await import('./signal-lab-regressions.mjs'),games=JSON.parse(fs.readFileSync(path.join(ROOT,'signal-lab/games.json')));assert.equal(games.length,20);assert.equal(Object.keys(engines).length,20);assert.equal(new Set(games.map(g=>g.id)).size,20);
 report.ruleRegressionAssertions=regressions();
 const fixture={runSeed:RUN_SEED,scope:report.limits[0],games:{}};
 for(const g of games){const win=[],loss=[];for(let stage=0;stage<3;stage++){const s=engines[g.id].init({stage,seed:stageSeed(RUN_SEED,stage),mode:'finite'}),p=winPlan(g.id,s),f=lossPlan(g.id,s);assert.equal(replay(g.id,s,p).outcome,'win',g.id+' finite model'+stage);assert.equal(replay(g.id,s,f).outcome,'loss',g.id+' model failure'+stage);win.push(p);loss.push(f)}fixture.games[g.id]={win,loss};}
 fs.writeFileSync(fixturePath,JSON.stringify(fixture,null,2)+'\n');
 for(const g of games.filter(g=>g.endless.supported)){const fingerprints=new Set();for(const stage of[0,1,2,3,17,250])for(const seed of[7,51,1337,91273]){const s=engines[g.id].init({stage,seed:stageSeed(seed,stage),mode:'endless'});assert.ok(JSON.stringify(s).length<30000);const p=winPlan(g.id,s),n=replay(g.id,s,p);assert.equal(n.outcome,'win',g.id+' generated challenge '+stage+'/'+seed);assert.ok(Number.isFinite(n.score)&&n.score>0);fingerprints.add(JSON.stringify(s));}assert.ok(fingerprints.size>=12,g.id+' generated diversity');report.generationProperties.push({id:g.id,passed:true,samples:24,stages:[0,1,2,3,17,250],scope:'Pure-model source-informed legal routes, bounded serializable state and positive terminal score; not browser evidence for all24samples.'});}
 const files=sourceFiles(),testedHash=hash(files);report.sourceFiles=files;
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
 try{for(const mobile of[false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:'reduce'}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const activate=async selector=>{const b=page.locator(selector).first();await b.scrollIntoViewIfNeeded();if(mobile)await b.tap();else{await b.focus();await b.press('Enter')}};
 const action=async k=>{if(!k.includes(':'))return activate(`[data-action="${k}"]`);const[key,v]=k.split(':'),desired=+v,loc=page.locator(`input[data-action="${key}"]`);await loc.scrollIntoViewIfNeeded();const opts=await loc.evaluate(el=>({min:+el.min,max:+el.max,value:+el.value}));if(mobile){for(let attempt=0;attempt<4;attempt++){const b=await loc.boundingBox(),fraction=(desired-opts.min)/(opts.max-opts.min),x=b.x+8+(b.width-16)*fraction+(attempt===0?0:attempt===1?1:attempt===2?-1:2);await page.touchscreen.tap(x,b.y+b.height/2);if(+(await loc.inputValue())===desired)break}assert.equal(+(await loc.inputValue()),desired,'native touch range '+k)}else{await loc.focus();await loc.press('Home');for(let n=opts.min;n<desired;n++)await loc.press('ArrowRight')}assert.equal(+(await loc.inputValue()),desired,'range target '+k);};
 const outcome=()=>page.locator('body').getAttribute('data-outcome'),board=()=>page.locator('#board').innerText();
 const bounds=async()=>{assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'document fits');if(mobile){await page.setViewportSize({width:320,height:720});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),'320px document fits');await page.setViewportSize({width:390,height:844})}};
 for(const g of games){console.log((mobile?'touch ':'keyboard ')+g.id);await page.goto(BASE+'/mini-games/'+g.url+'&seed='+RUN_SEED);await page.waitForSelector('body[data-game-ready="true"]');assert.equal(await page.locator('body').getAttribute('data-game-id'),g.id);assert.equal(await page.locator('#title').innerText(),g.name);assert.ok((await page.locator('#rules').innerText()).length>150);await activate('#start');const opening=await board();assert.equal(await outcome(),'playing');assert.ok((await page.locator('#seed-note').innerText()).includes(String(RUN_SEED)));
 await activate(g.smoke.actionSelector);if(await page.locator('#undo').isEnabled()){await activate('#undo');assert.equal(await board(),opening,'Undo restores full opening')};await activate('#reset');assert.equal(await board(),opening,'Reset restores initial challenge');await bounds();
 for(const k of fixture.games[g.id].loss[0])await action(k);assert.equal(await outcome(),'loss',g.id+' natural UI failure');assert.equal(await page.locator('#board button:not(:disabled),#board input:not(:disabled)').count(),0,'terminal controls disabled');await activate('#restart');assert.equal(await board(),opening,'Restart restores replay-seeded opening');
 let winActions=0;for(let stage=0;stage<3;stage++){assert.equal(+(await page.locator('body').getAttribute('data-stage')),stage);const fresh=await board();await activate('#reset');assert.equal(await board(),fresh,'Reset preserves campaign chapter');for(const k of fixture.games[g.id].win[stage]){await action(k);winActions++}assert.equal(await outcome(),stage===2?'win':'study-win',g.id+' UI chapter '+stage);assert.ok(await page.locator('#result').isVisible());assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');assert.equal(await page.locator('#board button:not(:disabled),#board input:not(:disabled)').count(),0);await bounds();if(stage<2)await activate('#next')};assert.ok(+(await page.locator('#score').innerText())>0);assert.ok(+(await page.locator('#best').innerText())>0);await activate('#again');assert.equal(await board(),opening);assert.equal(+(await page.locator('#score').innerText()),0);
 const optionalMode={supported:g.endless.supported};if(g.endless.supported){await page.locator('#mode').selectOption('endless');await activate('#start');assert.equal(await page.locator('body').getAttribute('data-mode'),'endless');assert.equal(await page.locator('#undo').isEnabled(),false);assert.equal(await page.locator('#reset').isEnabled(),false);const firstField=await board();for(const k of fixture.games[g.id].win[0])await action(k);const score1=+(await page.locator('#score').innerText());assert.equal(await outcome(),'study-win');await activate('#next');assert.notEqual(await board(),firstField,'second generated field differs');for(const k of fixture.games[g.id].win[1])await action(k);const score2=+(await page.locator('#score').innerText());assert.ok(score2>score1,'endless score accumulates');assert.equal(await outcome(),'study-win');await activate('#next');for(const k of fixture.games[g.id].loss[2])await action(k);assert.equal(await outcome(),'loss','endless terminal failure');assert.equal(+(await page.locator('#score').innerText()),score2,'loss retains banked score');await activate('#restart');assert.equal(await outcome(),'playing');assert.equal(+(await page.locator('#score').innerText()),0);await activate('#end-run');assert.equal(await outcome(),'win');await activate('#again');assert.equal(await outcome(),'playing');Object.assign(optionalMode,{kind:'challenge-stream',completedChallenges:2,freshChallenges:true,scoreAccumulated:true,terminalRecovery:true,playerEndRun:true,lateStageProperties:true,lateStageScope:'24pure-model generation samples including stages17and250; browser coverage plays first2generated challenges then real failure/restart.'});}else{assert.equal(await page.locator('#endless-option').evaluate(el=>el.disabled),true)}
 await bounds();assert.deepEqual(errors,[]);report.cases.push({id:g.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',finiteStudiesCompleted:3,restart:true,touchOnly:mobile,inputMethod:mobile?'Touchscreen taps on actual native buttons and slider tracks; source-informed routes through every campaign study. Mode setup uses native selectOption.':'Keyboard focus and Enter on native buttons; Home/ArrowRight on native sliders; source-informed routes through every campaign study.',winActions,lossActions:fixture.games[g.id].loss[0].length,edgeCases:['All3finite studies completed via real controls','Natural loss/restart and terminal controls disabled','Finite Undo/Reset restore rendered state and preserve chapter','Positive score/personal best and clean Play again','No page errors; document bounds at desktop/390px/320px','Mechanic-specific pure regressions separately cover all20ids'],optionalMode});save();}
 await context.close();}assert.equal(hash(files),testedHash,'Source changed during evidence run; rerun required');report.sourceHash=testedHash;report.passed=report.cases.length===40;save();}finally{await browser.close()}
})().catch(e=>{report.passed=false;report.error=e.stack;save();console.error(e);process.exitCode=1});
