const {chromium}=require('playwright');const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const errors=[];for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.clock.install({time:new Date("2026-01-01T00:00:00Z")});await page.clock.pauseAt(new Date("2026-01-01T00:00:01Z"));await page.goto((process.env.BASE_URL||'http://127.0.0.1:8790')+'/mini-games/sky-stack/');await page.locator('#action').click();
const pos=()=>page.evaluate(()=>{let m=document.querySelector('#moving rect'),all=document.querySelectorAll('#tower g');return {x:+m.getAttribute('x'),top:+all[all.length-1].firstChild.getAttribute('x')}});
// Play all twelve floors using only rendered positions and actual button input.
for(let floor=0;floor<12;floor++){let aligned=false;for(let i=0;i<400;i++){const p=await pos();if(Math.abs(p.x-p.top)<3){aligned=true;break;}await page.clock.runFor(16);}assert(aligned);await page.locator('#action')[mobile?'tap':'click']();assert.equal(await page.locator('#floors').textContent(),`${floor+1} / 12`);}
assert.match(await page.locator('#result-title').textContent(),/landmark/);assert.equal(await page.locator('#score').textContent(),'1800');assert.equal(await page.locator('#best').textContent(),'1,800');await page.screenshot({path:`/tmp/sky-stack-win-${mobile?'mobile':'desktop'}.png`,fullPage:true});await page.locator('#again').click();await page.clock.runFor(320);await page.keyboard.press('p');const before=await pos();await page.clock.runFor(10000);assert.deepEqual(await pos(),before);await page.keyboard.press('p');await page.clock.runFor(160);assert.notDeepEqual(await pos(),before);
await page.evaluate(()=>window.dispatchEvent(new Event('blur')));assert.equal(await page.locator('#pause').textContent(),'Resume');const background=await pos();await page.clock.runFor(60000);assert.deepEqual(await pos(),background);await page.locator('#pause').click();
// Reset, make a narrow first floor, then miss it completely.
await page.locator('#restart').click();await page.locator('#action').click();await page.locator('#action').click();assert.equal(await page.locator('#floors').textContent(),'1 / 12');await page.locator('#action').click();assert.match(await page.locator('#result-title').textContent(),/near-miss/);for(let i=0;i<4;i++){await page.locator('#restart').click();assert.equal(await page.locator('#floors').textContent(),'0 / 12');await page.locator('#action').click();await page.clock.runFor(80);}
await page.locator('#restart').click();await page.locator('#action').focus();await page.keyboard.press('Space');assert.equal(await page.locator('#action').textContent(),'Drop floor ↓');await page.clock.runFor(32);await page.keyboard.press('Escape');assert.equal(await page.locator('#pause').textContent(),'Resume');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:`/tmp/sky-stack-${mobile?'mobile':'desktop'}.png`,fullPage:true});await page.locator('.back').click();assert.match(page.url(),/mini-games\/$/);await context.close();}
for(const mode of ['read','write']){const context=await browser.newContext();await context.addInitScript(mode=>{Storage.prototype.setItem=function(){throw new Error('quota')};if(mode==='read')Storage.prototype.getItem=function(){throw new Error('blocked')}},mode);const p=await context.newPage();await p.goto((process.env.BASE_URL||'http://127.0.0.1:8790')+'/mini-games/sky-stack/');await p.locator('#action').click();await p.locator('#action').click();await p.locator('#action').click();assert.match(await p.locator('#storage-note').textContent(),/unavailable/);assert.notEqual(await p.locator('#best').textContent(),'—');await context.close();}assert.deepEqual(errors,[]);await browser.close();console.log('Sky Stack: desktop/mobile twelve-floor wins, losses, restart, pause, blur, keyboard, reduced motion, navigation, storage failure passed.');})().catch(e=>{console.error(e);process.exit(1)});
