const {chromium}=require('playwright');const fs=require('fs');const path=require('path');
const games=require('../spatial-room/games.json');
function crateSolve(){let start=[['A','B','A'],['B','A','B'],[]],q=[[start,[]]],seen=new Set;while(q.length){let [s,p]=q.shift(),k=JSON.stringify(s);if(seen.has(k))continue;seen.add(k);if(s[0].join('')==='AAA'&&s[1].join('')==='BBB')return p;for(let a=0;a<3;a++)for(let b=0;b<3;b++)if(a!==b&&s[a].length&&s[b].length<3){let n=s.map(x=>x.slice());n[b].push(n[a].pop());q.push([n,[...p,'stack:'+a,'stack:'+b]]);}}}
const solutions={
 'tangram-dock':['piece:0','place:0','piece:1','place:2','piece:2','place:5'],
 'mirror-mail':['mirror:0','mirror:2','mirror:3','mirror:4','beam'],
 'bilateral':[5,7,13,14,22,23,29,30].map(i=>'mark:'+i),
 'shadow-turn':[[1,3,2,1],[3,2,1,2],[2,1,3,3]].flatMap(a=>a.flatMap((n,i)=>Array(n).fill('turn:'+i))),
 'loose-ends':['node:1','node:3','node:2','node:3','node:3','node:5','node:4','node:5'],
 'gear-train':['gear:1','gear:2'],
 'measured-pour':['fill:1','pour:1','empty:0','pour:1','fill:1','pour:1'],
 'rover-script':('R F F L F F R R F F L F F L F F F F').split(' ').map(c=>'command:'+c).concat('run'),
 'paper-trail':['fold:L','fold:R','fold:R'],
 'pigment-lab':[[2,3,1],[3,1,2],[1,2,4]].flatMap(a=>a.flatMap((n,i)=>Array(n).fill('drop:'+i+':1'))),
 'cable-loom':[1,2,3,7,6,5,4,8,9,10,11,15,14,13,12].map(i=>'peg:'+i),
 'balance-mobile':['weight:3','hook:0','weight:1','hook:1','weight:4','hook:2','weight:2','hook:3'],
 'crate-crane':crateSolve(),
 'orbit-transfer':[1,3,2,4,5].map(i=>'travel:'+i),
 'stamp-studio':['stamp:0','stamp:3','stamp:1','stamp:2','stamp:2','stamp:4']};
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox']});const result=[];for(const mobile of [false,true]){const context=await browser.newContext({viewport:mobile?{width:320,height:740}:{width:1200,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});if(mobile)await context.addInitScript(()=>{Storage.prototype.getItem=()=>{throw Error('denied')};Storage.prototype.setItem=()=>{throw Error('denied')}});const page=await context.newPage();let errors=[];page.on('pageerror',e=>errors.push(e.message));for(const g of games){await page.goto((process.env.BASE_URL||'http://127.0.0.1:8790')+'/mini-games/'+g.url);await page.waitForSelector('body[data-game-ready=true]');const click=async a=>{const el=page.locator('[data-action="'+a+'"]');if(mobile)await el.tap();else await el.click();};if(g.id==='tangram-dock')await click('place:3');if(g.id==='cable-loom')await click('peg:15');if(g.id==='measured-pour')await click('pour:0');await page.locator('#restart').click();for(const a of solutions[g.id]){if(await page.locator('#result').isVisible())break;await click(a);}if(!await page.locator('#result').isVisible())throw Error(g.id+' did not complete: '+await page.locator('#message').textContent());if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error(g.id+' overflow');await page.locator('#again').click();if(await page.locator('#result').isVisible())throw Error('restart failed');await page.locator('#restart').click();await page.locator('#restart').click();if(await page.locator('#moves').textContent()!=='0')throw Error('moves not reset');const first=page.locator('#board button').first();await first.focus();await page.keyboard.press('Enter');if(errors.length)throw Error(errors.join('\n'));result.push({id:g.id,mobile,completed:true,restart:true,keyboard:true,overflow:false,storageBlocked:mobile,reducedMotion:mobile});console.log(g.id,mobile?'mobile':'desktop','passed');}await context.close();}await browser.close();fs.mkdirSync(path.join(__dirname,'../coverage'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../coverage/spatial-room.json'),JSON.stringify({passed:true,browser:'Chromium',notes:'All completions through legal click/tap inputs. Mobile320 reduced motion + blocked storage. Fixed crafted puzzles, no timing. Physical devices and screen readers untested.',checks:result},null,2));})().catch(e=>{console.error(e);process.exit(1)});
