/* Source-derived legal plans are replayed through real controls. No browser state injection.
   These are solver/probe reachability checks, not claims of unguided usability. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {chromium}=require('playwright');
const ROOT=path.resolve(__dirname,'..'),BASE=process.env.BASE_URL||'http://127.0.0.1:8790';
const evidencePath=path.join(ROOT,'coverage/systems-room.json');
const evidence={passed:false,cases:[],limits:['Winning plans were found by source-derived legal-state search, then replayed using real keyboard/touch UI controls. This does not establish unaided learnability or deep polish.','Mobile viewport and touch events are Chromium emulation, not a physical phone or screenreader test.','WebKit is covered separately by the repository expansion-controls CI suite; this file tests Chromium full rounds.']};
function save(){fs.writeFileSync(evidencePath,JSON.stringify(evidence,null,2)+'\n');}
function hash(){const files=fs.readdirSync(path.join(ROOT,'systems-room')).sort().map(f=>'systems-room/'+f).concat(['tests/systems-room.cjs','tests/systems-paths.json']);const h=crypto.createHash('sha256');for(const f of files)h.update(f+'\0').update(fs.readFileSync(path.join(ROOT,f)));return h.digest('hex');}
const failureChoice=(id,s,legal)=>({'junction-nine':'p0','assembly-belt':'gap','marsh-balance':'habitat','reorder-point':'o0','workshop-shift':'end','signal-cabinet':'wait','cold-chain':'wait',reservoir:'r0','power-desk':'0-reserve','carry-on':'pass','quiet-majority':'vote','safe-return':'decline',firebreak:'end','kiln-house':'h0','two-couriers':s.pos?.[0]===0?'0-1':'0-0','elevator-night':'doors','supply-web':'run','growing-block':'wait','borrowed-time':'day','convoy-ledger':'sail'}[id]||legal[0]);
(async()=>{
 save();const testedHash=hash();const{start,legal,step,view}=await import('../systems-room/engines.mjs');const games=JSON.parse(fs.readFileSync(path.join(ROOT,'systems-room/games.json'))),plans=JSON.parse(fs.readFileSync(path.join(__dirname,'systems-paths.json')));
 assert.equal(games.length,20);assert.equal(new Set(games.map(g=>g.id)).size,20);const failures={};
 for(const g of games){let s=start(g.id),snapshot=JSON.stringify(s);assert.equal(step(g.id,s,'invalid'),s);assert.equal(JSON.stringify(s),snapshot);for(const a of plans[g.id]){assert.ok(legal(g.id,s).includes(a),g.id+' legal win action '+a);const old=JSON.stringify(s),previous=s;s=step(g.id,s,a);assert.equal(JSON.stringify(previous),old,'Transition leaves original state untouched');}assert.ok(s.done&&s.won,g.id+' win plan must succeed');assert.equal(step(g.id,s,plans[g.id][0]),s);assert.deepEqual(legal(g.id,s),[]);s=start(g.id);let loss=[];while(!s.done&&loss.length<100){let a=failureChoice(g.id,s,legal(g.id,s));assert.ok(legal(g.id,s).includes(a));s=step(g.id,s,a);loss.push(a);}assert.ok(s.done&&!s.won,g.id+' deliberate failure must fail');failures[g.id]=loss;}
 // Concrete mechanical invariants supplement UI terminal checks.
 let s=start('assembly-belt');for(let i=0;i<17;i++)s=step('assembly-belt',s,'gap');assert.equal(s.energy,0);assert.equal(s.oven,false);assert.ok(!legal('assembly-belt',s).includes('oven'),'An exhausted oven cannot be heated');
 s=step('signal-cabinet',start('signal-cabinet'),'B');assert.equal(s.jobs[1].left,2,'Changing tool consumes setup only');assert.equal(s.tool,'wire');
 s=step('kiln-house',start('kiln-house'),'h3');assert.equal(s.core,20,'Core follows old gap, not newly heated shell');assert.equal(s.shell,50);
 s=step('reorder-point',start('reorder-point'),'o6');assert.deepEqual(s.pipe,[0,6]);
 s=step('two-couriers',start('two-couriers'),'0-1');s=step('two-couriers',s,'0-2');s=step('two-couriers',s,'1-3');assert.ok(!legal('two-couriers',s).includes('0-3'),'Occupied road stop cannot be entered');
 s=step('workshop-shift',start('workshop-shift'),'wood');assert.ok(!legal('workshop-shift',s).includes('wood'),'Occupied station unavailable until shift reset');
 s=step('cold-chain',start('cold-chain'),'cool-1');assert.ok(!legal('cold-chain',s).includes('parfait'),'One chilled tick is insufficient for parfait milk');
 s=step('power-desk',start('power-desk'),'2-reserve');assert.equal(s.out,0,'Cold turbine has a startup delay');assert.equal(s.charge,4);
 s=step('quiet-majority',start('quiet-majority'),'p0');s=step('quiet-majority',s,'g2');s=step('quiet-majority',s,'vote');assert.equal(s.policy[0],2,'Policy commitments persist across bills');assert.deepEqual(s.promises,[0,0,0,0],'Grants expire after the vote');
 s=step('safe-return',start('safe-return'),'farm');assert.ok(!legal('safe-return',s).includes('home'),'Outstanding collateral blocks another premium-funded policy');for(let i=0;i<3;i++)s=step('safe-return',s,'decline');assert.equal(s.active.length,0,'Four-day farm expires only after its fourth claim check');assert.equal(s.cash,27);
 s=start('firebreak');for(let i=0;i<3;i++)s=step('firebreak',s,'end');assert.equal(s.cells[3],'fire','Unprotected forecast lightning ignites after spread three');
 s=step('elevator-night',start('elevator-night'),'doors');assert.equal(s.people.filter(x=>x.status==='aboard').length,1);s=step('elevator-night',s,'doors');assert.equal(s.served,0,'Opening doors on origin does not deliver passenger');
 // Delivery deadlines are inclusive end-of-action, consistent with Signal Cabinet.
 for(const due of [11,12,13]){let lift=start('elevator-night');lift.people[0].due=due;for(let i=0;i<7;i++)lift=step('elevator-night',lift,'doors');for(let i=0;i<4;i++)lift=step('elevator-night',lift,'up');lift=step('elevator-night',lift,'doors');assert.equal(lift.people[0].status,due===11?'missed':'delivered','Delivery on/before due tick is accepted; later delivery is missed');}
 s=step('supply-web',start('supply-web'),'b4');assert.equal(s.made,0,'Assembly alone cannot run without enough ore/timber');s=step('supply-web',s,'run');assert.equal(s.made,1,'Upstream output feeds downstream within same tick');
 s=step('growing-block',start('growing-block'),'lot-0');assert.equal(s.land[0].pop,0,'Isolated home does not attract residents');assert.equal(s.land[5].pop,2,'Home beside park grows');
 // Independent yearly calculation: all homes migrate before any shop collects.
 const city=start('growing-block');city.land=Array.from({length:16},()=>({type:'empty',pop:0}));city.land[0]={type:'shop',pop:0};city.land[1]={type:'home',pop:0};city.land[4]={type:'home',pop:0};city.land[15]={type:'factory',pop:0};s=step('growing-block',city,'wait');assert.equal(s.land[1].pop,1);assert.equal(s.land[4].pop,1);assert.equal(s.cash,14,'Shop counts both newly occupied neighbors regardless of row order');
 s=step('borrowed-time',start('borrowed-time'),'0-0');assert.equal(s.turn,0,'Assignment does not advance a day');assert.ok(!legal('borrowed-time',s).includes('1-0'),'Second crew cannot take occupied task');assert.equal(s.jobs[0].left,2,'Specialist reduces task duration');
 s=step('convoy-ledger',start('convoy-ledger'),'a0');s=step('convoy-ledger',s,'sail');assert.equal(s.cargo,0,'Partial escort does not partially deliver cargo');assert.equal(s.lost,1,'Underprotected assigned escort is lost');
 s=step('reservoir',start('reservoir'),'r0');assert.equal(s.short,3);s=step('reservoir',s,'r0');assert.ok(s.done&&!s.won,'Accumulated shortage closes reservoir');
 s=start('marsh-balance');s=step('marsh-balance',s,'habitat');assert.equal(s.reeds,29);assert.equal(s.grazers,8,'Reeds and predation update in documented order');
 for(const a of plans['carry-on']){s=typeof s.bag==='undefined'?start('carry-on'):s;s=step('carry-on',s,a);assert.ok(s.bag.reduce((n,x)=>n+x.w,0)<=15);assert.ok(s.bag.reduce((n,x)=>n+x.v,0)<=14);}
 const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
 try{for(const mobile of[false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:900},hasTouch:mobile,isMobile:mobile,reducedMotion:mobile?'reduce':'no-preference'});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const activate=async selector=>{const b=page.locator(selector).first();if(mobile)await b.tap();else{await b.focus();await b.press('Enter');}};
 for(const g of games){console.log((mobile?'touch ':'keyboard ')+g.id);await page.goto(BASE+'/mini-games/'+g.url);await page.waitForSelector('body[data-game-ready="true"]');assert.equal(await page.locator('body').getAttribute('data-game-id'),g.id);assert.equal(await page.locator('h1').innerText(),g.name);assert.ok((await page.locator('#rules').innerText()).length>100);await activate('#start');const initial=await page.locator('#scoreboard').innerText(),opening=await page.locator('#cards').innerText(),openingBoard=await page.locator('#board').innerText();
 // Ordinary, unsolved first-button interaction checks activation/focus, not outcome quality.
 await activate('[data-action]:not(:disabled)');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');await activate('#restart');assert.equal(await page.locator('#scoreboard').innerText(),initial);assert.equal(await page.locator('#cards').innerText(),opening);assert.equal(await page.locator('#board').innerText(),openingBoard);
 for(const a of failures[g.id])await activate(`[data-action="${a}"]`);assert.equal(await page.locator('body').getAttribute('data-outcome'),'loss',g.id+' UI failure outcome');assert.ok(await page.locator('#result').isVisible());assert.equal(await page.locator('[data-action]:not(:disabled)').count(),0,'Terminal state has no playable action');await activate('#restart');assert.equal(await page.locator('#scoreboard').innerText(),initial);assert.equal(await page.locator('#cards').innerText(),opening);assert.equal(await page.locator('#board').innerText(),openingBoard);
 for(const a of plans[g.id])await activate(`[data-action="${a}"]`);assert.equal(await page.locator('body').getAttribute('data-outcome'),'win',g.id+' UI winning outcome');assert.ok(await page.locator('#result').isVisible());assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');assert.equal(await page.locator('[data-action]:not(:disabled)').count(),0);await activate('#again');assert.equal(await page.locator('#scoreboard').innerText(),initial);assert.equal(await page.locator('#cards').innerText(),opening);assert.equal(await page.locator('#board').innerText(),openingBoard);assert.equal(await page.locator('body').getAttribute('data-outcome'),'playing');
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'No horizontal overflow');assert.deepEqual(errors,[],'No browser errors');evidence.cases.push({id:g.id,profile:mobile?'mobile-touch':'desktop',passed:true,outcome:'win',restart:true,touchOnly:mobile,inputMethod:mobile?'Touch-only taps on actual onscreen controls; source-derived solution replay':'Keyboard focus + Enter activation on actual controls; source-derived solution replay',ordinaryInput:'Unsolved first available control activated, focus and restart checked; no unaided completion claim',winActions:plans[g.id].length,lossActions:failures[g.id].length,edgeCases:['Deliberate failure route reaches loss through UI','Terminal controls unavailable','Restart and Play again restore initial scoreboard','Keyboard focus never falls to BODY after action','Invalid engine action and post-terminal action are rejected','No horizontal overflow; no page errors']});save();
 }await context.close();}
 assert.equal(hash(),testedHash,'Source changed during verification; rerun required');evidence.sourceHash=testedHash;evidence.passed=evidence.cases.length===40&&evidence.cases.every(c=>c.passed);save();console.log('PASS systems: 20 games × keyboard and touch wins, failures and restarts.');}finally{await browser.close();}
})().catch(e=>{evidence.passed=false;evidence.error=e.stack;save();console.error(e);process.exitCode=1;});
