/* Pure-engine invariant checks plus source-planned, actual UI-input replays.
   Plans are reachability evidence, NOT unassisted ordinary player evidence. */
const {chromium}=require('playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const BASE=process.env.BASE_URL||'http://127.0.0.1:8790';
const reportPath=path.join(__dirname,'../coverage/tabletop-room.json');
const report={suite:'tabletop-room',passed:false,testedAt:new Date().toISOString(),cases:[],limits:['Source-planned pure-engine routes replayed through real visible UI controls; no runtime state injection or delivered test hooks.','Chromium desktop and emulated touch mobile; not physical-device or screen-reader verification.','Competitive routes include losses, so terminal coverage does not claim mastery or that every opponent is deeply tuned.','Separate independent reviewer covers ordinary play samples; these planned routes do not count as unassisted ordinary play.']};
const save=()=>fs.writeFileSync(reportPath,JSON.stringify(report,null,2)+'\n');save();
(async()=>{
const {start,step,actions,view,ids}=await import('../tabletop-room/engines.mjs');
const manifest=JSON.parse(fs.readFileSync(path.join(__dirname,'../tabletop-room/games.json')));
const routes=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/tabletop-paths.json')));
assert.equal(manifest.length,20);assert.equal(ids.length,20);assert.deepEqual(new Set(ids),new Set(manifest.map(g=>g.id)));assert.deepEqual(new Set(ids),new Set(Object.keys(routes)));
const finals={};let transitions=0;
for(const id of ids){for(const [kind,r]of Object.entries(routes[id])){let s=start(id);for(const code of r.path){assert.ok(actions(s).some(a=>a.code===code),`${id}/${kind} illegal planned ${code}`);const old=JSON.stringify(s);assert.equal(step(s,'invalid-action'),s);s=step(s,code);assert.notEqual(JSON.stringify(s),old,'each route action changes state');assert.equal(s.id,id);assert.ok(actions(s).every(a=>typeof a.code==='string'&&a.label));assert.equal(new Set(actions(s).map(a=>a.code)).size,actions(s).length,'action IDs unique');if(s.b)assert.ok(s.b.every(v=>[-2,-1,0,1,2].includes(v)));if(s.h)assert.ok(s.h.every(n=>n>=0&&n<=4));if(id==='five-card-evening'){assert.ok(s.tokens>=0);if(s.tokens===0&&s.redrawn&&s.phase==='hold')assert.ok(!actions(s).some(a=>a.code==='draw'),'exhausted extra-redraw budget cannot be overspent');}transitions++;}assert.equal(s.done,true);assert.equal(s.outcome,r.outcome);assert.equal(s.note,r.note);assert.deepEqual(actions(s),[]);assert.equal(step(s,r.path[0]),s);finals[id+':'+kind]=s;}}
for(const id of ['meld-atelier','five-card-evening','six-columns','court-of-suits'])assert.equal(finals[id+':main'].outcome,'win',id+' solo winning route');
// Targeted rule tests, isolated engine states only. These are not UI reachability claims.
let s=start('hidden-dice');s.bid={n:1,f:s.dice[0]};s.phase='bid';const before=s.yn;let t=step(s,'challenge');assert.equal(t.yn,before-1,'challenging a true house bid loses your die');s=start('hidden-dice');s.bid={n:8,f:1};s.dice=[2,2,2,2];s.house=[3,3,3,3];t=step(s,'challenge');assert.equal(t.hn,3,'false house bid loses house die');
s=start('bank-the-roll');assert.ok(!actions(s).some(a=>a.code==='bank'),'cannot bank zero');
s=start('last-hand');s.hand=[{r:3,u:0},{r:3,u:1},{r:5,u:2}];s.lead={n:2,r:2};s.sel=[0];assert.ok(!actions(s).some(a=>a.code==='play'),'cannot answer a pair with one card');s.sel=[0,1];assert.ok(actions(s).some(a=>a.code==='play'));
s=start('meld-atelier');s.phase='play';s.hand=[{r:3,u:0},{r:4,u:0},{r:5,u:0},{r:9,u:2}];s.sel=[0,1,2];assert.ok(actions(s).some(a=>a.code==='meld'));t=step(s,'meld');assert.equal(t.hand.length,1);assert.equal(t.melds.length,1);
s=start('scopa-shelf');s.hand=[{r:5,u:0}];s.sel=[0];s.table=[{r:5,u:1},{r:2,u:2},{r:3,u:3}];s.targets=[1,2];assert.ok(!actions(s).some(a=>a.code==='capture'),'single exact rank overrides equivalent sum');s.targets=[0];assert.ok(actions(s).some(a=>a.code==='capture'));
s=start('draught-garden');s.b=Array(36).fill(0);s.b[25]=1;s.b[20]=-1;s.b[10]=-1;s.b[35]=1;assert.deepEqual(actions(s).map(a=>a.code),['s25'],'mandatory capture excludes idle piece');s=step(s,'s25');s=step(s,'m15');assert.equal(s.chain,15,'capture chain locks same piece');assert.ok(actions(s).some(a=>a.code==='m5'));
s=start('borrowed-steps');s=step(s,'s20');const move=actions(s).find(a=>a.code.startsWith('m'));assert.ok(move);const oldCard=s.pc[0];s=step(s,move.code);assert.ok(!s.pc.includes(oldCard),'used card leaves player hand');
s=start('six-columns');s.dice=[2,2,2,3,3];assert.match(actions(s).find(a=>a.code==='score3').label,/25/);s=step(s,'score3');assert.ok(!actions(s).some(a=>a.code==='score3'),'score category cannot be reused');
s=start('court-of-suits');s.hand=[{r:6,u:0},{r:3,u:2}];s.enemy=24;s.boss=2;s.hp=10;t=step(s,'p0');assert.equal(t.hp,10,'spade guard absorbs five');assert.equal(t.enemy,21,'brace removes three incoming damage');s.beat=1;t=step(s,'p0');assert.equal(t.hp,8,'six guard blocks six of the heavy eight damage');assert.equal(t.enemy,18,'heavy strike carries no armor');
report.engineChecks={transitions,invalidAndTerminalLock:true,specific:['true/false liar challenges','zero-bank rejection','climbing group size','rummy run','Scopa exact capture priority','mandatory draught capture and chain','movement card exchange','dice row immutability','spade mitigation']};
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
try{for(const mobile of[false,true]){const context=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:mobile?'reduce':'no-preference'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
for(const game of manifest){const id=game.id;console.log((mobile?'touch ':'desktop ')+id);await page.goto(BASE+'/mini-games/'+game.url);await page.waitForFunction(()=>document.body.dataset.gameReady==='true');assert.equal(await page.locator('h1').innerText(),game.name);assert.equal(await page.locator('body').getAttribute('data-game-id'),id);assert.equal(await page.locator('#rules li').count(),game.rules.length);if(mobile)await page.locator('#start').tap();else{await page.locator('#start').focus();await page.keyboard.press('Enter');}const initial=await page.locator('#scoreboard').innerText();assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');const unavailable=page.locator('#board button[aria-disabled=true]').first();let blocked=false;if(await unavailable.count()){const status=await page.locator('#status').innerText();if(mobile)await unavailable.tap({force:true});else await unavailable.click({force:true});assert.equal(await page.locator('#status').innerText(),status);blocked=true;}
const variants=mobile?['main']:Object.keys(routes[id]);for(const variant of variants){if(variant!=='main'){await page.locator('#restart').click();assert.equal(await page.locator('#scoreboard').innerText(),initial);}const route=routes[id][variant];let count=0;for(const code of route.path){const button=page.locator(`[data-action="${code}"]`);assert.equal(await button.count(),1,`${id} control ${code}`);assert.equal(await button.isVisible(),true);if(mobile)await button.tap();else if(count===0){await button.focus();await page.keyboard.press('Space');}else await button.click();assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY',`${id} focus survives action`);count++;}assert.equal(await page.locator('body').getAttribute('data-completed'),'true');assert.equal(await page.locator('body').getAttribute('data-outcome'),route.outcome);assert.equal(await page.locator('#result-title').innerText(),route.note);assert.equal(await page.evaluate(()=>document.activeElement.id),'again');assert.equal(await page.locator('[data-action]').count(),0,'terminal controls lock');if(mobile)await page.locator('#again').tap();else await page.locator('#again').click();assert.equal(await page.locator('body').getAttribute('data-completed'),'false');assert.equal(await page.locator('#scoreboard').innerText(),initial);if(mobile)await page.locator('#restart').tap();else await page.locator('#restart').click();assert.equal(await page.locator('#scoreboard').innerText(),initial);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'no horizontal overflow');if(mobile){await page.setViewportSize({width:320,height:740});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'320px no overflow');await page.setViewportSize({width:390,height:844});}assert.deepEqual(errors,[]);report.cases.push({id,profile:mobile?'mobile-touch':'desktop',variant,passed:true,outcome:route.outcome,restart:true,edgeCases:['invalid engine action is inert','terminal gameplay controls removed','repeat restart restores opening',...(blocked?['unavailable board square is inert']:[]),...(variant==='failure'?['deliberate losing route']:[])],inputMethod:mobile?'Playwright touchscreen taps for every gameplay action':'Keyboard Space for first action, pointer clicks for remaining actions',touchOnly:mobile,classification:'source-planned UI-input reachability replay',actions:route.path.length});save();}
if(['five-card-evening','marble-council','terrace-duel'].includes(id))await page.screenshot({path:`/tmp/tabletop-${id}-${mobile?'touch':'desktop'}.png`,fullPage:true});}
await context.close();}report.passed=report.cases.length===48&&ids.every(id=>report.cases.some(c=>c.id===id&&c.profile==='desktop')&&report.cases.some(c=>c.id===id&&c.profile==='mobile-touch'));assert.equal(report.passed,true);save();console.log(JSON.stringify({passed:report.passed,cases:report.cases.length,engineTransitions:transitions}));}finally{await browser.close();}
})().catch(e=>{report.passed=false;report.error=e.stack;save();console.error(e);process.exitCode=1;});
