import{base,action,card,advance,finish}from'./core.mjs';
const winds=['east','south','east','east','south','east','south','east','east','south'];
const houses=[5,11,23,35];
export const rules=['Protect four cabins on a 6×6 hillside for ten wind shifts. You have one crew action before each spread. A trench permanently blocks fire; water extinguishes one burning cell and all burning neighbors, but only one tank are available.','Burning cells become ash after spreading. East wind spreads east and south; south wind spreads south and west. Fire cannot cross trenches, ash or wet cells. Lightning ignites an unprotected square after spreads 3, 5, 7 and 9: respectively row 1 column 4; row 3 column 5; row 5 column 5; row 2 column 4.','Keep all four cabins unburned. Build trenches on any empty non-cabin cell. The grid labels every location and terrain; choose a burning cell for a water action. End crew turn skips remaining actions.'];
export const init=()=>({...base(),cells:Array.from({length:36},(_,i)=>[0,12,24].includes(i)?'fire':houses.includes(i)?'cabin':'grass'),crew:1,water:1,burned:0});
const nearby=i=>[i-6,i+6,...(i%6?[i-1]:[]),...(i%6<5?[i+1]:[])].filter(x=>x>=0&&x<36);
export const choices=s=>[...s.cells.flatMap((x,i)=>x==='grass'?[action('t'+i,`Trench row ${Math.floor(i/6)+1}, column ${i%6+1}`,'Permanent barrier')]:x==='fire'&&s.water?[action('w'+i,`Water row ${Math.floor(i/6)+1}, column ${i%6+1}`,'Extinguish this fire and neighboring fires')]:[]),action('end','End crew turn',`${s.crew} actions unused`)];
export function apply(s,a){if(a[0]==='t'){s.cells[+a.slice(1)]='trench';s.crew--;}else if(a[0]==='w'){s.water--;for(let i of[+a.slice(1),...nearby(+a.slice(1))])if(s.cells[i]==='fire')s.cells[i]='wet';s.crew--;}else s.crew=0;if(s.crew){s.note=`Crew action used; ${s.crew} before wind shifts.`;return;}let next=[...s.cells],wind=winds[s.turn];s.cells.forEach((x,i)=>{if(x!=='fire')return;next[i]='ash';let dest=wind==='east'?[...(i%6<5?[i+1]:[]),i+6]:[i+6,...(i%6?[i-1]:[])];for(let d of dest)if(d>=0&&d<36&&['grass','cabin'].includes(s.cells[d])){if(s.cells[d]==='cabin'&&next[d]!=='fire')s.burned++;next[d]='fire';}});s.cells=next;let spark={2:3,4:16,6:28,8:9}[s.turn];if(spark!==undefined&&s.cells[spark]==='grass')s.cells[spark]='fire';advance(s,`${wind} wind spread. ${4-s.burned} cabins remain.`);s.crew=1;if(s.burned>=1)return finish(s,false,'A cabin burned. Protect the leading edge, including the forecast lightning square.');if(s.turn===10)return finish(s,true,`${4-s.burned} cabins protected. The fire front is contained.`);}
export const view=s=>({stats:[['Wind shift',`${s.turn}/10`],['Crew',s.crew],['Water',s.water]],grid:{cols:6,cells:s.cells.map((x,i)=>({label:`Row ${Math.floor(i/6)+1}, column ${i%6+1}: ${x}`,text:{fire:'FIRE',grass:'·',cabin:'HOME',trench:'═',wet:'≈',ash:'×'}[x],tone:x,action:x==='grass'?'t'+i:x==='fire'&&s.water?'w'+i:null}))},cards:[card('Cabins safe',`${4-s.burned}/4`,'Need all 4')],forecast:[`Next wind: ${winds[s.turn]||'none'}. Following: ${winds[s.turn+1]||'none'}.`,'Lightning after spreads 3/5/7/9: (row 1, col 4), (row 3, col 5), (row 5, col 5), (row 2, col 4).']});
