import{engines,start,choices,step,view}from'./engines.mjs';
const $=id=>document.getElementById(id),node=(tag,text,cls)=>{const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;};
try{
 const response=await fetch('games.json');if(!response.ok)throw Error('The game menu could not be loaded. Please reload.');
 const games=await response.json(),id=new URLSearchParams(location.search).get('game')||games[0].id,game=games.find(g=>g.id===id);if(!game||!engines[id])throw Error('This game is not in the systems room. Return to All games to choose a table.');
 let state=start(id),active=false;document.title=game.name+' — Small Hours';$('title').textContent=game.name;$('table-label').textContent=game.name;$('symbol').textContent=game.symbol;$('tagline').textContent=game.description;$('controls').textContent=game.controls;document.documentElement.style.setProperty('--accent',game.accent);document.body.dataset.gameId=id;
 for(const [i,text]of game.rules.entries()){const li=node('li');li.append(node('b',['Set the scene.','Consider the system.','Bring it home.'][i]||'One more thing.'),node('p',text));$('rules').append(li);}
 function render(focusId){const old=[...document.querySelectorAll('[data-action]')],index=old.findIndex(e=>e.dataset.action===focusId);const v=view(id,state),available=choices(id,state);$('scoreboard').replaceChildren(...v.stats.map(([label,value])=>{const d=node('div');d.append(node('span',label),node('strong',String(value)));return d;}));$('status').textContent=active?state.note:'Read the rules, inspect the opening state, then begin. Nothing moves until you choose.';$('start').hidden=active;$('cards').replaceChildren(...(v.cards||[]).map(c=>{const d=node('div',undefined,'state-card '+(c.tone||''));d.append(node('div',c.label,'label'),node('strong',String(c.value)),node('small',c.detail||''));return d;}));
  const gridIds=new Set();$('board').replaceChildren();if(v.grid){$('board').style.setProperty('--cols',v.grid.cols);for(const c of v.grid.cells){const legal=available.some(a=>a.id===c.action),e=node(c.action?'button':'div',c.text,'cell '+(c.tone||''));const actionInfo=available.find(a=>a.id===c.action);e.setAttribute('aria-label',c.label+(actionInfo?'. '+actionInfo.label+'. '+(actionInfo.detail||''):''));if(c.action){gridIds.add(c.action);e.dataset.action=c.action;e.type='button';e.disabled=!active||!legal;e.addEventListener('click',()=>play(c.action));}else e.setAttribute('role','img');$('board').append(e);}}
  $('actions').replaceChildren(...available.filter(a=>!gridIds.has(a.id)).map(a=>{const b=node('button');b.type='button';b.dataset.action=a.id;b.disabled=!active;b.append(node('span',a.label));if(a.detail)b.append(node('small',a.detail));b.addEventListener('click',()=>play(a.id));return b;}));$('forecast-list').replaceChildren(...(v.forecast||[]).map(t=>node('li',t)));$('forecast').hidden=!v.forecast?.length;$('log').replaceChildren(...state.log.map(t=>node('li',t)));$('ledger').hidden=!state.log.length;$('result').hidden=!state.done;document.body.dataset.completed=String(state.done);document.body.dataset.outcome=state.done?(state.won?'win':'loss'):'playing';
  if(state.done){$('result-title').textContent=state.won?'A plan well made.':'A lesson for next time.';$('result-copy').textContent=state.note;if(focusId!==undefined)$('again').focus({preventScroll:true});}else if(focusId!==undefined){const live=[...document.querySelectorAll('[data-action]')].filter(e=>!e.disabled),target=live.find(e=>e.dataset.action===focusId)||live[Math.min(Math.max(index,0),live.length-1)]||$('restart');target.focus({preventScroll:true});}document.body.dataset.gameReady='true';
 }
 function play(a){if(!active||state.done)return;const next=step(id,state,a);if(next===state)return;state=next;render(a);}
 function reset(){state=start(id);active=true;render();document.querySelector('[data-action]:not(:disabled)')?.focus();}
 $('start').addEventListener('click',()=>{active=true;render('');document.activeElement?.scrollIntoView({block:'nearest'});});$('restart').addEventListener('click',reset);$('again').addEventListener('click',reset);
 document.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!document.activeElement?.dataset.action)return;const live=[...document.querySelectorAll('[data-action]')].filter(e=>!e.disabled),i=live.indexOf(document.activeElement);if(i<0)return;e.preventDefault();const d=['ArrowLeft','ArrowUp'].includes(e.key)?-1:1;live[(i+d+live.length)%live.length].focus();});render();
}catch(e){$('status').textContent=e.message;$('start').disabled=true;$('restart').disabled=true;document.body.dataset.gameReady='error';}
