import{base,range,copy,shuffle,choose,finish,log,history,sum}from'./core.mjs';
export const cardRank=c=>c%6+1,cardSuit=c=>Math.floor(c/6),cardName=c=>(cardSuit(c)?'Leaf':'Sun')+' '+cardRank(c);
export const defenseLegal=(attack,card,trump)=>cardSuit(card)===cardSuit(attack)?cardRank(card)>cardRank(attack):cardSuit(card)===trump;
export function defenseAttacks(s,who){let hand=s.hands[who===1?0:1];if(!s.table.length)return hand.slice();let ranks=s.table.flatMap(p=>p.d===null?[cardRank(p.a)]:[cardRank(p.a),cardRank(p.d)]);return s.table.length<s.limit?hand.filter(c=>ranks.includes(cardRank(c))):[]}
function defenseRemove(s,who,c){let h=s.hands[who===1?0:1];h.splice(h.indexOf(c),1)}
export function defenseRefill(s,attacker){for(let who of[attacker,-attacker])while(s.hands[who===1?0:1].length<4&&s.deck.length)s.hands[who===1?0:1].push(s.deck.shift())}
function defenseEnd(s){if(!s.deck.length&&(!s.hands[0].length||!s.hands[1].length)||s.turn>=80){let win=!s.deck.length&&!s.hands[0].length&&!!s.hands[1].length;finish(s,win,win?'You shed the final card after the deck emptied.':'The house shed first, both hands emptied together, or eighty volleys held its defense.',s.discard.length*5+(win?200:0));return true}return false}
function defenseStart(s,who){s.attacker=who;s.table=[];s.limit=Math.min(3,s.hands[who===1?1:0].length);s.phase=who===1?'attack':'defend';if(defenseEnd(s))return;if(who===-1){let c=s.hands[1].slice().sort((a,b)=>(cardSuit(a)===s.trump)-(cardSuit(b)===s.trump)||cardRank(a)-cardRank(b))[0];defenseRemove(s,-1,c);s.table.push({a:c,d:null});log(s,'House attacks with '+cardName(c)+'.')}}
function defenseSettle(s,taken){let attacker=s.attacker,defender=-attacker;if(taken)s.hands[defender===1?0:1].push(...s.table.flatMap(p=>p.d===null?[p.a]:[p.a,p.d]));else s.discard.push(...s.table.flatMap(p=>[p.a,p.d]));defenseRefill(s,attacker);s.turn++;s.table=[];if(defenseEnd(s))return;defenseStart(s,taken?attacker:defender)}
function defenseHouseResponse(s){let p=s.table.at(-1),cards=s.hands[1].filter(c=>defenseLegal(p.a,c,s.trump)).sort((a,b)=>(cardSuit(a)===s.trump)-(cardSuit(b)===s.trump)||cardRank(a)-cardRank(b));if(!cards.length){log(s,'House takes the entire table.');defenseSettle(s,true);return}p.d=cards[0];defenseRemove(s,-1,p.d);log(s,'House defends '+cardName(p.a)+' with '+cardName(p.d)+'.')}
const defense={stages:3,init(o){let s=base('last-defense',o);s.trump=o.stage%2;let deck=o.mode==='endless'?shuffle(s,range(12)):o.stage===0?[0,1,2,3,6,8,10,11,4,5,7,9]:o.stage===1?[1,4,7,10,0,3,6,9,2,5,8,11]:[0,2,5,9,1,4,7,11,3,6,8,10];s.hands=[deck.slice(0,4),deck.slice(4,8)];s.deck=deck.slice(8);s.discard=[];s.table=[];s.attacker=1;s.phase='attack';s.limit=3;s.note='You attack first. Defenders must beat the attack in its suit or with trump; extra attacks must use a rank already on the paired table.';return s},act(s,k){if(s.phase==='attack'){if(k==='finish'&&s.table.length&&s.table.every(p=>p.d!==null)){defenseSettle(s,false);return}let c=+k.slice(5);if(!k.startsWith('card-')||!defenseAttacks(s,1).includes(c))return;defenseRemove(s,1,c);s.table.push({a:c,d:null});log(s,'You attack with '+cardName(c)+'.');defenseHouseResponse(s)}else{if(k==='take'){log(s,'You take the whole table.');defenseSettle(s,true);return}let c=+k.slice(5),p=s.table.at(-1);if(!k.startsWith('card-')||!s.hands[0].includes(c)||!defenseLegal(p.a,c,s.trump))return;defenseRemove(s,1,c);p.d=c;let extra=defenseAttacks(s,-1).sort((a,b)=>cardRank(a)-cardRank(b))[0];if(extra!==undefined){defenseRemove(s,-1,extra);s.table.push({a:extra,d:null});log(s,'You defend; house adds rank-linked '+cardName(extra)+'.')}else{log(s,'You defend the completed volley.');defenseSettle(s,false)}}},render(ui,s){ui.p(`Trump ${s.trump?'Leaf':'Sun'} · Deck ${s.deck.length} · House hand ${s.hands[1].length} · Volley ${s.turn}/80 · ${s.phase==='attack'?'You attack.':'You defend.'}`);ui.table(['Attack','Defense'],s.table.map(p=>[cardName(p.a),p.d===null?'Unanswered':cardName(p.d)]));ui.grid(3,'Your cards',{compact:true});let legal=s.phase==='attack'?defenseAttacks(s,1):s.table.length?s.hands[0].filter(c=>defenseLegal(s.table.at(-1).a,c,s.trump)):[];for(let c of s.hands[0])ui.button('card-'+c,cardName(c)+(cardSuit(c)===s.trump?' · trump':''),!legal.includes(c));ui.group('Volley decision');if(s.phase==='attack')ui.button('finish','Finish defended volley',!s.table.length||s.table.some(p=>p.d===null));else ui.button('take','Take whole table');ui.p('Higher same-suit cards beat attacks; any trump beats a non-trump. Additional attacks share a table rank and the volley is limited to the defender’s starting hand, at most three attacks. Successful defense changes attacker; taking keeps the attacker. Refill attacker first to four, then defender. Empty your hand after the deck ends to win.');history(ui,s)}};
export function columnScore(a){return range(3).reduce((n,i)=>n+(a[i]===a[i+3]?0:a[i]+a[i+3]),0)}
export function columnFinish(s){s.revealed=[Array(6).fill(true),Array(6).fill(true)];let a=columnScore(s.cards[0]),b=columnScore(s.cards[1]);finish(s,a<b,`Final grid scores: you ${a}, house ${b}. ${a<b?'Your lower score wins.':'The house holds equal or lower score.'}`,Math.max(0,80-a*2)+(a<b?200:0))}
function columnHouse(s){let drawn=s.deck.length?s.deck.shift():s.discard.pop(),side=s.cards[1],known=side.map((c,i)=>s.revealed[1][i]?c:5),best={i:-1,value:columnScore(known)};for(let i=0;i<6;i++){let q=known.slice();q[i]=drawn;let value=columnScore(q);if(value<best.value)best={i,value}}if(best.i>=0){s.discard.push(side[best.i]);side[best.i]=drawn;s.revealed[1][best.i]=true;log(s,'House replaces '+(best.i+1)+' after drawing.')}else{let hidden=s.revealed[1].findIndex(v=>!v);if(hidden>=0)s.revealed[1][hidden]=true;s.discard.push(drawn);log(s,'House discards its draw and reveals a hidden cell.')}s.turn++;if(s.closer===1||!s.deck.length||s.turn>=16){columnFinish(s);return}if(s.revealed[1].every(Boolean)){s.closer=-1;s.note+=' House closed; you receive the final turn.'}s.phase='draw';s.held=null}
function columnDone(s){if(s.closer===-1){columnFinish(s);return}if(s.revealed[0].every(Boolean))s.closer=1;columnHouse(s)}
const columns={stages:3,init(o){let s=base('covered-columns',o);let pool=shuffle(s,[-2,-2,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10]);if(o.mode==='finite'){let a=o.stage===0?[8,7,6,8,3,4]:o.stage===1?[6,8,5,2,8,9]:[9,6,7,8,2,7],b=o.stage===0?[5,6,5,4,7,4]:o.stage===1?[4,5,6,7,3,6]:[6,6,8,5,8,4];pool=a.concat(b,[-2,0,1,2,3,4,0,2,5,1,6,9])}s.cards=[pool.slice(0,6),pool.slice(6,12)];s.deck=pool.slice(13);s.discard=[pool[12]];s.revealed=[[true,true,false,false,false,false],[true,true,false,false,false,false]];s.phase='draw';s.held=null;s.closer=null;s.note='Draw from the deck or take the visible discard; replace a cell, or discard a deck draw and reveal one hidden cell.';return s},act(s,k){if(s.phase==='draw'){if(k==='draw'&&s.deck.length){s.held=s.deck.shift();s.from='deck'}else if(k==='discard'&&s.discard.length){s.held=s.discard.pop();s.from='discard'}else return;s.phase='place';s.note='Drawn '+s.held+'. Replace a grid cell'+(s.from==='deck'?', or discard it and reveal a hidden cell.':'.');return}let p=+k.split('-')[1];if(!Number.isInteger(p)||p<0||p>5)return;if(k.startsWith('replace-')){s.discard.push(s.cards[0][p]);s.cards[0][p]=s.held;s.revealed[0][p]=true;log(s,'You replace cell '+(p+1)+'.')}else if(k.startsWith('reveal-')&&s.from==='deck'&&!s.revealed[0][p]){s.discard.push(s.held);s.revealed[0][p]=true;log(s,'You discard the draw and reveal cell '+(p+1)+'.')}else return;s.held=null;columnDone(s)},render(ui,s){ui.p(`Turn ${s.turn}/16 · Deck ${s.deck.length} · Visible discard ${s.discard.at(-1)??'empty'} · ${s.closer?'Final turn has been triggered.':s.phase==='draw'?'Choose a draw source.':'Held card '+s.held+'.'}`);for(let side=0;side<2;side++){ui.h(side?'House grid':'Your grid');ui.grid(3,side?'House concealed grid':'Your concealed grid');for(let i=0;i<6;i++)ui.button('replace-'+i,(s.revealed[side][i]?s.cards[side][i]:'?')+' · '+(i+1),side!==0||s.phase!=='place')}ui.group('Draw sources');ui.button('draw','Draw deck',s.phase!=='draw'||!s.deck.length);ui.button('discard','Take visible discard',s.phase!=='draw'||!s.discard.length);if(s.phase==='place'&&s.from==='deck'){ui.grid(3,'Discard draw and reveal',{compact:true});for(let i=0;i<6;i++)ui.button('reveal-'+i,'Discard draw; reveal cell '+(i+1),s.revealed[0][i])}ui.p('Identical cards vertically in a column cancel to zero; every other card adds its value. Drawing from the deck permits discard-and-reveal, taking the visible discard requires replacement. Revealing your final cell gives the house one last turn, and vice versa. Deck exhaustion also settles all concealed cards. Strictly lower total wins.');history(ui,s)}};
export const cardTables={'last-defense':defense,'covered-columns':columns};
