import{base,range,copy,shuffle,choose,board,coord,offset,finish,log,history,random}from'./core.mjs';
const colors=['Sun','Wave','Leaf','Rose','Moon'];
export function colorMoves(s,who){let out=[];s.b.forEach((v,f)=>{if(!v||v.who!==who||s.forced!==null&&v.color!==s.forced)return;for(let dx of[-1,0,1])for(let k=1;k<5;k++){let t=offset(f,dx,-who,5,5,k);if(t<0||s.b[t])break;out.push({f,t})}});return out}
export function colorApply(s,m){s.b[m.t]=s.b[m.f];s.b[m.f]=null;s.forced=s.tiles[m.t];s.selected=null;s.passes=[]}
function colorEnd(s){let won=s.b.some((v,p)=>v?.who===1&&p<5),lost=s.b.some((v,p)=>v?.who===-1&&p>=20);if(won||lost){finish(s,won&&!lost,`${won?'Your':'The house'} pawn reached the far home row.`,won?240-s.turn*3:s.turn*3);return true}return false}
export function colorPass(s,who){let forced=s.b.findIndex(v=>v?.who===who&&v.color===s.forced);if(forced<0){finish(s,who===-1,'No pawn can move from the unrestricted opening.',who===-1?200:0);return true}let key=who+':'+s.forced;if(s.passes.includes(key)){finish(s,false,'The same blocked color/pass state returned. Neither side can break this forcing cycle; the house holds its defense.',s.turn);return true}s.passes.push(key);s.forced=s.tiles[forced];log(s,`${who===1?'You pass':'House passes'}: the blocked pawn stands on ${colors[s.forced]}, forcing that opposing pawn.`);return false}
function colorHouse(s){let ms=colorMoves(s,-1);if(!ms.length){colorPass(s,-1);return}let m=choose(s,ms,m=>{let q=copy(s);colorApply(q,m);if(m.t>=20)return 100000;let reply=colorMoves(q,1);return(reply.some(r=>r.t<5)?-10000:0)+Math.floor(m.t/5)*5-reply.length});colorApply(s,m);s.turn++;log(s,`House moves ${coord(m.f,5)} → ${coord(m.t,5)}, forcing your ${colors[s.forced]} pawn.`);if(!colorEnd(s)&&!colorMoves(s,1).length)s.note+=' Your forced pawn is blocked: pass using its square color.'}
const colorGame={stages:3,init(o){let s=base('chromatic-command',o);s.n=5;s.b=Array(25).fill(null);s.tiles=range(25).map(p=>((p%5)+Math.floor(p/5)*(o.stage%3+1))%5);if(o.mode==='endless'){let rows=shuffle(s,range(5)),cols=shuffle(s,range(5)),cs=shuffle(s,range(5));s.tiles=range(25).map(p=>cs[(rows[Math.floor(p/5)]+cols[p%5])%5])}for(let i=0;i<5;i++){s.b[20+i]={who:1,color:i};s.b[i]={who:-1,color:4-i}}if(o.mode==='finite'&&o.stage===2){s.b[17]=s.b[22];s.b[22]=null;s.b[8]=s.b[3];s.b[3]=null}s.forced=null;s.passes=[];s.note='Your first pawn is unrestricted. Every landing square then forces the opposing pawn of that color.';return s},act(s,k){if(k==='pass'&&!colorMoves(s,1).length){if(!colorPass(s,1))colorHouse(s);return}if(!k.startsWith('square-'))return;let p=+k.slice(7);if(colorMoves(s,1).some(m=>m.f===p)){s.selected=p;s.note='Your '+colors[s.b[p].color]+' pawn at '+coord(p,5)+' is selected. Choose a forward ray endpoint; its square color forces the house mover.';return}let m=colorMoves(s,1).find(m=>m.f===s.selected&&m.t===p);if(!m)return;let name=colors[s.b[m.f].color];colorApply(s,m);log(s,`Your ${name} moves to ${coord(m.t,5)}, forcing house ${colors[s.forced]}.`);if(!colorEnd(s))colorHouse(s)},render(ui,s){let ms=colorMoves(s,1);ui.p(`Turn ${s.turn} · Eligible pawn ${s.forced===null?'any':colors[s.forced]}. You advance toward row1; house toward row5. Forward vertical or diagonal rays stop before occupied squares; there are no captures.`);board(ui,s,{legal:[...new Set([...ms.map(m=>m.f),...ms.filter(m=>m.f===s.selected).map(m=>m.t)])],text:p=>colors[s.tiles[p]][0]+(s.b[p]?' '+(s.b[p].who===1?'●':'○')+colors[s.b[p].color][0]:''),detail:p=>coord(p,5)+': '+colors[s.tiles[p]]+' square'+(s.b[p]?', '+(s.b[p].who===1?'your':'house')+' '+colors[s.b[p].color]+' pawn':'')});if(!ms.length)ui.button('pass','Forced pawn blocked: pass');ui.p('S Sun · W Wave · L Leaf · R Rose · M Moon. Landing color selects the opposing pawn; a blocked pawn passes using the color beneath it. Repeated blocked pass cycles settle the defense.');history(ui,s)}};

const racerProgress=r=>r.done?12:r.back?12-r.p:r.p;
export function raceMove(s,who,i){let side=who===1?0:1,other=1-side,r=s.runners[side][i],q=copy(r),resets=[];if(r.done)return null;let step=r.back?-1:1,speed=s.speeds[side][i][r.back?1:0],crossed=false;for(let k=0;k<speed||crossed;k++){let p=q.p+step;if(p<=0||p>=6){q.p=p<=0?0:6;if(p>=6)q.back=true;else q.done=true;break}q.p=p;let hits=s.runners[other].flatMap((v,j)=>!v.done&&j+1===p&&v.p===i+1?[j]:[]);if(hits.length){resets.push(...hits);crossed=true}else if(crossed)break}return{i,next:q,resets:[...new Set(resets)]}}
export function raceApply(s,who,m){let side=who===1?0:1,other=1-side;s.runners[side][m.i]=m.next;for(let j of m.resets){let r=s.runners[other][j];r.p=r.back?6:0}}
function raceEnd(s){let a=s.runners[0].filter(r=>r.done).length,b=s.runners[1].filter(r=>r.done).length;if(a>=s.target||b>=s.target||s.turn>=90){let yours=sumProgress(s,0),theirs=sumProgress(s,1),win=a>=s.target||s.turn>=90&&yours>theirs&&b<s.target;finish(s,win,`Returned runners you ${a}/${s.target}, house ${b}/${s.target}. ${s.turn>=90?'Ninety turns settle total completed-leg progress.':'The first complete return team wins.'}`,a*60+(win?150:Math.round(yours)));return true}return false}
const sumProgress=(s,side)=>s.runners[side].reduce((v,r)=>v+racerProgress(r),0);
function raceValue(s,who){let side=who===1?0:1,other=1-side;if(s.runners[side].filter(r=>r.done).length>=s.target)return 100000;if(s.runners[other].filter(r=>r.done).length>=s.target)return-100000;let threat=0;for(let i=0;i<5;i++){let m=raceMove(s,-who,i);if(!m)continue;threat=Math.max(threat,m.resets.reduce((v,j)=>{let r=s.runners[side][j];return v+(r.back?6-r.p:r.p)},0))}return sumProgress(s,side)*4-sumProgress(s,other)*3+s.runners[side].filter(r=>r.done).length*20-threat*5}
const race={stages:3,init(o){let s=base('outward-and-home',o);s.n=7;s.runners=range(2).map(()=>range(5).map(()=>({p:0,back:false,done:false})));s.speeds=range(2).map((_,side)=>{let a=[1,3,2,3,1];if(o.mode==='endless')a=shuffle(s,a);else a=a.map((v,i)=>a[(i+Math.min(o.stage,2)*(side+1))%5]);return a.map(v=>[v,4-v])});s.target=o.mode==='endless'?4:2+Math.min(o.stage,2);if(o.mode==='finite'&&o.stage===1){s.runners[0][2].p=1;s.runners[1][1].p=2;s.runners[1][3].p=1}else if(o.mode==='finite'&&o.stage===2){s.runners[0][0]={p:6,back:true,done:false};s.runners[1][4]={p:6,back:true,done:false};s.runners[0][2].p=2;s.runners[1][2].p=1}if(o.mode==='endless'){for(let ply=0;ply<6;ply++){let who=ply%2? -1:1,i=Math.floor(random(s)*5);raceApply(s,who,raceMove(s,who,i))}}s.note='Your horizontal runners race out to the right edge and return. Crossing a vertical house runner resets that runner to its current leg start.';return s},act(s,k){if(!k.startsWith('run-'))return;let i=+k.slice(4),m=raceMove(s,1,i);if(!m)return;raceApply(s,1,m);log(s,`Your runner ${i+1} reaches ${m.next.p}${m.next.done?' and returns home':m.next.back?' on its return leg':' outward'}; reset house runners ${m.resets.map(n=>n+1).join(', ')||'none'}.`);if(raceEnd(s))return;let opts=range(5).map(i=>raceMove(s,-1,i)).filter(Boolean),h=choose(s,opts,m=>{let q=copy(s);raceApply(q,-1,m);return raceValue(q,-1)});raceApply(s,-1,h);s.turn++;log(s,`House runner ${h.i+1} reaches ${h.next.p}; resets yours ${h.resets.map(n=>n+1).join(', ')||'none'}.`);raceEnd(s)},render(ui,s){ui.p(`Turn ${s.turn}/90 · Return target ${s.target}. Your runners move horizontally; house vertically. Each uses its own outward/return speeds. A crossing resets the enemy, then stops at the first clear coordinate beyond the crossed run.`);ui.grid(7,'Crossing race field');for(let y=0;y<7;y++)for(let x=0;x<7;x++){let a=y>0&&y<6?s.runners[0][y-1]:null,b=x>0&&x<6?s.runners[1][x-1]:null,text=a&&!a.done&&a.p===x?'●'+y:b&&!b.done&&b.p===y?'○'+x:x>0&&x<6&&y>0&&y<6?'·':'–';let cell=ui.button('field-'+x+'-'+y,text,true);cell?.classList?.add('race-marker')}ui.table(['Runner','Your coordinate/leg','Your out/back speed','House coordinate/leg','House out/back speed'],range(5).map(i=>[i+1,s.runners[0][i].done?'home':s.runners[0][i].p+(s.runners[0][i].back?' return':' outward'),s.speeds[0][i].join('/'),s.runners[1][i].done?'home':s.runners[1][i].p+(s.runners[1][i].back?' return':' outward'),s.speeds[1][i].join('/')]));ui.group('Choose one horizontal runner');for(let i=0;i<5;i++){let m=raceMove(s,1,i);ui.button('run-'+i,m?`Runner ${i+1} → ${m.next.p}${m.next.done?' home':m.next.back?' return':''} · resets ${m.resets.map(j=>j+1).join(',')||'none'}`:`Runner ${i+1} completed`,!m)}history(ui,s)}};

export const forcedRaces={'chromatic-command':colorGame,'outward-and-home':race};
