import{base,range,copy,shuffle,choose,finish,log,history,board,coord}from'./core.mjs';
const triples=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
export function linkedCycle(s,a,b){let todo=[a],seen=new Set();while(todo.length){let p=todo.pop();if(p===b)return true;if(seen.has(p))continue;seen.add(p);for(let e of s.edges)if(e.a===p||e.b===p)todo.push(e.a===p?e.b:e.a)}return false}
export function linkedCollapse(s,edge,endpoint){let queue=[{e:edge,p:endpoint}];while(queue.length){let{e,p}=queue.shift();if(s.b[p])continue;s.b[p]={who:e.who,n:e.n};let incident=s.edges.filter(x=>x.a===p||x.b===p);s.edges=s.edges.filter(x=>x.a!==p&&x.b!==p);for(let x of incident)if(x.n!==e.n)queue.push({e:x,p:x.a===p?x.b:x.a})}s.phase='link';s.pending=null;s.selected=null}
export function linkedResult(s){let wins=[1,-1].map(w=>{let a=triples.filter(t=>t.every(p=>s.b[p]?.who===w));return a.length?Math.min(...a.map(t=>Math.max(...t.map(p=>s.b[p].n)))):Infinity});if(wins[0]!==Infinity||wins[1]!==Infinity)return wins[0]<wins[1]?'win':'loss';if(s.b.filter(Boolean).length>=8)return'loss';return'playing'}
export const linkedPairs=s=>range(9).filter(p=>!s.b[p]).flatMap((a,i,all)=>all.slice(i+1).map(b=>({a,b})));
export function linkedAdd(s,a,b,who){let cyclic=linkedCycle(s,a,b),e={a,b,who,n:++s.turn};s.edges.push(e);if(cyclic){s.phase='collapse';s.pending=e}return cyclic}
const linkValue=s=>s.b.reduce((n,v)=>n+(v?.who||0)*5,0)+triples.reduce((n,t)=>n+(t.filter(p=>s.b[p]?.who===1).length===2&&!t.some(p=>s.b[p]?.who===-1)?20:0)-(t.filter(p=>s.b[p]?.who===-1).length===2&&!t.some(p=>s.b[p]?.who===1)?20:0),0);
function linkedEnd(s){let r=linkedResult(s);if(r==='playing')return false;finish(s,r==='win',r==='win'?'Your classical line has the earlier closing move number.':'The house has the earlier classical line, or the exhausted board holds its defense.',s.b.filter(v=>v?.who===1).length*25+(r==='win'?200:0));return true}
function linkedHouse(s){let hs=linkedPairs(s).map(m=>{let q=copy(s);if(linkedAdd(q,m.a,m.b,-1)){let choices=[m.a,m.b].map(p=>{let r=copy(q);linkedCollapse(r,q.pending,p);return linkedResult(r)==='win'?10000:linkedResult(r)==='loss'?-10000:linkValue(r)});return{m,v:-Math.max(...choices)}}return{m,v:-(s.edges.filter(e=>e.who===1&&(e.a===m.a||e.b===m.a||e.a===m.b||e.b===m.b)).length)+triples.filter(t=>t.includes(m.a)&&t.includes(m.b)).length*3}}),h=choose(s,hs,x=>x.v);if(!h){linkedEnd(s);return}let cyc=linkedAdd(s,h.m.a,h.m.b,-1);log(s,`House links ${coord(h.m.a,3)} ↔ ${coord(h.m.b,3)} with mark ${s.turn}.${cyc?' You choose its collapse endpoint.':''}`);if(!cyc)linkedEnd(s)}
const linked={stages:3,init(o){let s=base('double-written',o);s.n=3;s.b=Array(9).fill(null);s.edges=[];s.phase='link';s.pending=null;let prefixes=o.stage===0?[[0,1],[3,4]]:o.stage===1?[[0,3],[1,4]]:[];if(o.mode==='endless'){prefixes=[];let q=copy(s);for(let i=0;i<2+2*(o.stage%3);i++){let legal=shuffle(s,linkedPairs(q)).filter(m=>!linkedCycle(q,m.a,m.b));if(!legal.length)break;let m=legal[0];linkedAdd(q,m.a,m.b,i%2?-1:1);prefixes.push([m.a,m.b])}}prefixes.forEach(([a,b],i)=>linkedAdd(s,a,b,i%2?-1:1));s.note='Choose two uncollapsed cells for one linked mark. A cycle gives the opponent the collapse choice and forces the connected marks to become classical.';return s},act(s,k){let p=+k.slice(7);if(!k.startsWith('square-')||s.b[p])return;if(s.phase==='collapse'){if(![s.pending.a,s.pending.b].includes(p))return;linkedCollapse(s,s.pending,p);log(s,'You collapse the triggering mark at '+coord(p,3)+'.');if(linkedEnd(s))return;return}if(s.selected===null){s.selected=p;s.note=coord(p,3)+' is the first endpoint; choose a different uncollapsed cell.';return}if(s.selected===p)return;let a=s.selected;s.selected=null;let cyc=linkedAdd(s,a,p,1);log(s,`You link ${coord(a,3)} ↔ ${coord(p,3)} with mark ${s.turn}.`);if(cyc){let choices=[a,p].map(endpoint=>{let q=copy(s);linkedCollapse(q,s.pending,endpoint);return{endpoint,q,v:linkedResult(q)==='loss'?10000:linkedResult(q)==='win'?-10000:-linkValue(q)}}),h=choose(s,choices,x=>x.v);linkedCollapse(s,s.pending,h.endpoint);log(s,'House collapses your trigger at '+coord(h.endpoint,3)+'.');if(linkedEnd(s))return}linkedHouse(s)},render(ui,s){ui.p(`Mark ${s.turn+1} · ${s.phase==='collapse'?'Cycle: choose one highlighted triggering endpoint.':'Link two uncollapsed cells.'}`);board(ui,s,{legal:s.phase==='collapse'?[s.pending.a,s.pending.b]:range(9).filter(p=>!s.b[p]),text:p=>s.b[p]?(s.b[p].who===1?'●':'○')+s.b[p].n:s.edges.filter(e=>e.a===p||e.b===p).map(e=>(e.who===1?'●':'○')+e.n).join(' ')||'·',detail:p=>coord(p,3)+' '+(s.b[p]?'classical '+s.b[p].n:'tentative links')});ui.table(['Move','Owner','Linked cells'],s.edges.map(e=>[e.n,e.who===1?'You':'House',coord(e.a,3)+' ↔ '+coord(e.b,3)]));ui.p('A tentative move is one edge joining two cells. Closing a cycle gives the opposing player an endpoint choice: that mark occupies the endpoint, and every other incident mark is forced to its other endpoint recursively. Classical cells no longer accept links. Three classical marks in a line win; simultaneous lines compare their largest move numbers, earlier wins.');history(ui,s)}};
export const linkedMarks={'double-written':linked};
