import{base,range,copy,shuffle,choose,finish,log,history,board,offset,orth,coord,sum}from'./core.mjs';
export function supplied(s,who){let root=s.capitals[who===1?0:1],seen=new Set();if(s.territory[root]!==who)return seen;let todo=[root];while(todo.length){let p=todo.pop();if(seen.has(p))continue;seen.add(p);for(let[d,e]of orth){let q=offset(p,d,e,5);if(q>=0&&!s.rocks.includes(q)&&s.territory[q]===who&&!seen.has(q))todo.push(q)}}return seen}
export function supplyMoves(s,who){return range(25).filter(p=>s.b[p]===who).flatMap(f=>orth.map(([dx,dy])=>offset(f,dx,dy,5)).filter(t=>t>=0&&!s.rocks.includes(t)&&s.b[t]!==who).map(t=>({f,t})))}
export function supplyRelays(s,who){let reach=supplied(s,who);return s.relays[who===1?0:1]?range(25).filter(t=>!s.rocks.includes(t)&&s.territory[t]!==who&&!s.b[t]&&orth.some(([dx,dy])=>reach.has(offset(t,dx,dy,5)))):[]}
export function supplyApply(s,m,who){let isolationAge=s.age[m.f];if(s.b[m.t]===-who)s.captured[who===1?0:1]++;s.b[m.f]=0;s.age[m.f]=0;s.b[m.t]=who;s.territory[m.t]=who;s.age[m.t]=isolationAge}
export function supplyMark(s,who,expire=false){let reach=supplied(s,who);for(let p of range(25))if(s.b[p]===who){if(reach.has(p))s.age[p]=0;else if(expire&&s.age[p]){s.b[p]=0;s.age[p]=0;s.attrition[who===1?0:1]++}else s.age[p]=1}}
function supplyEnd(s){let own=s.b.filter(v=>v===1).length,enemy=s.b.filter(v=>v===-1).length,win=s.territory[s.capitals[1]]===1||!enemy,loss=s.territory[s.capitals[0]]===-1||!own;if(win||loss||s.turn>=60){finish(s,!loss&&(win||s.turn>=60&&own>enemy),`Armies ${own} : ${enemy}; isolated losses ${s.attrition.join(' : ')}. ${win||loss?'A capital or its last army has fallen.':'Sixty turns settle surviving armies; ties defend the house.'}`,s.captured[0]*40+s.attrition[1]*40+s.territory.filter(v=>v===1).length*3+(!loss&&win?200:0));return true}return false}
function supplyValue(s,who){let reach=supplied(s,who),goal=s.capitals[who===1?1:0],x=goal%5,y=Math.floor(goal/5);return(s.territory[goal]===who?100000:0)+s.b.reduce((n,v,p)=>n+(v===who?40-(Math.abs(p%5-x)+Math.abs(Math.floor(p/5)-y))*5+(reach.has(p)?8:-30):v===-who?-40:0),0)+s.territory.filter(v=>v===who).length}
function supplyHouse(s){let options=supplyMoves(s,-1).map(m=>{let q=copy(s);supplyApply(q,m,-1);supplyMark(q,-1,true);return{m,q,v:supplyValue(q,-1)}}).concat(supplyRelays(s,-1).map(t=>{let q=copy(s);q.territory[t]=-1;q.relays[1]--;supplyMark(q,-1,true);return{relay:t,q,v:supplyValue(q,-1)}})),h=choose(s,options,x=>x.v);if(!h){finish(s,true,'House has no army or relay action.',250);return}s.b=h.q.b;s.territory=h.q.territory;s.age=h.q.age;s.relays=h.q.relays;s.attrition=h.q.attrition;s.captured=h.q.captured;s.turn++;s.selected=null;supplyMark(s,1);log(s,h.m?'House advances '+coord(h.m.f,5)+' → '+coord(h.m.t,5)+'.':'House repairs a relay at '+coord(h.relay,5)+'.');supplyEnd(s)}
const supply={stages:3,init(o){let s=base('capital-lines',o);s.n=5;s.b=Array(25).fill(0);s.territory=range(25).map(p=>p<10?-1:p>=15?1:0);s.capitals=[22,2];s.age=Array(25).fill(0);s.relays=[3,3];s.captured=[0,0];s.attrition=[0,0];s.rocks=o.stage===0?[]:o.stage===1?[10,14]:[11,13];let own=o.stage===0?[16,18,22]:o.stage===1?[15,17,23]:[16,19,22],enemy=o.stage===0?[2,6,8]:o.stage===1?[1,7,9]:[2,5,8];if(o.mode==='endless'){s.rocks=shuffle(s,[10,11,13,14]).slice(0,o.stage%3);own=shuffle(s,range(10).map(i=>i+15)).slice(0,3);enemy=shuffle(s,range(10)).slice(0,3)}own.forEach(p=>s.b[p]=1);enemy.forEach(p=>s.b[p]=-1);s.note='Advance an army or spend a relay to claim a cell. Supply follows orthogonally connected owned territory to your capital; marked isolated armies expire after your next action unless repaired.';return s},act(s,k){if(k.startsWith('square-')){let p=+k.slice(7);if(s.b[p]===1&&supplyMoves(s,1).some(m=>m.f===p)){s.selected=p;s.note=coord(p,5)+' selected. Choose an adjacent advance or attack.';return}let m=supplyMoves(s,1).find(m=>m.f===s.selected&&m.t===p);if(!m)return;supplyApply(s,m,1);log(s,'You advance '+coord(m.f,5)+' → '+coord(m.t,5)+'.')}else if(k.startsWith('relay-')){let t=+k.slice(6);if(!supplyRelays(s,1).includes(t))return;s.territory[t]=1;s.relays[0]--;log(s,'You claim relay '+coord(t,5)+'.')}else return;s.selected=null;supplyMark(s,1,true);supplyMark(s,-1);if(!supplyEnd(s))supplyHouse(s)},render(ui,s){let reach=supplied(s,1),ms=supplyMoves(s,1);ui.p(`Turn ${s.turn}/60 · Relays ${s.relays.join(' : ')} · Captures ${s.captured.join(' : ')} · Isolated attrition ${s.attrition.join(' : ')}.`);board(ui,s,{legal:range(25).filter(p=>ms.some(m=>m.f===p||m.f===s.selected&&m.t===p)),text:p=>s.rocks.includes(p)?'■':(s.capitals.includes(p)?'★':'')+(s.b[p]===1?'●':s.b[p]===-1?'○':s.territory[p]===1?'·+':s.territory[p]===-1?'·−':'·')+(s.age[p]?'!':''),detail:p=>coord(p,5)+' '+(s.age[p]?'isolated: repair this turn':reach.has(p)?'supplied territory':'')});ui.grid(4,'Relay repairs',{compact:true});for(let p of supplyRelays(s,1))ui.button('relay-'+p,'Claim relay '+coord(p,5));ui.p('Armies move one orthogonal cell; an enemy at the landing cell is captured. Landing claims territory permanently until recaptured; the vacated cell stays yours. Supply uses territory connectivity to your ★ capital. A disconnected army is marked ! and expires after its own next action if still disconnected. A relay claims an unoccupied adjacent frontier without moving an army. Capture the capital or last army.');history(ui,s)}};
export const supplyFront={'capital-lines':supply};
