import{base,range,copy,shuffle,choose,finish,log,history,cellFace}from'./core.mjs';
export const sockets=range(4).flatMap(l=>range((4-l)**2).map(i=>({l,x:i%(4-l),y:Math.floor(i/(4-l))})));
const socket=(l,x,y)=>sockets.findIndex(p=>p.l===l&&p.x===x&&p.y===y);
export const vaultSupport=p=>{let a=sockets[p];return a.l?[[0,0],[1,0],[0,1],[1,1]].map(([x,y])=>socket(a.l-1,a.x+x,a.y+y)):[]};
export const vaultAbove=p=>range(30).filter(q=>vaultSupport(q).includes(p));
export const vaultFree=(s,p)=>!vaultAbove(p).some(q=>s.b[q]);
export function vaultMoves(s,who){let empty=range(30).filter(p=>!s.b[p]&&vaultSupport(p).every(q=>s.b[q])),a=[];for(let t of empty){if(s.reserve[who===1?0:1])a.push({f:-1,t});for(let f of range(30))if(s.b[f]===who&&vaultFree(s,f)&&sockets[f].l<sockets[t].l&&!vaultSupport(t).includes(f))a.push({f,t})}return a}
export function vaultSquare(s,p,who){let a=sockets[p],n=4-a.l;return [[-1,-1],[0,-1],[-1,0],[0,0]].some(([dx,dy])=>{let x=a.x+dx,y=a.y+dy;return x>=0&&y>=0&&x<n-1&&y<n-1&&[[0,0],[1,0],[0,1],[1,1]].every(([u,v])=>s.b[socket(a.l,x+u,y+v)]===who)})}
export function vaultApply(s,m,who){if(m.f<0)s.reserve[who===1?0:1]--;else s.b[m.f]=0;s.b[m.t]=who;return vaultSquare(s,m.t,who)}
export function vaultReclaim(s,p,who){s.b[p]=0;s.reserve[who===1?0:1]++}
function vaultEnd(s,next){if(s.b[29]||!vaultMoves(s,next).length||s.turn>=80){let won=s.b[29]===1||!s.b[29]&&!vaultMoves(s,next).length&&next===-1;finish(s,won,s.b[29]?'The apex belongs to '+(won?'you.':'the house.'):s.turn>=80?'Eighty turns: the house holds the recycling defense.':'The next side has neither reserve placement nor supported promotion.',(won?250:0)+s.recycled[0]*10+s.b.reduce((n,v,p)=>n+(v===1?sockets[p].l*10:0),0));return true}return false}
function vaultValue(s,who){return(s.b[29]===who?100000:s.b[29]===-who?-100000:0)+(s.reserve[who===1?0:1]-s.reserve[who===1?1:0])*7+s.b.reduce((n,v,p)=>n+(v===who?1:v===-who?-1:0)*sockets[p].l*13,0)}
function vaultHouse(s){let hs=vaultMoves(s,-1).map(m=>{let q=copy(s),square=vaultApply(q,m,-1),re=[];if(square)for(let i=0;i<2;i++){let p=range(30).filter(p=>q.b[p]===-1&&vaultFree(q,p)&&p!==29).sort((a,b)=>sockets[a].l-sockets[b].l)[0];if(p===undefined)break;vaultReclaim(q,p,-1);re.push(p)}return{m,re,q,v:vaultValue(q,-1)}});let h=choose(s,hs,h=>h.v);if(!h){vaultEnd(s,-1);return}s.b=h.q.b;s.reserve=h.q.reserve;s.recycled[1]+=h.re.length;s.turn++;log(s,`House ${h.m.f<0?'places a reserve':'promotes a sphere'} at ${vaultLabel(h.m.t)}${h.re.length?' and recycles '+h.re.length:''}.`);vaultEnd(s,1)}
const vaultLabel=p=>{let a=sockets[p];return`Layer ${a.l+1} ${String.fromCharCode(65+a.x)}${a.y+1}`};
const vault={stages:3,init(o){let s=base('marble-vault',o);s.b=Array(30).fill(0);s.reserve=[15,15];s.recycled=[0,0];s.phase='build';s.left=0;let count=o.stage===0?8:o.stage===1?18:25,order=range(30);if(o.mode==='endless'){count=6+2*(o.stage%8);order=shuffle(s,range(16)).concat(range(14).map(p=>p+16))}for(let i=0;i<count;i++){let p=order[i],who=i%2?-1:1;if(vaultSupport(p).every(q=>s.b[q])){s.b[p]=who;s.reserve[who===1?0:1]--}}s.note='Place a reserve in a supported socket, or select an uncovered sphere for an upward promotion. Own squares permit recycling.';return s},act(s,k){if(s.phase==='reclaim'){if(k==='keep'){s.phase='build';s.left=0;if(!vaultEnd(s,-1))vaultHouse(s);return}if(k.startsWith('reclaim-')){let p=+k.slice(8);if(s.b[p]!==1||!vaultFree(s,p))return;vaultReclaim(s,p,1);s.recycled[0]++;s.left--;log(s,'You reclaim '+vaultLabel(p)+'.');if(!s.left){s.phase='build';if(!vaultEnd(s,-1))vaultHouse(s)}}return}if(k.startsWith('select-')){let p=+k.slice(7);if(vaultMoves(s,1).some(m=>m.f===p)){s.selected=p;s.note=vaultLabel(p)+' selected for promotion.'}return}let m=vaultMoves(s,1).find(m=>m.f<0?'place-'+m.t===k:`promote-${m.f}-${m.t}`===k);if(!m)return;let square=vaultApply(s,m,1);s.selected=null;log(s,'You '+(m.f<0?'place at ':'promote to ')+vaultLabel(m.t)+'.');if(vaultEnd(s,-1))return;if(square){s.phase='reclaim';s.left=2;s.note+=' An own square permits up to two uncovered own spheres to return to reserve.'}else vaultHouse(s)},render(ui,s){ui.p(`Turn ${s.turn}/80 · Reserves ${s.reserve.join(' : ')} · Recycled ${s.recycled.join(' : ')}. ${s.phase==='reclaim'?'Reclaim up to '+s.left+' uncovered spheres, or Keep.':'Build or promote.'}`);let ms=vaultMoves(s,1);for(let l=0;l<4;l++){ui.h('Layer '+(l+1));ui.grid(4-l,'Pyramid layer '+(l+1));for(let p of range(30).filter(p=>sockets[p].l===l)){let m=ms.find(m=>m.t===p&&(s.selected===null?m.f<0:m.f===s.selected)),select=ms.some(m=>m.f===p),can=s.phase==='reclaim'?s.b[p]===1&&vaultFree(s,p):!!m||select,key=s.phase==='reclaim'?'reclaim-'+p:m?m.f<0?'place-'+p:`promote-${m.f}-${p}`:'select-'+p,v=s.b[p],b=ui.button(key,vaultLabel(p)+' '+(v===1?'●':v===-1?'○':'·'),!can,s.selected===p);cellFace(b,String.fromCharCode(65+sockets[p].x)+(sockets[p].y+1),v===1?'●':v===-1?'○':'·',v)}}if(s.phase==='reclaim'){ui.group('Finish recycling');ui.button('keep','Keep remaining spheres')}ui.p('Upper sockets require all four spheres immediately below. A sphere supporting an occupied socket cannot move or be reclaimed. Promotion must move upward and cannot remove one of its own destination supports. An own 2×2 square permits up to two uncovered own spheres to return to reserve. The apex wins.');history(ui,s)}};
export const supportedVault={'marble-vault':vault};
