(async () => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('game'), ctx=canvas.getContext('2d');
canvas.width=960;canvas.height=880;ctx.scale(2,2);
const W=480,H=440, ink='#243c3b',cream='#f9f4df',coral='#d97863',green='#4f8072',gold='#e7b755';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rnd=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const circle=(x,y,r,fill,stroke)=>{ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=fill;ctx.fill();if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.stroke();}};
const rect=(x,y,w,h,fill,stroke)=>{ctx.fillStyle=fill;ctx.fillRect(x,y,w,h);if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);}};
const line=(x,y,a,b,color=ink,width=2)=>{ctx.strokeStyle=color;ctx.lineWidth=width;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(a,b);ctx.stroke();};
const text=(t,x,y,size=13,color=ink,align='center')=>{ctx.font=`${size>20?'bold ':''}${size}px ${size>20?'Arial':'monospace'}`;ctx.textAlign=align;ctx.fillStyle=color;ctx.fillText(t,x,y);};
function arrow(x,y,a,len,color=ink){line(x,y,x+Math.cos(a)*len,y+Math.sin(a)*len,color,2);circle(x+Math.cos(a)*len,y+Math.sin(a)*len,3,color);}
function ball(b,color=cream){circle(b.x,b.y,b.r||9,color,ink);circle(b.x-2,b.y-3,2,'#ffffff99');}
let meta;
try{const list=await (await fetch('games.json')).json();meta=list.find(g=>g.id===new URLSearchParams(location.search).get('game'))||list[0];}catch{ $('veil-title').textContent='The room could not open.';$('veil-copy').textContent='Please reload when the files are available.';return;}
document.title=`${meta.name} — Small Hours`;$('title').textContent=meta.name+'.';$('category').textContent=`Small Hours / ${meta.category}`;$('description').textContent=meta.description;$('tagline').textContent=meta.name;$('controls').textContent=meta.controls;canvas.setAttribute('aria-label',`${meta.name} game board. ${meta.controls}`);document.documentElement.style.setProperty('--accent',meta.accent);
meta.rules.forEach((r,i)=>{const li=document.createElement('li');const b=document.createElement('b');b.textContent=['Your little mission.','Find your technique.','Make it count.'][i];const p=document.createElement('p');p.textContent=r;li.append(b,p);$('rules').append(li);});
const record=SmallHours.record('small-hours-'+meta.id+'-best');
let mode='ready',d={},elapsed=0,score=0,last=null,frame,held=new Set(),notes='',game;
function say(t){$('message').textContent=t;}
function stats(progress,resource,label='Progress',resourceLabel='Status'){$('score').textContent=Math.floor(score);$('progress').textContent=progress;$('resource').textContent=resource;$('progress-label').textContent=label;$('resource-label').textContent=resourceLabel;}
function finish(win,copy){if(mode!=='playing')return;mode='ended';$('start').textContent='Round complete';held.clear();$('inputs').querySelectorAll('button').forEach(b=>{b.disabled=true;b.classList.remove('held');});$('pause').disabled=true;$('result').hidden=false;$('result-title').textContent=win?'A little victory.':'One more little try?';$('result-copy').textContent=copy+` Score: ${Math.floor(score)}.`;say(win?'Complete. Nicely played.':copy);record.save(Math.floor(score));$('again').focus({preventScroll:true});}
function court(){rect(18,18,444,404,'#ffffff28',ink);}
function aimControls(){return [['ArrowLeft','↶ Aim'],['ArrowRight','Aim ↷'],['ArrowDown','− Power'],['ArrowUp','+ Power'],['Space','Shoot']];}
function aiming(dt,min=-Math.PI,max=Math.PI){d.angle=clamp(d.angle+((held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0))*dt*1.4,min,max);d.power=clamp(d.power+((held.has('ArrowUp')?1:0)-(held.has('ArrowDown')?1:0))*dt*.65,.18,1);}
function aimPointer(x,y,phase,origin){if(phase==='down'||phase==='move'){d.angle=Math.atan2(y-origin.y,x-origin.x);d.power=clamp(Math.hypot(x-origin.x,y-origin.y)/210,.18,1);}if(phase==='up')game.press('Space');}
function reflectBall(b,lo=29,hi=451,top=29,bottom=411,bounce=.75){if(b.x-b.r<lo){b.x=lo+b.r;b.vx=Math.abs(b.vx)*bounce;}if(b.x+b.r>hi){b.x=hi-b.r;b.vx=-Math.abs(b.vx)*bounce;}if(b.y-b.r<top){b.y=top+b.r;b.vy=Math.abs(b.vy)*bounce;}if(b.y+b.r>bottom){b.y=bottom-b.r;b.vy=-Math.abs(b.vy)*bounce;}}
function collide(a,b,restitution=.9){let x=b.x-a.x,y=b.y-a.y,len=Math.hypot(x,y),r=a.r+b.r;if(len>=r)return false;if(!len){x=1;y=0;len=1;}x/=len;y/=len;let overlap=(r-len)/2;a.x-=x*overlap;a.y-=y*overlap;b.x+=x*overlap;b.y+=y*overlap;let v=(a.vx-b.vx)*x+(a.vy-b.vy)*y;if(v>0){let impulse=v*(1+restitution)/2;a.vx-=x*impulse;a.vy-=y*impulse;b.vx+=x*impulse;b.vy+=y*impulse;}return true;}
const games={
'velvet-snake':{
 controls:[['ArrowLeft','←'],['ArrowUp','↑'],['ArrowDown','↓'],['ArrowRight','→']],
 init(){d={snake:[{x:7,y:8},{x:6,y:8},{x:5,y:8}],dir:{x:1,y:0},next:{x:1,y:0},berry:null,tick:0,count:0};this.berry();},
 berry(){let free=[];for(let y=0;y<15;y++)for(let x=0;x<17;x++)if(!d.snake.some(s=>s.x===x&&s.y===y))free.push({x,y});d.berry=free[Math.floor(Math.random()*free.length)];},
 press(k){let map={ArrowLeft:{x:-1,y:0},ArrowRight:{x:1,y:0},ArrowUp:{x:0,y:-1},ArrowDown:{x:0,y:1}},v=map[k];if(v&&!(v.x===-d.dir.x&&v.y===-d.dir.y))d.next=v;},
 step(dt){d.tick+=dt;let interval=Math.max(.105,.185-d.count*.005);if(d.tick>=interval){d.tick-=interval;d.dir=d.next;let head={x:d.snake[0].x+d.dir.x,y:d.snake[0].y+d.dir.y},eat=head.x===d.berry.x&&head.y===d.berry.y;if(head.x<0||head.x>=17||head.y<0||head.y>=15||d.snake.slice(0,eat?undefined:-1).some(s=>s.x===head.x&&s.y===head.y)){finish(false,'Your snake found an edge. Twelve berries make a complete walk.');return;}d.snake.unshift(head);if(eat){d.count++;score+=100;say(`Berry ${d.count} of 12. A little longer, a little wiser.`);if(d.count===12)finish(true,'All twelve berries gathered. A very good garden walk.');else this.berry();}else d.snake.pop();}stats(`${d.count} / 12`,d.snake.length,'Berries','Length');notes='17 × 15 GARDEN · TURN EARLY';},
 draw(){rect(27,30,425,375,'#e3e6c8',ink);ctx.globalAlpha=.14;for(let x=0;x<17;x++)for(let y=0;y<15;y++)circle(39.5+x*25,42.5+y*25,1,ink);ctx.globalAlpha=1;d.snake.forEach((s,i)=>{rect(29+s.x*25,32+s.y*25,21,21,i?'#739265':ink);if(!i){circle(35+s.x*25,38+s.y*25,2,cream);circle(43+s.x*25,38+s.y*25,2,cream);}});circle(39.5+d.berry.x*25,42.5+d.berry.y*25,8,coral,ink);text('A SLOW LITTLE APPETITE',240,426,10);}
},
'rally-club':{
 controls:[['ArrowUp','↑ Paddle'],['ArrowDown','Paddle ↓']],
 init(){d={y:220,ai:220,p:0,c:0,ball:{x:240,y:220,vx:185,vy:80,r:8},delay:.7};},
 press(){},pointer(x,y){d.y=clamp(y,66,374);},
 step(dt){d.y=clamp(d.y+((held.has('ArrowDown')?1:0)-(held.has('ArrowUp')?1:0))*330*dt,66,374);let b=d.ball;if(d.delay>0){d.delay-=dt;}else{let target=b.vx>0?b.y:220;d.ai+=clamp(target-d.ai,-135*dt,135*dt);d.ai=clamp(d.ai,62,378);b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.y<30||b.y>410){b.y=clamp(b.y,30,410);b.vy*=-1;}for(const [x,y,side]of [[47,d.y,1],[433,d.ai,-1]])if(b.vx*side<0&&Math.abs(b.x-x)<12&&Math.abs(b.y-y)<51){b.x=x+side*13;let offset=(b.y-y)/49,speed=Math.min(380,Math.hypot(b.vx,b.vy)+17);b.vx=side*speed*Math.cos(offset*1.05);b.vy=speed*Math.sin(offset*1.05);say('Returned. Find the open side.');}if(b.x<0||b.x>480){if(b.x>480){d.p++;score+=200;}else d.c++;say(b.x>480?'Your point. Beautiful angle.':'A point to the house. Next serve.');if(d.p===5||d.c===5){finish(d.p===5,`Match complete: you ${d.p}, house ${d.c}.`);}else{d.ball={x:240,y:220,vx:(b.x>480?-1:1)*185,vy:rnd(-100,100),r:8};d.delay=.8;}}}stats(`${d.p} : ${d.c}`,'First to 5','Match','Goal');notes='YOU / LEFT · HOUSE / RIGHT';},
 draw(){court();ctx.setLineDash([5,9]);line(240,28,240,412,'#ffffff99');ctx.setLineDash([]);circle(240,220,48,'#ffffff12','#ffffff66');rect(39,d.y-44,12,88,ink);rect(429,d.ai-44,12,88,cream,ink);ball(d.ball);text('YOU',84,47,10);text('HOUSE',393,47,10);}
},
'paper-links':{
 controls:aimControls(),
 init(){d={level:0,strokes:0,angle:-Math.PI/2,power:.6,moving:false};this.course();},
 course(){let levels=[{ball:{x:100,y:350},cup:{x:375,y:91},walls:[{x:170,y:185,w:160,h:20}]},{ball:{x:80,y:360},cup:{x:390,y:90},walls:[{x:145,y:130,w:24,h:220},{x:285,y:45,w:24,h:245}]},{ball:{x:240,y:370},cup:{x:240,y:70},walls:[{x:90,y:235,w:220,h:20},{x:190,y:135,w:200,h:20}]}];let c=levels[d.level];d.ball={...c.ball,vx:0,vy:0,r:8};d.cup=c.cup;d.walls=c.walls;d.moving=false;d.angle=-Math.PI/2;},
 press(k){if(k==='Space'&&!d.moving){if(d.strokes>=12){finish(false,'Twelve strokes used. All three greens must fit within the round.');return;}d.strokes++;d.ball.vx=Math.cos(d.angle)*d.power*480;d.ball.vy=Math.sin(d.angle)*d.power*480;d.moving=true;}},
 pointer(x,y,p){if(!d.moving)aimPointer(x,y,p,d.ball);},
 step(dt){if(!d.moving)aiming(dt);let b=d.ball;if(d.moving){let ox=b.x,oy=b.y;b.x+=b.vx*dt;b.y+=b.vy*dt;reflectBall(b,28,452,28,412,.7);for(const w of d.walls)if(b.x+b.r>w.x&&b.x-b.r<w.x+w.w&&b.y+b.r>w.y&&b.y-b.r<w.y+w.h){if(ox+b.r<=w.x||ox-b.r>=w.x+w.w){b.x=ox;b.vx*=-.7;}else{b.y=oy;b.vy*=-.7;}}let f=Math.pow(.25,dt);b.vx*=f;b.vy*=f;if(dist(b,d.cup)<13&&Math.hypot(b.vx,b.vy)<190){score+=Math.max(50,450-d.strokes*15);d.level++;say(`Green ${d.level} sunk. A lovely little line.`);if(d.level===3){finish(true,`Three greens in ${d.strokes} strokes.`);}else if(d.strokes>=12){finish(false,'Twelve strokes used. The remaining greens will wait for your next round.');}else this.course();}else if(Math.hypot(b.vx,b.vy)<7){b.vx=b.vy=0;d.moving=false;if(d.strokes>=12)finish(false,'Twelve strokes used. Try a gentler bank off the walls.');}}stats(`${Math.min(3,d.level+1)} / 3`,`${d.strokes} / 12`,'Green','Strokes');notes=`POWER ${Math.round(d.power*100)}% · ${d.moving?'BALL IN MOTION':'AIM, THEN SHOOT'}`;},
 draw(){court();d.walls.forEach(w=>{rect(w.x+4,w.y+5,w.w,w.h,'#00000012');rect(w.x,w.y,w.w,w.h,green,ink);});circle(d.cup.x,d.cup.y,13,ink);line(d.cup.x,d.cup.y,d.cup.x,d.cup.y-38,ink);ctx.fillStyle=coral;ctx.beginPath();ctx.moveTo(d.cup.x,d.cup.y-38);ctx.lineTo(d.cup.x+24,d.cup.y-30);ctx.lineTo(d.cup.x,d.cup.y-23);ctx.fill();if(!d.moving)arrow(d.ball.x,d.ball.y,d.angle,30+d.power*85);ball(d.ball);}
},
'moon-basket':{
 controls:aimControls(),init(){d={angle:-.96,power:.65,shots:0,made:0,ball:{x:87,y:350,vx:0,vy:0,r:10},moving:false,hoop:{x:356,y:180}};},
 press(k){if(k==='Space'&&!d.moving){d.shots++;d.moving=true;d.ball={x:87,y:350,vx:Math.cos(d.angle)*d.power*560,vy:Math.sin(d.angle)*d.power*560,r:10};d.scored=false;}},
 pointer(x,y,p){if(!d.moving){aimPointer(x,y,p,{x:87,y:350});d.angle=clamp(d.angle,-1.5,-.15);}},
 step(dt){if(!d.moving)aiming(dt,-1.5,-.15);else{let b=d.ball,old=b.y;b.vy+=270*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x>397&&b.x<413&&b.y>110&&b.y<201){b.x=396;b.vx=-Math.abs(b.vx)*.6;}if(!d.scored&&b.vy>0&&old<d.hoop.y&&b.y>=d.hoop.y&&Math.abs(b.x-d.hoop.x)<24){d.scored=true;d.made++;score+=300;say('Nothing but evening air. Basket!');}if(b.y>425||b.x>490||b.x<-10){d.moving=false;d.ball={x:87,y:350,r:10};if(d.made>=3)finish(true,`Three baskets in ${d.shots} shots.`);else if(d.shots===8)finish(false,`${d.made} baskets from eight shots. Give the next one a little more arc.`);else if(!d.scored)say('A little wide. Adjust angle or power and try again.');}}stats(`${d.made} / 3`,`${d.shots} / 8`,'Baskets','Shots');notes=`ANGLE ${Math.round(-d.angle*180/Math.PI)}° · POWER ${Math.round(d.power*100)}%`;},
 draw(){circle(105,87,38,'#fff4d4');rect(22,390,436,30,'#ffffff44');line(18,391,462,391);line(411,110,411,390,ink,5);rect(398,107,10,96,cream,ink);line(329,180,383,180,coral,5);for(let i=0;i<5;i++)line(330+i*13,185,339+i*9,217,'#ffffff',2);line(339,217,375,217,'#ffffff',2);if(!d.moving)arrow(87,350,d.angle,30+d.power*100);ball(d.ball,coral);line(d.ball.x-7,d.ball.y,d.ball.x+7,d.ball.y,ink,1);}
},
'quiet-curl':{
 controls:aimControls(),init(){d={angle:-Math.PI/2,power:.58,stones:[],shots:0,moving:false,target:{x:240,y:110},settle:0};},
 press(k){if(k==='Space'&&!d.moving){d.shots++;d.stones.push({x:240,y:365,vx:Math.cos(d.angle)*d.power*390,vy:Math.sin(d.angle)*d.power*390,r:13});d.moving=true;d.settle=0;}},
 pointer(x,y,p){if(!d.moving){aimPointer(x,y,p,{x:240,y:365});d.angle=clamp(d.angle,-2.5,-.65);}},
 tally(){return d.stones.reduce((s,b)=>s+Math.max(0,Math.round(100-dist(b,d.target)*1.15)),0);},
 step(dt){if(!d.moving)aiming(dt,-2.5,-.65);else{for(const b of d.stones){b.x+=b.vx*dt;b.y+=b.vy*dt;reflectBall(b,48,432,27,413,.55);const sp=Math.hypot(b.vx,b.vy),next=Math.max(0,sp-95*dt);if(sp){b.vx*=next/sp;b.vy*=next/sp;}}for(let i=0;i<d.stones.length;i++)for(let j=i+1;j<d.stones.length;j++)collide(d.stones[i],d.stones[j],.85);if(d.stones.every(b=>Math.hypot(b.vx,b.vy)<1)){d.moving=false;score=this.tally();say(`Stone settled. ${score} points in the house.`);if(d.shots===3)finish(score>=120,`Three stones settled for ${score} points. The target was 120.`);}}stats(`${d.shots} / 3`,`${Math.floor(score)} / 120`,'Stones','Target');notes=`POWER ${Math.round(d.power*100)}% · ${d.moving?'LET IT GLIDE':'THE CENTER IS WORTH 100'}`;},
 draw(){rect(45,20,390,400,'#e3eee9',ink);line(240,25,240,414,'#93afb3',1);for(const [r,c]of [[86,'#83b5c4'],[59,cream],[31,coral],[8,ink]])circle(240,110,r,c);line(54,335,426,335,'#83b5c4',2);if(!d.moving&&d.shots<3){circle(240,365,13,cream,ink);arrow(240,365,d.angle,35+d.power*80);}d.stones.forEach((b,i)=>{ball(b,i%2?gold:coral);line(b.x-5,b.y-2,b.x+5,b.y-2,ink,4);});}
},
'kite-flight':{
 controls:[['Space','Hold to lift ↑']],init(){d={y:220,vy:0,gates:[],next:1.5,passed:0};},press(){},pointer(x,y,p){if(p==='down')held.add('Space');if(p==='up')held.delete('Space');},
 step(dt){d.vy=clamp(d.vy+(held.has('Space')?-370:255)*dt,-185,185);d.y+=d.vy*dt;d.next-=dt;if(d.next<=0){d.gates.push({x:510,y:rnd(140,300),passed:false});d.next=2.1;}for(const g of d.gates){g.x-=105*dt;if(!g.passed&&g.x<87){g.passed=true;d.passed++;score+=100;say(`Opening ${d.passed} of 10. Stay with the breeze.`);}if(Math.abs(g.x-110)<29&&(d.y<g.y-75||d.y>g.y+75)){finish(false,'Your kite brushed a rooftop. Try smaller, earlier corrections.');return;}}d.gates=d.gates.filter(g=>g.x>-50);if(d.y<15||d.y>425)finish(false,'Your kite left the safe air. Hold to rise; let go to glide.');if(d.passed>=10)finish(true,'Ten rooftops behind you. A very fine flight.');stats(`${d.passed} / 10`,`${Math.round(d.vy)}`,'Gates','Vertical speed');notes=held.has('Space')?'LIFTING · RELEASE TO GLIDE':'GLIDING · HOLD TO LIFT';},
 draw(){circle(375,74,35,cream);for(const g of d.gates){rect(g.x-16,0,32,g.y-86,'#6d9196',ink);rect(g.x-16,g.y+86,32,440-g.y-86,'#6d9196',ink);rect(g.x-23,g.y-96,46,10,ink);rect(g.x-23,g.y+86,46,10,ink);text('↕',g.x,g.y+4,18,green);}ctx.save();ctx.translate(110,d.y);ctx.rotate(d.vy/800);ctx.fillStyle=coral;ctx.beginPath();ctx.moveTo(0,-15);ctx.lineTo(17,0);ctx.lineTo(0,15);ctx.lineTo(-17,0);ctx.closePath();ctx.fill();ctx.strokeStyle=ink;ctx.stroke();line(0,-14,0,15);line(-16,0,16,0);ctx.restore();ctx.beginPath();ctx.moveTo(96,d.y+4);ctx.quadraticCurveTo(70,d.y+24,53,d.y+10);ctx.strokeStyle=ink;ctx.stroke();}
},
'soft-landing':{
 controls:[['ArrowLeft','↶ Tilt'],['Space','Hold thrust ↑'],['ArrowRight','Tilt ↷']],init(){d={x:140,y:90,vx:18,vy:7,angle:0,fuel:100,pad:{x:255,w:112}};},press(){},
 step(dt){d.angle=clamp(d.angle+((held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0))*1.4*dt,-1.2,1.2);d.vy+=34*dt;if(held.has('Space')&&d.fuel>0){d.vx+=Math.sin(d.angle)*75*dt;d.vy-=Math.cos(d.angle)*75*dt;d.fuel=Math.max(0,d.fuel-7*dt);}d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.x<15||d.x>465||d.y<15){finish(false,'The craft left the landing corridor. Keep the engine pointed into the drift.');return;}if(d.y>=384){const ok=d.x>d.pad.x+10&&d.x<d.pad.x+d.pad.w-10&&Math.abs(d.vx)<22&&d.vy<32&&Math.abs(d.angle)<.22;score=ok?Math.round(700+d.fuel*5):Math.round(elapsed*5);finish(ok,ok?'A soft landing. Cargo and coffee both intact.':'A rough touchdown. Aim for the pad, upright, below 32 vertical and 22 sideways speed.');}stats(`${Math.round(384-d.y)} m`,`${Math.round(d.fuel)}%`,'Altitude','Fuel');notes=`↓ ${Math.round(d.vy)} VERTICAL · ↔ ${Math.round(d.vx)} SIDEWAYS · TILT ${Math.round(d.angle*180/Math.PI)}°`;},
 draw(){for(let i=0;i<28;i++)circle((i*107+31)%480,(i*67+17)%330,1.4,'#fff9e5');ctx.fillStyle='#7e829a';ctx.beginPath();ctx.moveTo(0,395);for(let x=0;x<=480;x+=30)ctx.lineTo(x,395+(x>d.pad.x&&x<d.pad.x+d.pad.w?0:Math.sin(x)*9));ctx.lineTo(480,440);ctx.lineTo(0,440);ctx.fill();rect(d.pad.x,400,d.pad.w,9,cream,ink);for(let x=d.pad.x+7;x<d.pad.x+d.pad.w;x+=15)line(x,401,x+7,408,coral,4);text('SOFTLY DOES IT',d.pad.x+d.pad.w/2,429,10);ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.angle);ctx.fillStyle=cream;ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(14,12);ctx.lineTo(-14,12);ctx.closePath();ctx.fill();ctx.strokeStyle=ink;ctx.stroke();circle(0,0,5,'#83b5c4',ink);line(-10,8,-18,17);line(10,8,18,17);if(held.has('Space')&&d.fuel>0){ctx.fillStyle=coral;ctx.beginPath();ctx.moveTo(-6,13);ctx.lineTo(0,28);ctx.lineTo(6,13);ctx.fill();}ctx.restore();}
},
'star-tow':{
 controls:[['ArrowLeft','↶ Turn'],['Space','Thrust ↑'],['ArrowDown','Brake'],['ArrowRight','Turn ↷']],init(){d={x:240,y:220,vx:0,vy:0,angle:-Math.PI/2,pods:[{x:95,y:92},{x:387,y:113},{x:328,y:353}],cargo:false,delivered:0};},press(){},
 step(dt){d.angle+=((held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0))*2.3*dt;if(held.has('Space')){d.vx+=Math.cos(d.angle)*90*dt;d.vy+=Math.sin(d.angle)*90*dt;}const f=Math.exp(-(held.has('ArrowDown')?3.2:.18)*dt);d.vx*=f;d.vy*=f;const speed=Math.hypot(d.vx,d.vy);if(speed>170){d.vx*=170/speed;d.vy*=170/speed;}d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.x<13||d.x>467){d.x=clamp(d.x,13,467);d.vx*=-.6;}if(d.y<13||d.y>427){d.y=clamp(d.y,13,427);d.vy*=-.6;}if(!d.cargo){let i=d.pods.findIndex(p=>dist(p,d)<23);if(i>=0){d.pods.splice(i,1);d.cargo=true;say('Cargo attached. Coast back to the dock, then brake.');}}else if(Math.hypot(d.x-240,d.y-220)<32&&speed<70){d.cargo=false;d.delivered++;score+=300;say(`Delivery ${d.delivered} of 3. One little star back home.`);}if(d.delivered===3){score+=Math.floor((60-elapsed)*10);finish(true,'All three cargo pods home before the end of the shift.');}else if(elapsed>=60)finish(false,`Shift over. ${d.delivered} of three cargo pods delivered.`);stats(`${d.delivered} / 3`,`${Math.max(0,Math.ceil(60-elapsed))}s`,'Delivered','Shift');notes=`SPEED ${Math.round(speed)} · ${d.cargo?'CARGO ATTACHED / DOCK BELOW 70':'SEEK A GOLD POD'}`;},
 draw(){for(let i=0;i<35;i++)circle((i*109+23)%480,(i*83+9)%440,1,'#fff9e5');circle(240,220,36,'#ffffff35',cream);circle(240,220,21,'#ffffff33',cream);text('HOME',240,224,10);d.pods.forEach(p=>{rect(p.x-10,p.y-10,20,20,gold,ink);line(p.x-7,p.y,p.x+7,p.y);line(p.x,p.y-7,p.x,p.y+7);});if(d.cargo){line(d.x,d.y,d.x-Math.cos(d.angle)*28,d.y-Math.sin(d.angle)*28,cream);circle(d.x-Math.cos(d.angle)*29,d.y-Math.sin(d.angle)*29,8,gold,ink);}ctx.save();ctx.translate(d.x,d.y);ctx.rotate(d.angle);ctx.fillStyle=cream;ctx.beginPath();ctx.moveTo(16,0);ctx.lineTo(-11,10);ctx.lineTo(-7,0);ctx.lineTo(-11,-10);ctx.closePath();ctx.fill();ctx.strokeStyle=ink;ctx.stroke();if(held.has('Space'))line(-12,0,-23,0,coral,5);ctx.restore();}
},
'garden-guard':{
 controls:[],init(){d={cells:Array(9).fill(null),next:.3,caught:0,mistakes:0,spawn:0};},
 press(k){if(/^Digit[1-9]$/.test(k))this.hit(+k.slice(-1)-1);},
 pointer(x,y,p){if(p==='down'){let col=Math.floor((x-60)/120),row=Math.floor((y-35)/125);if(col>=0&&col<3&&row>=0&&row<3)this.hit(row*3+col);}},
 hit(i){const c=d.cells[i];if(!c)return;d.cells[i]=null;if(c.type==='pest'){d.caught++;score+=100;say(`Pest ${d.caught} of 12 sent on its way.`);}else{d.mistakes++;score=Math.max(0,score-50);say(`That was a flower. ${3-d.mistakes} mistakes left.`);}if(d.caught===12)finish(true,'Twelve pests caught. The garden says thank you.');else if(d.mistakes===3)finish(false,'Three flowers disturbed. Look for striped pests next time.');},
 step(dt){d.cells.forEach((c,i)=>{if(c){c.life-=dt;if(c.life<=0)d.cells[i]=null;}});d.next-=dt;if(d.next<=0){let free=d.cells.map((c,i)=>c?null:i).filter(i=>i!==null);if(free.length){let i=free[Math.floor(Math.random()*free.length)];d.cells[i]={type:d.spawn++%4===3?'flower':'pest',life:1.8};}d.next=.7;}if(elapsed>=30)finish(false,`Garden shift over. ${d.caught} pests caught; twelve completes the task.`);stats(`${d.caught} / 12`,`${3-d.mistakes} / 3`,'Pests','Care');notes=`${Math.max(0,Math.ceil(30-elapsed))}s LEFT · STRIPES = PEST / PETALS = FLOWER`;},
 draw(){for(let i=0;i<9;i++){let x=120+(i%3)*120,y=99+Math.floor(i/3)*125;circle(x,y+10,43,'#7f946c');circle(x,y+13,33,'#576d55');text(i+1,x,y+62,11);let c=d.cells[i];if(!c)continue;if(c.type==='pest'){circle(x,y,27,coral,ink);for(let o=-12;o<=12;o+=12)line(x+o,y-22,x+o,y+20,ink,4);circle(x-9,y-12,4,cream);circle(x+9,y-12,4,cream);}else{for(let j=0;j<6;j++)circle(x+Math.cos(j*Math.PI/3)*18,y+Math.sin(j*Math.PI/3)*18,12,cream,ink);circle(x,y,12,gold,ink);}ctx.strokeStyle=cream;ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,36,-Math.PI/2,-Math.PI/2+c.life/1.8*Math.PI*2);ctx.stroke();}}
},
'beat-post':{
 controls:[['ArrowLeft','A / ←'],['ArrowDown','S / ↓'],['ArrowRight','D / →']],init(){d={notes:Array.from({length:24},(_,i)=>({lane:(i*7+Math.floor(i/4))%3,time:2+i*.65,done:false})),hit:0,miss:0,flash:[0,0,0]};},
 press(k){let lane={ArrowLeft:0,ArrowDown:1,ArrowRight:2}[k];if(lane===undefined)return;d.flash[lane]=.18;let n=d.notes.filter(n=>!n.done&&n.lane===lane).sort((a,b)=>Math.abs(a.time-elapsed)-Math.abs(b.time-elapsed))[0];if(n&&Math.abs(n.time-elapsed)<=.19){n.done=true;d.hit++;score+=Math.abs(n.time-elapsed)<.075?100:65;say(Math.abs(n.time-elapsed)<.075?'Perfect delivery.':'Delivered. Keep the rhythm.');}else{score=Math.max(0,score-15);say('A little early or late. Wait for the delivery line.');}},
 step(dt){d.flash=d.flash.map(t=>Math.max(0,t-dt));for(let n of d.notes)if(!n.done&&elapsed>n.time+.2){n.done=true;d.miss++;say('Missed delivery. The next one is coming.');}if(d.miss>=8)finish(false,'Eight deliveries missed. Follow the line and try a gentler rhythm.');else if(d.notes.every(n=>n.done))finish(d.hit>=18,`${d.hit} of 24 notes delivered. Eighteen makes a complete round.`);stats(`${d.hit} / 24`,`${8-d.miss}`,'Delivered','Misses left');notes='HIT WHEN THE ENVELOPE MEETS THE GOLD LINE';},
 draw(){for(let i=0;i<3;i++){rect(69+i*116,25,108,385,d.flash[i]?'#fff4d4':'#ffffff24',ink);text(['A / ←','S / ↓','D / →'][i],123+i*116,397,15);}line(70,340,408,340,gold,7);d.notes.forEach(n=>{let y=340-(n.time-elapsed)*165;if(!n.done&&y>-20&&y<380){let x=123+n.lane*116;rect(x-31,y-13,62,26,cream,ink);line(x-30,y-12,x,y+4,ink);line(x,y+4,x+30,y-12,ink);}});}
},
'pinball-pocket':{
 controls:[['ArrowLeft','Left flipper'],['Space','Launch'],['ArrowRight','Right flipper']],init(){d={ball:{x:240,y:330,vx:0,vy:0,r:9},balls:3,waiting:true,bumpers:[{x:160,y:125,r:28,cool:0},{x:318,y:125,r:28,cool:0},{x:240,y:210,r:30,cool:0}],hit:0};},
 press(k){if(k==='Space'&&d.waiting){d.waiting=false;d.ball={x:240,y:325,vx:held.has('ArrowLeft')&&!held.has('ArrowRight')?-120:held.has('ArrowRight')&&!held.has('ArrowLeft')?120:rnd(-110,110),vy:-430,r:9};}},
 step(dt){const steps=Math.max(1,Math.ceil(dt/.008));for(let i=0;i<steps&&mode==='playing';i++)this.physics(dt/steps);},
 physics(dt){d.bumpers.forEach(p=>p.cool=Math.max(0,p.cool-dt));if(!d.waiting){let b=d.ball;b.vy+=290*dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<48||b.x>432){b.x=clamp(b.x,48,432);b.vx*=-.88;}if(b.y<40){b.y=40;b.vy=Math.abs(b.vy)*.8;}for(let p of d.bumpers){let len=dist(b,p);if(len<p.r+b.r){let nx=len?(b.x-p.x)/len:0,ny=len?(b.y-p.y)/len:-1;b.x=p.x+nx*(p.r+b.r+.3);b.y=p.y+ny*(p.r+b.r+.3);let dot=b.vx*nx+b.vy*ny;if(dot<0){b.vx-=2*dot*nx;b.vy-=2*dot*ny;}b.vx+=nx*85;b.vy+=ny*85;if(!p.cool){score+=100;p.cool=.16;d.hit++;say('Bumper lit. +100.');}}}
 // Flippers are actual raised segments: collision projects ball against each segment.
 for(const [ax,bx,key]of [[110,215,'ArrowLeft'],[370,265,'ArrowRight']]){let raised=held.has(key),ay=365,by=raised?322:390,dx=bx-ax,dy=by-ay,t=clamp(((b.x-ax)*dx+(b.y-ay)*dy)/(dx*dx+dy*dy),0,1),px=ax+t*dx,py=ay+t*dy,len=Math.hypot(b.x-px,b.y-py);if(len<16&&b.vy>0){let nx=(b.x-px)/(len||1),ny=(b.y-py)/(len||1);if(ny>0)ny=-ny;b.x=px+nx*16;b.y=py+ny*16;if(raised){b.vy=-390-t*90;b.vx=(ax<240?1:-1)*(70+t*130);}else{b.vy=-Math.abs(b.vy)*.38;b.vx+=(ax<240?1:-1)*45;}}}
 if(b.y>450){d.balls--;d.waiting=true;d.ball={x:240,y:330,r:9,vx:0,vy:0};say('Ball drained. Press Launch for the next one.');if(!d.balls)finish(false,`Three balls played. ${score} points; 1,000 lights the whole table.`);}if(score>=1000)finish(true,'Ten bumpers lit. A pocket full of points.');}stats(`${Math.floor(score)} / 1000`,d.balls,'Target','Balls');notes=d.waiting?'PRESS LAUNCH · HOLD FLIPPERS TO SAVE A LOW BALL':'LEFT / RIGHT FLIPPERS · SIDE GUTTERS STAY OPEN';},
 draw(){rect(35,20,410,414,'#ffffff25',ink);ctx.strokeStyle=coral;ctx.lineWidth=7;ctx.beginPath();ctx.arc(240,173,182,Math.PI,Math.PI*2);ctx.stroke();d.bumpers.forEach(p=>{circle(p.x,p.y,p.r,p.cool?cream:coral,ink);circle(p.x,p.y,p.r-8,'#ffffff44',ink);text('100',p.x,p.y+4,10);});for(const[ax,bx,key]of[[110,215,'ArrowLeft'],[370,265,'ArrowRight']]){line(ax,365,bx,held.has(key)?322:390,ink,16);line(ax,365,bx,held.has(key)?322:390,cream,10);circle(ax,365,8,gold,ink);}text('DRAIN',240,425,10);ball(d.ball);}
},
'rope-skip':{
 controls:[['Space','Jump ↑']],init(){d={height:0,vy:0,next:2.2,period:1.65,cleared:0,miss:0,landed:0,flash:0};},
 press(k){if(k==='Space'&&d.height===0&&d.landed<=0){d.vy=270;d.height=.1;}},
 step(dt){if(d.height>0){d.vy-=760*dt;d.height+=d.vy*dt;if(d.height<=0){d.height=0;d.vy=0;d.landed=.12;}}d.landed=Math.max(0,d.landed-dt);d.flash=Math.max(0,d.flash-dt);d.next-=dt;if(d.next<=0){if(d.height>20){d.cleared++;score+=100;say(`Clean skip ${d.cleared} of 16.`);}else{d.miss++;d.flash=.4;say(`Caught the rope. ${3-d.miss} catches left.`);}d.period=Math.max(1.05,1.65-d.cleared*.025);d.next+=d.period;if(d.cleared===16)finish(true,'Sixteen clean skips. A little rhythm in your step.');else if(d.miss===3)finish(false,'Three catches. Jump just before the rope reaches the ground.');}stats(`${d.cleared} / 16`,3-d.miss,'Skips','Catches left');notes=`NEXT SWEEP ${d.next.toFixed(1)}s · ${d.height>0?'IN THE AIR':d.landed>0?'LANDING':'READY TO JUMP'}`;},
 draw(){rect(25,365,430,52,'#ffffff33');line(35,366,445,366);let phase=1-d.next/d.period;ctx.strokeStyle=d.flash?coral:green;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(240,294,135,Math.max(7,Math.abs(Math.cos(phase*Math.PI))*81),0,0,Math.PI*2);ctx.stroke();let y=346-d.height;circle(240,y-45,17,cream,ink);line(240,y-27,240,y-3,ink,12);line(238,y-8,220,y+14,ink,6);line(242,y-8,260,y+14,ink,6);line(237,y-24,198,295,ink,5);line(243,y-24,282,295,ink,5);circle(240,92,37,'#ffffff44',ink);ctx.strokeStyle=coral;ctx.lineWidth=6;ctx.beginPath();ctx.arc(240,92,30,-Math.PI/2,-Math.PI/2+Math.max(0,phase)*Math.PI*2);ctx.stroke();text('HOP',240,97,12);}
},
 'table-bowls':{
 controls:aimControls(),init(){d={angle:-Math.PI/2,power:.65,shots:0,moving:false,balls:[{x:240,y:340,vx:0,vy:0,r:10,cue:true},{x:135,y:145,vx:0,vy:0,r:12,color:coral},{x:240,y:125,vx:0,vy:0,r:12,color:gold},{x:345,y:145,vx:0,vy:0,r:12,color:cream}],pockets:[{x:49,y:49},{x:240,y:42},{x:431,y:49},{x:49,y:391},{x:240,y:398},{x:431,y:391}],potted:0};},
 press(k){if(k==='Space'&&!d.moving){const b=d.balls.find(b=>b.cue);b.vx=Math.cos(d.angle)*d.power*540;b.vy=Math.sin(d.angle)*d.power*540;d.shots++;d.moving=true;}},
 pointer(x,y,p){if(!d.moving)aimPointer(x,y,p,d.balls.find(b=>b.cue));},
 step(dt){if(!d.moving)aiming(dt);else{for(let b of [...d.balls]){b.x+=b.vx*dt;b.y+=b.vy*dt;if(d.pockets.some(p=>dist(b,p)<22)){if(b.cue){b.x=240;b.y=340;b.vx=b.vy=0;say('Cue scratched. It returns to the start.');}else{d.balls.splice(d.balls.indexOf(b),1);d.potted++;score+=250;say(`Ball ${d.potted} of 3 pocketed. A satisfying little clack.`);}continue;}reflectBall(b,42,438,42,398,.8);let f=Math.pow(.24,dt);b.vx*=f;b.vy*=f;if(Math.hypot(b.vx,b.vy)<5)b.vx=b.vy=0;}for(let i=0;i<d.balls.length;i++)for(let j=i+1;j<d.balls.length;j++)collide(d.balls[i],d.balls[j],.95);if(d.potted===3){score+=Math.max(0,8-d.shots)*50;finish(true,`A clear table in ${d.shots} shots.`);}else if(d.balls.every(b=>Math.hypot(b.vx,b.vy)<5)){d.moving=false;if(d.shots===8)finish(false,`Eight shots used; ${d.potted} balls pocketed.`);}}stats(`${d.potted} / 3`,`${d.shots} / 8`,'Pocketed','Shots');notes=`POWER ${Math.round(d.power*100)}% · ${d.moving?'WAIT FOR THE TABLE TO SETTLE':'AIM THE WHITE CUE BALL'}`;},
 draw(){rect(22,22,436,396,'#4f7164',ink);rect(42,42,396,356,'#89b6a0',ink);d.pockets.forEach(p=>circle(p.x,p.y,21,ink));d.balls.forEach(b=>ball(b,b.cue?cream:b.color));if(!d.moving){const b=d.balls.find(b=>b.cue);arrow(b.x,b.y,d.angle,30+d.power*80,cream);}}
 },
 'balance-beam':{
 controls:[['ArrowLeft','Tilt left ↙'],['ArrowRight','Tilt right ↘']],init(){d={x:0,v:0,angle:0,breeze:0};},press(){},
 step(dt){const input=(held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0);d.angle+=(clamp(input*.24+d.x*.0012,-.32,.32)-d.angle)*Math.min(1,dt*5);d.breeze=Math.sin(elapsed*1.3)*15+Math.sin(elapsed*2.7)*8;d.v+=(Math.sin(d.angle)*160+d.breeze)*dt;d.v*=Math.exp(-.35*dt);d.x+=d.v*dt;score=Math.floor(elapsed*30);if(Math.abs(d.x)>166)finish(false,'The marble slipped beyond the beam. Small corrections work wonders.');else if(elapsed>=30){score=1000;finish(true,'Thirty seconds of balance. A steady little triumph.');}stats(`${Math.min(30,Math.floor(elapsed))} / 30s`,`${Math.round(d.v)}`,'Balance','Drift');notes=`BREEZE ${d.breeze>0?'→':'←'} · LEAN AGAINST THE DRIFT`;},
 draw(){circle(370,95,34,cream);ctx.fillStyle=green;ctx.beginPath();ctx.moveTo(240,253);ctx.lineTo(177,358);ctx.lineTo(303,358);ctx.closePath();ctx.fill();ctx.strokeStyle=ink;ctx.stroke();line(70,365,410,365,ink,3);ctx.save();ctx.translate(240,244);ctx.rotate(d.angle);rect(-174,-4,348,12,cream,ink);for(let x=-150;x<=150;x+=30)line(x,-4,x,-11,ink,1);circle(d.x,-17,13,coral,ink);ctx.restore();arrow(240,90,d.breeze>0?0:Math.PI,Math.abs(d.breeze)*2,green);text('EASY DOES IT',240,407,11);}
 },
 'harbor-catch':{
 controls:[['ArrowLeft','← Boat'],['Space','Hold cast / release reel'],['ArrowRight','Boat →']],
 init(){d={x:240,hook:72,phase:'idle',casts:0,caught:0,attached:null,fish:[{x:80,y:145,vx:45},{x:320,y:210,vx:-38},{x:190,y:278,vx:54},{x:410,y:335,vx:-30}]};},
 press(k){if(k==='Space'&&d.phase==='idle'){d.casts++;d.phase='lower';d.hook=73;d.snagged=false;say('Line away. Release to reel; meet a fish along its path.');}},
 pointer(x){if(d.phase==='idle')d.x=clamp(x,40,440);},
 step(dt){for(const fish of d.fish){fish.x+=fish.vx*dt;if(fish.x<35||fish.x>445){fish.x=clamp(fish.x,35,445);fish.vx*=-1;}}if(d.phase==='idle')d.x=clamp(d.x+((held.has('ArrowRight')?1:0)-(held.has('ArrowLeft')?1:0))*230*dt,40,440);else{if(d.phase==='lower'&&!held.has('Space'))d.phase='reel';d.hook+=(d.phase==='lower'?110:-145)*dt;if(!d.attached&&!d.snagged){const i=d.fish.findIndex(f=>Math.hypot(f.x-d.x,f.y-d.hook)<21);if(i>=0){d.attached=d.fish.splice(i,1)[0];d.phase='reel';say('A bite! Reeling your catch aboard.');}}if(d.hook>=376){d.hook=376;d.phase='reel';d.snagged=true;say('Snagged the seabed. Reeling an empty line.');}if(d.hook<=72){d.hook=72;d.phase='idle';if(d.attached){d.caught++;score+=300+Math.floor(d.attached.y/10);d.attached=null;say(`Fish ${d.caught} of 3 aboard. Choose the next depth.`);}else say('An empty hook. Shift the boat and try a different depth.');if(d.caught===3)finish(true,`Three fish landed in ${d.casts} casts. A patient little supper.`);else if(d.casts>=8)finish(false,`Eight casts used. ${d.caught} fish landed; three fills the basket.`);}}stats(`${d.caught} / 3`,`${d.casts} / 8`,'Fish landed','Casts');notes=d.phase==='idle'?'MOVE THE BOAT · HOLD CAST TO LOWER THE HOOK':`${d.phase==='lower'?'LOWERING / RELEASE TO REEL':'REELING IN'} · DEPTH ${Math.round(d.hook-72)}`;},
 draw(){rect(0,78,480,362,'#66959e');for(let y=144;y<370;y+=65){ctx.setLineDash([3,8]);line(18,y,462,y,'#c0d7d255',1);ctx.setLineDash([]);}circle(408,34,17,cream);rect(0,401,480,39,'#61756a');for(let x=18;x<480;x+=63)circle(x,407,12,'#455d59');for(const fish of [...d.fish,...(d.attached?[{x:d.x,y:d.hook,vx:1}]:[])]){ctx.save();ctx.translate(fish.x,fish.y);ctx.scale(fish.vx>0?1:-1,1);ctx.fillStyle=coral;ctx.beginPath();ctx.ellipse(0,0,17,9,0,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ink;ctx.stroke();ctx.beginPath();ctx.moveTo(-14,0);ctx.lineTo(-25,-9);ctx.lineTo(-25,9);ctx.closePath();ctx.fill();ctx.stroke();circle(9,-2,2,ink);ctx.restore();}line(d.x,66,d.x,d.hook,cream,1.5);ctx.strokeStyle=cream;ctx.lineWidth=3;ctx.beginPath();ctx.arc(d.x+5,d.hook,5,0,Math.PI);ctx.stroke();ctx.fillStyle=cream;ctx.beginPath();ctx.moveTo(d.x-30,57);ctx.lineTo(d.x+30,57);ctx.lineTo(d.x+20,73);ctx.lineTo(d.x-20,73);ctx.closePath();ctx.fill();ctx.strokeStyle=ink;ctx.stroke();line(d.x,57,d.x,27,ink,3);ctx.fillStyle=gold;ctx.beginPath();ctx.moveTo(d.x+3,28);ctx.lineTo(d.x+23,52);ctx.lineTo(d.x+3,52);ctx.fill();text('A PATIENT LITTLE SUPPER',240,428,10,cream);}
 }
};
game=games[meta.id];
function clearHeld(){held.clear();$('inputs').querySelectorAll('button').forEach(b=>b.classList.remove('held'));}
function reset(){cancelAnimationFrame(frame);mode='ready';elapsed=0;score=0;last=null;clearHeld();game.init();$('result').hidden=true;$('veil').hidden=false;$('veil-tag').textContent='A LITTLE ROOM FOR PLAY';$('veil-title').textContent=meta.name+'.';$('veil-copy').textContent=meta.description;$('start').disabled=false;$('start').textContent='Start playing';$('pause').disabled=true;$('pause').textContent='Pause';$('inputs').querySelectorAll('button').forEach(b=>b.disabled=true);stats('Ready','—');$('instrument').textContent=meta.controls;say(meta.rules[0]);draw();}
function start(){if(mode!=='ready')return;mode='playing';$('veil').hidden=true;$('start').disabled=true;$('start').textContent='Round in play';$('pause').disabled=false;$('inputs').querySelectorAll('button').forEach(b=>b.disabled=false);last=null;canvas.focus({preventScroll:true});frame=requestAnimationFrame(tick);}
function pause(){if(mode==='playing'){mode='paused';last=null;cancelAnimationFrame(frame);clearHeld();$('veil').hidden=false;$('veil-tag').textContent='TAKE A BREATHER';$('veil-title').textContent='A moment, held.';$('veil-copy').textContent='Everything waits for you. Resume when you’re ready.';$('pause').textContent='Resume';$('inputs').querySelectorAll('button').forEach(b=>b.disabled=true);say('Paused. Press Resume or P to continue.');}else if(mode==='paused'){mode='playing';last=null;$('veil').hidden=true;$('pause').textContent='Pause';$('inputs').querySelectorAll('button').forEach(b=>b.disabled=false);say(meta.rules[0]);canvas.focus({preventScroll:true});frame=requestAnimationFrame(tick);}}
function draw(){ctx.clearRect(0,0,W,H);ctx.fillStyle=meta.accent;ctx.fillRect(0,0,W,H);game.draw();}
function tick(now){if(mode!=='playing')return;const dt=last===null?0:Math.min((now-last)/1000,.04);last=now;elapsed+=dt;game.step(dt);$('instrument').textContent=notes;draw();if(mode==='playing')frame=requestAnimationFrame(tick);}
function press(k){if(mode!=='playing')return;if(['paper-links','moon-basket','quiet-curl','table-bowls'].includes(meta.id)&&!d.moving){if(k==='ArrowLeft')d.angle-=.045;if(k==='ArrowRight')d.angle+=.045;if(k==='ArrowUp')d.power=clamp(d.power+.025,.18,1);if(k==='ArrowDown')d.power=clamp(d.power-.025,.18,1);if(meta.id==='moon-basket')d.angle=clamp(d.angle,-1.5,-.15);if(meta.id==='quiet-curl')d.angle=clamp(d.angle,-2.5,-.65);}game.press(k);}
for(const[key,label]of game.controls){const b=document.createElement('button');b.textContent=label;b.dataset.key=key;b.setAttribute('aria-label',label);b.disabled=true;b.addEventListener('pointerdown',e=>{if(mode!=='playing')return;e.preventDefault();b.setPointerCapture(e.pointerId);held.add(key);b.classList.add('held');press(key);});const up=()=>{held.delete(key);b.classList.remove('held');};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('lostpointercapture',up);b.addEventListener('click',e=>{if(e.detail===0)press(key);});$('inputs').append(b);}
const alias={KeyW:'ArrowUp',KeyA:'ArrowLeft',KeyS:'ArrowDown',KeyD:'ArrowRight'};
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||e.target.closest('input,select,textarea'))return;const k=alias[e.code]||e.code;if(k==='KeyP'||k==='Escape'){e.preventDefault();if(!e.repeat)pause();return;}if(e.code==='Space'&&e.target.closest('#start,#again,#pause,#restart,a'))return;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space'].includes(k)||/^Digit[1-9]$/.test(k)){e.preventDefault();if(mode==='playing'){held.add(k);if(!e.repeat)press(k);}}});
document.addEventListener('keyup',e=>held.delete(alias[e.code]||e.code));
let dragging=false;function point(e){let r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*W/r.width,y:(e.clientY-r.top)*H/r.height};}
canvas.addEventListener('pointerdown',e=>{if(mode!=='playing')return;e.preventDefault();dragging=true;canvas.setPointerCapture(e.pointerId);canvas.focus({preventScroll:true});let p=point(e);game.pointer?.(p.x,p.y,'down');});canvas.addEventListener('pointermove',e=>{if(dragging&&mode==='playing'){let p=point(e);game.pointer?.(p.x,p.y,'move');}});canvas.addEventListener('pointerup',e=>{if(dragging&&mode==='playing'){let p=point(e);game.pointer?.(p.x,p.y,'up');}dragging=false;});canvas.addEventListener('pointercancel',()=>{dragging=false;clearHeld();});
$('start').addEventListener('click',start);$('pause').addEventListener('click',pause);$('restart').addEventListener('click',reset);$('again').addEventListener('click',()=>{reset();start();});window.addEventListener('blur',()=>{if(mode==='playing')pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&mode==='playing')pause();});reset();document.body.dataset.gameId=meta.id;document.body.dataset.gameReady='true';
})();
