/* Missing, failed, stale and legacy evidence never becomes a current pass. */
const fs=require('node:fs'),path=require('node:path'),E=require('./evidence.cjs');
const inventory=JSON.parse(fs.readFileSync(path.join(E.root,'inventory.json'))),runs=[];
for(const id of Object.keys(E.suites)){const file=path.join(E.root,'coverage','suite-runs',id+'.json');let run;try{run=JSON.parse(fs.readFileSync(file));}catch{runs.push({suite:id,current:false,reason:'missing or unreadable suite result'});continue;}
const current=E.validRun(run,id);
runs.push({...run,current,reason:current?null:run.passed?'source changed or unsupported provenance':'suite not passed',evidence:'coverage/suite-runs/'+id+'.json'});}
const games=inventory.games.map(game=>{const relevant=runs.filter(r=>E.gameIds(r.suite).includes(game.id)),good=relevant.filter(r=>r.current);const has=key=>good.some(r=>E.scopeForGame(r.suite,r,game.id)[key]);return {id:game.id,name:game.name,url:game.url,status:has('desktopCompletion')&&has('mobileViewportCompletion')?'verified':'unverified',fullCompletionDesktop:has('desktopCompletion'),fullCompletionMobileViewport:has('mobileViewportCompletion'),touchGameplayCompletion:has('touchGameplayCompletion'),evidence:good.map(r=>r.evidence),methods:good.map(r=>({suite:r.suite,...E.scopeForGame(r.suite,r,game.id)})),unverifiedSuites:relevant.filter(r=>!r.current).map(r=>({suite:r.suite,reason:r.reason}))};});
const report={schemaVersion:2,generatedAt:new Date().toISOString(),total:games.length,verified:games.filter(g=>g.status==='verified').length,desktopCompletions:games.filter(g=>g.fullCompletionDesktop).length,mobileViewportCompletions:games.filter(g=>g.fullCompletionMobileViewport).length,touchGameplayCompletions:games.filter(g=>g.touchGameplayCompletion).length,limits:'Current successful suite runs only; source content hashes exclude generated coverage and documentation. Mobile viewport completion is not touch-only completion or iPhone/Safari certification. Solvers may inspect hidden answers and use virtual time. Competitive strategy terminal results can be losses. Live route/reset checks and ordinary-play samples are separate.',games};
fs.writeFileSync(path.join(E.root,'coverage/index.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({total:report.total,verified:report.verified,desktop:report.desktopCompletions,mobileViewport:report.mobileViewportCompletions,touchGameplay:report.touchGameplayCompletions}));if(report.verified!==report.total)process.exitCode=1;
