/* Shared evidence schema: hashes content, not commit IDs or generated reports. */
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..');
const original={browser:['signal-run'],'signal-mobile-complete':['signal-run'],collection:['double-take','good-order','pocket-orbit'],afterglow:['afterglow'],'lantern-lines':['lantern-lines'],'tide-pool':['tide-pool'],'word-weave':['word-weave'],'sky-stack':['sky-stack'],'pebble-post':['pebble-post']};
const rooms=['spatial-room','logic-room','number-room','word-room','strategy-room','arcade-room'];
const helpers={afterglow:['afterglow-engine'], 'spatial-room':['gear-depth','balance-depth'],'word-room':['word-room-edges']};
const suites=Object.fromEntries([...Object.entries(original),...rooms.map(id=>[id,[id]])].map(([id,dirs])=>[id,{id,dirs,tests:[id,...(helpers[id]||[])]}]));
function filesIn(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?filesIn(path.join(dir,e.name)):[path.join(dir,e.name)]);}
function fingerprint(id){const suite=suites[id];if(!suite)throw Error('Unknown suite '+id);const files=[...suite.dirs.flatMap(d=>filesIn(path.join(root,d))),...fs.readdirSync(root).filter(n=>/\.(html|css|js|json)$/.test(n)&&!['progress.json'].includes(n)).map(n=>path.join(root,n)),...suite.tests.map(n=>path.join(root,'tests',n+'.cjs')),__filename,path.join(__dirname,'run-suite.cjs')].sort();const h=crypto.createHash('sha256');for(const file of files)h.update(path.relative(root,file)+'\0').update(fs.readFileSync(file)).update('\0');return {sha256:h.digest('hex'),files:files.map(f=>path.relative(root,f))};}
function gameIds(id){return original[id]||JSON.parse(fs.readFileSync(path.join(root,id,'games.json'))).map(g=>g.id);}
function scope(id){const mobileOnly=id==='signal-mobile-complete',desktopOnly=id==='browser';return {desktopCompletion:!mobileOnly,mobileViewportCompletion:!desktopOnly,touchGameplayCompletion:!desktopOnly&&!['arcade-room','afterglow','word-room','number-room'].includes(id),touchControlSmoke:!mobileOnly,completionMeans:id==='strategy-room'?'terminal result; competitive losses count':'winning full progression',method:['browser','signal-mobile-complete','collection','afterglow','logic-room','arcade-room'].includes(id)?'solver-directed UI with read-only injected observations; timing suites control virtual time':'scripted UI; curated answers or board solvers',mobileMethod:id==='arcade-room'?'keyboard/mouse solver in mobile viewport; separate touch smoke':id==='afterglow'?'DOM-set aiming with touch launch and upgrades':id==='word-room'?'touch buttons mixed with programmatic text entry':id==='number-room'?'touch controls mixed with keyboard/range actions':desktopOnly?'touch smoke only':'touch gameplay with scripted navigation/solvers'};}
const partialOptions=['GAMES','GAME_IDS','GAME','EDGE_ONLY','ONLY_GAME','RESUME','SKIP_DEEP'];
function runtimeFingerprint(id){const files=fingerprint(id).files.filter(f=>!f.startsWith('tests/')&&!f.startsWith('tools/'));const h=crypto.createHash('sha256');for(const f of files)h.update(f+'\0').update(fs.readFileSync(path.join(root,f))).update('\0');return {sha256:h.digest('hex'),files};}
function validRun(run,id){const start=Date.parse(run.startedAt),finish=Date.parse(run.finishedAt),served=run.servedRuntime,verified=Date.parse(served?.verifiedAt),expected=runtimeFingerprint(id);return run.schemaVersion===2&&run.suite===id&&run.passed===true&&run.status==='passed'&&run.exitCode===0&&run.sourceUnchanged===true&&Number.isFinite(start)&&Number.isFinite(finish)&&finish>=start&&run.browser?.engine==='Chromium'&&typeof run.browser.version==='string'&&run.browser.version.trim().length>0&&run.browser.version!=='unknown'&&run.source?.sha256===fingerprint(id).sha256&&served?.passed===true&&served.sha256===expected.sha256&&served.fileCount===expected.files.length&&/^https?:\/\//.test(served.baseURL)&&verified>=start&&verified<=finish;}
module.exports={root,suites,fingerprint,runtimeFingerprint,gameIds,scope,validRun,partialOptions};
