'use strict';
const requested=new URLSearchParams(location.search).get('game');
const game=SPATIAL_GAMES.find(g=>g.id===requested)||SPATIAL_GAMES[0];
const $=id=>document.getElementById(id), B=$('board');
$('title').textContent=game.name;document.title=game.name+' · Small Hours';$('description').textContent=game.description;$('symbol').textContent=game.symbol;$('rules').innerHTML=game.rules.map(r=>'<li><p>'+r+'</p></li>').join('');
const record=SmallHours.record('small-hours-'+game.id,true);let s,moves,done,notice;
const btn=(text,action,cls='chip',label=text)=>`<button class="${cls}" data-action="${action}" aria-label="${String(label).replace(/<[^>]*>/g,'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}">${text}</button>`;
const grid=(n,items)=>`<div class="matrix" style="grid-template-columns:repeat(${n},1fr)">${items.join('')}</div>`;
const caption=t=>'<p class="caption">'+t+'</p>';
const tray=a=>'<div class="tray">'+a.join('')+'</div>';
const patterns=[[0,1,4,5],[1,2,5,6],[4,5,8,9],[6,7,10,11],[0,4,8,12]];
const edges=[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]];
const points=[[50,35],[170,20],[290,35],[290,180],[170,210],[50,180]];
const roverWalls=[3,8,13,15,16,18];
function reset(){moves=0;done=false;notice='Explore the arrangement. Every move is reversible by restarting.';s={};switch(game.id){case'tangram-dock':s={selected:0,placed:[null,null,null]};break;case'mirror-mail':s={mirrors:[0,1,1,1,0]};break;case'bilateral':s={marks:[]};break;case'shadow-turn':s={turns:[0,0,0,0],round:0};break;case'loose-ends':s={order:[0,2,4,1,5,3],selected:null};break;case'gear-train':s={gears:[8,24,12,16],selected:null};break;case'measured-pour':s={jugs:[0,0]};break;case'rover-script':s={program:[],pos:20,dir:0,parcel:false};break;case'paper-trail':s={layers:Array.from({length:8},(_,i)=>[i+1])};break;case'pigment-lab':s={drops:[0,0,0],round:0};break;case'cable-loom':s={path:[0]};break;case'balance-mobile':s={weights:[1,2,3,4],hooks:[null,null,null,null],selected:null};break;case'crate-crane':s={stacks:[['A','B','A'],['B','A','B'],[]],selected:null};break;case'orbit-transfer':s={pos:0,seen:[],fuel:8};break;case'stamp-studio':s={stamps:[],round:0};break;}$('result').hidden=true;render();}
function win(){done=true;notice='Solved — every condition met. Your best move count is saved when possible.';record.save(Math.max(1,moves));$('result').hidden=false;}
function render(){let h='';switch(game.id){
case'tangram-dock':{let cells=Array(12).fill('');s.placed.forEach((p,i)=>{if(p!==null)shape(i).forEach(([x,y])=>cells[p+y*4+x]=String.fromCharCode(65+i));});h=caption('Dock · 4 × 3 / choose cargo, then its top-left square')+grid(4,cells.map((v,i)=>btn(v||'·','place:'+i,'cell'+(v?' on':''),'Dock square '+(i+1)+(v?', piece '+v:''))))+tray(['A: ┏','B: ┓','C: ■'].map((t,i)=>btn(t+'<br>'+stampIcon(shape(i).map(([x,y])=>x+y*4)),'piece:'+i,'chip'+(s.selected===i?' on':''))));break;}
case'mirror-mail':{const mirrors={1:0,11:1,13:2,8:3,9:4};h=caption('Entrance → row 1 · Delivery ↓ column 5')+grid(5,Array.from({length:20},(_,i)=>i in mirrors?btn(s.mirrors[mirrors[i]]?'\\':'/','mirror:'+mirrors[i],'cell target'+((s.beam||[]).includes(i)?' lit':''),'Mirror '+(mirrors[i]+1)+': '+(s.mirrors[mirrors[i]]?'backslash':'slash')):'<div class="cell fixed '+((s.beam||[]).includes(i)?'lit':'')+'">'+(i===0?'→':i===19?'↓':'·')+'</div>'))+tray([btn('Send beam','beam')]);break;}
case'bilateral':{const left=[0,2,5,6,8,9,13,14];h=caption('Reflect across the central seam')+grid(8,Array.from({length:32},(_,i)=>{let r=Math.floor(i/8),c=i%8;return c<4?'<div class="cell '+(left.includes(r*4+c)?'on':'fixed')+'">'+(left.includes(r*4+c)?'●':'·')+'</div>':btn(s.marks.includes(i)?'●':'·','mark:'+i,'cell'+(s.marks.includes(i)?' on':''),'Reflection row '+(r+1)+' column '+(c-3));}));break;}
case'shadow-turn':h=caption('Study '+(s.round+1)+'/3 · Turn each large cutout until it matches its small reference shadow.')+grid(2,s.turns.map((t,i)=>btn(silhouette(t,i,false)+silhouette([[1,3,2,1],[3,2,1,2],[2,1,3,3]][s.round][i],i,true),'turn:'+i,'cell','Rotate silhouette '+(i+1))));break;
case'loose-ends':h=caption('Select two numbered points to swap their locations')+'<svg class="diagram" viewBox="0 0 340 240" aria-hidden="true">'+edges.map(([a,b])=>{let p=points[s.order[a]],q=points[s.order[b]];return `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="#d08755" stroke-width="4"/>`;}).join('')+s.order.map((p,i)=>`<circle cx="${points[p][0]}" cy="${points[p][1]}" r="16" fill="#e5d7bf"/><text x="${points[p][0]-5}" y="${points[p][1]+5}">${i+1}</text>`).join('')+'</svg>'+tray(s.order.map((p,i)=>btn('Point '+(i+1),'node:'+i,'chip'+(s.selected===i?' on':''))));break;
case'gear-train':h=caption('Compound train: A drives B · B shares shaft with C · C drives D')+grid(4,s.gears.map((v,i)=>btn('⚙<br>'+v+'<small><br>'+['A','B','C','D'][i]+'</small>','gear:'+i,'cell'+(s.selected===i?' on':''),'Socket '+['A','B','C','D'][i]+', '+v+' teeth')))+caption('Output / input = (A ÷ B) × (C ÷ D). Two meshes preserve direction.')+'<p class="large">'+(s.gears[0]*s.gears[2]/s.gears[1]/s.gears[3]).toFixed(2)+'× → target 1.00×</p>';break;
case'measured-pour':h='<div class="swatches">'+s.jugs.map((v,i)=>`<div><div class="jug"><div class="water" style="height:${v/[3,5][i]*100}%">${v} L</div></div>${caption(['3L jug','5L jug'][i])}</div>`).join('')+'</div>'+tray([btn('Fill 3L','fill:0'),btn('Fill 5L','fill:1'),btn('Empty 3L','empty:0'),btn('Empty 5L','empty:1'),btn('3L → 5L','pour:0'),btn('5L → 3L','pour:1')]);break;
case'rover-script':h=caption('Rover starts facing ↑. Collect ◆ then finish at ⚑.')+grid(5,Array.from({length:25},(_,i)=>'<div class="cell '+(roverWalls.includes(i)?'wall':'fixed')+'">'+(s.pos===i?['↑','→','↓','←'][s.dir]:i===4?'⚑':i===12&&!s.parcel?'◆':roverWalls.includes(i)?'■':'·')+'</div>'))+'<div class="program">'+(s.program.join(' ')||'Your route…')+'</div>'+tray([btn('Forward','command:F'),btn('Turn left','command:L'),btn('Turn right','command:R'),btn('Undo','uncommand'),btn('Clear','clear'),btn('Run route','run')]);break;
case'paper-trail':h=caption('Target top → bottom: 6, 3, 2, 7, 8, 1, 4, 5')+tray(s.layers.map(a=>'<div class="chip">'+a.join('<br>')+'</div>'))+tray([btn('Fold left → right','fold:L'),btn('Fold right → left','fold:R')]);break;
case'pigment-lab':{let rgb=a=>`rgb(${255-a[0]*45},${255-a[1]*45},${255-a[2]*45})`;h=caption('Batch '+(s.round+1)+'/3 · '+['Cyan = yellow + 1 · magenta = cyan + 1 · 6 drops total','Cyan = yellow + 1 · yellow = magenta + 1 · 6 drops total','Yellow = 2 × magenta · magenta = cyan + 1 · 7 drops total'][s.round])+'<div class="swatches"><div><div class="swatch" style="background:'+rgb(s.drops)+'"></div>'+caption('Your mixture')+'</div><div><div class="swatch" style="background:'+rgb([[2,3,1],[3,1,2],[1,2,4]][s.round])+'"></div>'+caption('Reference')+'</div></div>'+tray(s.drops.map((v,i)=>'<div>'+caption(['Cyan','Magenta','Yellow'][i]+': '+v)+btn('−','drop:'+i+':-1','chip','Remove '+['cyan','magenta','yellow'][i])+btn('+','drop:'+i+':1','chip','Add '+['cyan','magenta','yellow'][i])+'</div>'));break;}
case'cable-loom':h=caption('Visit all 16 pegs, from S to E, without revisiting.')+grid(4,Array.from({length:16},(_,i)=>btn(i===0?'S':i===12?'E':s.path.includes(i)?s.path.indexOf(i)+1:'·','peg:'+i,'cell'+(s.path.includes(i)?' on':''),'Peg '+i)))+tray([btn('Undo segment','undopeg')]);break;
case'balance-mobile':h=caption('Left torque '+torque(0)+' · Right torque '+torque(1))+grid(4,s.hooks.map((v,i)=>btn((v===null?'＋':v+' kg')+'<small><br>'+['L ×3','L ×1','R ×1','R ×3'][i]+'</small>','hook:'+i,'cell','Hook '+(i+1))))+tray(s.weights.map(v=>btn(v+' kg','weight:'+v,'chip'+(s.selected===v?' on':''))));break;
case'crate-crane':h=caption('Goal: AAA on left · BBB on right · spare empty')+grid(3,s.stacks.map((a,i)=>btn('<div class="stack">'+a.map(v=>'<span class="crate">'+v+'</span>').join('')+'</div><small>'+['Left','Right','Spare'][i]+'</small>','stack:'+i,'cell'+(s.selected===i?' on':''),'Stack '+(i+1)+': '+(a.join(',')||'empty'))));break;
case'orbit-transfer':{let routes=[[1,2],[3,0],[1,4],[2,5],[3,5],[]];h=caption('Arrows: A→B,C · B→D,A · C→B,E · D→C,F · E→D,F. Dock F.')+'<p class="large">'+String.fromCharCode(65+s.pos)+' · '+s.fuel+' fuel</p>'+caption('Beacons at B, D, E: '+s.seen.map(i=>String.fromCharCode(65+i)).join(' / '))+tray(routes[s.pos].map(i=>btn('Travel to '+String.fromCharCode(65+i),'travel:'+i)));break;}
case'stamp-studio':{const target=[...new Set([[0,3],[1,2],[2,4]][s.round].flatMap(i=>patterns[i]))];const ink=[...new Set(s.stamps.flatMap(i=>patterns[i]))];const print=a=>grid(4,Array.from({length:16},(_,i)=>'<div class="cell '+(a.includes(i)?'on':'fixed')+'"></div>'));h=caption('Edition '+(s.round+1)+'/3 · Your print (left) · Target (right)')+'<div class="print">'+print(ink)+print(target)+'</div>'+tray(patterns.map((p,i)=>btn('Stamp '+(i+1)+'<br>'+stampIcon(p),'stamp:'+i,'chip'+(s.stamps.includes(i)?' on':''))));break;}}
B.innerHTML=h;$('moves').textContent=moves;$('status').textContent=done?'Solved':'Explore';$('message').textContent=notice;if(done)B.querySelectorAll('button').forEach(b=>b.disabled=true);}
function silhouette(turn,i,small){const sets=[[0,3,6,7],[0,1,4,7],[1,3,4,6],[0,1,2,5]];return '<svg width="'+(small?35:70)+'" height="80" viewBox="0 0 90 90" aria-hidden="true"><g transform="rotate('+turn*90+' 45 45)">'+sets[i].map(n=>'<rect x="'+(n%3*25+8)+'" y="'+(Math.floor(n/3)*25+8)+'" width="23" height="23" rx="3" fill="'+(small?'#ad7553':'#253e40')+'"/>').join('')+'</g></svg>';}
function traceBeam(){s.beam=[];let x=-1,y=0,dx=1,dy=0;const mirrors={'1,0':0,'1,2':1,'3,2':2,'3,1':3,'4,1':4};for(let step=0;step<30;step++){x+=dx;y+=dy;if(x<0||x>=5||y<0||y>=4)return x===4&&y===4;s.beam.push(y*5+x);const m=mirrors[x+','+y];if(m!==undefined){[dx,dy]=s.mirrors[m]?[dy,dx]:[-dy,-dx];}}return false;}
function stampIcon(p){return '<svg width=48 height=48 viewBox="0 0 40 40" aria-hidden=true>'+Array.from({length:16},(_,i)=>'<rect x="'+i%4*10+'" y="'+Math.floor(i/4)*10+'" width=8 height=8 fill="'+(p.includes(i)?'#b9784d':'#ddd1b8')+'"/>').join('')+'</svg>';}
function shape(i){return [[[0,0],[1,0],[0,1],[0,2]],[[0,0],[1,0],[1,1],[1,2]],[[0,0],[1,0],[0,1],[1,1]]][i];}
function torque(side){return s.hooks.reduce((a,v,i)=>a+((side===0?i<2:i>=2)?(v||0)*[3,1,1,3][i]:0),0);}
function crossing(){const orient=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);return edges.some(([a,b],i)=>edges.slice(i+1).some(([c,d])=>new Set([a,b,c,d]).size===4&&orient(points[s.order[a]],points[s.order[b]],points[s.order[c]])*orient(points[s.order[a]],points[s.order[b]],points[s.order[d]])<0&&orient(points[s.order[c]],points[s.order[d]],points[s.order[a]])*orient(points[s.order[c]],points[s.order[d]],points[s.order[b]])<0));}
function action(raw){if(done)return;let [a,b,c]=raw.split(':'),i=Number(b);let changed=true;notice='Keep exploring. Restart is always available.';switch(a){case'piece':if(s.placed[i]!==null)s.placed[i]=null;s.selected=i;break;case'place':{let p=s.selected;if(p===null){notice='Choose a cargo piece first.';changed=false;break;}let cells=shape(p).map(([x,y])=>[i%4+x,Math.floor(i/4)+y]);let used=[];s.placed.forEach((v,j)=>{if(v!==null&&j!==p)shape(j).forEach(([x,y])=>used.push(v+x+y*4));});if(cells.some(([x,y])=>x>=4||y>=3||used.includes(x+y*4))){notice='That piece crosses a wall or another piece.';changed=false;}else{s.placed[p]=i;s.selected=null;}break;}
case'mirror':s.mirrors[i]^=1;s.beam=[];break;case'beam':s.delivered=traceBeam();if(s.delivered)notice='Delivery confirmed.';else notice='The beam misses the delivery port. Try another mirror arrangement.';break;
case'mark':s.marks.includes(i)?s.marks.splice(s.marks.indexOf(i),1):s.marks.push(i);break;case'turn':s.turns[i]=(s.turns[i]+1)%4;break;
case'node':case'gear':if(s.selected===null){s.selected=i;changed=false;}else{let list=a==='node'?s.order:s.gears;[list[i],list[s.selected]]=[list[s.selected],list[i]];s.selected=null;}break;
case'fill':s.jugs[i]=[3,5][i];break;case'empty':s.jugs[i]=0;break;case'pour':{let n=Math.min(s.jugs[i],[3,5][1-i]-s.jugs[1-i]);s.jugs[i]-=n;s.jugs[1-i]+=n;break;}
case'command':if(s.program.length<30)s.program.push(b);else notice='30-command memory full. Undo or clear.';changed=false;break;case'uncommand':s.program.pop();changed=false;break;case'clear':s.program=[];changed=false;break;
case'run':s.pos=20;s.dir=0;s.parcel=false;for(let cmd of s.program){if(cmd==='L')s.dir=(s.dir+3)%4;else if(cmd==='R')s.dir=(s.dir+1)%4;else{let x=s.pos%5+[0,1,0,-1][s.dir],y=Math.floor(s.pos/5)+[-1,0,1,0][s.dir];if(x<0||x>4||y<0||y>4||roverWalls.includes(y*5+x)){notice='Route stopped at a wall. Edit the program and run again.';break;}s.pos=y*5+x;if(s.pos===12)s.parcel=true;}}break;
case'fold':if(s.layers.length===1){notice='The strip is fully folded. Restart to try a different sequence.';changed=false;break;}let half=s.layers.length/2,L=s.layers.slice(0,half),R=s.layers.slice(half);s.layers=b==='L'?R.map((v,j)=>[...L[half-1-j]].reverse().concat(v)):L.map((v,j)=>[...R[half-1-j]].reverse().concat(v));break;
case'drop':s.drops[i]=Math.max(0,Math.min(5,s.drops[i]+Number(c)));break;
case'peg':{let last=s.path.at(-1);if(!s.path.includes(i)&&Math.abs(last%4-i%4)+Math.abs(Math.floor(last/4)-Math.floor(i/4))===1){s.path.push(i);}else{notice='Choose an unused peg beside the cable tip.';changed=false;}break;}case'undopeg':if(s.path.length>1)s.path.pop();else changed=false;break;
case'weight':s.hooks=s.hooks.map(v=>v===i?null:v);s.selected=i;changed=false;break;case'hook':if(s.selected!==null&&s.hooks[i]===null){s.hooks[i]=s.selected;s.selected=null;}else{notice='Choose a weight and an empty hook.';changed=false;}break;
case'stack':if(s.selected===null){if(s.stacks[i].length)s.selected=i;changed=false;}else{if(i!==s.selected&&s.stacks[i].length<3)s.stacks[i].push(s.stacks[s.selected].pop());else{notice='Choose a different stack with space.';changed=false;}s.selected=null;}break;
case'travel':if(s.fuel>0){s.pos=i;s.fuel--;if([1,3,4].includes(i)&&!s.seen.includes(i))s.seen.push(i);if((i===5&&s.seen.length<3)||s.fuel===0)notice='Route ended without every beacon. Restart to chart a better course.';}else changed=false;break;
case'stamp':s.stamps.includes(i)?s.stamps.splice(s.stamps.indexOf(i),1):s.stamps.push(i);break;
}if(changed)moves++;if(!done&&solved()){if(['shadow-turn','pigment-lab','stamp-studio'].includes(game.id)&&s.round<2){s.round++;if(s.turns)s.turns=[0,0,0,0];if(s.drops)s.drops=[0,0,0];if(s.stamps)s.stamps=[];notice='Beautiful work. Study '+(s.round+1)+' of 3 is ready.';}else win();}if(game.id==='paper-trail'&&s.layers.length===1&&!done)notice='Folded, but the layers differ. Restart and try another fold order.';render();}
function solved(){switch(game.id){case'mirror-mail':return !!s.delivered;case'tangram-dock':return s.placed.every(v=>v!==null);case'bilateral':return [...s.marks].sort((a,b)=>a-b).join()===[5,7,13,14,22,23,29,30].join();case'shadow-turn':return s.turns.join()===[[1,3,2,1],[3,2,1,2],[2,1,3,3]][s.round].join();case'loose-ends':return !crossing();case'gear-train':return s.gears[0]*s.gears[2]===s.gears[1]*s.gears[3];case'measured-pour':return s.jugs[1]===4;case'rover-script':return s.pos===4&&s.parcel;case'paper-trail':return s.layers.length===1&&s.layers[0].join()==='6,3,2,7,8,1,4,5';case'pigment-lab':return s.drops.join()===[[2,3,1],[3,1,2],[1,2,4]][s.round].join();case'cable-loom':return s.path.length===16&&s.path.at(-1)===12;case'balance-mobile':return s.hooks.every(v=>v!==null)&&torque(0)===torque(1);case'crate-crane':return s.stacks[0].join()==='A,A,A'&&s.stacks[1].join()==='B,B,B';case'orbit-transfer':return s.pos===5&&s.seen.length===3;case'stamp-studio':return [...new Set(s.stamps.flatMap(i=>patterns[i]))].sort((a,b)=>a-b).join()===[...new Set([[0,3],[1,2],[2,4]][s.round].flatMap(i=>patterns[i]))].sort((a,b)=>a-b).join();default:return false;}}
B.addEventListener('click',e=>{let b=e.target.closest('button[data-action]');if(b){const key=b.dataset.action;action(key);const next=B.querySelector('[data-action="'+key+'"]');if(next&&!next.disabled)next.focus({preventScroll:true});}});$('restart').onclick=reset;$('again').onclick=reset;reset();document.body.dataset.gameId=game.id;document.body.dataset.gameReady='true';
