'use strict';
const requested=new URLSearchParams(location.search).get('game');
const game=SPATIAL_GAMES.find(g=>g.id===requested)||SPATIAL_GAMES[0];
const $=id=>document.getElementById(id), B=$('board');
$('title').textContent=game.name;document.title=game.name+' · Small Hours';$('description').textContent=game.description;$('symbol').textContent=game.symbol;$('rules').innerHTML=game.rules.map(r=>'<li><p>'+r+'</p></li>').join('');
const record=SmallHours.record('small-hours-'+game.id,true);let s,moves,done,notice;
const btn=(text,action,cls='chip',label=text)=>`<button class="${cls}" data-action="${action}" aria-label="${String(label).replace(/<[^>]*>/g,'').replace(/&/g,'&amp;').replace(/"/g,'&quot;')}">${text}</button>`;
const grid=(n,items)=>`<div class="matrix" style="grid-template-columns:repeat(${n},1fr)">${items.join('')}</div>`;
const caption=t=>'<p class="caption">'+t+'</p>';
const tray=a=>'<div class="tray">'+a.join('')+'</div>';
const patterns=[[0,1,4,5],[1,2,5,6],[4,5,8,9],[6,7,10,11],[0,4,8,12]];
const edges=[[0,1],[1,2],[2,3],[3,4],[4,5],[5,0]];
const points=[[50,35],[170,20],[290,35],[290,180],[170,210],[50,180]];
const roverWalls=[3,8,13,15,16,18];
const silhouetteSets=[[0,3,6,7],[0,1,4,7],[1,3,4,6],[0,1,2,5]];
const silhouetteTargets=[[1,3,2,1],[3,2,1,2],[2,1,3,3]];
const pointPositions=['upper left','top center','upper right','lower right','bottom center','lower left'];
// Text geometry uses the same cells and rotations as the artwork.
function describeSquares(cells,n){return Array.from({length:n},(_,r)=>{const cols=Array.from({length:n},(_,c)=>c).filter(c=>cells.includes(r*n+c)).map(c=>c+1);return cols.length?'row '+(r+1)+' columns '+cols.join(', '):null;}).filter(Boolean).join('; ')||'none';}
function silhouetteCells(turn,i){return silhouetteSets[i].map(cell=>{let x=cell%3,y=Math.floor(cell/3);for(let k=0;k<turn;k++)[x,y]=[2-y,x];return y*3+x;});}
function silhouetteDescription(turn,i){return 'Cutout '+(i+1)+'. On a 3 by 3 grid, current squares: '+describeSquares(silhouetteCells(turn,i),3)+'. Target squares: '+describeSquares(silhouetteCells(silhouetteTargets[s.round][i],i),3)+'. Activate to rotate clockwise.';}
function necklaceDescription(){return 'Necklace. '+s.order.map((p,i)=>'Point '+(i+1)+' at '+pointPositions[p]).join('; ')+'. Cords join '+edges.map(([a,b])=>(a+1)+' to '+(b+1)).join(', ')+'. '+(crossing()?'Some cords cross.':'No cords cross.');}


// Authored gear studies: adjacent bench exchanges make shaft placement a planning puzzle.
const gearStudies=[
 {name:'The double reducer',initial:[16,24,12,8],ratios:[[1,2],[1,2]],locked:[],brief:'Two half-speed meshes. Find which gears belong together, then arrange the bench.'},
 {name:'The anchored input',initial:[12,30,24,16,8,18],ratios:[[2,3],[1,2],[4,5]],locked:[0],brief:'Socket A is bolted in place. Route the other five gears around a fixed input.'},
 {name:'The mixed transmission',initial:[30,18,36,12,8,24],ratios:[[2,3],[3,2],[3,5]],locked:[],brief:'The middle mesh speeds up. Meet every shaft ratio, not just the final output.'}
];
function gearState(round,base=0){return {round,gears:[...gearStudies[round].initial],selected:null,gearHistory:[],gearCleared:false,gearBase:base};}
function gearFraction(n,d){let a=n,b=d;while(b){const t=a%b;a=b;b=t;}return n/a+(d/a===1?'':'/'+d/a);}
function gearMatches(){return gearStudies[s.round].ratios.every(([n,d],i)=>s.gears[i*2]*d===s.gears[i*2+1]*n);}

const pigmentStudies=[
 {shape:[[0,0],[1,0],[2,0]],target:[{at:0,turn:0},{at:1,turn:1},{at:8,turn:0}]},
 {shape:[[0,0],[0,1],[1,1]],target:[{at:0,turn:0},{at:1,turn:1},{at:5,turn:2}]},
 {shape:[[0,0],[1,0],[2,0],[1,1]],target:[{at:4,turn:0},{at:1,turn:1},{at:8,turn:0}]}
];
function pigmentState(round){return {round,inks:Array.from({length:3},()=>({at:null,turn:0})),selected:0};}
function inkShape(turn){let shape=pigmentStudies[s.round].shape.map(p=>[...p]);for(let n=0;n<turn;n++)shape=shape.map(([x,y])=>[-y,x]);const minX=Math.min(...shape.map(p=>p[0])),minY=Math.min(...shape.map(p=>p[1]));return shape.map(([x,y])=>[x-minX,y-minY]);}
function inkPrint(inks){const cells=Array(16).fill('');inks.forEach((ink,i)=>{if(ink.at!==null)inkShape(ink.turn).forEach(([x,y])=>{cells[ink.at+x+y*4]+='CMY'[i];});});return cells;}
function inkColor(code){return `rgb(${code.includes('C')?65:247},${code.includes('M')?65:239},${code.includes('Y')?65:216})`;}
function pigmentRender(){const actual=inkPrint(s.inks),target=inkPrint(pigmentStudies[s.round].target);let actualGrid=grid(4,actual.map((code,i)=>btn(code||'·','inkplace:'+i,'cell','Print row '+(Math.floor(i/4)+1)+' column '+(i%4+1)+': '+(code||'blank')).replace('<button','<button style="background:'+inkColor(code)+';color:'+(code.length>1?'white':'#172828')+'"')));let targetGrid=grid(4,target.map((code,i)=>'<div class="cell" aria-label="Target row '+(Math.floor(i/4)+1)+' column '+(i%4+1)+': '+(code||'blank')+'" style="background:'+inkColor(code)+';color:'+(code.length>1?'white':'#172828')+'">'+(code||'·')+'</div>'));return caption('Print study '+(s.round+1)+'/3 · '+['Straight strips','Elbow stencils','Branching stencils'][s.round])+'<div class="ink-target">'+caption('REFERENCE PRINT')+targetGrid+'</div>'+tray(s.inks.map((ink,i)=>btn(['C · Cyan','M · Magenta','Y · Yellow'][i]+'<br>'+stampIcon(inkShape(ink.turn).map(([x,y])=>x+y*4)),'inkselect:'+i,'chip'+(s.selected===i?' on':''))))+caption('Selected '+['cyan','magenta','yellow'][s.selected]+' · Tap a square for the stencil’s top-left corner.')+actualGrid+tray([btn('Rotate selected ↻','inkrotate'),btn('Lift selected','inklift')])+caption('C / M / Y identify inks. Combined letters show overlap; CMY is black. Match every cell, including blank paper.');}


const balanceStudies=[
 {name:'A quiet symmetry',arms:[-3,-1,1,3],weights:[1,2,3,4],fixed:{}},
 {name:'The anchored span',arms:[-4,-2,-1,1,3,5],weights:[1,2,3,4,5,6],fixed:{0:4,5:2}},
 {name:'The uneven mobile',arms:[-5,-3,-1,1,2,4],weights:[1,2,3,4,5,6],fixed:{1:3}}
];
function balanceState(round){const q=balanceStudies[round];return {round,weights:[...q.weights],hooks:q.arms.map((_,i)=>q.fixed[i]??null),selected:null};}
function balanceFixedWeight(v){return Object.values(balanceStudies[s.round].fixed).includes(v);}
function balanceArt(){const q=balanceStudies[s.round],angle=Math.max(-.18,Math.min(.18,(torque(1)-torque(0))*.013));let svg='<svg class="diagram mobile-sculpture" viewBox="'+(q.arms.length===4?'80 0 320 240':'0 0 480 240')+'" role="img" aria-label="Balance sculpture. Left torque '+torque(0)+', right torque '+torque(1)+'."><path d="M240 90L212 224H268Z" fill="#d9c9a8" stroke="#253e40" stroke-width="2"/>';const x=a=>240+a*34*Math.cos(angle),y=a=>90+a*34*Math.sin(angle);svg+='<line x1="'+x(Math.min(...q.arms)-.4)+'" y1="'+y(Math.min(...q.arms)-.4)+'" x2="'+x(Math.max(...q.arms)+.4)+'" y2="'+y(Math.max(...q.arms)+.4)+'" stroke="#253e40" stroke-width="7"/>';q.arms.forEach((a,i)=>{svg+='<circle cx="'+x(a)+'" cy="'+y(a)+'" r="6" fill="#e4b07d"/><text text-anchor="middle" x="'+x(a)+'" y="'+(y(a)-17)+'">'+(a<0?'L':'R')+Math.abs(a)+'</text>';if(s.hooks[i]!==null)svg+='<line x1="'+x(a)+'" y1="'+y(a)+'" x2="'+x(a)+'" y2="'+(y(a)+47)+'" stroke="#253e40" stroke-width="2"/><rect x="'+(x(a)-16)+'" y="'+(y(a)+47)+'" width="32" height="34" rx="6" fill="'+(i in q.fixed?'#b9c6b1':'#e4b07d')+'" stroke="#253e40"/><text text-anchor="middle" x="'+x(a)+'" y="'+(y(a)+69)+'">'+s.hooks[i]+'</text>';});return svg+'</svg>';}
function balanceRender(){const q=balanceStudies[s.round];return caption('Sculpture '+(s.round+1)+'/3 · '+q.name)+balanceArt()+caption('LEFT '+torque(0)+' ↔ '+torque(1)+' RIGHT · torque = mass × arm distance')+grid(q.arms.length===4?4:3,s.hooks.map((v,i)=>btn((v===null?'＋':v+' kg')+'<small><br>'+String.fromCharCode(65+i)+' · '+(q.arms[i]<0?'L':'R')+' ×'+Math.abs(q.arms[i])+(i in q.fixed?'<br>FIXED':'')+'</small>','hook:'+i,'cell'+(i in q.fixed?' fixed':''),'Hook '+String.fromCharCode(65+i)+', '+(q.arms[i]<0?'left':'right')+' arm '+Math.abs(q.arms[i])+', '+(v===null?'empty':v+' kilograms')+(i in q.fixed?', fixed anchor':''))))+tray(s.weights.map(v=>btn(v+' kg'+(balanceFixedWeight(v)?' · fixed':''),'weight:'+v,'chip'+(s.selected===v?' on':''),'Select '+v+' kilogram weight'+(balanceFixedWeight(v)?', fixed anchor':'' )).replace('<button',balanceFixedWeight(v)?'<button disabled':'<button')))+caption(s.selected===null?'Choose a free weight, then an empty hook. Choose a placed weight to lift it.':'Selected '+s.selected+' kg · choose an empty unlocked hook.');}

function reset(){moves=0;done=false;notice='Explore the arrangement. Every move is reversible by restarting.';s={};switch(game.id){case'tangram-dock':s={selected:0,placed:[null,null,null]};break;case'mirror-mail':s={mirrors:[0,1,1,1,0]};break;case'bilateral':s={marks:[]};break;case'shadow-turn':s={turns:[0,0,0,0],round:0};break;case'loose-ends':s={order:[0,2,4,1,5,3],selected:null};break;case'gear-train':s=gearState(0);break;case'measured-pour':s={jugs:[0,0]};break;case'rover-script':s={program:[],pos:20,dir:0,parcel:false};break;case'paper-trail':s={layers:Array.from({length:8},(_,i)=>[i+1])};break;case'pigment-lab':s=pigmentState(0);break;case'cable-loom':s={path:[0]};break;case'balance-mobile':s=balanceState(0);break;case'crate-crane':s={stacks:[['A','B','A'],['B','A','B'],[]],selected:null};break;case'orbit-transfer':s={pos:0,seen:[],fuel:8};break;case'stamp-studio':s={stamps:[],round:0};break;}$('result').hidden=true;render();}
function win(){done=true;notice='Solved — every condition met. Your best move count is saved when possible.';record.save(Math.max(1,moves));$('result').hidden=false;}
function render(){let h='';switch(game.id){
case'tangram-dock':{let cells=Array(12).fill('');s.placed.forEach((p,i)=>{if(p!==null)shape(i).forEach(([x,y])=>cells[p+y*4+x]=String.fromCharCode(65+i));});h=caption('Dock · 4 × 3 / choose cargo, then its top-left square')+grid(4,cells.map((v,i)=>btn(v||'·','place:'+i,'cell'+(v?' on':''),'Dock square '+(i+1)+(v?', piece '+v:''))))+tray(['A: ┏','B: ┓','C: ■'].map((t,i)=>btn(t+'<br>'+stampIcon(shape(i).map(([x,y])=>x+y*4)),'piece:'+i,'chip'+(s.selected===i?' on':''))));break;}
case'mirror-mail':{const mirrors={1:0,11:1,13:2,8:3,9:4};h=caption('Entrance → row 1 · Delivery ↓ column 5')+grid(5,Array.from({length:20},(_,i)=>i in mirrors?btn(s.mirrors[mirrors[i]]?'\\':'/','mirror:'+mirrors[i],'cell target'+((s.beam||[]).includes(i)?' lit':''),'Mirror '+(mirrors[i]+1)+': '+(s.mirrors[mirrors[i]]?'backslash':'slash')):'<div class="cell fixed '+((s.beam||[]).includes(i)?'lit':'')+'">'+(i===0?'→':i===19?'↓':'·')+'</div>'))+tray([btn('Send beam','beam')]);break;}
case'bilateral':{const left=[0,2,5,6,8,9,13,14];h=caption('Reflect across the central seam')+grid(8,Array.from({length:32},(_,i)=>{let r=Math.floor(i/8),c=i%8;return c<4?'<div class="cell '+(left.includes(r*4+c)?'on':'fixed')+'">'+(left.includes(r*4+c)?'●':'·')+'</div>':btn(s.marks.includes(i)?'●':'·','mark:'+i,'cell'+(s.marks.includes(i)?' on':''),'Reflection row '+(r+1)+' column '+(c-3));}));break;}
case'shadow-turn':h=caption('Study '+(s.round+1)+'/3 · Turn each large cutout until it matches its small reference shadow.')+grid(2,s.turns.map((t,i)=>btn(silhouette(t,i,false)+silhouette(silhouetteTargets[s.round][i],i,true),'turn:'+i,'cell',silhouetteDescription(t,i))));break;
case'loose-ends':h=caption('Select two numbered points to swap their locations')+'<svg class="diagram" viewBox="0 0 340 240" role="img" aria-label="'+necklaceDescription()+'">'+edges.map(([a,b])=>{let p=points[s.order[a]],q=points[s.order[b]];return `<line x1="${p[0]}" y1="${p[1]}" x2="${q[0]}" y2="${q[1]}" stroke="#d08755" stroke-width="4"/>`;}).join('')+s.order.map((p,i)=>`<circle cx="${points[p][0]}" cy="${points[p][1]}" r="16" fill="#e5d7bf"/><text x="${points[p][0]-5}" y="${points[p][1]+5}">${i+1}</text>`).join('')+'</svg>'+tray(s.order.map((p,i)=>btn('Point '+(i+1),'node:'+i,'chip'+(s.selected===i?' on':''),'Point '+(i+1)+', '+pointPositions[p]).replace('<button','<button aria-pressed="'+(s.selected===i)+'"')));break;
case'gear-train':{const study=gearStudies[s.round],letters='ABCDEF';let outN=1,outD=1,targetN=1,targetD=1;study.ratios.forEach(([n,d],i)=>{outN*=s.gears[2*i];outD*=s.gears[2*i+1];targetN*=n;targetD*=d;});h=caption('Study '+(s.round+1)+'/3 · '+study.name)+caption(study.brief)+caption('Bench order: '+letters.slice(0,s.gears.length).split('').join(' → ')+'. Only neighboring sockets may exchange gears.')+grid(s.gears.length===4?4:3,s.gears.map((v,i)=>btn('⚙<br>'+v+'<small><br>'+letters[i]+(study.locked.includes(i)?' · fixed':'')+'</small>','gear:'+i,'cell'+(study.locked.includes(i)?' fixed':s.selected===i?' on':s.selected!==null&&Math.abs(s.selected-i)===1?' target':''),'Socket '+letters[i]+', '+v+' teeth'+(study.locked.includes(i)?', locked':s.selected===i?', selected':''))))+study.ratios.map(([n,d],i)=>caption('Mesh '+(i+1)+' · '+letters[2*i]+' ÷ '+letters[2*i+1]+': '+gearFraction(s.gears[2*i],s.gears[2*i+1])+'× / target '+gearFraction(n,d)+'× '+(s.gears[2*i]*d===s.gears[2*i+1]*n?'✓':''))).join('')+caption('Shafts link consecutive meshes. Speed ratios multiply; each meshing pair reverses rotation.')+'<p class="large">'+gearFraction(outN,outD)+'× → '+gearFraction(targetN,targetD)+'×</p>'+caption(s.gearCleared?(s.round===2?'All three studies certified.':'Study certified. Continue when you are ready.'):'All individual mesh targets must match before testing the train.')+tray(s.gearCleared?(s.round<2?[btn('Next study →','gearnext')]:[]):[btn('Test the train','geartest'),btn('Undo swap','gearundo'),btn('Reset this study','gearretry')]);break;}
case'measured-pour':h='<div class="swatches">'+s.jugs.map((v,i)=>`<div><div class="jug"><div class="water" style="height:${v/[3,5][i]*100}%">${v} L</div></div>${caption(['3L jug','5L jug'][i])}</div>`).join('')+'</div>'+tray([btn('Fill 3L','fill:0'),btn('Fill 5L','fill:1'),btn('Empty 3L','empty:0'),btn('Empty 5L','empty:1'),btn('3L → 5L','pour:0'),btn('5L → 3L','pour:1')]);break;
case'rover-script':h=caption('Rover starts facing ↑. Collect ◆ then finish at ⚑.')+caption('Program: '+s.program.length+'/30 commands · Run attempts: '+moves)+grid(5,Array.from({length:25},(_,i)=>'<div class="cell '+(roverWalls.includes(i)?'wall':'fixed')+'">'+(s.pos===i?['↑','→','↓','←'][s.dir]:i===4?'⚑':i===12&&!s.parcel?'◆':roverWalls.includes(i)?'■':'·')+'</div>'))+'<div class="program">'+(s.program.join(' ')||'Your route…')+'</div>'+tray([btn('Forward','command:F'),btn('Turn left','command:L'),btn('Turn right','command:R'),btn('Undo','uncommand'),btn('Clear','clear'),btn('Run route','run')]);break;
case'paper-trail':h=caption('Target top → bottom: 6, 3, 2, 7, 8, 1, 4, 5')+tray(s.layers.map(a=>'<div class="chip">'+a.join('<br>')+'</div>'))+tray([btn('Fold left → right','fold:L'),btn('Fold right → left','fold:R')]);break;
case'pigment-lab':h=pigmentRender();break;
case'cable-loom':h=caption('Visit all 16 pegs, from S to E, without revisiting.')+grid(4,Array.from({length:16},(_,i)=>btn(i===0?'S':i===12?'E':s.path.includes(i)?s.path.indexOf(i)+1:'·','peg:'+i,'cell'+(s.path.includes(i)?' on':''),'Peg '+i)))+tray([btn('Undo segment','undopeg')]);break;
case'balance-mobile':h=balanceRender();break;
case'crate-crane':h=caption('Goal: AAA on left · BBB on right · spare empty')+grid(3,s.stacks.map((a,i)=>btn('<div class="stack">'+a.map(v=>'<span class="crate">'+v+'</span>').join('')+'</div><small>'+['Left','Right','Spare'][i]+'</small>','stack:'+i,'cell'+(s.selected===i?' on':''),'Stack '+(i+1)+': '+(a.join(',')||'empty'))));break;
case'orbit-transfer':{let routes=[[1,2],[3,0],[1,4],[2,5],[3,5],[]];h=caption('Arrows: A→B,C · B→D,A · C→B,E · D→C,F · E→D,F. Dock F.')+'<p class="large">'+String.fromCharCode(65+s.pos)+' · '+s.fuel+' fuel</p>'+caption('Beacons at B, D, E: '+s.seen.map(i=>String.fromCharCode(65+i)).join(' / '))+tray(routes[s.pos].map(i=>btn('Travel to '+String.fromCharCode(65+i),'travel:'+i)));break;}
case'stamp-studio':{const target=[...new Set([[0,3],[1,2],[2,4]][s.round].flatMap(i=>patterns[i]))];const ink=[...new Set(s.stamps.flatMap(i=>patterns[i]))];const print=(a,label)=>grid(4,Array.from({length:16},(_,i)=>'<div class="cell '+(a.includes(i)?'on':'fixed')+'"></div>')).replace('<div','<div role="img" aria-label="'+label+'. On a 4 by 4 grid, filled squares: '+describeSquares(a,4)+'. All other squares are blank."');h=caption('Edition '+(s.round+1)+'/3 · Your print (left) · Target (right)')+'<div class="print">'+print(ink,'Your print')+print(target,'Target print')+'</div>'+tray(patterns.map((p,i)=>btn('Stamp '+(i+1)+'<br>'+stampIcon(p),'stamp:'+i,'chip'+(s.stamps.includes(i)?' on':''),'Stamp '+(i+1)+'. Fills '+describeSquares(p,4)+'.').replace('<button','<button aria-pressed="'+s.stamps.includes(i)+'"')));break;}}
B.innerHTML=h;$('moves').textContent=moves;$('status').textContent=done?'Solved':'Explore';if(game.id==='orbit-transfer'&&!done&&(s.fuel===0||s.pos===5)){$('status').textContent='Stranded';B.querySelectorAll('button').forEach(b=>b.disabled=true);}$('message').textContent=notice;if(done)B.querySelectorAll('button').forEach(b=>b.disabled=true);}
function silhouette(turn,i,small){return '<svg width="'+(small?35:70)+'" height="80" viewBox="0 0 90 90" aria-hidden="true"><g transform="rotate('+turn*90+' 45 45)">'+silhouetteSets[i].map(n=>'<rect x="'+(n%3*25+8)+'" y="'+(Math.floor(n/3)*25+8)+'" width="23" height="23" rx="3" fill="'+(small?'#ad7553':'#253e40')+'"/>').join('')+'</g></svg>';}
function traceBeam(){s.beam=[];let x=-1,y=0,dx=1,dy=0;const mirrors={'1,0':0,'1,2':1,'3,2':2,'3,1':3,'4,1':4};for(let step=0;step<30;step++){x+=dx;y+=dy;if(x<0||x>=5||y<0||y>=4)return x===4&&y===4;s.beam.push(y*5+x);const m=mirrors[x+','+y];if(m!==undefined){[dx,dy]=s.mirrors[m]?[dy,dx]:[-dy,-dx];}}return false;}
function stampIcon(p){return '<svg width=48 height=48 viewBox="0 0 40 40" aria-hidden=true>'+Array.from({length:16},(_,i)=>'<rect x="'+i%4*10+'" y="'+Math.floor(i/4)*10+'" width=8 height=8 fill="'+(p.includes(i)?'#b9784d':'#ddd1b8')+'"/>').join('')+'</svg>';}
function shape(i){return [[[0,0],[1,0],[0,1],[0,2]],[[0,0],[1,0],[1,1],[1,2]],[[0,0],[1,0],[0,1],[1,1]]][i];}
function torque(side){const q=balanceStudies[s.round];return s.hooks.reduce((total,v,i)=>total+((side===0?q.arms[i]<0:q.arms[i]>0)?(v||0)*Math.abs(q.arms[i]):0),0);}
function crossing(){const orient=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);return edges.some(([a,b],i)=>edges.slice(i+1).some(([c,d])=>new Set([a,b,c,d]).size===4&&orient(points[s.order[a]],points[s.order[b]],points[s.order[c]])*orient(points[s.order[a]],points[s.order[b]],points[s.order[d]])<0&&orient(points[s.order[c]],points[s.order[d]],points[s.order[a]])*orient(points[s.order[c]],points[s.order[d]],points[s.order[b]])<0));}
function action(raw){if(done)return;let [a,b,c]=raw.split(':'),i=Number(b);let changed=true;notice='Keep exploring. Restart is always available.';switch(a){case'piece':if(s.placed[i]!==null)s.placed[i]=null;s.selected=i;break;case'place':{let p=s.selected;if(p===null){notice='Choose a cargo piece first.';changed=false;break;}let cells=shape(p).map(([x,y])=>[i%4+x,Math.floor(i/4)+y]);let used=[];s.placed.forEach((v,j)=>{if(v!==null&&j!==p)shape(j).forEach(([x,y])=>used.push(v+x+y*4));});if(cells.some(([x,y])=>x>=4||y>=3||used.includes(x+y*4))){notice='That piece crosses a wall or another piece.';changed=false;}else{s.placed[p]=i;s.selected=null;}break;}
case'mirror':s.mirrors[i]^=1;s.beam=[];break;case'beam':s.delivered=traceBeam();if(s.delivered)notice='Delivery confirmed.';else notice='The beam misses the delivery port. Try another mirror arrangement.';break;
case'mark':s.marks.includes(i)?s.marks.splice(s.marks.indexOf(i),1):s.marks.push(i);break;case'turn':s.turns[i]=(s.turns[i]+1)%4;notice='Cutout '+(i+1)+' rotated clockwise. '+(s.turns[i]===silhouetteTargets[s.round][i]?'It matches its reference.':'Its shape differs from the reference.');break;
case'node':if(s.selected===null){s.selected=i;changed=false;notice='Point '+(i+1)+' selected at '+pointPositions[s.order[i]]+'. Choose another point to swap.';}else{const other=s.selected;[s.order[i],s.order[other]]=[s.order[other],s.order[i]];s.selected=null;notice='Point '+(other+1)+' is now at '+pointPositions[s.order[other]]+'; point '+(i+1)+' is at '+pointPositions[s.order[i]]+'. '+(crossing()?'Some cords still cross.':'No cords cross.');}break;
case'gear':{changed=false;const study=gearStudies[s.round];if(s.gearCleared){notice='This study is certified. Choose Next study.';break;}if(!Number.isInteger(i)||i<0||i>=s.gears.length||study.locked.includes(i)){notice='That socket is bolted in place. Choose an unlocked gear.';break;}if(s.selected===null){s.selected=i;notice='Selected '+String.fromCharCode(65+i)+'. Choose a neighboring socket, or select it again to cancel.';}else if(s.selected===i){s.selected=null;notice='Selection cleared.';}else if(Math.abs(s.selected-i)!==1){notice='Only neighbors in the bench order may exchange gears.';}else{s.gearHistory.push([...s.gears]);[s.gears[i],s.gears[s.selected]]=[s.gears[s.selected],s.gears[i]];s.selected=null;changed=true;notice='One exchange. Inspect the mesh ratios before testing.';}break;}
case'geartest':changed=false;if(gearMatches()){s.gearCleared=true;s.selected=null;notice=s.round===2?'All three transmission studies certified.':'Every mesh matches. Study '+(s.round+1)+' certified; choose Next study.';}else notice='Not yet. Every individual mesh must meet its target, even when the final product is right.';break;
case'gearnext':changed=false;if(s.gearCleared&&s.round<2){s=gearState(s.round+1,moves);notice='Study '+(s.round+1)+' of 3. '+gearStudies[s.round].brief;}break;
case'gearundo':changed=false;if(!s.gearCleared&&s.gearHistory.length){s.gears=s.gearHistory.pop();s.selected=null;moves--;notice='Last exchange undone.';}else notice='No exchange to undo in this study.';break;
case'gearretry':changed=false;if(!s.gearCleared){moves=s.gearBase;s=gearState(s.round,moves);notice='This study reset. Earlier certified studies are kept.';}break;
case'fill':s.jugs[i]=[3,5][i];break;case'empty':s.jugs[i]=0;break;case'pour':{let n=Math.min(s.jugs[i],[3,5][1-i]-s.jugs[1-i]);s.jugs[i]-=n;s.jugs[1-i]+=n;break;}
case'command':if(s.program.length<30)s.program.push(b);else notice='30-command memory full. Undo or clear.';changed=false;break;case'uncommand':s.program.pop();changed=false;break;case'clear':s.program=[];changed=false;break;
case'run':s.pos=20;s.dir=0;s.parcel=false;s.routeFailed=false;for(let [commandIndex,cmd] of s.program.entries()){if(cmd==='L')s.dir=(s.dir+3)%4;else if(cmd==='R')s.dir=(s.dir+1)%4;else{let x=s.pos%5+[0,1,0,-1][s.dir],y=Math.floor(s.pos/5)+[-1,0,1,0][s.dir];if(x<0||x>4||y<0||y>4||roverWalls.includes(y*5+x)){s.routeFailed=true;notice='Command '+(commandIndex+1)+' (Forward) is blocked from row '+(Math.floor(s.pos/5)+1)+', column '+(s.pos%5+1)+'. Turn before this step or edit the route.';break;}s.pos=y*5+x;if(s.pos===12)s.parcel=true;}}if(!s.routeFailed)notice='Program finished at row '+(Math.floor(s.pos/5)+1)+', column '+(s.pos%5+1)+'. '+(s.parcel?'Parcel collected; reach the flag at row 1, column 5.':'Collect the parcel at row 3, column 3, then reach the flag.');break;
case'fold':if(s.layers.length===1){notice='The strip is fully folded. Restart to try a different sequence.';changed=false;break;}let half=s.layers.length/2,L=s.layers.slice(0,half),R=s.layers.slice(half);s.layers=b==='L'?R.map((v,j)=>[...L[half-1-j]].reverse().concat(v)):L.map((v,j)=>[...R[half-1-j]].reverse().concat(v));break;
case'inkselect':s.selected=i;changed=false;break;
case'inkrotate':s.inks[s.selected].turn=(s.inks[s.selected].turn+1)%4;s.inks[s.selected].at=null;notice='Stencil rotated and lifted. Choose its new top-left square.';break;
case'inklift':s.inks[s.selected].at=null;break;
case'inkplace':{const ink=s.inks[s.selected],shape=inkShape(ink.turn);if(shape.some(([x,y])=>i%4+x>3||Math.floor(i/4)+y>3)){notice='The whole stencil must fit on the paper. Try another anchor or rotation.';changed=false;}else ink.at=i;break;}
case'peg':{let last=s.path.at(-1);if(!s.path.includes(i)&&Math.abs(last%4-i%4)+Math.abs(Math.floor(last/4)-Math.floor(i/4))===1){s.path.push(i);}else{notice='Choose an unused peg beside the cable tip.';changed=false;}break;}case'undopeg':if(s.path.length>1)s.path.pop();else changed=false;break;
case'weight':if(balanceFixedWeight(i)){notice='This anchor is fixed. Arrange the free weights around it.';changed=false;}else{s.hooks=s.hooks.map(v=>v===i?null:v);s.selected=i;changed=false;}break;
case'hook':if(i in balanceStudies[s.round].fixed){notice='This hook is anchored. Fixed weights cannot move.';changed=false;}else if(s.selected!==null&&s.hooks[i]===null){s.hooks[i]=s.selected;s.selected=null;}else{notice='Choose a free weight and an empty unlocked hook.';changed=false;}break;
case'stack':if(s.selected===null){if(s.stacks[i].length)s.selected=i;changed=false;}else{if(i!==s.selected&&s.stacks[i].length<3)s.stacks[i].push(s.stacks[s.selected].pop());else{notice='Choose a different stack with space.';changed=false;}s.selected=null;}break;
case'travel':if(s.fuel>0){s.pos=i;s.fuel--;if([1,3,4].includes(i)&&!s.seen.includes(i))s.seen.push(i);if((i===5&&s.seen.length<3)||s.fuel===0)notice='Route ended without every beacon. Restart to chart a better course.';}else changed=false;break;
case'stamp':s.stamps.includes(i)?s.stamps.splice(s.stamps.indexOf(i),1):s.stamps.push(i);notice='Stamp '+(i+1)+(s.stamps.includes(i)?' added.':' removed.')+' Your print now has '+new Set(s.stamps.flatMap(k=>patterns[k])).size+' filled squares.';break;
}if(changed)moves++;if(!done&&solved()){if(['shadow-turn','pigment-lab','stamp-studio','balance-mobile'].includes(game.id)&&s.round<2){s.round++;if(s.turns)s.turns=[0,0,0,0];if(s.inks)s=pigmentState(s.round);if(game.id==='balance-mobile')s=balanceState(s.round);if(s.stamps)s.stamps=[];notice='Beautiful work. Study '+(s.round+1)+' of 3 is ready.';}else win();}if(game.id==='paper-trail'&&s.layers.length===1&&!done)notice='Folded, but the layers differ. Restart and try another fold order.';render();}
function solved(){switch(game.id){case'mirror-mail':return !!s.delivered;case'tangram-dock':return s.placed.every(v=>v!==null);case'bilateral':return [...s.marks].sort((a,b)=>a-b).join()===[5,7,13,14,22,23,29,30].join();case'shadow-turn':return s.turns.join()===silhouetteTargets[s.round].join();case'loose-ends':return !crossing();case'gear-train':return s.round===2&&s.gearCleared&&gearMatches();case'measured-pour':return s.jugs[1]===4;case'rover-script':return s.pos===4&&s.parcel&&!s.routeFailed;case'paper-trail':return s.layers.length===1&&s.layers[0].join()==='6,3,2,7,8,1,4,5';case'pigment-lab':return s.inks.every(i=>i.at!==null)&&inkPrint(s.inks).join('|')===inkPrint(pigmentStudies[s.round].target).join('|');case'cable-loom':return s.path.length===16&&s.path.at(-1)===12;case'balance-mobile':return s.hooks.every(v=>balanceStudies[s.round].weights.includes(v))&&new Set(s.hooks).size===s.weights.length&&Object.entries(balanceStudies[s.round].fixed).every(([i,v])=>s.hooks[i]===v)&&torque(0)===torque(1);case'crate-crane':return s.stacks[0].join()==='A,A,A'&&s.stacks[1].join()==='B,B,B';case'orbit-transfer':return s.pos===5&&s.seen.length===3;case'stamp-studio':return [...new Set(s.stamps.flatMap(i=>patterns[i]))].sort((a,b)=>a-b).join()===[...new Set([[0,3],[1,2],[2,4]][s.round].flatMap(i=>patterns[i]))].sort((a,b)=>a-b).join();default:return false;}}
B.addEventListener('click',e=>{let b=e.target.closest('button[data-action]');if(b){const key=b.dataset.action;action(key);const next=B.querySelector('[data-action="'+key+'"]');if(done)$('again').focus({preventScroll:true});else if(next&&!next.disabled)next.focus({preventScroll:true});}});$('restart').onclick=reset;$('again').onclick=reset;reset();document.body.dataset.gameId=game.id;document.body.dataset.gameReady='true';
