import{base,range,dirs,dirNames,offset,coord,copy,random,shuffle,log,finish,grid,rays,material,turnLimit,sum}from'./core.mjs';

// Capture by contact in front of (approach) or behind (withdrawal) a mover.
export function tideMoves(s,who,chain=s.chain){const out=[];for(let f=0;f<25;f++){if(s.b[f]!==who||chain&&f!==chain.at)continue;for(let d=0;d<8;d++){const[dx,dy]=dirs[d];if(dx&&dy&&(f%5+Math.floor(f/5))%2)continue;if(chain&&chain.direction===d)continue;const t=offset(f,dx,dy);if(t<0||s.b[t]||chain?.visited.includes(t))continue;let variants=[];for(const sign of[1,-1]){const captured=[];for(let k=1;k<5;k++){const p=sign===1?offset(t,dx,dy,k):offset(f,-dx,-dy,k);if(p<0||s.b[p]!==-who)break;captured.push(p)}if(captured.length)variants.push({f,t,d,style:sign===1?'approach':'withdraw',captured})}if(variants.length)out.push(...variants);else if(!chain)out.push({f,t,d,style:'step',captured:[]})}}const captures=out.filter(m=>m.captured.length);return captures.length?captures:chain?[]:out}
export function tideApply(s,m,who){s.b[m.f]=0;s.b[m.t]=who;m.captured.forEach(p=>s.b[p]=0);s.chain=m.captured.length?{at:m.t,visited:[...(s.chain?.visited||[m.f]),m.t],direction:m.d}:null}
function tideTerminal(s){if(!material(s.b,-1)){finish(s,true,'Every opposing pawn was captured by approach or withdrawal.',200+material(s.b,1)*15-s.turn);return true}if(!material(s.b,1)){finish(s,false,'Your final pawn was captured.',s.turn*2);return true}return false}
function tideHouse(s){s.chain=null;let guard=0;do{let moves=tideMoves(s,-1,s.chain);if(!moves.length)break;let best=moves.map(m=>{let q=copy(s);tideApply(q,m,-1);return{m,v:m.captured.length*40-tideMoves({...q,chain:null},1,null).reduce((v,n)=>Math.max(v,n.captured.length),0)*30+random(s)*.1}}).sort((a,b)=>b.v-a.v)[0].m;tideApply(s,best,-1);log(s,`House ${best.style}: ${coord(best.f)} → ${coord(best.t)}, ${best.captured.length} captured.`);if(tideTerminal(s))return;guard++}while(s.chain&&tideMoves(s,-1,s.chain).length&&guard<20);s.chain=null;s.turn++;if(turnLimit(s))return;if(!tideMoves(s,1,null).length)finish(s,false,'Your surviving pawns have no legal move.',s.turn*2)}
const tide={stages:3,init(o){let s=base('tide-and-retreat',o);s.b=Array(25).fill(0);const layouts=[[[15,16,17,20,21,22,23,24],[0,1,2,3,4,5,7]],[[14,16,18,20,21,22,24],[0,2,3,4,6,7,9]],[[12,15,17,18,20,21,23,24],[0,1,3,4,5,6,8,10]]];let[a,b]=layouts[Math.min(o.stage,2)];if(o.mode==='endless'){const top=shuffle(s,range(10)),bot=shuffle(s,range(10).map(n=>n+15));a=bot.slice(0,6+o.stage%3);b=top.slice(0,a.length-1)}a.forEach(p=>s.b[p]=1);b.forEach(p=>s.b[p]=-1);s.selected=null;s.chain=null;s.note='A capture is compulsory when available. Select a pawn, then choose approach or withdrawal.';return s},act(s,k){if(k==='end-chain'&&s.chain){tideHouse(s);s.selected=null;return}if(k.startsWith('square-')){let p=+k.slice(7);if(tideMoves(s,1).some(m=>m.f===p)){s.selected=p;s.note='Select a labeled capture or landing below the board.'}return}let m=tideMoves(s,1).find(m=>'move-'+m.f+'-'+m.t+'-'+m.style===k);if(!m)return;tideApply(s,m,1);s.selected=null;log(s,`${m.style}: ${coord(m.f)} → ${coord(m.t)}; ${m.captured.length} captured.`);if(tideTerminal(s))return;if(s.chain&&tideMoves(s,1).length){s.selected=m.t;s.note+=' Continue with this pawn, changing direction and avoiding visited intersections, or finish the chain.'}else tideHouse(s)},render(ui,s){let ms=tideMoves(s,1);ui.p(`You ${material(s.b,1)} · House ${material(s.b,-1)} · Turn ${s.turn}/48. Diagonal edges exist at intersections of even row+column parity. Captures sweep contiguous enemy lines.`);grid(ui,s,[...new Set(ms.map(m=>m.f))]);ui.group('Moves from selected pawn');for(const m of ms.filter(m=>m.f===s.selected))ui.button(`move-${m.f}-${m.t}-${m.style}`,`${m.style} to ${coord(m.t)} · capture ${m.captured.length}`);if(s.chain)ui.button('end-chain','Finish capture chain');if(s.log.length)ui.pre(s.log.join('\n'))}};

export function sporeMoves(s,who){const out=[];s.b.forEach((v,f)=>{if(v!==who)return;for(let dy=-2;dy<=2;dy++)for(let dx=-2;dx<=2;dx++){let n=Math.max(Math.abs(dx),Math.abs(dy)),t=offset(f,dx,dy);if(n&&t>=0&&!s.b[t])out.push({f,t,jump:n===2})}});return out}
export function sporeApply(s,m,who){if(m.jump)s.b[m.f]=0;s.b[m.t]=who;for(const[dx,dy]of dirs){let t=offset(m.t,dx,dy);if(t>=0&&s.b[t]===-who)s.b[t]=who}}
function sporeValue(b,who){return material(b,who)*20-material(b,-who)*20+sporeMoves({b},who).length*.15}
function sporeEnd(s){let yours=sporeMoves(s,1),theirs=sporeMoves(s,-1);if(!material(s.b,1)||!material(s.b,-1)||!yours.length&&!theirs.length||s.turn>=60){let a=material(s.b,1),b=material(s.b,-1);finish(s,a>b,`Colonies at settlement: you ${a}, house ${b}. ${a>b?'Your living colony is larger.':'The house has the larger colony; tied defense also holds.'}`,a*15);return true}return false}
function sporeHouse(s){for(let guard=0;guard<60;guard++){const ms=sporeMoves(s,-1);if(ms.length){let best=ms.map(m=>{let q=copy(s);sporeApply(q,m,-1);let threats=sporeMoves(q,1),worst=Math.max(...threats.map(p=>{let r=copy(q);sporeApply(r,p,1);return sporeValue(r.b,1)}),-500);return{m,v:sporeValue(q.b,-1)-worst*.35+random(s)*.05}}).sort((a,b)=>b.v-a.v)[0].m;sporeApply(s,best,-1);log(s,`House ${best.jump?'jumps':'clones'} ${coord(best.f)} → ${coord(best.t)}.`)}s.turn++;if(sporeEnd(s)||sporeMoves(s,1).length)return;log(s,'You have no landing, so the house takes the next turn.')}}
const spore={stages:3,init(o){let s=base('spore-council',o);s.b=Array(25).fill(0);[20,21,22,23,24].forEach(p=>s.b[p]=1);[0,1,2,3,4].forEach(p=>s.b[p]=-1);let rocks=o.mode==='finite'?[[],[7,17],[6,8,16,18]][o.stage]:shuffle(s,[6,7,8,11,12,13,16,17,18]).slice(0,Math.min(4,1+o.stage%4));rocks.forEach(p=>s.b[p]=9);s.selected=null;s.note='Nearby clones add a pawn. Two-step jumps move an existing pawn. Landing converts adjacent enemies.';return s},act(s,k){if(k.startsWith('square-')){let p=+k.slice(7);if(s.b[p]===1&&sporeMoves(s,1).some(m=>m.f===p))s.selected=p;else{let m=sporeMoves(s,1).find(m=>m.f===s.selected&&m.t===p);if(!m)return;sporeApply(s,m,1);log(s,`You ${m.jump?'jumped':'cloned'} to ${coord(p)} and converted its neighboring enemies.`);s.selected=null;if(!sporeEnd(s))sporeHouse(s)}}},render(ui,s){let ms=sporeMoves(s,1);ui.p(`You ${material(s.b,1)} · House ${material(s.b,-1)} · Turn ${s.turn}/60. A one-square landing clones; a two-square Chebyshev landing jumps.`);grid(ui,s,[...new Set([...ms.map(m=>m.f),...ms.filter(m=>m.f===s.selected).map(m=>m.t)])]);if(s.selected!==null)ui.p('Choose a highlighted landing; every adjacent enemy changes sides.');if(s.log.length)ui.pre(s.log.join('\n'))}};

export function cometMoves(s,who){if(s.phase==='comet')return rays(s.b,s.b.indexOf(3));return s.b.flatMap((v,p)=>v===who?rays(s.b,p):[])}
export function cometApply(s,m){const v=s.b[m.f];s.b[m.f]=0;s.b[m.t]=v;s.phase=v===3?'blocker':'comet'}
function cometEnd(s,mover){const row=Math.floor(s.b.indexOf(3)/5);if(row===4||row===0){finish(s,row===4,`The shared comet reached the ${row===4?'your':'house'} home edge.`,row===4?250-s.turn*3:s.turn*2);return true}if(s.phase==='comet'&&!rays(s.b,s.b.indexOf(3)).length){finish(s,mover===1,'The next player cannot move the shared comet; the preceding complete turn wins.',mover===1?200:s.turn*2);return true}if(s.turn>=40){finish(s,false,'Forty turns without a home-edge arrival. The house holds its defense.',s.turn);return true}return false}
function cometHouse(s){s.phase='comet';let ms=cometMoves(s,-1);if(!ms.length){finish(s,true,'The house cannot move the shared comet.',200);return}let opts=[];for(const m of ms){let q=copy(s);cometApply(q,m);let row=Math.floor(m.t/5);if(row===0){opts.push({m,n:null,v:10000});continue}if(row===4){opts.push({m,n:null,v:-10000});continue}for(const n of cometMoves(q,-1)){let r=copy(q);cometApply(r,n);let reply=cometMoves(r,1);let danger=reply.some(a=>Math.floor(a.t/5)===4);let good=reply.filter(a=>Math.floor(a.t/5)===0).length;opts.push({m,n,v:(danger?-1000:0)+good*30-reply.length+(4-Math.floor(m.t/5))*2+random(s)*.1})}}if(!opts.length){finish(s,true,'The house cannot complete a comet-and-blocker turn.',200);return}let best=opts.sort((a,b)=>b.v-a.v)[0];cometApply(s,best.m);if(cometEnd(s,-1))return;cometApply(s,best.n);s.selected=null;s.turn++;log(s,`House slides comet to ${coord(best.m.t)}, then blocker ${coord(best.n.f)} → ${coord(best.n.t)}.`);cometEnd(s,-1)}
const comet={stages:3,init(o){let s=base('shared-comet',o);s.b=Array(25).fill(0);[20,21,22,23,24].forEach(p=>s.b[p]=1);[0,1,2,3,4].forEach(p=>s.b[p]=-1);s.b[12]=3;if(o.stage%3===1){s.b[21]=0;s.b[16]=1;s.b[3]=0;s.b[8]=-1}if(o.stage%3===2){s.b[23]=0;s.b[18]=1;s.b[1]=0;s.b[6]=-1}if(o.mode==='endless'){s.b=Array(25).fill(0);[20,21,22,23,24].forEach(p=>s.b[p]=1);[0,1,2,3,4].forEach(p=>s.b[p]=-1);let p=shuffle(s,[15,16,17,18,19])[0],q=shuffle(s,[5,6,7,8,9])[0];s.b[20+p%5]=0;s.b[p]=1;s.b[q%5]=0;s.b[q]=-1;s.b[12]=0;let candidates=shuffle(s,[11,12,13]);for(let c of candidates){s.b[c]=3;if(!rays(s.b,c).some(m=>m.t<5||m.t>=20))break;s.b[c]=0}}s.phase='comet';s.selected=null;s.note='Slide the shared comet to a ray endpoint, then slide one of your blockers. Bottom edge wins for you.';return s},act(s,k){if(!k.startsWith('square-'))return;let p=+k.slice(7);if(s.phase==='blocker'&&s.b[p]===1){s.selected=p;return}let ms=cometMoves(s,1),m=ms.find(m=>m.t===p&&(s.phase==='comet'||m.f===s.selected));if(!m)return;cometApply(s,m);if(cometEnd(s,1))return;if(s.phase==='blocker'){if(!cometMoves(s,1).length){finish(s,false,'Your comet move left no legal blocker slide.',s.turn);return}s.selected=null;log(s,'Now slide one friendly blocker to the furthest empty point of a clear ray.')}else cometHouse(s)},render(ui,s){let ms=cometMoves(s,1);ui.p(`Turn ${s.turn}/40 · ${s.phase==='comet'?'Shared comet move':'Your blocker move'} · Your edge A5–E5; house edge A1–E1. Every slide stops at the furthest clear square.`);let legal=s.phase==='comet'?ms.map(m=>m.t):[...ms.map(m=>m.f),...ms.filter(m=>m.f===s.selected).map(m=>m.t)];grid(ui,s,[...new Set(legal)]);if(s.log.length)ui.pre(s.log.join('\n'))}};

export function socketMoves(s,who){const out=[];for(let f=0;f<25;f++){if(s.b[f]!==who)continue;for(let d=0;d<8;d++){if(!(s.pods[f]&(1<<d)))continue;let[dx,dy]=dirs[d],mid=offset(f,dx,dy);if(mid<0)continue;if(!s.b[mid])out.push({f,t:mid,d,c:-1});else if(s.b[mid]===-who){let t=offset(f,dx,dy,2);if(t>=0&&!s.b[t])out.push({f,t,d,c:mid})}}}return out}
export function socketApply(s,m,who){let mask=s.pods[m.f];s.b[m.f]=0;s.pods[m.f]=0;if(m.c>=0){s.stock[who===1?0:1]+=bitCount(s.pods[m.c]);s.b[m.c]=0;s.pods[m.c]=0}s.b[m.t]=who;s.pods[m.t]=mask}
function bitCount(n){let c=0;while(n){c+=n&1;n>>>=1}return c}
export function socketCanAct(s,who){return socketMoves(s,who).length>0||s.stock[who===1?0:1]>0&&s.b.some((v,p)=>v===who&&s.pods[p]!==255)}
function socketEnd(s,next=-1){if(s.b[s.homes[1]]===1||!material(s.b,-1)){finish(s,true,'You entered the opposing home or captured its last configured piece.',220+sum(s.pods.map((p,i)=>s.b[i]===1?bitCount(p):0))*5-s.turn);return true}if(s.b[s.homes[0]]===-1||!material(s.b,1)){finish(s,false,'The house entered your home or captured your last piece.',s.turn*3);return true}if(!socketCanAct(s,next)){finish(s,next===-1,`${next===1?'Your pieces have':'The house has'} neither a legal move nor an available pod installation.`,next===-1?200:s.turn*3);return true}return turnLimit(s,40)}
function socketHouse(s){const opts=[];for(const m of socketMoves(s,-1)){let q=copy(s);socketApply(q,m,-1);let danger=socketMoves(q,1).some(n=>n.t===q.homes[1]);let captured=m.c>=0?bitCount(s.pods[m.c])+2:0;opts.push({m,v:m.t===s.homes[0]?10000:captured*20-(danger?1000:0)+(q.b[q.homes[1]]===-1?25:0)+Math.floor(m.t/5)*4+random(s)*.1})}if(s.stock[1])for(let f=0;f<25;f++)if(s.b[f]===-1)for(let d=0;d<8;d++)if(!(s.pods[f]&(1<<d))){let q=copy(s);q.pods[f]|=1<<d;let newMoves=socketMoves(q,-1).filter(m=>m.f===f&&m.d===d);let v=Math.max(...newMoves.map(m=>m.t===s.homes[0]?80:(m.c>=0?45:0)+Math.floor(m.t/5)*3),-100);let threat=socketMoves(q,1).some(m=>m.t===q.homes[1]);opts.push({f,d,v:v-(threat?1000:0)-5+random(s)*.1})}if(!opts.length){finish(s,true,'The house has neither a move nor a pod installation.',200);return}let best=opts.sort((a,b)=>b.v-a.v)[0];if(best.m){socketApply(s,best.m,-1);log(s,`House moves ${coord(best.m.f)} → ${coord(best.m.t)}${best.m.c>=0?' and recycles captured pods':''}.`)}else{s.pods[best.f]|=1<<best.d;s.stock[1]--;log(s,`House installs ${dirNames[best.d]} on ${coord(best.f)}.`)}s.selected=null;s.turn++;socketEnd(s,1)}
const socket={stages:3,init(o){let s=base('socket-skirmish',o);s.b=Array(25).fill(0);s.pods=Array(25).fill(0);s.stock=[6,5];s.homes=[22,2];let own=[20,22,24],enemy=[0,2,4];if(o.stage%3===1){own=[16,20,24];enemy=[0,4,8]}if(o.stage%3===2){own=[17,21,23];enemy=[1,3,7]}if(o.mode==='endless'){own=shuffle(s,range(10).map(n=>n+15)).slice(0,3);enemy=shuffle(s,range(10)).slice(0,3);s.homes=[20+Math.floor(random(s)*5),Math.floor(random(s)*5)]}own.forEach((p,i)=>{s.b[p]=1;s.pods[p]=i===1?(1<<3)|(1<<4):(i===0?1<<4:1<<3)});enemy.forEach((p,i)=>{s.b[p]=-1;s.pods[p]=(1<<6)|(i===1?1<<5:1<<7)});s.selected=null;s.note='Your home is '+coord(s.homes[0])+'. Configure movement pods, capture by jumping, or enter '+coord(s.homes[1])+' to win.';return s},act(s,k){if(k.startsWith('square-')){let p=+k.slice(7);if(s.b[p]===1)s.selected=p;else{let m=socketMoves(s,1).find(m=>m.f===s.selected&&m.t===p);if(!m)return;socketApply(s,m,1);if(!socketEnd(s))socketHouse(s)}}else if(k.startsWith('install-')&&s.selected!==null){let d=+k.slice(8);if(d<0||d>7||!s.stock[0]||s.pods[s.selected]&(1<<d))return;s.pods[s.selected]|=1<<d;s.stock[0]--;log(s,`Installed ${dirNames[d]} on ${coord(s.selected)}. Fitting hardware spends this turn.`);socketHouse(s)}},render(ui,s){let ms=socketMoves(s,1);ui.p(`Your spare pods ${s.stock[0]} · House ${s.stock[1]} · Homes ${coord(s.homes[0])}/${coord(s.homes[1])}. Turn ${s.turn}/40. Each installed direction permits a one-step move or a two-step enemy jump.`);grid(ui,s,[...new Set([...s.b.flatMap((v,p)=>v===1?[p]:[]),...ms.filter(m=>m.f===s.selected).map(m=>m.t)])],p=>(s.b[p]===1||s.b[p]===-1?' ['+dirNames.filter((n,d)=>s.pods[p]&(1<<d)).join('/')+']':'')+(p===s.homes[0]?' ⚑':p===s.homes[1]?' ⚐':''));if(s.selected!==null){ui.group('Fit movement pod');for(let d=0;d<8;d++)ui.button('install-'+d,'Install '+dirNames[d],!s.stock[0]||!!(s.pods[s.selected]&(1<<d)))}if(s.log.length)ui.pre(s.log.join('\n'))}};

export function cannonMoves(s,who){let out=[];for(let f=0;f<25;f++)if(s.b[f]===who){for(const dx of[-1,0,1]){let t=offset(f,dx,-who);if(t>=0&&s.b[t]!==who&&s.b[t]!==who*2)out.push({f,t,kind:s.b[t]?'capture':'move'})}for(const dx of[-1,1]){let t=offset(f,dx,0);if(t>=0&&s.b[t]===-who)out.push({f,t,kind:'capture'})}for(let d=0;d<8;d++){let[dx,dy]=dirs[d],m=offset(f,dx,dy),front=offset(f,dx,dy,2);if(m<0||front<0||s.b[m]!==who||s.b[front]!==who)continue;let end=offset(f,dx,dy,3);if(end>=0&&!s.b[end])out.push({f,t:end,kind:'shift'});let gap=offset(front,dx,dy);if(gap<0||s.b[gap])continue;for(let k=2;k<=3;k++){let t=offset(front,dx,dy,k);if(t<0)break;if(s.b[t]===-who||s.b[t]===-who*2)out.push({f,t,kind:'fire'});if(s.b[t])break}}}return out}
export function cannonApply(s,m,who){if(m.kind==='fire')s.b[m.t]=0;else{s.b[m.f]=0;s.b[m.t]=who}}
function cannonEnd(s){if(!s.b.includes(-2)||!material(s.b,-1)){finish(s,true,'The opposing town or its last soldier was destroyed.',240+material(s.b,1)*12-s.turn);return true}if(!s.b.includes(2)||!material(s.b,1)){finish(s,false,'Your town or last soldier was destroyed.',s.turn*3);return true}return turnLimit(s,40)}
function cannonHouse(s){let ms=cannonMoves(s,-1);if(!ms.length){finish(s,true,'The opposing army has no legal move.',200);return}let best=ms.map(m=>{let q=copy(s);cannonApply(q,m,-1);let threats=cannonMoves(q,1);let danger=threats.some(p=>q.b[p.t]===-2);return{m,v:(s.b[m.t]===2?10000:s.b[m.t]===1?60:0)-(danger?1000:0)+Math.floor(m.t/5)*3+threats.filter(p=>q.b[p.t]===-1).length*-8+random(s)*.1}}).sort((a,b)=>b.v-a.v)[0].m;cannonApply(s,best,-1);s.selected=null;s.turn++;log(s,`House ${best.kind}: ${coord(best.f)} → ${coord(best.t)}.`);if(!cannonEnd(s)&&!cannonMoves(s,1).length)finish(s,false,'Your army has no legal move.',s.turn*2)}
const cannon={stages:3,init(o){let s=base('cannon-council',o);s.b=Array(25).fill(0);s.b[22]=2;s.b[2]=-2;let own=[[15,16,17,21,23],[14,16,18,20,21,23],[12,15,17,20,23,24]][Math.min(o.stage,2)],enemy=[[5,6,7,1,3],[5,6,8,1,4],[5,7,9,0,3]][Math.min(o.stage,2)];if(o.mode==='endless'){own=shuffle(s,range(10).map(p=>p+15).filter(p=>p!==22)).slice(0,6);enemy=shuffle(s,range(10).filter(p=>p!==2)).slice(0,5)}own.forEach(p=>s.b[p]=1);enemy.forEach(p=>s.b[p]=-1);s.selected=null;s.note='Align three soldiers to shift a cannon or bombard beyond one empty muzzle square. Protect your ◆ town.';return s},act(s,k){if(k.startsWith('square-')){let p=+k.slice(7);if(s.b[p]===1)s.selected=p;return}let m=cannonMoves(s,1).find(m=>'move-'+m.f+'-'+m.t+'-'+m.kind===k);if(!m)return;cannonApply(s,m,1);log(s,`You ${m.kind}: ${coord(m.f)} → ${coord(m.t)}.`);if(!cannonEnd(s))cannonHouse(s)},render(ui,s){let ms=cannonMoves(s,1);ui.p(`Soldiers you ${material(s.b,1)} / house ${material(s.b,-1)} · Turn ${s.turn}/40. Three consecutive soldiers form a cannon in any of eight directions. Bombardment needs an empty muzzle gap; a nearer blocker stops the ray.`);grid(ui,s,[...new Set(ms.map(m=>m.f))]);ui.group('Soldier and formation orders');for(const m of ms.filter(m=>m.f===s.selected))ui.button(`move-${m.f}-${m.t}-${m.kind}`,`${m.kind} ${coord(m.t)}`);if(s.log.length)ui.pre(s.log.join('\n'))}};

export const boards={'tide-and-retreat':tide,'spore-council':spore,'shared-comet':comet,'socket-skirmish':socket,'cannon-council':cannon};
