/* Small, deterministic rule engines. Rendering and input live separately in game.js. */
const clone=s=>structuredClone(s),sum=a=>a.reduce((x,y)=>x+y,0),range=n=>Array.from({length:n},(_,i)=>i);
const dirs=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
const inside=(r,c,n)=>r>=0&&c>=0&&r<n&&c<n;
const cell=(id,text,label,kind='',legal=true)=>({id:String(id),text,label,kind,legal});
const finish=(s,title,note,score=1)=>Object.assign(s,{done:true,title,note,score});
const result=(s,a,b,noun='points')=>finish(s,a>b?'Your table. Your victory.':a===b?'A perfectly balanced draw.':'The house takes this round.',`You ${a} · House ${b} ${noun}. Play again to try a different opening.`,a>b?3:a===b?2:1);
function flips(b,p,who,n=4){if(b[p])return[];const r=Math.floor(p/n),c=p%n,out=[];for(const [dr,dc]of dirs){let y=r+dr,x=c+dc,line=[];while(inside(y,x,n)&&b[y*n+x]===-who){line.push(y*n+x);y+=dr;x+=dc;}if(line.length&&inside(y,x,n)&&b[y*n+x]===who)out.push(...line);}return out;}
function revMoves(b,w){return range(16).filter(p=>flips(b,p,w).length);}
function revBoard(b,p,w){b=[...b];for(const i of [p,...flips(b,p,w)])b[i]=w;return b;}
function revValue(b){return sum(b.map((v,i)=>v*([0,3,12,15].includes(i)?12:[5,6,9,10].includes(i)?1:3)));}
function revSearch(b,w,depth){const m=revMoves(b,w);if(!depth||(!m.length&&!revMoves(b,-w).length))return revValue(b);if(!m.length)return revSearch(b,-w,depth-1);const vals=m.map(p=>revSearch(revBoard(b,p,w),-w,depth-1));return w===1?Math.max(...vals):Math.min(...vals);}
const reversi={init:()=>({b:[0,0,0,0,0,1,-1,0,0,-1,1,0,0,0,0,0],turns:0,note:'You are ink. Place beside pale pieces to bracket and turn them.'}),actions:s=>revMoves(s.b,1).map(String),play(s,a){s=clone(s);s.b=revBoard(s.b,+a,1);s.turns++;s.note='House played. Your turn: dotted squares are legal.';for(let k=0;k<16;k++){const m=revMoves(s.b,-1);if(m.length){const p=m.sort((a,b)=>revSearch(revBoard(s.b,a,-1),1,3)-revSearch(revBoard(s.b,b,-1),1,3))[0];s.b=revBoard(s.b,p,-1);}if(revMoves(s.b,1).length)break;if(!revMoves(s.b,-1).length){result(s,s.b.filter(v=>v===1).length,s.b.filter(v=>v===-1).length,'discs');break;}s.note='You had no legal move, so the house played again.';}return s;},view:s=>({cols:4,cells:s.b.map((v,i)=>cell(i,v===1?'●':v===-1?'○':'·',`Square ${i+1}: ${v===1?'your disc':v===-1?'house disc':'empty'}`,v===1?'ink':v===-1?'pale':'',!v)),stats:[['You',s.b.filter(v=>v===1).length],['House',s.b.filter(v=>v===-1).length],['Turns',s.turns]]})};
const fourLines=[];for(let r=0;r<6;r++)for(let c=0;c<7;c++)for(const[dr,dc]of[[0,1],[1,0],[1,1],[1,-1]]){const line=range(4).map(k=>[r+dr*k,c+dc*k]);if(line.every(([y,x])=>y<6&&x>=0&&x<7))fourLines.push(line.map(([y,x])=>y*7+x));}
function fourWin(b,w){return fourLines.some(line=>line.every(p=>b[p]===w));}
function drops(b){return[3,2,4,1,5,0,6].filter(c=>!b[c]);}function drop(b,c,w){b=[...b];for(let r=5;r>=0;r--)if(!b[r*7+c]){b[r*7+c]=w;break;}return b;}
function fourSearch(b,w,d,alpha=-1e9,beta=1e9){if(fourWin(b,-1))return 100000+d;if(fourWin(b,1))return-100000-d;if(!d||!drops(b).length){let value=0;for(const line of fourLines){let me=0,them=0;for(const p of line){if(b[p]===-1)me++;else if(b[p]===1)them++;}if(!them)value+=[0,1,8,70,999][me];if(!me)value-=[0,1,9,80,999][them];}return value;}let best=w===-1?-1e9:1e9;for(const c of drops(b)){const v=fourSearch(drop(b,c,w),-w,d-1,alpha,beta);best=w===-1?Math.max(best,v):Math.min(best,v);if(w===-1)alpha=Math.max(alpha,best);else beta=Math.min(beta,best);if(beta<=alpha)break;}return best;}
const four={init:()=>({b:Array(42).fill(0),turns:0,note:'You are ink. Choose a column to drop a disc.'}),actions:s=>drops(s.b).map(String),play(s,a){s=clone(s);s.b=drop(s.b,+a,1);s.turns++;if(fourWin(s.b,1))return finish(s,'Four, beautifully connected.','Your line wins the round.',3);if(!drops(s.b).length)return finish(s,'Every space, shared.','The board is full. A draw.',2);const c=drops(s.b).map(c=>({c,value:fourSearch(drop(s.b,c,-1),1,3)})).sort((a,b)=>b.value-a.value)[0].c;s.b=drop(s.b,c,-1);s.note=`House dropped in column ${c+1}. Your move.`;if(fourWin(s.b,-1))finish(s,'The house found a line.','Look for both a threat and a block next time.',1);else if(!drops(s.b).length)finish(s,'Every space, shared.','The board is full. A draw.',2);return s;},view:s=>({cols:7,cells:s.b.map((v,i)=>cell('board-'+i,v===1?'●':v===-1?'○':'',`Row ${Math.floor(i/7)+1}, column ${i%7+1}: ${v===1?'you':v===-1?'house':'empty'}`,v===1?'ink':v===-1?'pale':'',false)),buttons:range(7).map(c=>cell(c,'↓ '+(c+1),'Drop in column '+(c+1))),stats:[['You','●'],['House','○'],['Drops',s.turns]]})};
function sow(b,p,who){b=[...b];let seeds=b[p];b[p]=0;let i=p;const store=who===1?6:13,skip=who===1?13:6;while(seeds){i=(i+1)%14;if(i===skip)continue;b[i]++;seeds--;}if(i!==store&&b[i]===1&&(who===1?i<6:i>6&&i<13)&&b[12-i]){b[store]+=b[12-i]+1;b[12-i]=b[i]=0;}return{b,again:i===store};}
function pits(b,w){return range(6).map(i=>i+(w===1?0:7)).filter(i=>b[i]);}
function kalahEnd(s){if(!pits(s.b,1).length||!pits(s.b,-1).length){s.b[6]+=sum(s.b.slice(0,6));s.b[13]+=sum(s.b.slice(7,13));for(let i=0;i<14;i++)if(i!==6&&i!==13)s.b[i]=0;result(s,s.b[6],s.b[13],'seeds');return true;}return false;}
const kalah={init:()=>({b:[3,3,3,3,3,3,0,3,3,3,3,3,3,0],turns:0,note:'Choose one of your six lower bowls. Seeds travel right along your row, then left along the house row.'}),actions:s=>pits(s.b,1).map(String),play(s,a){s=clone(s);const own=sow(s.b,+a,1);s.b=own.b;s.turns++;if(kalahEnd(s))return s;if(own.again){s.note='Last seed in your store: take another turn.';return s;}for(let k=0;k<50;k++){const m=pits(s.b,-1);const best=m.sort((a,b)=>{const av=sow(s.b,a,-1),bv=sow(s.b,b,-1);return(bv.b[13]-bv.b[6]+(bv.again?3:0))-(av.b[13]-av.b[6]+(av.again?3:0));})[0];const next=sow(s.b,best,-1);s.b=next.b;if(kalahEnd(s))return s;if(!next.again)break;}s.note='The house has sown. Choose a lower bowl.';return s;},view:s=>({cols:6,cells:[12,11,10,9,8,7,0,1,2,3,4,5].map(i=>cell(i,String(s.b[i]),`${i<6?'Your':'House'} bowl ${i<6?i+1:i-6}: ${s.b[i]} seeds`,i<6?'bowl':'bowl pale',i<6)),stats:[['Your store',s.b[6]],['House store',s.b[13]],['Turns',s.turns]],caption:'HOUSE ← 6 5 4 3 2 1  /  YOU → 1 2 3 4 5 6'})};
const nim={init:()=>({heaps:[3,4,5],turns:0,note:'Remove one or more matches from exactly one row. Take the last match to win.'}),actions:s=>s.heaps.flatMap((h,i)=>range(h).map(k=>i+':'+(k+1))),play(s,a){s=clone(s);const[i,n]=a.split(':').map(Number);s.heaps[i]-=n;s.turns++;if(!sum(s.heaps))return finish(s,'The last light is yours.','You took the last match. Well planned.',3);const xor=s.heaps.reduce((a,b)=>a^b,0);let h=s.heaps.findIndex(v=>(v^xor)<v),take;if(h<0){h=s.heaps.findIndex(Boolean);take=1;}else take=s.heaps[h]-(s.heaps[h]^xor);s.heaps[h]-=take;s.note=`House removed ${take} from row ${h+1}. Your turn.`;if(!sum(s.heaps))finish(s,'One match ahead.','House took the last match. Try leaving balanced heaps.',1);return s;},view:s=>({cols:1,cells:s.heaps.map((h,i)=>cell('heap'+i,'│ '.repeat(h)||'—',`Row ${i+1}: ${h} matches`,'matches',false)),buttons:s.heaps.flatMap((h,i)=>range(h).map(k=>cell(i+':'+(k+1),`Row ${i+1} −${k+1}`,`Remove ${k+1} from row ${i+1}`))),stats:s.heaps.map((h,i)=>['Row '+(i+1),h])})};
// Dots-and-boxes: edges on a 7×7 display, nine scoring cells.
const fenceEdges=()=>{const a=[];for(let y=0;y<7;y++)for(let x=0;x<7;x++)if((y%2)!==(x%2))a.push(y*7+x);return a;};
const boxEdges=p=>[p-7,p+7,p-1,p+1];const boxCenters=[8,10,12,22,24,26,36,38,40];
function fenceTake(s,e,w){s.edges[e]=w;let n=0;for(const p of boxCenters)if(!s.boxes[p]&&boxEdges(p).every(k=>s.edges[k])){s.boxes[p]=w;n++;}return n;}
const fences={init:()=>({edges:{},boxes:{},turns:0,note:'Join two dots. Completing a square scores a point and gives you another edge.'}),actions:s=>fenceEdges().filter(e=>!s.edges[e]).map(String),play(s,a){s=clone(s);s.turns++;const got=fenceTake(s,+a,1);if(!got){let guard=0;while(guard++<24){const free=fenceEdges().filter(e=>!s.edges[e]);if(!free.length)break;const score=e=>{let capture=0,danger=0;for(const p of boxCenters)if(boxEdges(p).includes(e)&&!s.boxes[p]){const n=boxEdges(p).filter(k=>s.edges[k]).length;if(n===3)capture++;if(n===2)danger++;}return capture*100-danger*10;};const e=free.sort((a,b)=>score(b)-score(a))[0];if(!fenceTake(s,e,-1))break;}}s.note=got?'Square signed. Take another edge.':'House drew its edge. Your turn.';if(Object.keys(s.boxes).length===9)result(s,Object.values(s.boxes).filter(v=>v===1).length,Object.values(s.boxes).filter(v=>v===-1).length,'squares');return s;},view:s=>({cols:7,kind:'fences',cells:range(49).map(p=>{const y=Math.floor(p/7),x=p%7;if(!(y%2)&&!(x%2))return cell('dot'+p,'•','Dot','dot',false);if(y%2&&x%2)return cell('box'+p,s.boxes[p]===1?'●':s.boxes[p]===-1?'○':'',`Square ${p}: ${s.boxes[p]===1?'yours':s.boxes[p]===-1?'house':'unclaimed'}`,'field '+(s.boxes[p]===1?'ink':''),false);return cell(p,s.edges[p]?(y%2?'│':'─'):'',`Draw ${y%2?'vertical':'horizontal'} edge ${p}`,`edge ${y%2?'vertical':'horizontal'} ${s.edges[p]===1?'ink':s.edges[p]===-1?'pale':''}`);}),stats:[['You',Object.values(s.boxes).filter(v=>v===1).length],['House',Object.values(s.boxes).filter(v=>v===-1).length],['Squares',Object.keys(s.boxes).length+'/9']]})};
const pegHoles=[2,6,7,8,10,11,12,13,14,16,17,18,22];
function pegMoves(b){const out=[];for(const p of b)for(const d of[-5,5,-1,1]){const q=p+d,r=p+2*d;if(pegHoles.includes(r)&&b.includes(q)&&!b.includes(r)&&Math.abs(p%5-r%5)+Math.abs(Math.floor(p/5)-Math.floor(r/5))===2)out.push([p,r]);}return out;}
const peg={init:()=>({b:[2,10,7,17,22,12,13],selected:null,moves:0,note:'Select a pebble, then an empty hole two spaces away. Jumped pebbles leave the board.'}),actions:s=>s.selected===null?s.b.map(String):[...s.b,...pegMoves(s.b).filter(([p])=>p===s.selected).map(([,r])=>r)].map(String),play(s,a){s=clone(s);const p=+a;if(s.b.includes(p)){s.selected=s.selected===p?null:p;s.note='Choose a highlighted landing hole, or select another pebble.';return s;}const from=s.selected;s.b=s.b.filter(v=>v!==from&&v!==(from+p)/2);s.b.push(p);s.selected=null;s.moves++;s.note='One less pebble. Every jump changes your options.';if(s.b.length===1)finish(s,'A single quiet pebble.','Six considered jumps. A perfect clearing.',7);else if(!pegMoves(s.b).length)finish(s,'The garden comes to rest.',`${s.b.length} pebbles remain. Restart and try a different opening.`,8-s.b.length);return s;},view:s=>({cols:5,cells:range(25).map(p=>cell(p,s.b.includes(p)?'●':pegHoles.includes(p)?'·':'',`Hole ${p+1}: ${s.b.includes(p)?'pebble':'empty'}`,!pegHoles.includes(p)?'void':s.selected===p?'selected':s.b.includes(p)?'ink':'',pegHoles.includes(p))),stats:[['Remaining',s.b.length],['Jumps',s.moves],['Goal','1']]})};
function pawnMoves(b,w){const out=[];for(let p=0;p<25;p++)if(b[p]===w){const r=Math.floor(p/5)+(w===1?-1:1);for(const dc of[-1,0,1]){const c=p%5+dc;if(inside(r,c,5)&&b[r*5+c]!==w&&(dc!==0||!b[r*5+c]))out.push([p,r*5+c]);}}return out;}
function pawnApply(b,m,w){b=[...b];b[m[0]]=0;b[m[1]]=w;return b;}function pawnWinner(b){if(b.slice(0,5).includes(1)||!b.includes(-1))return 1;if(b.slice(20).includes(-1)||!b.includes(1))return-1;return 0;}
function pawnSearch(b,w,d){const win=pawnWinner(b);if(win)return win*(10000+d);if(!d)return sum(b.map((v,i)=>v===1?(5-Math.floor(i/5))*5:v===-1?-(Math.floor(i/5)+1)*5:0));const m=pawnMoves(b,w);if(!m.length)return-w*10000;const vals=m.map(a=>pawnSearch(pawnApply(b,a,w),-w,d-1));return w===1?Math.max(...vals):Math.min(...vals);}
const pawns={init:()=>({b:[-1,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1],selected:null,turns:0,note:'Your ink pawns travel upward. Reach the far edge before the house reaches yours.'}),actions:s=>s.selected===null?pawnMoves(s.b,1).map(m=>String(m[0])):[...pawnMoves(s.b,1).map(m=>m[0]),...pawnMoves(s.b,1).filter(m=>m[0]===s.selected).map(m=>m[1])].map(String),play(s,a){s=clone(s);const p=+a;if(s.b[p]===1){s.selected=s.selected===p?null:p;return s;}s.b=pawnApply(s.b,[s.selected,p],1);s.selected=null;s.turns++;let win=pawnWinner(s.b);if(!win){const m=pawnMoves(s.b,-1);if(!m.length)win=1;else{s.b=pawnApply(s.b,m.sort((a,b)=>pawnSearch(pawnApply(s.b,a,-1),1,2)-pawnSearch(pawnApply(s.b,b,-1),1,2))[0],-1);win=pawnWinner(s.b);if(!pawnMoves(s.b,1).length)win=-1;}}if(win)finish(s,win===1?'A royal arrival.':'The house crossed first.',win===1?'Your pawn reached the far bank.':'Try keeping two pawns together to cover each other.',win===1?3:1);s.note=s.done?s.note:'House moved. Select a pawn, then a highlighted square.';return s;},view:s=>({cols:5,cells:s.b.map((v,p)=>cell(p,v===1?'♟':v===-1?'♙':'',`Square ${p+1}: ${v===1?'your pawn':v===-1?'house pawn':'empty'}`,s.selected===p?'selected':v===1?'ink':v===-1?'pale':'')),stats:[['You',s.b.filter(v=>v===1).length],['House',s.b.filter(v=>v===-1).length],['Turns',s.turns]]})};
const fleetShips=[[0,1,2],[9,14],[21,22]];
const fleet={init:()=>({shots:[],hits:[],note:'Three vessels hide in this 5×5 bay: lengths 3, 2, and 2. Ships are straight and never touch, even diagonally.'}),actions:s=>range(25).filter(p=>!s.shots.includes(p)).map(String),play(s,a){s=clone(s);const p=+a;s.shots.push(p);const ship=fleetShips.find(b=>b.includes(p));if(ship){s.hits.push(p);s.note=ship.every(i=>s.hits.includes(i))?`Vessel of length ${ship.length} located. Follow the remaining clues.`:'A hit. Vessels form straight lines.';}else s.note='Open water. That square is clear.';if(s.hits.length===7)finish(s,'Every vessel accounted for.',`Seven occupied squares found in ${s.shots.length} soundings. Same chart each replay: can you chart it with fewer?`,26-s.shots.length);return s;},view:s=>({cols:5,cells:range(25).map(p=>cell(p,s.hits.includes(p)?'◆':s.shots.includes(p)?'×':'·',`${String.fromCharCode(65+Math.floor(p/5))}${p%5+1}: ${s.hits.includes(p)?'vessel':s.shots.includes(p)?'water':'uncharted'}`,s.hits.includes(p)?'ink':s.shots.includes(p)?'pale':'')),stats:[['Soundings',s.shots.length],['Located',s.hits.length+'/7'],['Vessels',fleetShips.filter(b=>b.every(p=>s.hits.includes(p))).length+'/3']]})};
const guildValues=[3,1,2,2,1,4,1,3,2,1,4,1,2,3,1,2];
const adjacent=(p,n=4)=>[-n,n,-1,1].map(d=>p+d).filter(q=>q>=0&&q<n*n&&Math.abs(p%n-q%n)+Math.abs(Math.floor(p/n)-Math.floor(q/n))===1);
function guildScore(b,w){return sum(b.map((v,p)=>v===w?guildValues[p]+adjacent(p).filter(q=>q>p&&b[q]===w).length*2:0));}
const guild={init:()=>({b:Array(16).fill(0),turns:0,note:'Draft a district. Its printed value scores once; each shared edge between your districts adds 2.'}),actions:s=>range(16).filter(p=>!s.b[p]).map(String),play(s,a){s=clone(s);s.b[+a]=1;s.turns++;const free=range(16).filter(p=>!s.b[p]);if(free.length){const value=p=>guildValues[p]+adjacent(p).filter(q=>s.b[q]===-1).length*2+adjacent(p).filter(q=>s.b[q]===1).length*1.5;const p=free.sort((a,b)=>value(b)-value(a))[0];s.b[p]=-1;s.note=`House claimed district ${p+1}. Connected edges add up.`;}if(s.b.every(Boolean))result(s,guildScore(s.b,1),guildScore(s.b,-1),'influence');return s;},view:s=>({cols:4,cells:s.b.map((v,p)=>cell(p,`${guildValues[p]}${v===1?'●':v===-1?'○':''}`,`District ${p+1}, value ${guildValues[p]}, ${v===1?'yours':v===-1?'house':'available'}`,v===1?'ink':v===-1?'pale':'')),stats:[['You',guildScore(s.b,1)],['House',guildScore(s.b,-1)],['Round',s.turns+'/8']]})};
const orchard={init:()=>({trees:Array(9).fill(-1),water:8,fruit:0,day:0,note:'Twelve days until market. Plant for 2 water; trees ripen after 3 actions. Harvest ripe trees for 4 fruit.'}),actions:s=>['rain',...s.trees.flatMap((v,p)=>v<0&&s.water>=2||v>=3?[String(p)]:[])],play(s,a){s=clone(s);if(a==='rain'){s.water+=3;s.note='Rain collected: +3 water.';}else{const p=+a;if(s.trees[p]<0){s.trees[p]=0;s.water-=2;s.note='A new sapling. Two more actions until ripe.';}else{s.trees[p]=-1;s.fruit+=4;s.note='Four ripe fruits, ready for market.';}}s.day++;s.trees=s.trees.map(v=>v<0?v:Math.min(v+1,3));if(s.day===12)finish(s,s.fruit>=20?'A generous market basket.':'A quiet harvest.',`${s.fruit} fruit gathered in 12 days. The market goal is 20. Plant early, let actions ripen trees, then harvest.`,s.fruit+1);return s;},view:s=>({cols:3,cells:s.trees.map((v,p)=>cell(p,v<0?'+':v>=3?'✹':'♧ '+v,`Plot ${p+1}: ${v<0?'empty, plant for 2 water':v>=3?'ripe, harvest 4 fruit':`growing, ${3-v} actions until ripe`}`,v>=3?'ripe':v>=0?'growing':'')),buttons:[cell('rain','Collect rain +3','Spend one day collecting three water')],stats:[['Day',s.day+'/12'],['Water',s.water],['Fruit',s.fruit+'/20']]})};
const edgeKey=(a,b)=>[a,b].sort((a,b)=>a-b).join('-');
function bridgePath(p,goal,walls){const q=[[p,[]]],seen=new Set([p]);for(let i=0;i<q.length;i++){const[x,path]=q[i];if(Math.floor(x/5)===goal)return path;for(const n of adjacent(x,5))if(!walls.includes(edgeKey(x,n))&&!seen.has(n)){seen.add(n);q.push([n,[...path,n]]);}}return null;}
function wallLegal(s,a,b){if(!adjacent(a,5).includes(b)||s.walls.includes(edgeKey(a,b)))return false;const walls=[...s.walls,edgeKey(a,b)];return bridgePath(s.p,0,walls)!==null&&bridgePath(s.ai,4,walls)!==null;}
function bridgeMoves(s,p,other){
  const moves=new Set();
  for(const n of adjacent(p,5)){
    if(s.walls.includes(edgeKey(p,n)))continue;
    if(n!==other){moves.add(n);continue;}
    // Face-to-face couriers may jump straight over one another. If a wall or
    // board edge prevents that jump, they may step sideways around the other.
    const beyond=other+(other-p);
    if(adjacent(other,5).includes(beyond)&&!s.walls.includes(edgeKey(other,beyond)))moves.add(beyond);
    else for(const side of adjacent(other,5))if(side!==p&&!s.walls.includes(edgeKey(other,side)))moves.add(side);
  }
  return [...moves];
}
const bridge={init:()=>({p:22,ai:2,walls:[],stock:3,aiStock:3,mode:'move',selected:null,turns:0,note:'Reach the top row. Move one square, or spend a turn adding a fence between adjacent squares.'}),actions:s=>[...(s.stock>0?['mode']:[]),...(s.mode==='move'?bridgeMoves(s,s.p,s.ai).map(String):s.selected===null?range(25).map(String):[String(s.selected),...adjacent(s.selected,5).filter(n=>wallLegal(s,s.selected,n)).map(String)])],play(s,a){s=clone(s);if(a==='mode'){s.mode=s.mode==='move'&&s.stock>0?'wall':'move';s.selected=null;s.note=s.mode==='wall'?'Choose one end of your fence, then an adjacent square. A route must remain for both couriers.':'Choose a neighboring square to walk.';return s;}const p=+a;if(s.mode==='wall'){if(s.selected===null){s.selected=p;return s;}if(s.selected===p){s.selected=null;return s;}s.walls.push(edgeKey(s.selected,p));s.stock--;s.mode='move';s.selected=null;}else s.p=p;s.turns++;if(Math.floor(s.p/5)===0)return finish(s,'Across, with room to spare.','You reached the far bank first.',3);
    let placed=false;const own=bridgePath(s.ai,4,s.walls).length,theirs=bridgePath(s.p,0,s.walls).length;
    if(s.aiStock&&theirs<=own){const candidates=[];for(let a=0;a<25;a++)for(const b of adjacent(a,5))if(b>a&&wallLegal(s,a,b)){const ws=[...s.walls,edgeKey(a,b)],gain=bridgePath(s.p,0,ws).length-theirs-(bridgePath(s.ai,4,ws).length-own);if(gain>=2)candidates.push({e:edgeKey(a,b),gain});}if(candidates.length){s.walls.push(candidates.sort((a,b)=>b.gain-a.gain)[0].e);s.aiStock--;placed=true;}}
    if(!placed){const m=bridgeMoves(s,s.ai,s.p);if(m.length)s.ai=m.sort((a,b)=>bridgePath(a,4,s.walls).length-bridgePath(b,4,s.walls).length)[0];}
    if(Math.floor(s.ai/5)===4)finish(s,'The house crossed the bridge.','A fence costs a turn. Place one when the detour is worth it.',1);else if(s.turns>=60)finish(s,'A patient stalemate.','Sixty turns. Both couriers agree to meet another day.',2);else s.note=placed?'House placed a fence. Your route remains open.':'House moved. Your turn.';return s;},view:s=>({cols:5,cells:range(25).map(p=>{const c=cell(p,p===s.p?'●':p===s.ai?'○':'',`Square ${p+1}${p===s.p?', your courier':p===s.ai?', house courier':''}`,s.selected===p?'selected':p===s.p?'ink':p===s.ai?'pale':'');c.walls=adjacent(p,5).filter(n=>s.walls.includes(edgeKey(p,n))).map(n=>n===p-5?'up':n===p+5?'down':n===p-1?'left':'right');return c;}),buttons:[cell('mode',s.mode==='wall'?'Switch to walking':'Place a fence',s.mode==='wall'?'Switch to walking':'Choose fence mode')],stats:[['Your fences',s.stock],['House fences',s.aiStock],['Turns',s.turns]],caption:s.mode==='wall'?'FENCE MODE · choose two neighboring squares':'WALK MODE · reach the top row'})};
const hexNeighbors=p=>{const r=Math.floor(p/4),c=p%4;return[[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0]].map(([dr,dc])=>[r+dr,c+dc]).filter(([y,x])=>inside(y,x,4)).map(([y,x])=>y*4+x);};
function hexDistance(b,w){const dist=Array(16).fill(99),used=new Set();for(let p=0;p<16;p++)if(w===1?Math.floor(p/4)===0:p%4===0)dist[p]=b[p]===-w?99:b[p]===w?0:1;for(let i=0;i<16;i++){let p=-1;for(let k=0;k<16;k++)if(!used.has(k)&&(p<0||dist[k]<dist[p]))p=k;if(p<0)break;used.add(p);for(const q of hexNeighbors(p)){const v=b[q]===-w?99:b[q]===w?0:1;dist[q]=Math.min(dist[q],dist[p]+v);}}return Math.min(...range(16).filter(p=>w===1?Math.floor(p/4)===3:p%4===3).map(p=>dist[p]));}
const hex={init:()=>({b:Array(16).fill(0),turns:0,note:'Connect top to bottom with ink stones. The house connects left to right. Six-neighbor contact follows the slanted board.'}),actions:s=>range(16).filter(p=>!s.b[p]).map(String),play(s,a){s=clone(s);s.b[+a]=1;s.turns++;if(hexDistance(s.b,1)===0)return finish(s,'An unbroken thread.','Your ink stones connect the top and bottom banks.',3);const free=range(16).filter(p=>!s.b[p]);const value=p=>{const b=[...s.b];b[p]=-1;if(hexDistance(b,-1)===0)return 1e5;const threat=[...s.b];threat[p]=1;return(hexDistance(threat,1)===0?1e4:0)+hexDistance(b,1)*3-hexDistance(b,-1)*4+hexNeighbors(p).filter(q=>s.b[q]===-1).length*.1;};s.b[free.sort((a,b)=>value(b)-value(a))[0]]=-1;if(hexDistance(s.b,-1)===0)finish(s,'The house found its thread.','Its pale chain reached from left to right. Try connecting while cutting the other route.',1);else s.note='House placed a pale stone. Your turn.';return s;},view:s=>({cols:4,kind:'hex',cells:s.b.map((v,p)=>cell(p,v===1?'●':v===-1?'○':'',`Hex ${p+1}: ${v===1?'you':v===-1?'house':'empty'}`,v===1?'ink':v===-1?'pale':'')),stats:[['Your route','↕'],['House route','↔'],['Turns',s.turns]],caption:'INK: TOP ↕ BOTTOM · PALE: LEFT ↔ RIGHT'})};
function queenCover(q){const covered=new Set();for(const p of q)for(let x=0;x<25;x++)if(Math.floor(p/5)===Math.floor(x/5)||p%5===x%5||Math.abs(Math.floor(p/5)-Math.floor(x/5))===Math.abs(p%5-x%5))covered.add(x);return covered;}
const towers={init:()=>({q:[],note:'Place exactly three watchtowers. Each watches its row, column, and diagonals. Cover all 25 squares.'}),actions:s=>[...range(25).filter(p=>s.q.length<3||s.q.includes(p)).map(String),...(s.q.length===3?['submit']:[])],play(s,a){s=clone(s);if(a==='submit'){const n=queenCover(s.q).size;return finish(s,n===25?'Every corner, cared for.':'A few quiet blind spots.',`${n} of 25 squares watched by three towers. Shift your arrangement and try again.`,n);}const p=+a;s.q=s.q.includes(p)?s.q.filter(x=>x!==p):[...s.q,p];s.note=`${queenCover(s.q).size} of 25 squares watched. ${s.q.length===3?'Inspect the coverage, then seal your plan.':'Place '+(3-s.q.length)+' more tower'+(s.q.length===2?'':'s')+'.'}`;return s;},view:s=>({cols:5,cells:range(25).map(p=>cell(p,s.q.includes(p)?'♜':queenCover(s.q).has(p)?'·':'',`Square ${p+1}: ${s.q.includes(p)?'tower, tap to remove':queenCover(s.q).has(p)?'watched':'unwatched'}`,s.q.includes(p)?'ink':queenCover(s.q).has(p)?'covered':'')),buttons:[cell('submit','Seal the plan','Finish with this tower arrangement')],stats:[['Towers',s.q.length+'/3'],['Watched',queenCover(s.q).size+'/25'],['Goal','25']]})};
function rays(b,p){const out=[],r=Math.floor(p/4),c=p%4;for(const[dr,dc]of dirs){let y=r+dr,x=c+dc;while(inside(y,x,4)&&!b[y*4+x]){out.push(y*4+x);y+=dr;x+=dc;}}return out;}
const siege={init:()=>({b:[0,0,-1,0,0,0,0,0,0,0,0,0,0,1,0,0],phase:'move',turns:0,note:'Move your ink queen in a straight line, then close one visible empty square. Trap the house queen before it traps you.'}),actions:s=>rays(s.b,s.b.indexOf(1)).map(String),play(s,a){s=clone(s);const p=+a;if(s.phase==='move'){s.b[s.b.indexOf(1)]=0;s.b[p]=1;s.phase='block';s.note='Now close an empty square along a clear row, column, or diagonal.';return s;}s.b[p]=2;s.turns++;const ai=s.b.indexOf(-1),m=rays(s.b,ai);if(!m.length)return finish(s,'A perfectly quiet siege.','The house queen has no legal move. Your enclosure wins.',3);
  let best=null;for(const dest of m){const b=[...s.b];b[ai]=0;b[dest]=-1;for(const wall of rays(b,dest)){b[wall]=2;const mine=rays(b,b.indexOf(1)).length,theirs=rays(b,dest).length,value=mine===0?1000:theirs-mine*1.5;if(!best||value>best.value)best={dest,wall,value};b[wall]=0;}}s.b[ai]=0;s.b[best.dest]=-1;s.b[best.wall]=2;s.phase='move';if(!rays(s.b,s.b.indexOf(1)).length)finish(s,'Your queen finds a quiet corner.','No legal moves remain. Leave yourself a corridor next time.',1);else s.note='House moved and closed a square. Move your queen, then place your own barrier.';return s;},view:s=>({cols:4,cells:s.b.map((v,p)=>cell(p,v===1?'♛':v===-1?'♕':v===2?'×':'',`Square ${p+1}: ${v===1?'your queen':v===-1?'house queen':v===2?'closed':'empty'}`,v===1?'ink':v===-1?'pale':v===2?'blocked':'')),stats:[['Action',s.phase==='move'?'Move':'Close'],['Turns',s.turns],['Open',s.b.filter(v=>!v).length]]})};
const prices=[3,5,2,4,7,3,6,8];
const trade={init:()=>({day:0,cash:12,goods:0,note:'Eight market days. Buy low, sell high. Prices are public; carry at most three crates. Finish with 24 coins.'}),actions:s=>['wait',...(s.cash>=prices[s.day]&&s.goods<3?['buy']:[]),...(s.goods?['sell']:[])],play(s,a){s=clone(s);const price=prices[s.day];if(a==='buy'){s.cash-=price;s.goods++;s.note=`Bought one crate for ${price} coins.`;}else if(a==='sell'){s.cash+=price;s.goods--;s.note=`Sold one crate for ${price} coins.`;}else s.note='You let this market pass.';s.day++;if(s.day===8){s.cash+=s.goods*prices[7];s.goods=0;finish(s,s.cash>=24?'A tidy little enterprise.':'The market closes.',`${s.cash} coins after the last-day automatic sale. Goal: 24. One trade per day; timing is everything.`,s.cash);}return s;},view:s=>({cols:4,cells:prices.map((p,i)=>cell('day'+i,String(p),`Day ${i+1}: price ${p} coins`,i===s.day?'selected':i<s.day?'pale':'',false)),buttons:[cell('buy','Buy one','Buy one crate at today’s price'),cell('sell','Sell one','Sell one crate at today’s price'),cell('wait','Wait','Pass today without trading')],stats:[['Day',Math.min(s.day+1,8)+'/8'],['Coins',s.cash],['Crates',s.goods+'/3']],caption:'PUBLIC PRICE CALENDAR · ONE ACTION PER DAY'})};
export const engines={reversi,four,kalah,nim,fences,peg,pawns,fleet,guild,orchard,bridge,hex,towers,siege,trade};
export function start(id){return engines[id].init();}
export function legal(id,s){return s.done?[]:[...new Set(engines[id].actions(s))];}
export function step(id,s,a){return legal(id,s).includes(String(a))?engines[id].play(s,String(a)):s;}
export function view(id,s){return engines[id].view(s);}
