import {range,a,finish,compare,random} from './core.mjs';
const G={};
const dirs=[[0,-1],[1,-1],[1,0],[1,1],[0,1],[-1,1],[-1,0],[-1,-1]];
const orth=[[0,-1],[1,0],[0,1],[-1,0]];
const at=(x,y,n)=>x>=0&&y>=0&&x<n&&y<n?y*n+x:-1;
const side=v=>Math.sign(v);
const cellName=(i,n)=>`${String.fromCharCode(65+i%n)}${Math.floor(i/n)+1}`;
function selectActions(s,moves){const sources=[...new Set(moves.map(m=>m.f))];return [...sources.map(i=>a('s'+i,'Select '+cellName(i,s.n),'Board',s.selected===i)),...moves.filter(m=>m.f===s.selected).map(m=>a('m'+m.t,'Move to '+cellName(m.t,s.n),'Board'))];}
function boardView(s,extra=[]){return {stats:[`Turn ${s.turn+1}`,`You ${s.b.filter(v=>v>0).length} pieces`,`House ${s.b.filter(v=>v<0).length} pieces`],board:{n:s.n,cells:s.b.map((v,i)=>({text:v===2?'♔':v===-2?'♚':v===1?'●':v===-1?'○':'',label:`${cellName(i,s.n)}: ${v===2?'your master':v===-2?'house master':v===1?'your piece':v===-1?'house piece':'empty'}`,special:(s.special||[]).includes(i)}))},panels:extra};}
function genericMove(s,x,moves,apply,aiMoves,score,terminal){if(x[0]==='s'){s.selected=+x.slice(1);s.note='Choose a highlighted destination.';return;}const m=moves(s,1).find(m=>m.f===s.selected&&m.t===+x.slice(1));apply(s,m,1);s.selected=null;if(terminal(s,1))return;const opts=aiMoves(s,-1);if(!opts.length)return finish(s,'win','The house has no legal move.');let best=null,val=-Infinity;for(const m of opts){const q=structuredClone(s);apply(q,m,-1);const v=score(q,m)+(random(s)*.02);if(v>val){val=v;best=m;}}apply(s,best,-1);s.turn++;s.note=`You moved ${cellName(m.f,s.n)} → ${cellName(m.t,s.n)}. House ${cellName(best.f,s.n)} → ${cellName(best.t,s.n)}.`;if(terminal(s,-1))return;if(!moves(s,1).length)finish(s,'loss','You have no legal move.');}
// Crown & Guard: asymmetric rook mobility, hostile throne/corners, escorted king.
const corners=[0,6,42,48],throne=24;
function taflMoves(s,who){const out=[];s.b.forEach((v,f)=>{if(side(v)!==who)return;for(const [dx,dy]of orth){for(let n=1;n<7;n++){const t=at(f%7+dx*n,Math.floor(f/7)+dy*n,7);if(t<0||s.b[t])break;if(v===2||(!corners.includes(t)&&t!==throne))out.push({f,t});}}});return out;}
function taflApply(s,m,who){const v=s.b[m.f];s.b[m.f]=0;s.b[m.t]=v;for(const[dx,dy]of orth){const mid=at(m.t%7+dx,Math.floor(m.t/7)+dy,7),end=at(m.t%7+dx*2,Math.floor(m.t/7)+dy*2,7);if(mid<0||end<0||s.b[mid]===2)continue;if(side(s.b[mid])===-who&&(side(s.b[end])===who||corners.includes(end)||(end===throne&&!s.b[end])))s.b[mid]=0;}}
function taflEnd(s){const k=s.b.indexOf(2);if(corners.includes(k)){finish(s,'win','The crown reaches an open corner.');return true;}const trapped=orth.every(([dx,dy])=>{const i=at(k%7+dx,Math.floor(k/7)+dy,7);return i<0||s.b[i]===-1;});if(trapped){finish(s,'loss','The crown is surrounded on all four sides.');return true;}if(s.turn>=80){finish(s,'loss','Eighty turns. The attackers hold the siege.');return true;}return false;}
G['crown-and-guard']={init(s){s.n=7;s.b=Array(49).fill(0);s.b[24]=2;[17,23,25,31].forEach(i=>s.b[i]=1);[2,3,21,28,45,46,20,27].forEach(i=>s.b[i]=-1);s.special=[...corners,throne];s.turn=0;s.selected=null;},actions(s){return selectActions(s,taflMoves(s,1));},move(s,x){genericMove(s,x,taflMoves,taflApply,taflMoves,q=>{const k=q.b.indexOf(2),near=orth.filter(([dx,dy])=>{const i=at(k%7+dx,Math.floor(k/7)+dy,7);return i<0||q.b[i]===-1;}).length;return (taflEnd(q)?q.outcome==='loss'?10000:-10000:0)+near*12-q.b.filter(v=>v===1).length*5-q.b.filter(v=>v===-1).length*-4-taflMoves(q,1).filter(m=>m.f===k&&corners.includes(m.t)).length*100;},taflEnd);},view(s){return boardView(s,[['Special squares','Crown ♔ · guards ● · attackers ○. Only the crown may stop on the gold throne or corners.']]);}};
// Draughts: captures compulsory, chains locked to one piece, promotion ends the turn.
function draughtMoves(s,who,locked=null){const jumps=[],steps=[];s.b.forEach((v,f)=>{if(side(v)!==who||(locked!==null&&f!==locked))return;const ds=Math.abs(v)===2?[[-1,-1],[1,-1],[-1,1],[1,1]]:[[-1,-who],[1,-who]];for(const [dx,dy]of ds){const mid=at(f%6+dx,Math.floor(f/6)+dy,6);if(mid<0)continue;if(!s.b[mid])steps.push({f,t:mid});else if(side(s.b[mid])===-who){const t=at(f%6+2*dx,Math.floor(f/6)+2*dy,6);if(t>=0&&!s.b[t])jumps.push({f,t,c:mid});}}});return jumps.length?jumps:locked!==null?[]:steps;}
function draughtApply(s,m,who){const v=s.b[m.f];s.b[m.f]=0;s.b[m.t]=v;if(m.c!==undefined)s.b[m.c]=0;const promote=Math.abs(v)===1&&Math.floor(m.t/6)===(who===1?0:5);if(promote)s.b[m.t]=who*2;s.quiet=m.c!==undefined||promote?0:s.quiet+1;return promote;}
function draughtEnd(s){if(!s.b.some(v=>v<0)||!draughtMoves(s,-1).length){finish(s,'win','The house has no legal move.');return true;}if(!s.b.some(v=>v>0)||!draughtMoves(s,1).length){finish(s,'loss','Your draughts have no legal move.');return true;}if(s.quiet>=80){finish(s,'draw','Forty turns without capture or promotion.');return true;}if(s.turn>=160){finish(s,'draw','The long match ends level after 160 turns.');return true;}return false;}
G['draught-garden']={init(s){s.n=6;s.b=range(36).map(i=>(i%6+Math.floor(i/6))%2===1?(i<12?-1:i>=24?1:0):0);s.turn=0;s.quiet=0;s.selected=null;s.chain=null;},actions(s){return selectActions(s,draughtMoves(s,1,s.chain));},move(s,x){if(x[0]==='s'){s.selected=+x.slice(1);return;}const m=draughtMoves(s,1,s.chain).find(m=>m.f===s.selected&&m.t===+x.slice(1)),promote=draughtApply(s,m,1);if(m.c!==undefined&&!promote&&draughtMoves(s,1,m.t).length){s.chain=m.t;s.selected=m.t;s.note='Continue the compulsory capture with this piece.';return;}s.chain=null;s.selected=null;if(draughtEnd(s))return;let lock=null;do{const opts=draughtMoves(s,-1,lock);opts.sort((a,b)=>(b.c!==undefined?100:0)+(Math.floor(b.t/6)===5?20:0)+Math.floor(b.t/6)-(a.c!==undefined?100:0)-(Math.floor(a.t/6)===5?20:0)-Math.floor(a.t/6));const best=opts[0];if(!best)break;const promoted=draughtApply(s,best,-1);s.note=`House moves ${cellName(best.f,6)} → ${cellName(best.t,6)}.`;lock=best.c!==undefined&&!promoted&&draughtMoves(s,-1,best.t).length?best.t:null;}while(lock!==null);s.turn++;draughtEnd(s);},view(s){const moves=draughtMoves(s,1,s.chain);return boardView(s,[['Move rule',s.chain!==null?'Capture chain: continue with the selected piece.':moves.some(m=>m.c!==undefined)?'A capture is compulsory.':'Step diagonally forward. Crowned pieces can move backward.']]);}};
// Borrowed Steps: two cards per side, one exchanged spare; movement is relative to owner.
const patterns=[{name:'Tiger',d:[[0,-2],[0,1]]},{name:'Crab',d:[[-2,0],[0,-1],[2,0]]},{name:'Monkey',d:[[-1,-1],[1,-1],[-1,1],[1,1]]},{name:'Crane',d:[[0,-1],[-1,1],[1,1]]},{name:'Dragon',d:[[-2,-1],[2,-1],[-1,1],[1,1]]}];
function oniMoves(s,who){const out=[],cards=who===1?s.pc:s.hc;s.b.forEach((v,f)=>{if(side(v)!==who)return;cards.forEach((id,slot)=>patterns[id].d.forEach(([dx,dy])=>{const t=at(f%5+dx*who,Math.floor(f/5)+dy*who,5);if(t>=0&&side(s.b[t])!==who)out.push({f,t,slot,id});}));});return out;}
function oniApply(s,m,who){s.b[m.t]=s.b[m.f];s.b[m.f]=0;const cards=who===1?s.pc:s.hc;[cards[m.slot],s.spare]=[s.spare,cards[m.slot]];}
function oniEnd(s){if(!s.b.includes(-2)||s.b[2]===2){finish(s,'win','Your master claims the temple or captures its rival.');return true;}if(!s.b.includes(2)||s.b[22]===-2){finish(s,'loss','The house master claims victory.');return true;}if(s.turn>=80){finish(s,'draw','Eighty turns; both schools stand.');return true;}return false;}
G['borrowed-steps']={init(s){s.n=5;s.b=range(25).map(i=>i<5?i===2?-2:-1:i>=20?i===22?2:1:0);s.pc=[0,1];s.hc=[2,3];s.spare=4;s.turn=0;s.selected=null;s.cardSlot=0;s.special=[2,22];},actions(s){return [...s.pc.map((id,i)=>a('card'+i,patterns[id].name,'Movement card',s.cardSlot===i)),...selectActions(s,oniMoves(s,1).filter(m=>m.slot===s.cardSlot))];},move(s,x){if(x.startsWith('card')){s.cardSlot=+x.slice(4);s.selected=null;return;}if(x[0]==='s'){s.selected=+x.slice(1);return;}const m=oniMoves(s,1).find(m=>m.slot===s.cardSlot&&m.f===s.selected&&m.t===+x.slice(1));oniApply(s,m,1);s.selected=null;if(oniEnd(s))return;const opts=oniMoves(s,-1);if(!opts.length)return finish(s,'win','House has no legal move.');const scored=opts.map(m=>{const q=structuredClone(s);const captured=Math.max(0,q.b[m.t]);oniApply(q,m,-1);const threat=oniMoves(q,1).some(p=>q.b[p.t]===-2||(q.b[p.f]===2&&p.t===2));return {m,v:(oniEnd(q)&&q.outcome==='loss'?10000:0)+captured*15-(threat?1000:0)+Math.floor(m.t/5)};}).sort((a,b)=>b.v-a.v);oniApply(s,scored[0].m,-1);s.turn++;s.note=`House uses ${patterns[scored[0].m.id].name}. Used cards exchange with the spare.`;oniEnd(s);if(!s.done&&!oniMoves(s,1).length)finish(s,'loss','Your school has no legal move.');},view(s){const describe=id=>patterns[id].name+': '+patterns[id].d.map(([x,y])=>`${x<0?-x+' left':x>0?x+' right':'straight'}, ${y<0?-y+' forward':y>0?y+' back':'level'}`).join(' / ');return boardView(s,[['Your movement cards',s.pc.map(describe).join('\n')],['House cards (from house perspective)',s.hc.map(describe).join('\n')],['Spare card',describe(s.spare)]]);}};
// Marble Council: axial hex coordinates, up to three inline marbles; strict pushing advantage.
const hexes=[];for(let r=-3;r<=3;r++)for(let q=-3;q<=3;q++)if(Math.abs(q+r)<=3)hexes.push([q,r]);
const hd=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]],hn=['east','southeast','southwest','west','northwest','northeast'];
const hi=(q,r)=>hexes.findIndex(h=>h[0]===q&&h[1]===r);
function hexNext(i,d){const [q,r]=hexes[i],[dq,dr]=hd[d];return hi(q+dq,r+dr);}
function marbleMoves(s,who){const out=[];s.b.forEach((v,f)=>{if(v!==who)return;for(let d=0;d<6;d++){const own=[f];let t=hexNext(f,d);while(t>=0&&s.b[t]===who&&own.length<=3){own.push(t);t=hexNext(t,d);}if(own.length>3||t<0)continue;const enemy=[];while(t>=0&&s.b[t]===-who){enemy.push(t);t=hexNext(t,d);}if(enemy.length>=own.length||enemy.length>2||t>=0&&s.b[t])continue;if(!enemy.length&&t<0)continue;out.push({f,t:d,d,own,enemy,eject:enemy.length&&t<0});}});return out;}
function marbleApply(s,m,who){const ids=[...m.own,...m.enemy],vals=ids.map(i=>s.b[i]);ids.forEach(i=>s.b[i]=0);ids.forEach((i,j)=>{const next=hexNext(i,m.d);if(next>=0)s.b[next]=vals[j];else s[who===1?'you':'them']++;});}
function marbleEnd(s){if(s.you>=3||s.them>=3){compare(s,s.you,s.them,'Ejections');return true;}if(s.turn>=50){const center=who=>s.b.reduce((v,p,i)=>v+(p===who?4-Math.max(...hexes[i].map(Math.abs),Math.abs(sumHex(hexes[i]))):0),0);compare(s,s.you*100+center(1),s.them*100+center(-1),'Ejections ×100 + central presence');return true;}return false;}
const sumHex=h=>h[0]+h[1];
G['marble-council']={init(s){s.n=7;s.b=hexes.map(([q,r])=>r<=-2?-1:r>=2?1:0);s.turn=0;s.selected=null;s.you=0;s.them=0;},actions(s){const ms=marbleMoves(s,1);return [...[...new Set(ms.map(m=>m.f))].map(i=>a('s'+i,`Select marble ${hexes[i].join(', ')}`,'Board',s.selected===i)),...ms.filter(m=>m.f===s.selected).map(m=>a('d'+m.d,`${hn[m.d]} · move ${m.own.length}${m.enemy.length?', push '+m.enemy.length:''}${m.eject?' · eject':''}`,'Push direction'))];},move(s,x){if(x[0]==='s'){s.selected=+x.slice(1);return;}const m=marbleMoves(s,1).find(m=>m.f===s.selected&&m.d===+x.slice(1));marbleApply(s,m,1);s.selected=null;if(marbleEnd(s))return;const opts=marbleMoves(s,-1);if(!opts.length)return finish(s,'win','House has no legal push.');const scored=opts.map(m=>{const q=structuredClone(s);marbleApply(q,m,-1);const danger=marbleMoves(q,1).filter(p=>p.eject).length;const central=q.b.reduce((v,p,i)=>v+(p===-1?4-Math.max(Math.abs(hexes[i][0]),Math.abs(hexes[i][1]),Math.abs(sumHex(hexes[i]))):0),0);return {m,v:(m.eject?1000:0)-danger*200+m.enemy.length*8+central};}).sort((a,b)=>b.v-a.v);marbleApply(s,scored[0].m,-1);s.turn++;s.note=`House pushes ${hn[scored[0].m.d]}${scored[0].m.eject?' and ejects a marble':''}.`;marbleEnd(s);if(!s.done&&!marbleMoves(s,1).length)finish(s,'loss','No legal push remains.');},view(s){return {stats:[`You eject ${s.you}/3`,`House ${s.them}/3`,`Turn ${s.turn}/50`],board:{hex:true,n:7,cells:hexes.map(([q,r],i)=>({text:s.b[i]===1?'●':s.b[i]===-1?'○':'',label:`Axial ${q}, ${r}: ${s.b[i]===1?'your marble':s.b[i]===-1?'house marble':'empty'}`,q,r}))},panels:[['Inline movement','Select the rear marble of a line. Directions show group size and pushes. An equal-strength group cannot push.']]};}};
// Lines of Action: occupied line sets travel distance; opponents block transit, not destination.
function loaMoves(s,who){const out=[];s.b.forEach((v,f)=>{if(v!==who)return;for(const[dx,dy]of dirs){let count=1;for(const sign of[-1,1])for(let k=1;k<6;k++){const t=at(f%6+dx*k*sign,Math.floor(f/6)+dy*k*sign,6);if(t<0)break;if(s.b[t])count++;}const t=at(f%6+dx*count,Math.floor(f/6)+dy*count,6);if(t<0||s.b[t]===who)continue;let clear=true;for(let k=1;k<count;k++){const mid=at(f%6+dx*k,Math.floor(f/6)+dy*k,6);if(s.b[mid]===-who)clear=false;}if(clear)out.push({f,t});}});return out;}
function components(s,who){const remaining=new Set(s.b.flatMap((v,i)=>v===who?[i]:[]));let count=0;while(remaining.size){count++;const queue=[remaining.values().next().value];remaining.delete(queue[0]);for(const p of queue)for(const[dx,dy]of dirs){const t=at(p%6+dx,Math.floor(p/6)+dy,6);if(remaining.delete(t))queue.push(t);}}return count;}
function loaApply(s,m){s.b[m.t]=s.b[m.f];s.b[m.f]=0;}
function loaEnd(s,mover){const p=components(s,1)===1,h=components(s,-1)===1;if(p||h){finish(s,p&&h?mover===1?'win':'loss':p?'win':'loss','All remaining pieces connect through neighboring squares.');return true;}if(s.turn>=80){finish(s,'draw','Eighty turns; the armies remain divided.');return true;}return false;}
G['joining-lines']={init(s){s.n=6;s.b=range(36).map(i=>Math.floor(i/6)===0||Math.floor(i/6)===5?i%6>0&&i%6<5?1:0:i%6===0||i%6===5?-1:0);s.turn=0;s.selected=null;},actions(s){return selectActions(s,loaMoves(s,1));},move(s,x){genericMove(s,x,loaMoves,loaApply,loaMoves,(q,m)=>{const win=components(q,-1)===1;return (win?10000:0)-components(q,-1)*40+components(q,1)*8-(Math.abs(m.t%6-2.5)+Math.abs(Math.floor(m.t/6)-2.5));},loaEnd);},view(s){return boardView(s,[['Connected groups',`You ${components(s,1)} · house ${components(s,-1)}. Merge yours into one group. Diagonal neighbors count.`]]);}};
// Terrace Duel: every move followed by local construction, reachable winning levels.
function terraceMoves(s,who){const out=[];s.b.forEach((v,f)=>{if(v!==who)return;for(const[dx,dy]of dirs){const t=at(f%5+dx,Math.floor(f/5)+dy,5);if(t>=0&&!s.b[t]&&s.h[t]<4&&s.h[t]<=s.h[f]+1)out.push({f,t});}});return out;}
function builds(s,t,from){return dirs.map(([dx,dy])=>at(t%5+dx,Math.floor(t/5)+dy,5)).filter(i=>i>=0&&(!s.b[i]||i===from)&&s.h[i]<4);}
function terraceApply(s,m,who){s.b[m.f]=0;s.b[m.t]=who;if(m.build!==undefined)s.h[m.build]++;}
function terraceEnd(s){if(s.b.some((v,i)=>v===1&&s.h[i]===3)){finish(s,'win','Your worker reaches the third level.');return true;}if(s.b.some((v,i)=>v===-1&&s.h[i]===3)){finish(s,'loss','House reaches the third level first.');return true;}if(!terraceMoves(s,1).length){finish(s,'loss','Both workers are trapped.');return true;}if(!terraceMoves(s,-1).length){finish(s,'win','The house workers are trapped.');return true;}return false;}
G['terrace-duel']={init(s){s.n=5;s.b=Array(25).fill(0);s.h=Array(25).fill(0);[20,24].forEach(i=>s.b[i]=1);[0,4].forEach(i=>s.b[i]=-1);s.turn=0;s.selected=null;s.buildFrom=null;},actions(s){if(s.buildFrom!==null)return builds(s,s.buildFrom,-1).map(i=>a('b'+i,'Build at '+cellName(i,5),'Board'));return selectActions(s,terraceMoves(s,1));},move(s,x){if(x[0]==='s'){s.selected=+x.slice(1);return;}if(x[0]==='m'){const t=+x.slice(1);terraceApply(s,{f:s.selected,t},1);s.selected=null;if(s.h[t]===3){finish(s,'win','Your worker reaches the third level.');return;}s.buildFrom=t;s.note='Now build on a highlighted neighboring square.';return;}s.h[+x.slice(1)]++;s.buildFrom=null;const opts=terraceMoves(s,-1).flatMap(m=>s.h[m.t]===3?[m]:builds(s,m.t,m.f).map(b=>({...m,build:b})));if(!opts.length)return finish(s,'win','The house has no complete move.');const scored=opts.map(m=>{const q=structuredClone(s);terraceApply(q,m,-1);const danger=terraceMoves(q,1).filter(p=>q.h[p.t]===3).length;return {m,v:(s.h[m.t]===3?10000:0)-danger*1000+s.h[m.t]*30+(m.build!==undefined&&q.h[m.build]===s.h[m.t]+1?8:0)-Math.abs(m.t%5-2)-Math.abs(Math.floor(m.t/5)-2)};}).sort((a,b)=>b.v-a.v);terraceApply(s,scored[0].m,-1);s.turn++;s.note=`House moves to ${cellName(scored[0].m.t,5)}${scored[0].m.build!==undefined?' and builds at '+cellName(scored[0].m.build,5):''}.`;terraceEnd(s);},view(s){const v=boardView(s,[['Height key','0 ground · 1 first floor · 2 second floor · 3 winning terrace · 4 closed dome. Move, then build.']]);v.board.cells=v.board.cells.map((c,i)=>({...c,text:(s.h[i]===4?'▰':s.h[i])+ (s.b[i]===1?' ●':s.b[i]===-1?' ○':''),label:`${cellName(i,5)}: height ${s.h[i]}${s.h[i]===4?', dome':''}, ${s.b[i]===1?'your worker':s.b[i]===-1?'house worker':'empty'}`,height:s.h[i]}));return v;}};
export default G;
