import {start,actions,step,view} from './engines.mjs';
const $=id=>document.getElementById(id);
const manifest=await fetch('games.json').then(r=>{if(!r.ok)throw Error('Game list unavailable');return r.json();});
const id=new URLSearchParams(location.search).get('game');
const game=manifest.find(g=>g.id===id)||manifest[0];
let seed=87321,state=start(game.id,seed),playing=false,bidQuantity=null,largeBoardMode=false;
document.title=game.name+' — Small Hours';$('title').textContent=game.name;$('tagline').textContent=game.description;$('seal').textContent=game.symbol;$('controls').textContent=game.controls;document.documentElement.style.setProperty('--table-accent',game.accent);
for(const rule of game.rules){const li=document.createElement('li');li.textContent=rule;$('rules').append(li);}
function button(action){const b=document.createElement('button');b.type='button';b.className='move';b.dataset.action=action.code;b.textContent=action.label;b.setAttribute('aria-pressed',String(!!action.selected));b.addEventListener('click',()=>{if(b.dataset.boardAction)largeBoardMode=true;play(action.code);});return b;}
function render(restore=true){const fromLarge=largeBoardMode||!!document.activeElement?.dataset?.boardAction;const old=document.activeElement?.dataset?.action||document.activeElement?.dataset?.boardAction;const wasPlaying=playing;const v=view(state),as=actions(state);$('welcome').hidden=playing;$('play-area').hidden=!playing;$('scoreboard').replaceChildren(...v.stats.map(t=>{const el=document.createElement('strong');el.textContent=t;return el;}));$('status').textContent=playing?state.note:'Read the rules, then take a seat.';document.body.dataset.completed=String(state.done);document.body.dataset.outcome=state.outcome||'';
$('panels').replaceChildren(...(v.panels||[]).map(([title,copy])=>{const section=document.createElement('section');section.className='info-panel';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=copy;section.append(h,p);return section;}));
const board=$('board');board.replaceChildren();board.className=v.board?.hex?'hex':'';
if(v.board){board.style.gridTemplateColumns=`repeat(${v.board.n}, minmax(0, 1fr))`;v.board.cells.forEach((c,i)=>{const acts=as.filter(a=>a.group==='Board');const action=acts.find(a=>a.code==='m'+i||a.code==='b'+i)||acts.find(a=>a.code==='s'+i);const b=document.createElement('button');b.type='button';b.className='cell'+(action?.selected?' selected':'')+(action&&action.code[0]!=='s'?' destination':'')+(c.special?' special':'');b.textContent=c.text;b.setAttribute('aria-label',c.label+(action?' · '+action.label:' · unavailable'));b.setAttribute('aria-disabled',String(!action));if(action){b.dataset.action=action.code;b.addEventListener('click',()=>{largeBoardMode=false;play(action.code);});}if(v.board.hex){b.style.gridColumnStart=String(c.q*2+c.r+7);b.style.gridRowStart=String(c.r+4);b.style.gridColumnEnd='span 2';}else{const co=document.createElement('span');co.className='coordinate';co.setAttribute('aria-hidden','true');co.textContent=String.fromCharCode(65+i%v.board.n)+(Math.floor(i/v.board.n)+1);b.append(co);}board.append(b);});}
$('actions').replaceChildren();
// Dense boards keep their spatial map and offer equally capable, large controls.
const boardActions=as.filter(action=>action.group==='Board');
if(boardActions.length){const section=document.createElement('section');section.className='control-group board-alternatives';const heading=document.createElement('h3');heading.textContent='Large board controls';const row=document.createElement('div');row.className='control-row';for(const action of boardActions){const b=button(action);delete b.dataset.action;b.dataset.boardAction=action.code;const index=Number(action.code.slice(1));b.setAttribute('aria-label',action.label+'. '+(v.board?.cells[index]?.label||''));row.append(b);}section.append(heading,row);$('actions').append(section);}
for(const group of [...new Set(as.filter(a=>a.group!=='Board').map(a=>a.group))]){const section=document.createElement('section');section.className='control-group';const h=document.createElement('h3');h.textContent=group;const row=document.createElement('div');row.className='control-row';const groupActions=as.filter(a=>a.group===group);
if(game.id==='hidden-dice'&&group==='Raise the bid'){
const quantities=[...new Set(groupActions.map(a=>Number(a.code.slice(1).split(':')[0])))];
if(!quantities.includes(bidQuantity))bidQuantity=quantities[0];
const label=document.createElement('label');label.className='bid-quantity';label.textContent='Quantity of matching dice';const select=document.createElement('select');select.id='bid-quantity';for(const n of quantities){const option=document.createElement('option');option.value=n;option.textContent=n+' '+(n===1?'die':'dice');option.selected=n===bidQuantity;select.append(option);}select.addEventListener('change',()=>{bidQuantity=Number(select.value);render(false);$('bid-quantity')?.focus();});label.append(select);row.append(label,...groupActions.filter(a=>Number(a.code.slice(1).split(':')[0])===bidQuantity).map(button));
}else row.append(...groupActions.map(button));section.append(h,row);$('actions').append(section);}
$('result').hidden=!state.done;$('result-title').textContent=state.done?state.note:'';$('result-outcome').textContent=state.outcome==='win'?'A well-played round':state.outcome==='draw'?'Honors shared':'The table has another lesson';if(restore&&playing){if(state.done)$('again').focus({preventScroll:true});else if(old){const target=(fromLarge?([...document.querySelectorAll('[data-board-action]')].find(b=>b.dataset.boardAction===old)||document.querySelector('[data-board-action]')):null)||[...document.querySelectorAll('[data-action]')].find(b=>b.dataset.action===old)||document.querySelector('[data-action]');target?.focus({preventScroll:true});}}}
function play(code){if(!playing||state.done)return;state=step(state,code);render();}
function reset(newDeal=false){bidQuantity=null;largeBoardMode=false;if(newDeal)seed=(seed+7919)>>>0;state=start(game.id,seed);playing=true;render(false);document.querySelector('[data-action]')?.focus({preventScroll:true});}
$('start').addEventListener('click',()=>{playing=true;render(false);document.querySelector('[data-action]')?.focus({preventScroll:true});});$('restart').addEventListener('click',()=>reset());$('again').addEventListener('click',()=>reset());$('new-deal').addEventListener('click',()=>reset(true));
document.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)||!document.activeElement?.closest('#play-area'))return;const controls=[...document.querySelectorAll('#play-area button')];const current=controls.indexOf(document.activeElement);if(current<0)return;let offset=e.key==='ArrowLeft'?-1:e.key==='ArrowRight'?1:e.key==='ArrowUp'?-(view(state).board?.n||1):(view(state).board?.n||1);e.preventDefault();controls[(current+offset+controls.length)%controls.length]?.focus();});
render(false);document.body.dataset.gameId=game.id;document.body.dataset.gameReady='true';
