(() => {
 'use strict';
 const $ = id => document.getElementById(id), D = WordRoomData;
 const requested = new URLSearchParams(location.search).get('game');
 const game = WordRoomCatalog.find(g => g.id === requested) || WordRoomCatalog[0];
 const shuffle = array => SmallHours.shuffle([...array]);
 const pick = array => array[Math.floor(Math.random() * array.length)];
 const el = (tag, text, className) => {const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;};
 const board=$('board'); let state, render, keyHandler = null, previous = -1;
 document.body.dataset.gameId=game.id;document.documentElement.style.setProperty('--accent',game.accent);
 document.title=`${game.name} — Small Hours`; $('title').textContent=game.name+'.';$('subtitle').textContent=game.description;$('symbol').textContent=game.symbol;$('aside-title').textContent=game.name;
 game.rules.forEach(text=>{const li=el('li');li.append(el('p',text));$('rules').append(li);});
 WordRoomCatalog.forEach(item=>{const a=el('a',item.name);a.href=`?game=${item.id}`;if(item.id===game.id)a.setAttribute('aria-current','page');$('room-links').append(a);});
 const record=SmallHours.record('small-hours-word-room-'+game.id);
 const say=text=>{$('message').textContent=text;};
 function stats(progress){$('progress').textContent=progress;$('score').textContent=state.score;$('mistakes').textContent=state.mistakes;}
 function mistake(text){if(state.done)return;state.mistakes++;state.score=Math.max(100,state.score-10);$('score').textContent=state.score;$('mistakes').textContent=state.mistakes;say(text);}
 function button(text, action, cls='tile'){const b=el('button',text.endsWith(' ↗')?text.slice(0,-2):text,cls);if(text.endsWith(' ↗')){const arrow=el('span',' ↗');arrow.setAttribute('aria-hidden','true');b.append(arrow);}b.type='button';b.addEventListener('click',()=>{if(!state.done)action();});return b;}
 function focus(selector){board.querySelector(selector)?.focus();}
 function note(text){board.append(el('p',text,'instruction'));}
 function prompt(text){board.append(el('p',text,'prompt'));}
 function actions(...buttons){const row=el('div',undefined,'actions');row.append(...buttons);board.append(row);return row;}
 function form(label,submit,maxLength=30){const f=el('form',undefined,'word-form'),l=el('label',label),wrap=el('div',undefined,'input-wrap'),input=el('input');input.id='entry';input.autocomplete='off';input.autocapitalize='characters';input.spellcheck=false;input.maxLength=maxLength;l.htmlFor='entry';const b=el('button','Submit','cta');const arrow=el('span',' ↗');arrow.setAttribute('aria-hidden','true');b.append(arrow);b.type='submit';wrap.append(input,b);f.append(l,wrap);f.addEventListener('submit',event=>{event.preventDefault();if(!state.done)submit(input.value.trim().toUpperCase());});board.append(f);return input;}
 function win(text='You found your way through every word.'){if(state.done)return;state.done=true;record.save(state.score);$('result-title').textContent='A page well played.';$('result-copy').textContent=`${text} ${state.score} points, ${state.mistakes} misstep${state.mistakes===1?'':'s'}.`;$('result').hidden=false;board.querySelectorAll('button,input').forEach(n=>n.disabled=true);say('Complete. '+text);$('again').focus();}
 function loss(text){state.done=true;$('result-title').textContent='Another page awaits.';$('result-copy').textContent=text;$('result').hidden=false;board.querySelectorAll('button,input').forEach(n=>n.disabled=true);say(text);$('again').focus();}
 function oneOf(array){let index=Math.floor(Math.random()*array.length);if(index===previous)index=(index+1)%array.length;previous=index;return array[index];}
 function begin(){state={done:false,score:1000,mistakes:0};keyHandler=null;$('result').hidden=true;board.replaceChildren();engines[game.id]();document.body.dataset.gameReady='true';}
 function gridKeys(grid,columns){grid.addEventListener('keydown',event=>{const nodes=[...grid.querySelectorAll('button,input')],index=nodes.indexOf(event.target);if(index<0)return;let next=index;if(event.key==='ArrowRight')next++;else if(event.key==='ArrowLeft')next--;else if(event.key==='ArrowDown')next+=columns;else if(event.key==='ArrowUp')next-=columns;else return;event.preventDefault();nodes[Math.max(0,Math.min(nodes.length-1,next))].focus();});}
 function shortRound(items,draw){state.items=shuffle(items).slice(0,3);state.round=0;state.accepted=false;render=()=>{board.replaceChildren();stats(`${state.round} / 3`);draw(state.items[state.round]);};state.advance=()=>{state.round++;state.accepted=false;render();focus('input,button');say('A fresh little puzzle.');};render();}
 function solvedShort(text){if(state.accepted)return;state.accepted=true;stats(`${state.round+1} / 3`);board.querySelectorAll('button,input').forEach(n=>n.disabled=true);say(text);board.append(el('p',text,'feedback-note'));if(state.round===2)win(text);else{const next=button('Next page ↗',state.advance,'cta');actions(next);next.focus();}}
 const engines={
 'hidden-grove'(){
  const words=oneOf(D.search);let cells,placements;
  const dirs=[[1,0],[0,1],[1,1],[-1,0],[0,-1],[-1,-1],[1,-1],[-1,1]];
  for(let attempt=0;attempt<100;attempt++){
   cells=Array(36).fill('');placements=[];
   for(const word of words){let placed=false;for(let tries=0;tries<250;tries++){const x=Math.floor(Math.random()*6),y=Math.floor(Math.random()*6),[dx,dy]=pick(dirs),endX=x+dx*(word.length-1),endY=y+dy*(word.length-1);if(endX<0||endX>5||endY<0||endY>5)continue;const path=[...word].map((_,i)=>(y+dy*i)*6+x+dx*i);if(path.some((at,i)=>cells[at]&&cells[at]!==word[i]))continue;path.forEach((at,i)=>cells[at]=word[i]);placements.push(path);placed=true;break;}if(!placed)break;}
   if(placements.length===words.length)break;
  }
  // Deterministic safe fallback if random placement cannot fit the four words.
  if(placements.length!==words.length){cells=Array(36).fill('');placements=words.map((w,r)=>[...w].map((ch,c)=>{cells[r*6+c]=ch;return r*6+c;}));}
  cells=cells.map(c=>c||pick([...'ABCDEFGHIJKLMNOPQRSTUVWXYZ']));state.found=[];state.highlight=[];state.start=null;
  const select=index=>{if(state.start===null){state.start=index;render();focus(`[data-cell="${index}"]`);say('Start marked. Choose the last letter.');return;}if(state.start===index){state.start=null;render();focus(`[data-cell="${index}"]`);say('Selection cleared.');return;}const from=state.start;state.start=null;const dx=index%6-from%6,dy=Math.floor(index/6)-Math.floor(from/6);let path=[];if(dx===0||dy===0||Math.abs(dx)===Math.abs(dy)){const length=Math.max(Math.abs(dx),Math.abs(dy))+1;path=Array.from({length},(_,i)=>from+i*Math.sign(dx)+i*Math.sign(dy)*6);}const text=path.map(i=>cells[i]).join(''),word=words.find(w=>w===text||w===[...text].reverse().join(''));if(word&&!state.found.includes(word)){state.found.push(word);state.highlight.push(...path);say(`${word} found.`);}else if(word)say('You have already found that word.');else mistake('That line is not one of the four words. Try another start and end.');render();focus(`[data-cell="${index}"]`);if(state.found.length===4)win('All four hidden words found.');};
  render=()=>{board.replaceChildren();stats(`${state.found.length} / 4`);note('Tap a word’s first letter, then its last. No dragging needed.');const grid=el('div',undefined,'grid search');grid.setAttribute('role','group');grid.setAttribute('aria-label','Six by six word search');cells.forEach((ch,i)=>{const b=button(ch,()=>select(i));b.dataset.cell=i;b.setAttribute('aria-label',`${ch}, row ${Math.floor(i/6)+1}, column ${i%6+1}`);b.setAttribute('aria-pressed',String(state.start===i));b.classList.toggle('found',state.highlight.includes(i));grid.append(b);});gridKeys(grid,6);board.append(grid);const list=el('ul',undefined,'list');words.forEach(w=>list.append(el('li',w,state.found.includes(w)?'done':'')));board.append(list);};render();say('Four words are hiding in plain sight.');
 },
 'one-letter-away'(){
  const chain=oneOf(D.ladders),start=chain[0],target=chain.at(-1),vocabulary=[...new Set(D.ladders.flat())].sort();state.path=[start];
  const submit=word=>{const current=state.path.at(-1);if(!vocabulary.includes(word)){mistake('Use a four-letter word from the notebook.');return;}if([...word].filter((ch,i)=>ch!==current[i]).length!==1){mistake('Change exactly one letter from '+current+'.');return;}if(state.path.includes(word)){mistake('That word is already on your path. Undo to revisit it.');return;}state.path.push(word);render();focus('input');say(`${word} is a valid step.`);if(word===target)win(`From ${start} to ${target} in ${state.path.length-1} steps.`);};
  render=()=>{board.replaceChildren();stats(`${state.path.length-1} steps`);prompt(`${start} → ${target}`);const path=el('div',undefined,'progress-path');state.path.forEach(w=>path.append(el('span',w)));board.append(path);form('Your next four-letter word',submit,4);const undo=button('Undo step',()=>{if(state.path.length>1)state.path.pop();render();focus('input');say('Last step removed.');},'quiet');undo.disabled=state.path.length===1;actions(undo);const detail=el('details');detail.open=true;detail.append(el('summary','The complete word notebook'));const shelf=el('div',undefined,'word-shelf');vocabulary.forEach(w=>shelf.append(el('span',w)));detail.append(shelf);board.append(detail);};render();say('One letter at a time. The notebook is your map.');
 },
 'last-letter'(){
  const [word,clue]=oneOf(D.words);state.guesses=[];state.wrong=0;
  const guess=letter=>{if(state.guesses.includes(letter))return;state.guesses.push(letter);if(!word.includes(letter)){state.wrong++;mistake(`${letter} is not in the word. ${6-state.wrong} leaves remain.`);}else say(`${letter} belongs in the word.`);render();focus('.keyboard button:not(:disabled)');if([...word].every(c=>state.guesses.includes(c)))win(`The word was ${word}.`);else if(state.wrong===6)loss(`The word was ${word}. All six leaves have fallen. Try a fresh clue.`);};
  render=()=>{board.replaceChildren();stats(`${6-state.wrong} leaves`);prompt(clue);const garden=el('div','✿'.repeat(6-state.wrong)+'·'.repeat(state.wrong),'life-garden');garden.setAttribute('aria-hidden','true');board.append(garden);const masked=[...word].map(c=>state.guesses.includes(c)?c:'_').join(' '),line=el('p',masked,'masked');line.setAttribute('aria-label','Word: '+masked);board.append(line);const keys=el('div',undefined,'keyboard');[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'].forEach(c=>{const b=button(c,()=>guess(c));b.disabled=state.guesses.includes(c);b.setAttribute('aria-label','Guess '+c);if(b.disabled&&word.includes(c))b.classList.add('correct');keys.append(b);});board.append(keys);};keyHandler=e=>{if(/^[a-z]$/i.test(e.key)){e.preventDefault();guess(e.key.toUpperCase());}};render();say('Six leaves. One hidden word.');
 },
 'crossings'(){
  const puzzle=oneOf(D.crosswords);const answer=Array(25).fill(null);[0,2,4].forEach((r,i)=>[...puzzle.across[i][0]].forEach((c,x)=>answer[r*5+x]=c));[...puzzle.down[0]].forEach((c,r)=>answer[r*5+2]=c);state.letters=Array(25).fill('');state.checked=false;
  render=()=>{board.replaceChildren();stats(`${state.letters.filter(Boolean).length} / 17`);const grid=el('div',undefined,'grid crossword');answer.forEach((ch,i)=>{const cell=el('div',undefined,'cross-cell'+(ch?'':' block'));if(ch){const input=el('input');input.maxLength=1;input.autocomplete='off';input.autocapitalize='characters';input.spellcheck=false;input.value=state.letters[i];input.dataset.cell=i;input.setAttribute('aria-label',`Row ${Math.floor(i/5)+1}, column ${i%5+1}`);input.addEventListener('input',()=>{state.letters[i]=input.value.replace(/[^a-z]/gi,'').toUpperCase().slice(-1);input.value=state.letters[i];cell.classList.remove('correct');stats(`${state.letters.filter(Boolean).length} / 17`);});input.addEventListener('keydown',event=>{const shifts={ArrowRight:1,ArrowLeft:-1,ArrowDown:5,ArrowUp:-5};if(shifts[event.key]){event.preventDefault();let next=i+shifts[event.key];while(next>=0&&next<25&&!answer[next])next+=shifts[event.key];grid.querySelector(`[data-cell="${next}"]`)?.focus();}});cell.append(input);const number={0:'1',2:'2',10:'3',20:'4'}[i];if(number)cell.append(el('span',number));if(state.checked&&state.letters[i]===ch)cell.classList.add('correct');}else cell.setAttribute('aria-hidden','true');grid.append(cell);});board.append(grid);const clues=el('div',undefined,'clues'),across=el('div'),down=el('div');across.append(el('h3','Across'));puzzle.across.forEach((a,i)=>across.append(el('p',`${[1,3,4][i]}. ${a[1]} (5)`)));down.append(el('h3','Down'),el('p',`2. ${puzzle.down[1]} (5)`));clues.append(across,down);board.append(clues);actions(button('Check grid ↗',()=>{if(state.letters.filter(Boolean).length<17){say('Fill all seventeen white squares first.');focus('input');return;}state.checked=true;if(answer.every((c,i)=>!c||c===state.letters[i])){render();win('Four clues, one connected crossword.');}else{mistake('Some letters need another look. Correct squares are now green.');render();focus('input');}},'cta'));};render();say('Three across. One down. Every crossing counts.');
 },
 'wordbreak'(){
  let boundaries=new Set();shortRound(D.breaks,([phrase,clue])=>{boundaries=new Set();const letters=phrase.replaceAll(' ','');const expected=[];let count=0;phrase.split(' ').slice(0,-1).forEach(w=>{count+=w.length;expected.push(count-1);});prompt(clue);note('Tap between letters to add a space.');const line=el('div',undefined,'boundary-line');[...letters].forEach((ch,i)=>{line.append(el('span',ch));if(i<letters.length-1){const b=button('·',()=>{boundaries.has(i)?boundaries.delete(i):boundaries.add(i);b.textContent=boundaries.has(i)?'│':'·';b.setAttribute('aria-pressed',String(boundaries.has(i)));},'boundary');b.dataset.boundary=i;b.setAttribute('aria-label',`Space after letter ${i+1}, ${ch}`);b.setAttribute('aria-pressed','false');line.append(b);}});board.append(line);actions(button('Check spaces ↗',()=>{if(boundaries.size===expected.length&&expected.every(i=>boundaries.has(i)))solvedShort(phrase[0].toUpperCase()+phrase.slice(1)+'.');else mistake('The phrase needs different spaces. Read the clue and try again.');},'cta'));});say('A sentence is hiding between the letters.');
 },
 'secret-post'(){
  const [plain,clue]=oneOf(D.ciphers),alphabet=[...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'],permutation=shuffle(alphabet),encode=Object.fromEntries(alphabet.map((c,i)=>[c,permutation[i]]));const cipher=[...plain].map(c=>encode[c]||c).join('');state.mapping={};state.selected=[...cipher].find(c=>c!==' ');
  const setLetter=letter=>{const old=Object.keys(state.mapping).find(k=>state.mapping[k]===letter&&k!==state.selected);if(old){say(`${letter} is already assigned to cipher ${old}. Clear that tile first.`);return;}state.mapping[state.selected]=letter;render();focus(`[data-code="${state.selected}"]`);say(`Cipher ${state.selected} now reads ${letter}.`);};
  const check=()=>{if([...cipher].every((c,i)=>c===' '||state.mapping[c]===plain[i]))win(plain+'.');else mistake('The whole message is not decoded yet. Repeated cipher letters share one answer.');};
  render=()=>{board.replaceChildren();const unique=[...new Set(cipher.replaceAll(' ',''))];stats(`${unique.filter(c=>state.mapping[c]).length} / ${unique.length}`);prompt(clue);const phrase=el('div',undefined,'cipher-phrase');cipher.split(' ').forEach(word=>{const group=el('div',undefined,'cipher-word');[...word].forEach(c=>{const unit=el('div',undefined,'cipher-unit'),b=button(state.mapping[c]||'·',()=>{state.selected=c;render();focus(`[data-code="${c}"]`);say(`Choose the letter for cipher ${c}.`);});b.dataset.code=c;b.setAttribute('aria-label',`Cipher ${c}, ${state.mapping[c]||'unassigned'}`);b.setAttribute('aria-pressed',String(state.selected===c));unit.append(b,el('span',c));group.append(unit);});phrase.append(group);});board.append(phrase);note(`Selected cipher: ${state.selected}. Type a letter or choose below.`);const keys=el('div',undefined,'keyboard');alphabet.forEach(c=>keys.append(button(c,()=>setLetter(c))));board.append(keys);actions(button('Clear letter',()=>{delete state.mapping[state.selected];render();focus(`[data-code="${state.selected}"]`);},'quiet'),button('Reveal one −20',()=>{const index=[...cipher].findIndex((c,i)=>c!==' '&&state.mapping[c]!==plain[i]);if(index<0){say('Your message is ready to check.');return;}const c=cipher[index],letter=plain[index];Object.keys(state.mapping).forEach(k=>{if(state.mapping[k]===letter)delete state.mapping[k];});state.mapping[c]=letter;state.selected=c;state.score=Math.max(100,state.score-20);render();focus(`[data-code="${c}"]`);say(`Cipher ${c} means ${letter}. Twenty points used.`);},'quiet'),button('Check message ↗',check,'cta'));};keyHandler=e=>{if(/^[a-z]$/i.test(e.key)){e.preventDefault();setLetter(e.key.toUpperCase());}else if(e.key==='Backspace'){e.preventDefault();delete state.mapping[state.selected];render();focus(`[data-code="${state.selected}"]`);}};render();say('One substitution opens many doors.');
 },
 'center-letter'(){
  const puzzle=oneOf(D.centers);state.found=[];
  const submit=word=>{if(state.found.includes(word)){say('That word is already on your page.');return;}if(!word.includes(puzzle.center)||[...word].some(c=>!puzzle.letters.includes(c))){mistake(`Use only these letters, including ${puzzle.center}.`);return;}if(!puzzle.words.some(w=>w[0]===word)){mistake('That is not one of this puzzle’s five clue answers.');return;}state.found.push(word);render();focus('input');say(word+' found.');if(state.found.length===5)win('All five words share their center.');};
  render=()=>{board.replaceChildren();stats(`${state.found.length} / 5`);const honey=el('div',undefined,'honey');honey.append(el('strong',puzzle.center),document.createTextNode([...puzzle.letters].filter(c=>c!==puzzle.center).join(' ')));board.append(honey);form('A clue word using the center letter',submit,12);const list=el('ul',undefined,'list');puzzle.words.forEach(([word,clue])=>list.append(el('li',`${state.found.includes(word)?word+' — ':''}${clue} (${word.length})`,state.found.includes(word)?'done':'')));board.append(list);};render();say('Five words. One essential letter.');
 },
 'odd-company'(){
  shortRound(D.odd,([question,words,answer,explanation])=>{prompt(question);const row=el('div',undefined,'tiles');shuffle(words).forEach(word=>row.append(button(word,()=>{if(word===answer)solvedShort(explanation);else mistake(`${word} belongs to the group. Look for the exception.`);})));board.append(row);});say('Three belong together. Find the fourth.');
 },
 'alphabet-trail'(){
  // Generate a full orthogonal path before placing letters, so every board is solvable.
  const neighbors=i=>[i%5>0?i-1:-1,i%5<4?i+1:-1,i>=5?i-5:-1,i<20?i+5:-1].filter(n=>n>=0);
  let path=[],budget=18000;const visited=new Set();
  function walk(at){if(--budget<0)return false;path.push(at);visited.add(at);if(path.length===25)return true;const options=shuffle(neighbors(at).filter(n=>!visited.has(n))).sort((a,b)=>neighbors(a).filter(n=>!visited.has(n)).length-neighbors(b).filter(n=>!visited.has(n)).length);for(const next of options)if(walk(next))return true;path.pop();visited.delete(at);return false;}
  const starts=Array.from({length:25},(_,i)=>i).filter(i=>(i%5+Math.floor(i/5))%2===0);
  if(!walk(pick(starts))){path=[];for(let r=0;r<5;r++)for(let c=0;c<5;c++)path.push(r*5+(r%2?4-c:c));}
  const cells=Array(25);path.forEach((at,i)=>cells[at]=String.fromCharCode(65+i));state.path=[];
  const choose=i=>{const expected=String.fromCharCode(65+state.path.length),last=state.path.at(-1);if(cells[i]!==expected||(last!==undefined&&Math.abs(i%5-last%5)+Math.abs(Math.floor(i/5)-Math.floor(last/5))!==1)){mistake(`Next is ${expected}, one horizontal or vertical step away.`);return;}state.path.push(i);render();focus(`[data-cell="${i}"]`);say(`${cells[i]} added. ${state.path.length<25?'Next is '+String.fromCharCode(65+state.path.length)+'.':'Trail complete.'}`);if(state.path.length===25)win('A to Y, with every letter connected.');};
  render=()=>{board.replaceChildren();stats(`${state.path.length} / 25`);note(`Next letter: ${String.fromCharCode(65+Math.min(state.path.length,24))}. Neighbors share an edge.`);const grid=el('div',undefined,'grid trail');cells.forEach((c,i)=>{const b=button(c,()=>choose(i));b.dataset.cell=i;b.setAttribute('aria-label',`${c}, row ${Math.floor(i/5)+1}, column ${i%5+1}`);b.classList.toggle('found',state.path.includes(i));b.setAttribute('aria-pressed',String(state.path.at(-1)===i));grid.append(b);});gridKeys(grid,5);board.append(grid);const undo=button('Undo letter',()=>{state.path.pop();render();focus('.grid button');say('Last letter removed.');},'quiet');undo.disabled=!state.path.length;actions(undo);};render();say('Begin with A. Follow the alphabet through the garden.');
 },
 'sentence-studio'(){
  shortRound(D.sentences,([sentence,clue])=>{const words=sentence.split(' '),order=shuffle(words.map((_,i)=>i));let selected=[];prompt(clue);const answer=el('div',undefined,'answer-line'),bank=el('div',undefined,'tiles');const draw=()=>{answer.replaceChildren();bank.replaceChildren();selected.forEach((id,at)=>answer.append(button(words[id],()=>{selected.splice(at,1);draw();(answer.children[Math.min(at,selected.length-1)]||bank.querySelector('button:not(:disabled)')).focus();})));order.forEach(id=>{const b=button(words[id],()=>{selected.push(id);draw();(selected.length===words.length?check:bank.querySelector('button:not(:disabled)')).focus();});b.disabled=selected.includes(id);bank.append(b);});};board.append(answer,bank);const check=button('Check saying ↗',()=>{if(selected.length!==words.length){say('Use every word slip first.');return;}if(selected.map(i=>words[i]).join(' ')===sentence)solvedShort(sentence);else mistake('That is not quite the familiar saying. Move a word and try again.');},'cta');actions(button('Clear',()=>{selected=[];draw();bank.querySelector('button').focus();},'quiet'),check);draw();});say('Put a familiar thought back together.');
 },
 'compound-works'(){pairEngine(D.compounds,false);},
 'rhyme-lines'(){pairEngine(D.rhymes,true);},
 'vowel-weather'(){
  shortRound(D.words,([word,clue])=>{prompt(clue);const pattern=word.replace(/[AEIOU]/g,'_');board.append(el('p',pattern.split('').join(' '),'masked'));form('The restored whole word',value=>{if(value.length!==word.length||[...pattern].some((c,i)=>c!=='_'?value[i]!==c:!/[AEIOU]/.test(value[i]||''))){mistake('Keep the consonants in place and put only vowels in the blanks.');return;}if(value===word)solvedShort(word+' — restored.');else mistake('Those vowels do not match the clue. Try another combination.');},word.length);});say('A, E, I, O and U: bring the missing ones home.');
 },
 'chain-reaction'(){
  const words=oneOf(D.chains),order=shuffle(words.slice(1));state.chain=[words[0]];
  render=()=>{board.replaceChildren();stats(`${state.chain.length} / 6`);const line=el('div',undefined,'progress-path');state.chain.forEach(word=>line.append(el('span',word)));board.append(line);note('Next word must begin with '+state.chain.at(-1).at(-1)+'.');const bank=el('div',undefined,'tiles');order.forEach(word=>{const b=button(word,()=>{if(word[0]!==state.chain.at(-1).at(-1)){mistake('Match the last letter of the chain to the first letter of the next word.');return;}state.chain.push(word);render();focus('.tiles button:not(:disabled)');say(word+' joins the chain.');if(state.chain.length===6)win('Six words, one continuous thread.');});b.disabled=state.chain.includes(word);bank.append(b);});board.append(bank);const undo=button('Undo join',()=>{state.chain.pop();render();focus('.tiles button:not(:disabled)');say('Last word returned.');},'quiet');undo.disabled=state.chain.length===1;actions(undo);};render();say('The end of one word begins another.');
 },
 'proofreader'(){
  shortRound(D.proofs,([sentence,wrong,correct])=>{note('Exactly one word needs a spelling correction.');const row=el('div',undefined,'sentence-words');sentence.split(' ').forEach(word=>{const b=button(word,()=>{if(word.replace(/[.,!?]/g,'')!==wrong){mistake('That word is already spelled correctly. Look elsewhere in the sentence.');return;}row.querySelectorAll('button').forEach(n=>n.setAttribute('aria-pressed',String(n===b)));let input=board.querySelector('input');if(!input){input=form('Correct spelling of '+wrong,value=>{if(value===correct.toUpperCase())solvedShort(sentence.replace(wrong,correct));else mistake('That spelling still needs a little repair.');},20);}input.value=wrong;input.focus();input.select();});row.append(b);});board.append(row);});say('A tiny typo is hiding in this sentence.');
 }
 };
 function pairEngine(packs,rhyme){const pairs=oneOf(packs),left=shuffle(pairs.map((_,i)=>i)),right=shuffle(pairs.map((_,i)=>i));state.found=[];state.selected=null;render=()=>{board.replaceChildren();stats(`${state.found.length} / 4`);note(rhyme?'Match ending sounds, even when spellings differ.':'Choose the beginning on the left, then the ending on the right.');const columns=el('div',undefined,'pair-columns');[left,right].forEach((order,side)=>{const col=el('div',undefined,'tiles');order.forEach(i=>{const b=button(pairs[i][side],()=>{if(side===0){state.selected=i;render();focus('[data-side="1"]:not(:disabled)');say('Now choose its partner on the right.');}else if(state.selected===null)say('Choose a word on the left first.');else if(i===state.selected){state.found.push(i);state.selected=null;render();focus('[data-side="0"]:not(:disabled)');say(rhyme?`${pairs[i][0]} rhymes with ${pairs[i][1]}.`:pairs[i].join('')+' joined.');if(state.found.length===4)win(rhyme?'Four pairs in perfect rhyme.':'Four compound words, neatly joined.');}else{state.selected=null;mistake('Those two do not make a matching pair. Choose a new beginning.');render();focus('[data-side="0"]:not(:disabled)');}});b.dataset.side=side;b.dataset.pair=i;b.disabled=state.found.includes(i);b.classList.toggle('correct',state.found.includes(i));b.setAttribute('aria-pressed',String(side===0&&state.selected===i));col.append(b);});columns.append(col);});board.append(columns);};render();say(rhyme?'Follow the sound.':'Two little words become one.');}
 document.addEventListener('keydown',event=>{if(state.done||event.ctrlKey||event.metaKey||event.altKey||event.repeat||['INPUT','TEXTAREA'].includes(event.target.tagName))return;if(keyHandler)keyHandler(event);});
 $('restart').addEventListener('click',begin);$('again').addEventListener('click',begin);begin();
})();
