import{base,random,level,win,lose,sum,cards,record,spend}from'./core.mjs';

function pageParent(s,id){return Object.values(s.pages).find(p=>p.children.includes(id))}
function pageLeaves(s){const out=[];function go(id,depth){const p=s.pages[id];if(!p.children.length)out.push([id,depth]);else p.children.forEach(x=>go(x,depth+1))}go(s.root,0);return out}
function pageKeys(s,id=s.root){const p=s.pages[id],out=[];if(!p.children.length)return p.keys.slice();p.keys.forEach((k,i)=>{out.push(...pageKeys(s,p.children[i]),k)});out.push(...pageKeys(s,p.children.at(-1)));return out}
function pageProblem(s){const depths=pageLeaves(s).map(x=>x[1]);if(new Set(depths).size!==1)return'Leaves have different depths.';const walk=(id,lo=-Infinity,hi=Infinity)=>{const p=s.pages[id];if(p.keys.length>3)return'Page '+id+' has more than three keys.';if(id!==s.root&&!p.keys.length)return'Page '+id+' is empty below the root.';if(p.keys.some((k,i)=>k<=lo||k>=hi||(i&&k<=p.keys[i-1])))return'Page '+id+' breaks its ordered key interval.';if(p.children.length&&p.children.length!==p.keys.length+1)return'Page '+id+' has the wrong child count.';for(let i=0;i<p.children.length;i++){const e=walk(p.children[i],i?p.keys[i-1]:lo,i<p.keys.length?p.keys[i]:hi);if(e)return e}return null};return walk(s.root)}
function pageFind(s,k){let id=s.root;for(;;){const p=s.pages[id],i=p.keys.findIndex(x=>x>=k);if(i>=0&&p.keys[i]===k)return{id,index:i,found:true};if(!p.children.length)return{id,index:i<0?p.keys.length:i,found:false};id=p.children[i<0?p.keys.length:i]}}
function pageAudit(s){const e=pageProblem(s);if(e)return e;if(JSON.stringify(pageKeys(s))!==JSON.stringify(s.expected.slice().sort((a,b)=>a-b)))return'The tree lost, duplicated or invented a stored key.';return null}
const pageStudies=[
 {pages:{1:{keys:[10,20,30],children:[]}},root:1,requests:[['add',25],['add',5],['add',35],['add',15],['add',40]],budget:24},
 {pages:{1:{keys:[20],children:[2,3]},2:{keys:[5,10],children:[]},3:{keys:[25,30],children:[]}},root:1,requests:[['delete',10],['delete',5],['add',15],['delete',30],['delete',25]],budget:25},
 {pages:{1:{keys:[20,40],children:[2,3,4]},2:{keys:[5,10],children:[]},3:{keys:[25,30],children:[]},4:{keys:[45,50],children:[]}},root:1,requests:[['delete',10],['delete',5],['delete',25],['delete',30],['delete',45],['delete',50],['delete',40]],budget:39}
];
function pageDraw(ui,s){ui.canvas('page-tree',600,280,ctx=>{const depth=new Map();function go(id,d){if(!depth.has(d))depth.set(d,[]);depth.get(d).push(id);s.pages[id].children.forEach(c=>go(c,d+1))}go(s.root,0);const points=new Map();for(const[d,ids]of depth)ids.forEach((id,i)=>points.set(id,[600*(i+1)/(ids.length+1),40+d*85]));ctx.font='14px system-ui';ctx.textAlign='center';for(const[id,[x,y]]of points){for(const c of s.pages[id].children){const[u,v]=points.get(c);ctx.strokeStyle='#829a8d';ctx.beginPath();ctx.moveTo(x,y+20);ctx.lineTo(u,v-20);ctx.stroke()}ctx.fillStyle=id===s.selected?'#c8b07f':'#dce6d4';ctx.fillRect(x-64,y-22,128,44);ctx.fillStyle='#294a42';ctx.fillText('Page '+id,x,y-5);ctx.fillText(s.pages[id].keys.join(' | ')||'empty',x,y+14)}})}
export const pages={stages:3,init({stage,seed,mode}){const l=level(stage),r=random(seed),d=structuredClone(pageStudies[l]);if(mode==='endless'){const keys=r.shuffle(Array.from({length:70},(_,i)=>i+1)).slice(0,8).sort((a,b)=>a-b);d.pages={1:{keys:[keys[2],keys[5]],children:[2,3,4]},2:{keys:keys.slice(0,2),children:[]},3:{keys:keys.slice(3,5),children:[]},4:{keys:keys.slice(6),children:[]}};d.root=1;const additions=r.shuffle(Array.from({length:70},(_,i)=>i+1).filter(k=>!keys.includes(k))).slice(0,2+r.int(3));const deletions=r.shuffle(keys).slice(0,3+r.int(3));d.requests=r.shuffle(additions.map(k=>['add',k]).concat(deletions.map(k=>['delete',k])));d.budget=12+d.requests.length*4;}
 const s={...base(),...d,nextId:Math.max(...Object.keys(d.pages).map(Number))+1,at:0,used:0,selected:d.root,pendingDelete:null,log:[]};s.expected=pageKeys(s);return s},
 act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('page:')){const id=+a.split(':')[1];if(s.pages[id])s.selected=id;return}if(a==='request'){const e=pageAudit(s);if(e)return lose(s,'The next request cannot start: '+e);if(s.pendingDelete)return lose(s,'Finish the chosen internal deletion before the next request.');const q=s.requests[s.at];if(!q)return;const[op,k]=q,f=pageFind(s,k),p=s.pages[f.id];if(op==='add'){if(f.found)return lose(s,'An insertion tried to duplicate a key.');p.keys.splice(f.index,0,k);s.expected.push(k);s.at++;spend(s,1,'Inserted '+k+' into page '+f.id+'. Repair any overflow before advancing.');s.log.push('Insert '+k+' → page '+f.id)}else{if(!f.found)return lose(s,'The requested deletion is absent.');if(p.children.length){s.pendingDelete={id:f.id,index:f.index,key:k};s.selected=f.id;s.note='Choose a predecessor or successor replacement for internal key '+k+'.';return}p.keys.splice(f.index,1);s.expected=s.expected.filter(x=>x!==k);s.at++;spend(s,1,'Deleted '+k+' from leaf '+f.id+'. Repair any underfill.');s.log.push('Delete '+k+' from page '+f.id)}return}
 if(a==='predecessor'||a==='successor'){const d=s.pendingDelete;if(!d)return;const p=s.pages[d.id],before=a==='predecessor';let id=p.children[d.index+(before?0:1)];while(s.pages[id].children.length)id=before?s.pages[id].children.at(-1):s.pages[id].children[0];const leaf=s.pages[id],v=before?leaf.keys.pop():leaf.keys.shift();p.keys[d.index]=v;s.expected=s.expected.filter(x=>x!==d.key);s.at++;s.pendingDelete=null;spend(s,2,'Replaced '+d.key+' by '+v+'; leaf '+id+' may need repair.');s.log.push(a+' '+v+' replaces '+d.key);return}
 if(a.startsWith('split:')){const p=s.pages[s.selected],m=+a.split(':')[1];if(!p||p.keys.length!==4||![1,2].includes(m))return;let parent=pageParent(s,s.selected);if(!parent){const id=s.nextId++;s.pages[id]={keys:[],children:[s.selected]};s.root=id;parent=s.pages[id]}const i=parent.children.indexOf(s.selected),key=p.keys[m],id=s.nextId++,right={keys:p.keys.slice(m+1),children:p.children.length?p.children.slice(m+1):[]};p.keys=p.keys.slice(0,m);p.children=p.children.length?p.children.slice(0,m+1):[];s.pages[id]=right;parent.keys.splice(i,0,key);parent.children.splice(i+1,0,id);spend(s,3,'Promoted '+key+' and split the overflowing page.');s.log.push('Split page '+s.selected+' at '+key);return}
 if(a==='borrow-left'||a==='borrow-right'||a==='merge-left'||a==='merge-right'){const p=s.pages[s.selected],par=pageParent(s,s.selected);if(!p||p.keys.length||!par)return;const i=par.children.indexOf(s.selected),left=a.endsWith('left'),j=i+(left?-1:1),sib=s.pages[par.children[j]];if(!sib)return;if(a.startsWith('borrow')){if(sib.keys.length<=1)return;if(left){p.keys.unshift(par.keys[i-1]);par.keys[i-1]=sib.keys.pop();if(sib.children.length)p.children.unshift(sib.children.pop())}else{p.keys.push(par.keys[i]);par.keys[i]=sib.keys.shift();if(sib.children.length)p.children.push(sib.children.shift())}spend(s,3,'Borrowed through the parent separator from page '+par.children[j]+'.');s.log.push(a+' at '+s.selected)}else{if(sib.keys.length>2)return;const first=left?sib:p,second=left?p:sib,sep=left?i-1:i;first.keys.push(par.keys[sep],...second.keys);first.children.push(...second.children);const dead=left?s.selected:par.children[j];delete s.pages[dead];par.keys.splice(sep,1);par.children.splice(sep+1,1);s.selected=par.children[sep];if(par===s.pages[s.root]&&!par.keys.length){const old=s.root;s.root=par.children[0];delete s.pages[old]}spend(s,3,'Merged siblings around their parent separator; recheck the parent.');s.log.push(a+' removed page '+dead)}return}
 if(a==='audit'){const e=pageAudit(s);if(s.pendingDelete||s.at!==s.requests.length||e)return lose(s,'The tree contract is unfinished: '+(e||'complete every request and pending deletion.'));win(s,'All requested keys are stored once in an ordered, occupancy-safe tree.',150-s.used*2)}},
 render(ui,s){ui.p('Pages hold1–3 ordered keys (root may be smaller); every leaf must have the same depth. Writes '+s.used+'/'+s.budget+'. Request '+Math.min(s.at+1,s.requests.length)+'/'+s.requests.length+'.');pageDraw(ui,s);ui.table(['Page','Ordered keys','Child pages'],Object.entries(s.pages).map(([id,p])=>[id,p.keys.join(', ')||'empty',p.children.join(', ')||'leaf']));ui.p('Requests: '+s.requests.map(([a,k],i)=>(i<s.at?'✓ ':i===s.at?'▶ ':'')+a+' '+k).join(' · '));ui.group();for(const id of Object.keys(s.pages))ui.button('page:'+id,'Select page '+id,false,s.selected===+id);const p=s.pages[s.selected],par=pageParent(s,s.selected),i=par?.children.indexOf(s.selected);ui.group();ui.button('request','Apply next request',!!s.pendingDelete||s.at===s.requests.length);ui.button('predecessor','Replace with left predecessor',!s.pendingDelete);ui.button('successor','Replace with right successor',!s.pendingDelete);ui.group();[1,2].forEach(m=>ui.button('split:'+m,'Split page '+s.selected+' at '+(p?.keys[m]??'—'),p?.keys.length!==4));for(const side of ['left','right']){const sib=par&&s.pages[par.children[i+(side==='left'?-1:1)]];ui.button('borrow-'+side,'Borrow from '+side+' sibling',!p||p.keys.length!==0||!sib||sib.keys.length<=1);ui.button('merge-'+side,'Merge with '+side+' sibling',!p||p.keys.length!==0||!sib||sib.keys.length>2)}ui.button('audit','Close and audit tree');ui.p(pageProblem(s)||'Current tree satisfies ordering, occupancy and leaf depth.');record(ui,s.log)}
};

function hashPairs(r,n,slots){const homes=r.shuffle(Array.from({length:slots},(_,i)=>i)).slice(0,n);return homes.map(h=>{let b=r.int(slots-1);if(b>=h)b++;return r.shuffle([h,b])})}
export const cuckoo={stages:3,init({stage,seed}){const r=random(seed),n=5+level(stage),slots=n+1;return{...base(),n,slots,pairs:hashPairs(r,n,slots),alternate:hashPairs(r,n,slots),order:r.shuffle(Array.from({length:n},(_,i)=>i)),at:0,carried:null,berths:Array(slots).fill(null),stash:null,rescue:1,used:0,budget:n*3+2,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a==='arrival'){if(s.carried!==null)return lose(s,'The carried key must find a legal home before another arrives.');if(s.at>=s.n)return;s.carried=s.order[s.at++];s.note='Key '+'ABCDEFG'[s.carried]+' arrived; choose one of its two berths.';return}if(a.startsWith('berth:')){const i=+a.split(':')[1];if(s.carried===null||!s.pairs[s.carried].includes(i))return;const previous=s.berths[i],key=s.carried;s.berths[i]=key;s.carried=previous;spend(s,1,'Key '+'ABCDEFG'[key]+' occupies berth '+(i+1)+(previous===null?'.':'; '+'ABCDEFG'[previous]+' is displaced.'));s.log.push('ABCDEFG'[key]+' → berth '+(i+1)+(previous!==null?' displaces '+'ABCDEFG'[previous]:''));return}if(a==='stash'){if(s.carried===null||s.stash!==null)return;s.stash=s.carried;s.carried=null;spend(s,1,'The carried key uses the single searchable stash slot.');s.log.push('Stash '+'ABCDEFG'[s.stash]);return}if(a==='withdraw'){if(s.stash===null||s.carried!==null)return;s.carried=s.stash;s.stash=null;s.note='The stashed key is carried again.';return}if(a==='rehash'){if(!s.rescue)return;s.rescue=0;s.pairs=s.alternate;s.at=0;s.berths.fill(null);s.stash=null;s.carried=null;spend(s,3,'Rescue rehash changed every pair; all arrivals must be reinserted.');s.log.push('Rehash; pair graph changed');return}if(a==='audit'){const placed=s.berths.filter(x=>x!==null).concat(s.stash===null?[]:[s.stash]);if(s.carried!==null||s.at!==s.n||new Set(placed).size!==s.n||placed.length!==s.n)return lose(s,'Lookup audit found a missing or duplicate key. Finish the arrivals and carried key.');if(s.berths.some((k,i)=>k!==null&&!s.pairs[k].includes(i)))return lose(s,'A key is outside both hashed berths.');win(s,'Every key is searchable in its two berths or the single stash.',150-s.used*3)}},
 render(ui,s){ui.p('Each key has exactly two legal homes. A placement costs1 and evicts the old occupant into your hand. Work '+s.used+'/'+s.budget+'; arrived '+s.at+'/'+s.n+'; rescue '+s.rescue+'.');ui.table(['Key','Two hashed berths','State'],s.pairs.map((p,k)=>['ABCDEFG'[k],p.map(i=>i+1).join(' or '),s.carried===k?'CARRIED':s.stash===k?'stash':s.berths.includes(k)?'berth '+(s.berths.indexOf(k)+1):'waiting']));ui.grid(4,'Hashed berths');s.berths.forEach((k,i)=>ui.button('berth:'+i,'Berth '+(i+1)+' · '+(k===null?'empty':'ABCDEFG'[k]),s.carried===null||!s.pairs[s.carried].includes(i),k!==null));ui.p('Hand: '+(s.carried===null?'empty':'ABCDEFG'[s.carried])+' · Stash: '+(s.stash===null?'empty':'ABCDEFG'[s.stash])+'.');ui.group();ui.button('arrival','Begin next arrival',s.carried!==null||s.at>=s.n);ui.button('stash','Use single stash',s.carried===null||s.stash!==null);ui.button('withdraw','Carry stashed key',s.carried!==null||s.stash===null);ui.button('rehash','Rescue rehash · costs3',!s.rescue);ui.button('audit','Audit every lookup');record(ui,s.log)}
};

function ringOwner(pos,markers,size){const ids=Object.keys(markers).filter(k=>markers[k]!==null);return ids.sort((a,b)=>((markers[a]-pos+size)%size)-((markers[b]-pos+size)%size)||a.localeCompare(b))[0]}
function ringLoads(s){const loads=Object.fromEntries(Object.keys(s.markers).filter(k=>s.markers[k]!==null).map(k=>[k,0]));for(const k of s.keys)loads[ringOwner(k.pos,s.markers,s.size)]+=k.weight;return loads}
function ringDiagram(ui,s){ui.canvas('hash-ring',600,300,ctx=>{const pt=p=>[300+115*Math.sin(p/s.size*2*Math.PI),150-115*Math.cos(p/s.size*2*Math.PI)];ctx.strokeStyle='#80968b';ctx.lineWidth=2;ctx.beginPath();ctx.arc(300,150,115,0,Math.PI*2);ctx.stroke();ctx.font='12px system-ui';ctx.textAlign='center';for(let i=0;i<s.size;i++){const[x,y]=pt(i);ctx.fillStyle='#80968b';ctx.fillRect(x-2,y-2,4,4)}for(const k of s.keys){const[x,y]=pt(k.pos);ctx.fillStyle='#af8354';ctx.beginPath();ctx.arc(x,y,7,0,Math.PI*2);ctx.fill();ctx.fillStyle='#294a42';ctx.fillText(k.name+'('+k.weight+')',x+((x>300)?22:-22),y)}for(const[id,pos]of Object.entries(s.markers)){if(pos===null)continue;const[x,y]=pt(pos);ctx.fillStyle=id===s.selected?'#b0c998':'#294a42';ctx.fillRect(x-10,y-10,20,20);ctx.fillStyle='#fffdf5';ctx.fillText(id,x,y+4)}})}
export const ring={stages:3,init({stage,seed}){const l=level(stage),r=random(seed),size=24,markers=l===0?{A:0,B:12,C:null}:l===1?{A:0,C:null}:{B:12,C:null,D:null},witness=l===0?{A:0,B:12,C:6}:l===1?{A:0,C:12}:{B:12,C:4,D:20},positions=r.shuffle([2,4,6,8,10,14,16,18,20,22]).slice(0,6+l),keys=positions.map((pos,i)=>({name:'K'+(i+1),pos,weight:1+r.int(3)})),initial={A:0,B:12},loads={};for(const k of keys){const o=ringOwner(k.pos,witness,size);loads[o]=(loads[o]||0)+k.weight}const cap=Math.max(...Object.values(loads)),budget=sum(keys.filter(k=>ringOwner(k.pos,initial,size)!==ringOwner(k.pos,witness,size)).map(k=>k.weight))+2;return{...base(),size,markers,keys,initial,cap,budget,used:0,selected:'C',aim:0,phase:'layout',authority:keys.map(k=>ringOwner(k.pos,initial,size)),copies:keys.map(k=>[ringOwner(k.pos,initial,size)]),log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('server:')){const id=a.split(':')[1];if(id in s.markers){s.selected=id;s.aim=s.markers[id]??0}return}if(a.startsWith('position:')&&s.phase==='layout'){const p=+a.split(':')[1];if(Number.isInteger(p)&&p>=0&&p<s.size)s.aim=p;return}if(a==='place'&&s.phase==='layout'){if(Object.entries(s.markers).some(([id,v])=>id!==s.selected&&v===s.aim)){s.note='Server markers must occupy different ring addresses.';return}s.markers[s.selected]=s.aim;s.note='Marker '+s.selected+' placed at address '+s.aim+'. Forecast recomputed.';return}if(a==='begin'){if(s.phase!=='layout')return;if(Object.values(s.markers).some(x=>x===null))return lose(s,'Install every new marker before beginning migration.');const loads=ringLoads(s);if(Object.values(loads).some(x=>x>s.cap))return lose(s,'The proposed ownership exceeds load cap '+s.cap+'. Check the forecast before committing.');s.phase='migrate';s.note='Ownership plan locked. Copy affected keys before switching authority.';return}if(a.startsWith('copy:')&&s.phase==='migrate'){const i=+a.split(':')[1],k=s.keys[i];if(!k)return;const target=ringOwner(k.pos,s.markers,s.size);if(s.copies[i].includes(target))return;s.copies[i].push(target);spend(s,k.weight,'Copied '+k.name+' to '+target+' for '+k.weight+' bandwidth.');s.log.push('Copy '+k.name+' to '+target);return}if(a.startsWith('switch:')&&s.phase==='migrate'){const i=+a.split(':')[1],k=s.keys[i];if(!k)return;const target=ringOwner(k.pos,s.markers,s.size);if(!s.copies[i].includes(target))return lose(s,'Authority switched before '+k.name+' had a destination copy.');s.authority[i]=target;s.note=k.name+' now serves from '+target+'.';s.log.push('Switch '+k.name+' to '+target);return}if(a==='audit'){if(s.phase!=='migrate'||s.keys.some((k,i)=>s.authority[i]!==ringOwner(k.pos,s.markers,s.size)||!s.copies[i].includes(s.authority[i])))return lose(s,'At least one key still serves from the wrong or missing owner.');win(s,'Every key moved safely to its clockwise owner within load and bandwidth limits.',150-s.used*3)}},
 render(ui,s){ui.p('A server owns the interval clockwise up to its marker, including that address. Retired servers do not appear in the final ring. Load cap '+s.cap+'; bandwidth '+s.used+'/'+s.budget+'; phase '+s.phase+'.');ringDiagram(ui,s);ui.table(['Server','Marker address','Forecast owned weight'],Object.entries(s.markers).map(([id,p])=>[id,p===null?'unplaced':p,p===null?'—':ringLoads(s)[id]||0]));ui.group();Object.keys(s.markers).forEach(id=>ui.button('server:'+id,'Select server '+id,s.phase!=='layout',s.selected===id));ui.range('position','Selected marker '+s.selected,{min:0,max:s.size-1,step:1,value:s.aim});ui.group('Confirm marker placement');ui.button('place','Place selected marker at shown address',s.phase!=='layout');ui.button('begin','Lock ownership and begin migration',s.phase!=='layout');ui.table(['Key','Address','Weight','Serving owner','Final owner','Copies'],s.keys.map((k,i)=>[k.name,k.pos,k.weight,s.authority[i],Object.values(s.markers).some(v=>v!==null)?ringOwner(k.pos,s.markers,s.size):'—',s.copies[i].join(', ')]));ui.group();s.keys.forEach((k,i)=>{const target=ringOwner(k.pos,s.markers,s.size);ui.button('copy:'+i,'Copy '+k.name+' to '+target,s.phase!=='migrate'||s.copies[i].includes(target));ui.button('switch:'+i,'Serve '+k.name+' from '+target,s.phase!=='migrate'||s.authority[i]===target)});ui.button('audit','Retire old copies and close migration');record(ui,s.log)}
};

function versionValues(s,root){const n=s.pool[root];return n.leaf!==undefined?[n.value]:versionValues(s,n.left).concat(versionValues(s,n.right))}
function versionReach(s,root,into=new Set()){if(root===null||into.has(root))return into;into.add(root);const n=s.pool[root];if(n.leaf===undefined){versionReach(s,n.left,into);versionReach(s,n.right,into)}return into}
function versionImmutable(s){const out=new Set();for(const v of s.versions.filter(v=>v.retained))versionReach(s,v.root,out);return out}
function draftNodes(s){if(s.draft===null)return[];const out=[];function go(id,path){out.push({id,path});const n=s.pool[id];if(n.leaf===undefined){go(n.left,path+'L');go(n.right,path+'R')}}go(s.draft,'');return out}
function draftParent(s,path){let id=s.draft;for(const c of path.slice(0,-1))id=s.pool[id][c==='L'?'left':'right'];return id}
function versionRequests(l,r){const v=()=>1+r.int(9);return l===0?[{source:0,changes:[[0,v()],[1,v()]],keep:true}]:l===1?[{source:0,changes:[[0,v()]],keep:true},{source:1,changes:[[3,v()]],keep:true}]:[{source:0,changes:[[0,v()]],keep:false},{source:1,changes:[[1,v()]],keep:false},{source:2,changes:[[0,v()],[2,v()]],keep:true}]}
export const persistent={stages:3,init({stage,seed,mode}){const l=level(stage),r=random(seed),values=Array.from({length:4},()=>1+r.int(9)),pool={1:{left:2,right:3},2:{left:4,right:5},3:{left:6,right:7},4:{leaf:0,value:values[0]},5:{leaf:1,value:values[1]},6:{leaf:2,value:values[2]},7:{leaf:3,value:values[3]}};const requests=mode==='endless'?Array.from({length:3+r.int(3)},(_,i)=>({source:i&&r.int(3)?i:0,changes:r.shuffle([0,1,2,3]).slice(0,1+r.int(2)).map(k=>[k,1+r.int(9)]),keep:r.int(3)===0})):versionRequests(l,r);if(mode==='endless')requests.at(-1).keep=true;const budget=mode==='endless'?requests.reduce((n,q)=>n+1+q.changes.length*2,0):[4,6,8][l];return{...base(),pool,nextId:8,versions:[{root:1,expected:values,retained:true,required:true}],requests,at:0,draft:null,selected:'',used:0,budget,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a==='begin'){if(s.draft!==null||s.at>=s.requests.length)return;const q=s.requests[s.at],v=s.versions[q.source];if(!v||!v.retained)return lose(s,'The requested source version was released too early.');s.draft=v.root;s.selected='';s.note='Draft shares the source root. Copy protected nodes before changing them.';return}if(a.startsWith('path:')){const path=a.slice(5);if(draftNodes(s).some(n=>n.path===path))s.selected=path;return}if(a==='copy'){if(s.draft===null)return;const item=draftNodes(s).find(n=>n.path===s.selected),immutable=versionImmutable(s);if(!item)return;if(item.path){const parent=draftParent(s,item.path);if(immutable.has(parent))return lose(s,'The parent belongs to a published version. Copy the ancestor before replacing its child.')}const id=s.nextId++;s.pool[id]={...s.pool[item.id]};if(!item.path)s.draft=id;else s.pool[draftParent(s,item.path)][item.path.at(-1)==='L'?'left':'right']=id;spend(s,1,'Copied node '+item.id+' to private node '+id+'.');s.log.push('Copy '+item.id+' → '+id);return}if(a==='change'){if(s.draft===null)return;const item=draftNodes(s).find(n=>n.path===s.selected),n=item&&s.pool[item.id];if(!n||n.leaf===undefined)return;const q=s.requests[s.at],change=q.changes.find(([i])=>i===n.leaf);if(!change){s.note='This leaf has no requested change in the current draft.';return}if(versionImmutable(s).has(item.id))return lose(s,'Changing this node would corrupt a retained published version.');n.value=change[1];s.note='Private leaf '+(n.leaf+1)+' now holds requested value '+n.value+'.';s.log.push('Set leaf '+(n.leaf+1)+' to '+n.value);return}if(a.startsWith('release:')){const i=+a.split(':')[1],v=s.versions[i];if(!v||!v.retained||v.required)return;if(s.draft===null&&s.requests.slice(s.at).some(q=>q.source===i))return lose(s,'A future draft still requires that version.');v.retained=false;s.note='Version '+i+' released; its uniquely owned draft nodes may now be edited.';s.log.push('Release version '+i);return}if(a==='publish'){if(s.draft===null)return;const q=s.requests[s.at],target=s.versions[q.source].expected.slice();for(const[i,v]of q.changes)target[i]=v;if(JSON.stringify(versionValues(s,s.draft))!==JSON.stringify(target))return lose(s,'The draft values do not match every requested leaf update.');s.versions.push({root:s.draft,expected:target,retained:true,required:q.keep});s.draft=null;s.at++;s.selected='';s.note='Version '+(s.versions.length-1)+' published; all retained roots remain protected.';s.log.push('Publish version '+(s.versions.length-1));return}if(a==='audit'){if(s.draft!==null||s.at!==s.requests.length)return lose(s,'Finish and publish every requested draft before closing.');if(s.versions.some(v=>v.retained&&JSON.stringify(versionValues(s,v.root))!==JSON.stringify(v.expected)))return lose(s,'A retained version changed after publication.');win(s,'All retained histories keep their original values with only '+s.used+' copied nodes.',150-s.used*4)}},
 render(ui,s){ui.p('Published roots protect every reachable node. Copying costs1; releasing optional old versions may let an already copied draft path be reused. Copies '+s.used+'/'+s.budget+'.');ui.table(['Version','Values of leaves1–4','Retained','Must keep'],s.versions.map((v,i)=>[i,versionValues(s,v.root).join(', '),v.retained?'yes':'released',v.required?'yes':'optional']));const q=s.requests[s.at];ui.p(q?'Draft '+(s.at+1)+' from version '+q.source+': '+q.changes.map(([i,v])=>'leaf '+(i+1)+'→'+v).join(', ')+'. '+(q.keep?'Keep this publication.':'May release this publication after it supplies the next draft.'):'All requested drafts are published.');ui.button('begin','Begin requested draft',s.draft!==null||!q);if(s.draft!==null){const immutable=versionImmutable(s),list=draftNodes(s);ui.canvas('persistent-tree',600,280,ctx=>{const pts=new Map();for(const n of list){const d=n.path.length,index=parseInt(n.path.replaceAll('L','0').replaceAll('R','1')||'0',2);pts.set(n.path,[600*(index+.5)/2**d,40+d*90])}ctx.font='13px system-ui';ctx.textAlign='center';for(const n of list){const[x,y]=pts.get(n.path),node=s.pool[n.id];if(node.leaf===undefined)for(const c of ['L','R']){const[u,v]=pts.get(n.path+c);ctx.strokeStyle='#869a8b';ctx.beginPath();ctx.moveTo(x,y+20);ctx.lineTo(u,v-20);ctx.stroke()}ctx.fillStyle=n.path===s.selected?'#ccb17f':immutable.has(n.id)?'#b7cbb0':'#e7debc';ctx.fillRect(x-38,y-20,76,40);ctx.fillStyle='#294a42';ctx.fillText('Node '+n.id,x,y-3);ctx.fillText(node.leaf===undefined?(immutable.has(n.id)?'protected':'private'):'leaf'+(node.leaf+1)+'='+node.value,x,y+13)}});ui.grid(4,'Select draft node',{compact:true});list.forEach(n=>ui.button('path:'+n.path,(n.path||'root')+' · node '+n.id,false,s.selected===n.path));ui.group();ui.button('copy','Copy selected node');const item=list.find(n=>n.path===s.selected),leaf=item&&s.pool[item.id].leaf;ui.button('change','Store requested leaf value',leaf===undefined||!q.changes.some(([i])=>i===leaf));ui.button('publish','Publish completed draft')}
 ui.group();s.versions.forEach((v,i)=>ui.button('release:'+i,'Release optional version '+i,!v.retained||v.required));ui.button('audit','Audit every retained version');record(ui,s.log)}
};

export const storageInternals={pageAudit,pageKeys,pageFind,ringOwner,ringLoads,versionValues,versionImmutable,draftNodes};
