import{base,random,level,win,lose,sum,record,nodes,spend}from'./core.mjs';

function safeClaims(s){const free=s.free.slice(),remaining=s.max.map((m,i)=>m.map((x,j)=>x-s.held[i][j])),done=new Set();let completed=0;for(let pass=0;pass<s.max.length;pass++){const i=remaining.findIndex((n,i)=>!done.has(i)&&(!s.finished[i])&&n.every((x,j)=>x<=free[j]));if(i<0)break;done.add(i);completed++;s.held[i].forEach((x,j)=>free[j]+=x)}return s.finished.filter(x=>!x).length===completed}
function requestFor(s,i){const n=s.max[i].map((x,j)=>x-s.held[i][j]),order=s.orders[i],j=order.find(j=>n[j]>0);return j===undefined?null:n.map((x,k)=>k===j?Math.min(x,s.quantum[i]):0)}
const bankerStudies=[
 {free:[1],held:[[1],[1],[0]],max:[[3],[2],[2]],orders:[[0],[0],[0]],quantum:[1,1,1]},
 {free:[1,2],held:[[1,0],[0,1],[1,1]],max:[[3,2],[2,2],[2,3]],orders:[[0,1],[0,1],[0,1]],quantum:[1,1,1]},
 {free:[3,3,2],held:[[0,1,0],[2,0,0],[3,0,2],[2,1,1],[0,0,2]],max:[[7,5,3],[3,2,2],[9,0,2],[2,2,2],[4,3,3]],orders:[[0,1,2],[0,1,2],[0,1,2],[1,2,0],[0,1,2]],quantum:[2,1,2,1,1]}
];
export const banker={stages:3,init({stage,seed,mode}){const r=random(seed),l=level(stage),d=structuredClone(bankerStudies[l]);if(mode==='endless'){const resources=2+r.int(2),n=3+r.int(3);d.free=Array.from({length:resources},()=>1+r.int(3));d.held=Array.from({length:n},()=>Array.from({length:resources},()=>r.int(3)));let avail=d.free.slice();const order=r.shuffle(Array.from({length:n},(_,i)=>i));d.max=Array(n);for(const i of order){d.max[i]=d.held[i].map((a,j)=>a+1+r.int(avail[j]));d.held[i].forEach((a,j)=>avail[j]+=a)}d.orders=Array.from({length:n},()=>r.shuffle(Array.from({length:resources},(_,i)=>i)));d.quantum=Array.from({length:n},()=>1+r.int(2))}return{...base(),...d,finished:d.max.map(()=>false),selected:[],used:0,budget:sum(d.max.map((m,i)=>sum(m.map((x,j)=>x-d.held[i][j]))))+d.max.length+3,deferrals:3,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('select:')){const i=+a.split(':')[1];if(s.max[i]&&!s.finished[i])s.selected=s.selected.includes(i)?s.selected.filter(x=>x!==i):s.selected.concat(i);return}if(a==='bundle'){const requests=s.selected.filter(i=>!s.finished[i]).map(i=>[i,requestFor(s,i)]).filter(([,q])=>q);if(!requests.length)return;const total=s.free.map((_,j)=>sum(requests.map(([,q])=>q[j])));if(total.some((x,j)=>x>s.free[j]))return lose(s,'The committed request bundle requires '+total.join('/')+' but only '+s.free.join('/')+' is free.');for(const[i,q]of requests)q.forEach((x,j)=>{s.free[j]-=x;s.held[i][j]+=x});s.selected=[];spend(s,1,'Granted '+requests.length+' concurrent requests as one atomic bundle.');if(!safeClaims(s))lose(s,'The affordable bundle removed every safe completion order.');return}if(a.startsWith('grant:')){const i=+a.split(':')[1],q=s.held[i]&&!s.finished[i]&&requestFor(s,i);if(!q||q.some((x,j)=>x>s.free[j]))return;q.forEach((x,j)=>{s.free[j]-=x;s.held[i][j]+=x});spend(s,1,'Granted '+q.join('/')+' to client '+(i+1)+'.');s.log.push('Grant client '+(i+1)+' '+q.join('/'));if(!safeClaims(s))lose(s,'The affordable grant removed every safe completion order. Future maximum claims can now deadlock.');return}if(a.startsWith('finish:')){const i=+a.split(':')[1];if(!s.held[i]||s.finished[i]||s.max[i].some((x,j)=>x!==s.held[i][j]))return;s.held[i].forEach((x,j)=>{s.free[j]+=x;s.held[i][j]=0});s.finished[i]=true;spend(s,1,'Client '+(i+1)+' completed and returned every held resource.');s.log.push('Finish client '+(i+1));if(s.finished.every(Boolean))win(s,'Every maximum claim completed without an unsafe intermediate allocation.',180-s.used*2);return}if(a==='defer'){if(!s.deferrals)return lose(s,'No request-deferral patience remains.');s.deferrals--;spend(s,1,'Deferred this opportunity; choose a safer client request.');s.log.push('Defer')}},
 render(ui,s){ui.p('Free resources: '+s.free.join(' / ')+'. A grant may be affordable yet unsafe. A safe sequence could supply one client’s WHOLE remaining claim, return its held resources, and continue. Actions '+s.used+'/'+s.budget+'; deferrals '+s.deferrals+'.');ui.table(['Client','Held','Declared maximum','Still needs','Next request','Done'],s.max.map((m,i)=>[i+1,s.held[i].join('/'),m.join('/'),s.finished[i]?'0':m.map((x,j)=>x-s.held[i][j]).join('/'),s.finished[i]?'—':requestFor(s,i)?.join('/')||'ready to finish',s.finished[i]?'yes':'no']));ui.grid(Math.min(3,s.max.length),'Client decisions',{compact:true});s.max.forEach((m,i)=>{const q=requestFor(s,i);ui.button('grant:'+i,'Grant client '+(i+1)+' '+(q?.join('/')||'—'),s.finished[i]||!q||q.some((x,j)=>x>s.free[j]));ui.button('finish:'+i,'Finish client '+(i+1)+' and release',s.finished[i]||m.some((x,j)=>x!==s.held[i][j]))});ui.group();s.max.forEach((_,i)=>ui.button('select:'+i,'Bundle client '+(i+1),s.finished[i]||!requestFor(s,i),s.selected.includes(i)));ui.p('Selected bundle asks '+s.free.map((_,j)=>sum(s.selected.map(i=>requestFor(s,i)?.[j]||0))).join('/')+'.');ui.button('bundle','Commit selected request bundle',!s.selected.length);ui.button('defer','Defer · spends one patience',!s.deferrals);ui.p('The safety check reports whether progress remains possible, but does not reveal an order.');record(ui,s.log)}
};

function reservationRead(s,t){const groups=s.constraints.filter(g=>g.rows.includes(t.row)),reads=[...new Set([t.row,...groups.flatMap(g=>g.rows)])];t.snapshot=s.rows.slice();t.readVersions=s.versions.slice();t.reads=reads;t.allow=s.rows[t.row]===0&&groups.every(g=>sum(g.rows.map(i=>s.rows[i]))<g.cap);t.phase='staged';t.guard='none'}
function reservationInvariant(s){return s.constraints.every(g=>sum(g.rows.map(i=>s.rows[i]))<=g.cap)}
export const versions={stages:3,init({stage,seed,mode}){const l=level(stage),r=random(seed);let n=l===0?1:l===1?2:3,targets=l===0?[0,0]:Array.from({length:n},(_,i)=>i),constraints=l===0?[{rows:[0],cap:1}]:l===1?[{rows:[0,1],cap:1}]:[{rows:[0,1],cap:1},{rows:[1,2],cap:1}],quota=l===2?2:1;if(mode==='endless'){n=5+r.int(3);targets=r.shuffle(Array.from({length:n},(_,i)=>i));const independent=r.shuffle(Array.from({length:n},(_,i)=>i)).slice(0,2+r.int(2)),other=Array.from({length:n},(_,i)=>i).filter(i=>!independent.includes(i));constraints=[];for(const i of independent)for(const j of other)if(r.int(3)!==0)constraints.push({rows:[i,j],cap:1});if(!constraints.length)constraints.push({rows:[independent[0],other[0]],cap:1});quota=independent.length}return{...base(),rows:Array(n).fill(0),versions:Array(n).fill(0),constraints,quota,transactions:targets.map((row,i)=>({name:'T'+(i+1),row,phase:'new',guard:'none',allow:false,snapshot:[],readVersions:[],reads:[]})),guardCredits:targets.length,used:0,budget:targets.length*5+3,retries:2,accepted:0,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;const[op,text,kind]=a.split(':'),i=+text,t=s.transactions[i];if(op==='read'&&t&&['new','retry'].includes(t.phase)){reservationRead(s,t);spend(s,1,t.name+' saved a snapshot and '+(t.allow?'staged a reservation.':'staged a decline.'));s.log.push(t.name+' reads versions '+t.readVersions.join('/'));return}if(op==='protect'&&t&&t.phase==='staged'){if(!['field','range'].includes(kind)||t.guard!=='none')return;if(!s.guardCredits)return lose(s,'Predicate-protection credits are exhausted.');s.guardCredits--;t.guard=kind;spend(s,1,t.name+' protects '+(kind==='field'?'its written field only.':'every row used by its capacity predicates.'));return}if(op==='refresh'&&t&&t.phase==='staged'){if(!s.retries)return lose(s,'The bounded restart reserve is exhausted.');s.retries--;reservationRead(s,t);spend(s,1,t.name+' refreshed its snapshot; prior guard is discarded.');return}if(op==='commit'&&t&&t.phase==='staged'){const protectedRows=t.guard==='range'?t.reads:t.guard==='field'?[t.row]:[],direct=t.allow&&s.versions[t.row]!==t.readVersions[t.row],stale=protectedRows.some(j=>s.versions[j]!==t.readVersions[j]);if(direct||stale){if(!s.retries)return lose(s,t.name+' has a stale protected read or conflicting write and no retry remains.');s.retries--;t.phase='retry';spend(s,1,t.name+' was safely aborted by '+(direct?'a direct write conflict.':'its protected predicate read.'));s.log.push(t.name+' aborts; reread required');return}if(t.allow){s.rows[t.row]=1;s.versions[t.row]++;s.accepted++}t.phase='done';spend(s,1,t.name+' committed its '+(t.allow?'reservation.':'decline.'));s.log.push(t.name+' commits '+(t.allow?'row '+(t.row+1):'no write'));if(!reservationInvariant(s))return lose(s,'The committed history exceeds a capacity constraint. Separate written rows still shared a stale predicate.');if(s.transactions.every(t=>t.phase==='done')){if(s.accepted<s.quota)return lose(s,'The history is safe but only '+s.accepted+'/'+s.quota+' reservations were served. Choosing the middle conflicting slot can strand other work.');win(s,'All clients received safe committed answers; '+s.accepted+' reservations satisfy the shared limits.',180-s.used*3)}return}},
 render(ui,s){ui.p('Each read saves a private snapshot. A direct changed write aborts automatically; a changed capacity scan is checked only by a range guard. Serve at least '+s.quota+' reservations; retries '+s.retries+'; protection credits '+s.guardCredits+'; actions '+s.used+'/'+s.budget+'.');ui.table(['Row','Committed occupied','Version'],s.rows.map((x,i)=>[i+1,x,s.versions[i]]));ui.table(['Capacity group','Rows observed together','Maximum occupied'],s.constraints.map((g,i)=>[i+1,g.rows.map(j=>j+1).join(', '),g.cap]));ui.table(['Client','Wants row','Phase','Saved values','Staged answer','Protection'],s.transactions.map(t=>[t.name,t.row+1,t.phase,t.snapshot.join('/')||'none',t.phase==='new'||t.phase==='retry'?'—':t.allow?'reserve':'decline',t.guard]));ui.grid(3,'Transaction controls',{compact:true});s.transactions.forEach((t,i)=>{ui.button('read:'+i,'Read snapshot for '+t.name,!['new','retry'].includes(t.phase));ui.button('protect:'+i+':field','Protect '+t.name+' written field',t.phase!=='staged'||t.guard!=='none');ui.button('protect:'+i+':range','Protect '+t.name+' whole capacity scan',t.phase!=='staged'||t.guard!=='none');ui.button('refresh:'+i,'Refresh '+t.name+' · one retry',t.phase!=='staged');ui.button('commit:'+i,'Commit '+t.name,t.phase!=='staged')});record(ui,s.log)}
};

export function privileges(s){return s.colors.flatMap((c,i)=>i===0?(c===s.colors.at(-1)?[i]:[]):(c!==s.colors[i-1]?[i]:[]))}
export const tokenRing={stages:3,init({stage,seed}){const l=level(stage),r=random(seed),n=4+l,alphabet=n+1;let colors=Array.from({length:n},()=>r.int(alphabet));while(privileges({colors}).length<2)colors=Array.from({length:n},()=>r.int(alphabet));return{...base(),colors,alphabet,used:0,budget:n-1+l,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('repair:')){const i=+a.split(':')[1];if(!privileges(s).includes(i))return;const old=s.colors[i];s.colors[i]=i===0?(s.colors[0]+1)%s.alphabet:s.colors[i-1];spend(s,1,'Process '+(i+1)+(i===0?' incremented its matching color.':' copied its predecessor.')+' Now '+privileges(s).length+' processes are privileged.');s.log.push('P'+(i+1)+': '+old+'→'+s.colors[i]);return}if(a==='audit'){if(privileges(s).length!==1)return lose(s,'Token ownership is not unique: '+privileges(s).length+' processes are still eligible.');win(s,'One process owns the token after '+s.used+' legal local repairs.',160-s.used*5)}},
 render(ui,s){const p=privileges(s);ui.p('Ordinary processes copy their predecessor only when colors differ. Process1 increments modulo '+s.alphabet+' only when it matches the last process. Find exactly ONE eligible process; this is a bounded repair puzzle, not a general convergence guarantee. Actions '+s.used+'/'+s.budget+'.');nodes(ui,'token-ring',s.colors.map((c,i)=>'P'+(i+1)+'='+c),s.colors.map((_,i)=>[i,(i+1)%s.colors.length]),{active:p});ui.grid(3,'Local eligible repairs',{compact:true});s.colors.forEach((c,i)=>ui.button('repair:'+i,'Process '+(i+1)+' · '+(i===0?'increment':'copy P'+i),!p.includes(i)));ui.button('audit','Certify exactly one token');ui.p('Currently eligible: '+p.map(i=>'P'+(i+1)).join(', ')+'.');record(ui,s.log)}
};

function creditJob(s,id){return s.jobs.find(j=>j.id===id)}
function returnable(s,from,to){return s.jobs.filter(j=>j.id!==0&&j.owner===from&&creditJob(s,j.parent).owner===to&&j.delivered&&j.executed&&!j.outstanding.length&&!j.ackSent)}
function creditSetup(r,l){const workers=3+l,children=2+l,jobs=[{id:0,parent:null,owner:0,depth:0,children:[]}];for(let i=0;i<children;i++){const id=jobs.length;const owner=1+r.int(workers-1);jobs.push({id,parent:0,owner,depth:1,children:[]});jobs[0].children.push(id)}for(let p=1;p<=children;p++){const count=1+r.int(2);for(let k=0;k<count;k++){const id=jobs.length;let owner=r.int(workers);if(owner===jobs[p].owner)owner=(owner+1)%workers;jobs.push({id,parent:p,owner,depth:2,children:[]});jobs[p].children.push(id)}}if(l===2){for(const p of r.shuffle(jobs.filter(j=>j.depth===2)).slice(0,2)){const id=jobs.length;let owner=r.int(workers);if(owner===p.owner)owner=(owner+1)%workers;jobs.push({id,parent:p.id,owner,depth:3,children:[]});p.children.push(id)}}return{workers,jobs}}
export const termination={stages:3,init({stage,seed}){const r=random(seed),d=creditSetup(r,level(stage)),workGroups=sum(d.jobs.map(j=>new Set(j.children.map(id=>d.jobs[id].owner)).size)),ackGroups=new Set(d.jobs.filter(j=>j.id).map(j=>j.depth+':'+j.owner+':'+d.jobs[j.parent].owner)).size;return{...base(),...d,jobs:d.jobs.map(j=>({...j,delivered:j.id===0,executed:false,outstanding:[],ackSent:false,acked:false})),queue:[],used:0,budget:d.jobs.length+workGroups+ackGroups,serial:1,log:[]}},
 act(s,a){if(s.outcome!=='playing')return;if(a.startsWith('execute:')){const id=+a.split(':')[1],j=creditJob(s,id);if(!j||!j.delivered||j.executed)return;j.executed=true;j.outstanding=j.children.slice();const groups=new Map();for(const child of j.children){const c=creditJob(s,child);if(!groups.has(c.owner))groups.set(c.owner,[]);groups.get(c.owner).push(child)}for(const[to,ids]of groups)s.queue.push({serial:s.serial++,type:'work',from:j.owner,to,ids});spend(s,1,'Job '+id+' executed and issued '+j.children.length+' child credits.');s.log.push('Execute J'+id+'; spawn '+j.children.join(','));return}if(a.startsWith('deliver:')){const serial=+a.split(':')[1],i=s.queue.findIndex(q=>q.serial===serial);if(i<0)return;const q=s.queue.splice(i,1)[0];if(q.type==='work')for(const id of q.ids)creditJob(s,id).delivered=true;else for(const id of q.ids){const j=creditJob(s,id),p=creditJob(s,j.parent);p.outstanding=p.outstanding.filter(x=>x!==id);j.acked=true}spend(s,1,'Delivered '+q.type+' envelope '+serial+' carrying credits '+q.ids.join(', ')+'.');s.log.push('Deliver '+q.type+' '+q.ids.join(','));return}if(a.startsWith('return:')){const[,f,t]=a.split(':'),from=+f,to=+t,ready=returnable(s,from,to);if(!ready.length)return;for(const j of ready)j.ackSent=true;s.queue.push({serial:s.serial++,type:'ack',from,to,ids:ready.map(j=>j.id)});spend(s,0,'One acknowledgment envelope groups '+ready.length+' completed credits from worker '+(from+1)+' to '+(to+1)+'.');s.log.push('Batch return '+ready.map(j=>j.id).join(','));return}if(a==='declare'){const root=creditJob(s,0);if(!root.executed||root.outstanding.length||s.queue.length||s.jobs.some(j=>!j.executed||(j.id&&!j.acked)))return lose(s,'Idle workers are insufficient: execution, in-flight envelopes or child credits remain outstanding.');win(s,'Every child obligation returned and every channel is empty; global termination is justified.',180-s.used*4)}},
 render(ui,s){ui.p('Executing a job issues one credit per child. A child returns its credit only after ALL of its children return. Same-worker-to-same-parent-worker acknowledgments can share one envelope; wait for useful batches to meet '+s.budget+' costed executions/deliveries. Used '+s.used+'.');nodes(ui,'credit-tree',Array.from({length:s.workers},(_,i)=>'Worker '+(i+1)),s.queue.map(q=>[q.from,q.to,q.type+':'+q.ids.length]));ui.table(['Job','Worker','Parent','Phase','Child credits owed'],s.jobs.map(j=>[j.id,j.owner+1,j.parent===null?'root':j.parent,!j.delivered?'in transit/waiting':!j.executed?'ready':j.acked?'returned':j.ackSent?'ack traveling':'executed',j.outstanding.join(', ')||'none']));ui.group();s.jobs.forEach(j=>ui.button('execute:'+j.id,'Execute ready job '+j.id,!j.delivered||j.executed));ui.h('Channel envelopes');ui.grid(3,'Deliver envelopes',{compact:true});s.queue.forEach(q=>ui.button('deliver:'+q.serial,q.type+' '+q.serial+': W'+(q.from+1)+'→W'+(q.to+1)+' · J'+q.ids.join('/')));ui.h('Group completed credit returns');ui.grid(3,'Credit batches',{compact:true});for(let from=0;from<s.workers;from++)for(let to=0;to<s.workers;to++){const a=returnable(s,from,to);if(a.length)ui.button('return:'+from+':'+to,'Return '+a.length+' credits W'+(from+1)+'→W'+(to+1))}ui.button('declare','Declare global completion');record(ui,s.log)}
};

export const systemsInternals={requestFor,reservationInvariant,returnable,creditJob};
