import {a,range,shuffle,best,compare,sum,turnNote,panelLog} from './core.mjs';
const hex=[];for(let r=-2;r<=2;r++)for(let q=-2;q<=2;q++)if(Math.abs(q+r)<=2)hex.push([q,r]);
const dirs=[[1,0],[0,1],[-1,1],[-1,0],[0,-1],[1,-1]],index=(q,r)=>hex.findIndex(([x,y])=>x===q&&y===r),near=i=>dirs.map(([q,r])=>index(hex[i][0]+q,hex[i][1]+r)).filter(j=>j>=0),label=i=>hex[i].join(',');
function moves(s,p){const out=[];s.b.forEach((stack,i)=>{if(stack.at(-1)!==p||near(i).length===6&&near(i).every(j=>s.b[j].length))return;dirs.forEach(([dq,dr])=>{const j=index(hex[i][0]+dq*stack.length,hex[i][1]+dr*stack.length);if(j>=0&&s.b[j].length)out.push({i,j});});});return out;}
function apply(s,m){s.b[m.j].push(...s.b[m.i]);s.b[m.i]=[];const keep=new Set(),q=[];s.b.forEach((st,i)=>{if(st.includes(0)){keep.add(i);q.push(i);}});for(const i of q)for(const j of near(i))if(s.b[j].length&&!keep.has(j)){keep.add(j);q.push(j);}const removed=[];s.b.forEach((st,i)=>{if(st.length&&!keep.has(i)){removed.push(i);s.b[i]=[];}});return removed;}
const score=(s,p)=>sum(s.b.map(st=>st.at(-1)===p?st.length:0));
function ended(s){if(!moves(s,1).length&&!moves(s,2).length){compare(s,score(s,1),score(s,2),'Controlled stack height');return true;}return false;}
function house(s){const ms=moves(s,2);if(ms.length){const m=best(s,ms,m=>{const q={b:s.b.map(st=>[...st])};apply(q,m);return score(q,2)*3-score(q,1)*3+moves(q,2).length*.3;});const removed=apply(s,m);turnNote(s,`House moves ${label(m.i)} to ${label(m.j)}; ${removed.length} disconnected stacks fall.`);}else turnNote(s,'House has no move and passes.');ended(s);}
export default {init(s){const setup=shuffle(s,[...Array(8).fill(1),...Array(8).fill(2),0,0,0]);s.b=setup.map(x=>[x]);s.selected=null;s.note='Only exposed stacks can move. Carry their full height along a hex axis to another occupied cell.';},actions(s){const ms=moves(s,1);return [...[...new Set(ms.map(m=>m.i))].map(i=>a('s'+i,'Select stack '+label(i),'Board',s.selected===i)),...ms.filter(m=>m.i===s.selected).map(m=>a('m'+m.j,'Move to '+label(m.j),'Destination')),...(!ms.length?[a('pass','No legal stack — pass')]:[])];},move(s,c){if(c[0]==='s'){s.selected=+c.slice(1);return;}if(c[0]==='m'){const m={i:s.selected,j:+c.slice(1)},removed=apply(s,m);turnNote(s,`You move ${label(m.i)} to ${label(m.j)}; ${removed.length} disconnected stacks fall.`);}s.selected=null;if(!ended(s))house(s);},view(s){return {stats:[`Your controlled height ${score(s,1)}`,`House ${score(s,2)}`,`${s.b.filter(st=>st.length).length} stacks remain`],board:{n:5,cells:range(25).map(k=>{const i=index(k%5-2,Math.floor(k/5)-2),st=i>=0?s.b[i]:[];return {text:i<0?'':!st.length?'·':`${st.at(-1)===1?'●':st.at(-1)===2?'○':'◆'}${st.length}`,label:`${k%5-2},${Math.floor(k/5)-2}: ${i<0?'off board':!st.length?'empty':`height${st.length}, top ${st.at(-1)===1?'you':st.at(-1)===2?'house':'anchor'}, ${st.filter(x=>!x).length} anchors`}`,action:i>=0&&moves(s,1).some(m=>m.i===i)?'s'+i:null};})},panels:[['Stack census',s.b.flatMap((st,i)=>st.length?[`${label(i)}: bottom→top ${st.map(x=>x===1?'you':x===2?'house':'anchor').join(', ')}`]:[]).join('\n')],['Movement & anchors','A surrounded stack cannot move. Distance is its entire height; may cross holes but must land occupied. All layers travel, including anchors. After every move, components without any embedded anchor vanish. Select a stack, then a destination.'],panelLog(s)]};}};
