import {a,range,around,grid,coord,finish,clone,best,turnNote,panelLog} from './core.mjs';
const N=7;
function group(b,i){const seen=new Set([i]),q=[i],lib=new Set();for(const p of q)for(const j of around(p,N)){if(!b[j])lib.add(j);else if(b[j]===b[i]&&!seen.has(j)){seen.add(j);q.push(j);}}return {stones:q,lib:[...lib]};}
function apply(s,i,p,ko=true){if(s.b[i])return null;const b=[...s.b];b[i]=p;let cap=0;for(const j of around(i,N))if(b[j]===-p){const g=group(b,j);if(!g.lib.length){cap+=g.stones.length;g.stones.forEach(k=>b[k]=0);}}if(!group(b,i).lib.length)return null;if(ko&&s.history.includes(b.join(',')))return null;return {b,cap};}
function score(b){let plus=b.filter(x=>x===1).length,minus=b.filter(x=>x===-1).length;const visited=new Set();for(let i=0;i<49;i++){if(b[i]||visited.has(i))continue;const q=[i],owners=new Set();visited.add(i);for(const j of q)for(const k of around(j,N))if(b[k])owners.add(b[k]);else if(!visited.has(k)){visited.add(k);q.push(k);}if(owners.size===1){if(owners.has(1))plus+=q.length;else minus+=q.length;}}return [plus,minus+2.5];}
function end(s){const [p,h]=score(s.b);finish(s,p>h?'win':p<h?'loss':'draw',`Two passes end play. Area: you ${p}, house ${h} (includes 2.5 compensation). ${p>h?'You win.':'House wins.'} All remaining stones count; no invisible dead-group removal.`);}
function play(s,i,p){if(i===-1){s.passes++;turnNote(s,(p===1?'You':'House')+' pass.');if(s.passes===2)end(s);return;}const m=apply(s,i,p);s.b=m.b;s.history.push(s.b.join(','));s.passes=0;s.moves++;turnNote(s,`${p===1?'You':'House'} play ${coord(i,N)}${m.cap?`, capture ${m.cap}`:''}.`);}
function ai(s){const options=range(49).filter(i=>apply(s,i,-1));if(!options.length){play(s,-1,-1);return;}const values=new Map(options.map(i=>{const m=apply(s,i,-1),ns=around(i,N),own=ns.filter(j=>s.b[j]===-1),enemy=ns.filter(j=>s.b[j]===1),g=group(m.b,i);let saved=0;for(const j of own)if(group(s.b,j).lib.length===1)saved+=group(s.b,j).stones.length;let threat=0;for(const j of enemy)if(m.b[j]===1&&group(m.b,j).lib.length===1)threat+=group(m.b,j).stones.length;const eye=ns.length>=3&&ns.every(j=>s.b[j]===-1);return [i,m.cap*40+saved*18+threat*5+Math.min(g.lib.length,5)+enemy.length*1.2+own.length*.3-(g.lib.length===1?18:0)-(eye?30:0)-(Math.abs(i%N-3)+Math.abs(Math.floor(i/N)-3))*.12];}));const spot=best(s,options,i=>values.get(i));const [p,h]=score(s.b);if((s.passes&&h>p)||values.get(spot)<0)play(s,-1,-1);else play(s,spot,-1);}
export default {init(s){s.b=Array(49).fill(0);s.history=[s.b.join(',')];s.passes=0;s.moves=0;s.selected=null;s.note='Place ink stones. Keep shared liberties open; two eyes can make a group safe. House receives 2.5 compensation.';},actions(s){return [...range(49).filter(i=>apply(s,i,1)).map(i=>a('s'+i,'Inspect placement '+coord(i,N),'Board',s.selected===i)),...(s.selected!==null?[a('place','Confirm '+coord(s.selected,N)),a('cancel','Cancel preview')]:[]),a('pass','Pass — may end the match')];},move(s,c){if(c[0]==='s'){s.selected=+c.slice(1);const m=apply(s,s.selected,1);s.note=`Preview ${coord(s.selected,N)}: captures ${m.cap}; new group has ${group(m.b,s.selected).lib.length} liberties. Confirm to place.`;return;}if(c==='cancel'){s.selected=null;s.note='Preview cancelled.';return;}play(s,c==='pass'?-1:s.selected,1);s.selected=null;if(!s.done)ai(s);},view(s){const sc=score(s.b);return {stats:[`${s.moves} stones played`,`Current area ${sc[0]} : ${sc[1]}`,`${s.passes} consecutive pass`],board:grid(s,N,i=>s.b[i]===1?'●':s.b[i]===-1?'○':s.selected===i?'?':'·',i=>s.b[i]?(s.b[i]===1?'ink':'house')+` group ${group(s.b,i).stones.map(j=>coord(j,N)).join(' ')}; ${group(s.b,i).lib.length} liberties`:'empty',i=>!s.b[i]&&apply(s,i,1)?'s'+i:null),panels:[['Area scoring',`Ink area ${sc[0]}; house area ${sc[1]-2.5} plus 2.5 compensation. Empty regions score only if bordering one side. Disputed stones remain on board: continue playing rather than assume them dead.`],['Liberties & repetition','Neighbors up/down/left/right only. Capture opposing zero-liberty groups first; then suicide is illegal. A placement repeating any earlier board is illegal. Click a legal empty intersection to preview.'],panelLog(s)]};}};
