import {a,range,best,compare,grid,coord,turnNote,panelLog} from './core.mjs';
const raw=[[[0,0]],[[0,0],[1,0]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[2,0]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[1,1],[2,1]],[[0,0],[1,0],[0,1],[1,1],[0,2]],[[1,0],[0,1],[1,1],[1,2],[2,2]]];
const names=['Seed1','Twig2','Elbow3','Rod3','Tee4','Square4','Zig4','Bud5','Fork5'];
const shapeVariants=raw.map(shape=>{const out=[],seen=new Set();for(let f=0;f<2;f++)for(let r=0;r<4;r++){let cs=shape.map(([x,y])=>[f?-x:x,y]);for(let k=0;k<r;k++)cs=cs.map(([x,y])=>[-y,x]);let mx=Math.min(...cs.map(c=>c[0])),my=Math.min(...cs.map(c=>c[1]));cs=cs.map(([x,y])=>[x-mx,y-my]).sort((a,b)=>a[1]-b[1]||a[0]-b[0]);const key=JSON.stringify(cs);if(!seen.has(key)){seen.add(key);out.push(cs);}}return out;});
function placeCells(b,p,shape,anchor){const x=anchor%10,y=Math.floor(anchor/10),cs=shape.map(([dx,dy])=>[x+dx,y+dy]);if(cs.some(([x,y])=>x>=10||y>=10||b[y*10+x]))return null;const ids=cs.map(([x,y])=>y*10+x);if(!b.includes(p))return ids.includes(p===1?0:99)?ids:null;let corner=false;for(const [x,y]of cs){for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(x+dx>=0&&x+dx<10&&y+dy>=0&&y+dy<10&&b[(y+dy)*10+x+dx]===p)return null;for(const dx of[-1,1])for(const dy of[-1,1])if(x+dx>=0&&x+dx<10&&y+dy>=0&&y+dy<10&&b[(y+dy)*10+x+dx]===p)corner=true;}return corner?ids:null;}
function moves(s,p,only=null){const out=[];for(const id of s.inv[p-1]){if(only!==null&&id!==only)continue;shapeVariants[id].forEach((shape,v)=>{for(let i=0;i<100;i++){const cs=placeCells(s.b,p,shape,i);if(cs)out.push({id,v,i,cs});}});}return out;}
function apply(s,p,m){m.cs.forEach(i=>s.b[i]=p);s.inv[p-1].splice(s.inv[p-1].indexOf(m.id),1);turnNote(s,`${p===1?'You':'House'} plant ${names[m.id]} at ${coord(m.i,10)}.`);}
function finishCheck(s){const own=moves(s,1),enemy=moves(s,2);if(!own.length&&!enemy.length){const scores=s.inv.map(xs=>-xs.reduce((n,i)=>n+raw[i].length,0)+(xs.length?0:2));compare(s,...scores,'Negative leftover area plus all-planted bonus');return true;}return false;}
function house(s){const ms=moves(s,2);if(ms.length){const m=best(s,ms,m=>m.cs.length*6+m.cs.reduce((n,i)=>n+(9-i%10+9-Math.floor(i/10))*.15,0)+m.cs.filter(i=>[i-11,i-9,i+9,i+11].some(j=>j>=0&&j<100&&s.b[j]===1)).length);apply(s,2,m);}else turnNote(s,'House cannot place and passes.');finishCheck(s);}
export default {init(s){s.b=Array(100).fill(0);s.inv=[range(9),range(9)];s.piece=null;s.variant=0;s.anchor=null;s.note='Cover A1 with your first piece. Later pieces touch your corners, never your edges.';},actions(s){const out=s.inv[0].map(i=>a('p'+i,names[i]+` (${raw[i].length} cells)`,'Your shapes',s.piece===i));if(s.piece!==null){out.push(a('rotate','Next rotation / reflection'));const sh=shapeVariants[s.piece][s.variant];for(let i=0;i<100;i++)if(placeCells(s.b,1,sh,i))out.push(a('a'+i,'Preview anchor '+coord(i,10),'Board',s.anchor===i));if(s.anchor!==null)out.push(a('plant','Confirm placement'));}if(!moves(s,1).length)out.push(a('pass','No legal placement — pass'));return out;},move(s,c){if(c[0]==='p'&&c!=='plant'&&c!=='pass'){s.piece=+c.slice(1);s.variant=0;s.anchor=null;return;}if(c==='rotate'){s.variant=(s.variant+1)%shapeVariants[s.piece].length;s.anchor=null;return;}if(c[0]==='a'){s.anchor=+c.slice(1);s.note='Placement preview. Confirm, or select another anchor.';return;}if(c==='plant'){const cs=placeCells(s.b,1,shapeVariants[s.piece][s.variant],s.anchor);apply(s,1,{id:s.piece,i:s.anchor,cs});s.piece=null;s.anchor=null;}house(s);},view(s){const sh=s.piece===null?[]:shapeVariants[s.piece][s.variant],ghost=s.anchor===null?[]:placeCells(s.b,1,sh,s.anchor)||[];return {stats:[`${s.inv[0].length} your pieces left`,`${s.inv[1].length} house pieces left`],board:grid(s,10,i=>s.b[i]===1?'●':s.b[i]===2?'○':ghost.includes(i)?'◇':'·',i=>s.b[i]===1?'your garden':s.b[i]===2?'house garden':ghost.includes(i)?'preview':'empty',i=>s.piece!==null&&placeCells(s.b,1,sh,i)?'a'+i:null),panels:[['Selected shape',s.piece===null?'Choose a piece.':names[s.piece]+` orientation ${s.variant+1}/${shapeVariants[s.piece].length}\nOffsets from anchor: `+sh.map(([x,y])=>`${x} right ${y} down`).join('; ')],['Boundary rule','Own edge contact is forbidden; own corner contact required after first move. Enemy edges may touch. Start corners A1 and J10. Smaller unplaced area wins; playing everything gives +2.'],panelLog(s)]};}};
