import {a,range,shuffle,best,finish,sum,turnNote,panelLog} from './core.mjs';
const names=['Sun','Wave','Leaf','Rose','Moon'];
const pos=(r,c)=>(r+c)%5;
function deal(s){if(s.bag.length<20){s.bag.push(...shuffle(s,s.discard));s.discard=[];}s.fact=range(5).map(()=>s.bag.splice(0,4));s.center=[];s.token=true;s.source=null;s.color=null;}
function options(s){return [...s.fact.map((cs,i)=>({src:i,cs})),{src:5,cs:s.center}].flatMap(({src,cs})=>[...new Set(cs)].map(c=>({src,c,n:cs.filter(x=>x===c).length})));}
function rows(s,p,c){return range(5).filter(r=>!s.wall[p][r][pos(r,c)]&&(s.rows[p][r].c===null||s.rows[p][r].c===c));}
function wallScore(w,r,k){let h=1,v=1;for(const d of[-1,1]){for(let j=k+d;j>=0&&j<5&&w[r][j];j+=d)h++;for(let i=r+d;i>=0&&i<5&&w[i][k];i+=d)v++;}return h===1&&v===1?1:(h>1?h:0)+(v>1?v:0);}
function take(s,p,o,r){const source=o.src===5?s.center:s.fact[o.src],n=source.filter(c=>c===o.c).length;if(o.src===5){s.center=source.filter(c=>c!==o.c);if(s.token){s.token=false;s.nextStarter=p;s.floor[p]++;}}else{s.center.push(...source.filter(c=>c!==o.c));s.fact[o.src]=[];}if(r===5){s.floor[p]+=n;s.discard.push(...Array(n).fill(o.c));}else{const row=s.rows[p][r],f=Math.min(n,r+1-row.n);row.c=o.c;row.n+=f;s.floor[p]+=n-f;s.discard.push(...Array(n-f).fill(o.c));}turnNote(s,`${p?'House':'You'} take ${n} ${names[o.c]} to ${r===5?'floor':'pattern row '+(r+1)}.`);}
function endRound(s){for(let p=0;p<2;p++){for(let r=0;r<5;r++){const row=s.rows[p][r];if(row.n===r+1){const k=pos(r,row.c);s.wall[p][r][k]=true;s.scores[p]+=wallScore(s.wall[p],r,k);s.discard.push(...Array(r).fill(row.c));s.rows[p][r]={c:null,n:0};}}const penalty=[0,1,2,4,6,8,11,14][Math.min(7,s.floor[p])]+Math.max(0,s.floor[p]-7)*3;s.scores[p]=Math.max(0,s.scores[p]-penalty);s.floor[p]=0;}if(s.wall.some(w=>w.some(row=>row.every(Boolean)))||s.round>=10){for(let p=0;p<2;p++){s.scores[p]+=s.wall[p].filter(r=>r.every(Boolean)).length*2;for(let c=0;c<5;c++){if(s.wall[p].every(r=>r[c]))s.scores[p]+=7;if(range(5).every(r=>s.wall[p][r][pos(r,c)]))s.scores[p]+=10;}}finish(s,s.scores[0]>s.scores[1]?'win':s.scores[0]<s.scores[1]?'loss':'draw',`Final mosaic: you ${s.scores[0]}, house ${s.scores[1]}. Row, column and color bonuses included.`);return;}s.round++;s.turn=s.nextStarter;deal(s);}
function house(s){let guard=0;while(s.turn===1&&!s.done&&guard++<20){const opts=options(s).flatMap(o=>[...rows(s,1,o.c).filter(r=>s.rows[1][r].n<r+1),5].map(r=>({...o,r})));const o=best(s,opts,o=>{if(o.r===5)return -o.n*3;const row=s.rows[1][o.r],capacity=o.r+1-row.n,spill=Math.max(0,o.n-capacity),fill=Math.min(o.n,capacity),w=s.wall[1].map(r=>[...r]);w[o.r][pos(o.r,o.c)]=true;return fill*1.2-spill*3+(o.n>=capacity?wallScore(w,o.r,pos(o.r,o.c))+3:0)+(o.src===5&&s.token?-1:0);});take(s,1,o,o.r);s.turn=0;if(!options(s).length)endRound(s);}}
export default {init(s){s.bag=shuffle(s,range(100).map(i=>i%5));s.discard=[];s.rows=range(2).map(()=>range(5).map(()=>({c:null,n:0})));s.wall=range(2).map(()=>range(5).map(()=>Array(5).fill(false)));s.scores=[0,0];s.floor=[0,0];s.round=1;s.turn=0;s.nextStarter=0;deal(s);s.note='Take every tile of one color from a source. Factory leftovers feed the center—and your rival next turn.';},actions(s){if(s.source!==null)return [...rows(s,0,s.color).map(r=>a('r'+r,'Pattern row '+(r+1)+` (room ${r+1-s.rows[0][r].n})`,'Place entire take')),a('r5','Send all to floor'),a('cancel','Choose another source')];return options(s).map(o=>a(`s${o.src}_${o.c}`,`${o.src===5?'Center':'Factory '+(o.src+1)}: take ${o.n} ${names[o.c]}`,'Draft source'));},move(s,c){if(c==='cancel'){s.source=null;return;}if(c[0]==='s'){[s.source,s.color]=c.slice(1).split('_').map(Number);s.note=`Choose one pattern row for every ${names[s.color]} tile. Excess goes to the penalty floor.`;return;}take(s,0,{src:s.source,c:s.color},+c.slice(1));s.source=null;s.color=null;s.turn=1;if(!options(s).length)endRound(s);house(s);},view(s){return {stats:[`Round ${s.round}/10`,`Scores ${s.scores.join(' : ')}`,`Floor ${s.floor.join(' : ')}`],panels:[['Factories',s.fact.map((cs,i)=>`F${i+1}: ${cs.map(c=>names[c]).join(', ')||'empty'}`).join('\n')],['Center',s.center.map(c=>names[c]).join(', ')||'Empty'],...range(2).flatMap(p=>[[p?'House patterns':'Your patterns',s.rows[p].map((row,r)=>`${r+1}: ${row.n}/${r+1} ${row.c===null?'empty':names[row.c]}`).join('\n')],[p?'House wall':'Your wall',s.wall[p].map((row,r)=>row.map((v,k)=>{const c=(k-r+5)%5;return v?'['+names[c]+']':'·'+names[c];}).join(' ')).join('\n')]]),['Scoring','Complete patterns transfer one tile. Connected horizontal and vertical lines each score their length (isolated tile1). Floor losses:1,1,2,2,2,3,3, then3 each. Final rows+2, columns+7, colors+10. First center taker takes one floor penalty and next-round initiative.'],panelLog(s)]};}};
