const $=id=>document.getElementById(id);
const manifest=await fetch('games.json').then(r=>r.json());
const game=manifest.find(g=>g.id===new URLSearchParams(location.search).get('game'))||manifest[0];
const engine=(await import('./'+game.module+'.mjs')).default;
let seed=731,playing=false,state;
const init=()=>{state={id:game.id,seed,rng:seed,done:false,note:'Your move. Take your time.',log:[]};engine.init(state);};init();
document.title=game.name+' — Small Hours';$('title').textContent=game.name;$('tagline').textContent=game.description;$('intro').textContent=game.decisions;$('decisions').textContent=game.decisions;$('controls').textContent=game.controls;$('accessibility').textContent=game.accessibility;
for(const rule of game.rules){const li=document.createElement('li');li.textContent=rule;$('rules').append(li);}
function activate(code){if(!playing||state.done)return;const allowed=engine.actions(state);if(!allowed.some(a=>a.code===code))return;engine.move(state,code);render();}
function button(a,board=false){const b=document.createElement('button');b.type='button';b.textContent=a.label;b.dataset[board?'boardAction':'action']=a.code;b.setAttribute('aria-pressed',String(!!a.selected));b.addEventListener('click',()=>activate(a.code));return b;}
function render(restore=true){const old=document.activeElement?.dataset.action||document.activeElement?.dataset.boardAction;const fromLarge=!!document.activeElement?.dataset.boardAction;const open=$('large-controls')?.open;const v=engine.view(state),as=state.done?[]:engine.actions(state);$('welcome').hidden=playing;$('play-area').hidden=!playing;$('deal').textContent=`Deal ${seed}. Restart preserves this deal; Another deal changes it.`;document.body.dataset.completed=String(state.done);document.body.dataset.outcome=state.outcome||'';$('status').textContent=state.note;$('scoreboard').replaceChildren(...(v.stats||[]).map(t=>{const e=document.createElement('strong');e.textContent=t;return e;}));$('panels').replaceChildren(...(v.panels||[]).map(([h,t])=>{const e=document.createElement('section');e.className='info-panel';const title=document.createElement('h3');title.textContent=h;const p=document.createElement('p');p.textContent=t;e.append(title,p);return e;}));
const board=$('board');board.replaceChildren();if(v.board){board.style.gridTemplateColumns=`repeat(${v.board.n},minmax(0,1fr))`;for(const c of v.board.cells){const action=as.find(a=>a.code===c.action);const b=action?button({...action,label:c.text}):document.createElement('button');b.type='button';b.className='cell'+(action?' available':'');b.textContent=c.text;b.setAttribute('aria-label',c.label+(action?' · '+action.label:''));b.setAttribute('aria-disabled',String(!action));const pos=document.createElement('span');pos.textContent=c.label.split(':')[0];pos.setAttribute('aria-hidden','true');b.append(pos);board.append(b);}}
$('actions').replaceChildren();for(const group of [...new Set(as.map(a=>a.group||'Your turn'))]){const large=group==='Board';const e=document.createElement(large?'details':'section');e.className=large?'board-alternatives':'control-group';if(large){e.id='large-controls';e.open=!!open;}const h=document.createElement(large?'summary':'h3');h.textContent=large?'Large board controls':group;const row=document.createElement('div');row.className='control-row';row.append(...as.filter(a=>(a.group||'Your turn')===group).map(a=>button(a,large)));e.append(h,row);$('actions').append(e);}
$('result').hidden=!state.done;$('result-title').textContent=state.done?state.note:'';$('result-outcome').textContent=state.outcome==='win'?'Well played':state.outcome==='loss'?'Another approach awaits':'Honors shared';if(restore&&playing){if(state.done)$('again').focus({preventScroll:true});else if(old){const root=fromLarge?document.querySelectorAll('[data-board-action]'):document.querySelectorAll('[data-action]');([...root].find(b=>(b.dataset.action||b.dataset.boardAction)===old)||root[0]||document.querySelector('[data-action]'))?.focus({preventScroll:true});}}}
function reset(change=false){if(change)seed+=7919;init();playing=true;render(false);document.querySelector('[data-action]')?.focus({preventScroll:true});}
$('start').onclick=()=>{playing=true;render(false);document.querySelector('[data-action]')?.focus({preventScroll:true});};$('restart').onclick=()=>reset();$('again').onclick=()=>reset();$('new-deal').onclick=()=>reset(true);
document.addEventListener('keydown',e=>{if(!e.target.closest('#board')||!['ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const cells=[...$('board').children],i=cells.indexOf(e.target),n=engine.view(state).board.n,d={ArrowUp:-n,ArrowDown:n,ArrowLeft:-1,ArrowRight:1}[e.key];cells[(i+d+cells.length)%cells.length]?.focus();});render(false);for(const id of ['start','restart','new-deal'])$(id).disabled=false;$('start').textContent='Take a seat';document.body.dataset.gameReady='true';document.body.dataset.gameId=game.id;
