import {a,range,grid,coord,finish,pick,best,turnNote,panelLog} from './core.mjs';
const traits=['tall / short','round / square','hollow / solid','smooth / striped'];
const words=[['short','tall'],['square','round'],['solid','hollow'],['striped','smooth']];
const name=p=>words.map((v,i)=>v[(p>>i)&1]).join(' · ');
const lines=[...range(4).map(r=>range(4).map(c=>r*4+c)),...range(4).map(c=>range(4).map(r=>r*4+c)),[0,5,10,15],[3,6,9,12]];
function win(b){for(const l of lines){if(l.some(i=>b[i]===null))continue;for(let bit=0;bit<4;bit++)if(l.every(i=>((b[i]>>bit)&1)===((b[l[0]]>>bit)&1)))return {l,word:words[bit][(b[l[0]]>>bit)&1]};}return null;}
const empties=b=>range(16).filter(i=>b[i]===null);
function threats(b,p){return empties(b).filter(i=>{const q=[...b];q[i]=p;return win(q);});}
function house(s){const free=empties(s.b);const immediate=threats(s.b,s.gift);const spot=immediate[0]??best(s,free,i=>{const q=[...s.b];q[i]=s.gift;const safe=s.pool.filter(p=>!threats(q,p).length);const ownFuture=lines.filter(l=>l.includes(i)&&l.filter(j=>q[j]!==null).length===3).length;return safe.length*10+ownFuture;});s.b[spot]=s.gift;const w=win(s.b);if(w)return finish(s,'loss',`House places ${name(s.gift)} at ${coord(spot,4)}. Four ${w.word} pieces: house wins.`);if(!s.pool.length)return finish(s,'draw','The board fills without a common-trait line.');const safe=s.pool.filter(p=>!threats(s.b,p).length);s.gift=pick(s,safe.length?safe:s.pool);s.pool.splice(s.pool.indexOf(s.gift),1);s.phase='place';turnNote(s,`House placed at ${coord(spot,4)} and gives you ${name(s.gift)}. Choose its square.`);}
export default {init(s){s.b=Array(16).fill(null);s.pool=range(16);s.gift=null;s.phase='give';s.note='You begin by giving the house a piece. It chooses where to place it.';},actions(s){return s.phase==='give'?s.pool.map(p=>a('g'+p,name(p),'Give the house a piece')):empties(s.b).map(i=>a('p'+i,'Place gifted piece at '+coord(i,4),'Board'));},move(s,c){const k=+c.slice(1);if(c[0]==='g'){s.gift=k;s.pool.splice(s.pool.indexOf(k),1);house(s);}else{s.b[k]=s.gift;const w=win(s.b);if(w)return finish(s,'win',`You complete four ${w.word} pieces through ${w.l.map(i=>coord(i,4)).join(', ')}. You win.`);if(!s.pool.length)return finish(s,'draw','All sixteen pieces placed. No shared-trait line.');s.phase='give';s.gift=null;s.note='Now choose the piece the house must place. Check every three-piece line before gifting.';}},view(s){return {stats:[`${s.b.filter(x=>x!==null).length}/16 placed`,s.phase==='give'?'Choose their piece':'Place your gift'],board:grid(s,4,i=>s.b[i]===null?'·':s.b[i].toString(2).padStart(4,'0'),i=>s.b[i]===null?'empty':name(s.b[i]),i=>s.phase==='place'&&s.b[i]===null?'p'+i:null),panels:[['Received piece',s.gift===null?'Choose the house gift.':name(s.gift)],['Reading the pieces','Board code bits, left to right: smooth(1)/striped(0), hollow(1)/solid(0), round(1)/square(0), tall(1)/short(0). Every piece is unique. Cell accessible names spell out all four traits.'],['Placed pieces',s.b.flatMap((p,i)=>p===null?[]:[coord(i,4)+': '+name(p)]).join('\n')||'Empty board.'],panelLog(s)]};}};
