import {a,clone,random,best,finish,turnNote,panelLog,range} from './core.mjs';
const sign=p=>p===1?1:-1,own=(b,i,p)=>Math.max(0,b[i]*sign(p));
export function pipsApply(s,p,m){const t={b:[...s.b],bar:[...s.bar],off:[...s.off]};if(m.from===-1)t.bar[p-1]--;else t.b[m.from]-=sign(p);if(m.to===12)t.off[p-1]++;else{if(t.b[m.to]===-sign(p)){t.b[m.to]=0;t.bar[2-p]++}t.b[m.to]+=sign(p)}return t}
function singles(s,p,d){const sg=sign(p),out=[],home=p===1?[9,10,11]:[0,1,2],points=range(12).filter(i=>own(s.b,i,p)),bearing=!s.bar[p-1]&&points.every(i=>home.includes(i)),sources=s.bar[p-1]?[-1]:points;for(const from of sources){let to=from===-1?(p===1?d-1:12-d):from+sg*d;if(to<0||to>=12){if(from<0||!bearing)continue;const exact=p===1?to===12:to===-1,farthest=p===1?Math.min(...points):Math.max(...points);if(!exact&&from!==farthest)continue;to=12}else if(s.b[to]*sg<=-2)continue;out.push({from,to,die:d,hit:to<12&&s.b[to]===-sg})}return out}
export function pipsPlans(s,p,dice){let all=[];function search(t,left,path){let advanced=false;for(const d of new Set(left)){const rest=[...left];rest.splice(rest.indexOf(d),1);for(const m of singles(t,p,d)){advanced=true;search(pipsApply(t,p,m),rest,[...path,m])}}if(!advanced)all.push({path,position:t})}search({b:[...s.b],bar:[...s.bar],off:[...s.off]},dice,[]);const used=Math.max(...all.map(x=>x.path.length));all=all.filter(x=>x.path.length===used);if(used===1){const highest=Math.max(...all.map(x=>x.path[0].die));all=all.filter(x=>x.path[0].die===highest)}const seen=new Set();return all.filter(x=>{const k=JSON.stringify(x.path);if(seen.has(k))return false;seen.add(k);return true})}
const pip=(s,p)=>s.bar[p-1]*13+s.b.reduce((z,v,i)=>z+Math.max(0,v*sign(p))*(p===1?12-i:i+1),0);
export function pipsScore(s,p){const sg=sign(p),other=3-p;let val=(s.off[p-1]-s.off[other-1])*32-pip(s,p)*.65+pip(s,other)*.2+(s.bar[other-1]-s.bar[p-1])*4;for(let i=0;i<12;i++){const count=own(s.b,i,p);if(count>=2)val+=1.5+((p===1?i>=9:i<=2)?2:0);if(count===1){val-=.6;for(let j=0;j<12;j++)if(own(s.b,j,other)&&((p===1?j>i:j<i))&&Math.abs(i-j)<=6)val-=.4}}return val}
function roll(s){const d=[1+Math.floor(random(s)*6),1+Math.floor(random(s)*6)];return d[0]===d[1]?Array(4).fill(d[0]):d}
const describe=m=>`${m.die}: ${m.from<0?'bar':m.from+1} → ${m.to===12?'off':m.to+1}${m.hit?' (hit)':''}`;
function remaining(s){return s.plans.filter(x=>s.played.every((m,i)=>JSON.stringify(m)===JSON.stringify(x.path[i])))}
function firstOptions(s){const seen=new Set(),out=[];for(const plan of remaining(s)){const m=plan.path[s.played.length];if(m&&!seen.has(JSON.stringify(m))){seen.add(JSON.stringify(m));out.push(m)}}return out}
function house(s){const dice=roll(s),plans=pipsPlans(s,2,dice),plan=best(s,plans,p=>pipsScore(p.position,2));Object.assign(s,clone(plan.position));turnNote(s,`House rolled ${dice.join(', ')}; ${plan.path.map(describe).join('; ')||'all entries blocked — no legal move'}.`);s.turn++;if(s.off[1]===7)finish(s,'loss','The house bore off all seven checkers first. You bore off '+s.off[0]+'.');else{s.phase='roll';s.plans=[];s.played=[];s.showPlans=false;s.note+=' Your roll.'}}
export default {
init(s){const mode=Math.floor((s.seed-731)/7919)%3;s.b=mode===0?[2,0,0,2,0,3,-3,0,-2,0,0,-2]:mode===1?[1,0,-2,2,0,2,-1,0,-2,2,0,-2]:[0,0,0,0,-2,-2,-3,3,2,2,0,0];s.bar=[0,0];s.off=[0,0];s.phase='roll';s.turn=1;s.dice=[];s.played=[];s.plans=[];s.showPlans=false;s.note='Seven checkers each. Roll, then allocate as many dice as legally possible. You travel 1→12→off; the house travels 12→1→off.';},
actions(s){if(s.phase==='roll')return[a('roll','Roll two dice')];const next=firstOptions(s),as=next.map((m,i)=>a('move:'+i,describe(m),'Use a die'));if(s.played.length)as.push(a('undo','Undo this uncommitted roll','Roll controls'));as.push(a('plans','Show / hide complete legal turn plans','Roll controls',s.showPlans));if(!next.length)as.push(a('confirm','Confirm turn','Roll controls'));if(s.showPlans)remaining(s).forEach((plan,i)=>as.push(a('whole:'+i,plan.path.map(describe).join(' · ')||'No legal checker move','Complete roll plans')));return as},
move(s,code){if(code==='roll'){s.dice=roll(s);s.start={b:[...s.b],bar:[...s.bar],off:[...s.off]};s.plans=pipsPlans(s,1,s.dice);s.played=[];s.phase='moving';turnNote(s,'You rolled '+s.dice.join(', ')+'. Maximum usable dice: '+s.plans[0].path.length+'.');return}if(code==='plans'){s.showPlans=!s.showPlans;return}if(code==='undo'){Object.assign(s,clone(s.start));s.played=[];s.note='Roll restored with the SAME dice; no reroll or changed luck.';return}if(code.startsWith('move:')){const m=firstOptions(s)[+code.split(':')[1]];Object.assign(s,pipsApply(s,1,m));s.played.push(m);s.note='Uncommitted move '+describe(m)+'.';return}if(code.startsWith('whole:')){const plan=remaining(s)[+code.split(':')[1]];Object.assign(s,clone(plan.position));s.played=clone(plan.path);s.note='Complete plan placed on the board. Confirm, or Undo the entire roll.';return}if(code==='confirm'){turnNote(s,'You: '+(s.played.map(describe).join('; ')||'no legal moves')+'.');if(s.off[0]===7){finish(s,'win','All seven of your checkers are borne off. The house bore off '+s.off[1]+'.');return}house(s)}},
view(s){return{stats:[`Turn ${s.turn}`,`Borne off: you ${s.off[0]}/7 · house ${s.off[1]}/7`,`Bar: you ${s.bar[0]} · house ${s.bar[1]}`,`Pips remaining: you ${pip(s,1)} · house ${pip(s,2)}`],board:{n:6,cells:range(12).map(i=>({text:`${i+1}\n${s.b[i]>0?'you ×'+s.b[i]:s.b[i]<0?'house ×'+(-s.b[i]):'empty'}`,label:`Point ${i+1}: ${s.b[i]>0?s.b[i]+' your checkers':s.b[i]<0?(-s.b[i])+' house checkers':'empty'}${i>=9?', your home':''}${i<=2?', house home':''}`}))},panels:[['Current roll',s.phase==='roll'?'Ready to roll.':`Dice: ${s.dice.join(', ')}. Played: ${s.played.map(describe).join('; ')||'none'}. Legal complete continuations: ${remaining(s).length}.`],['Rules that constrain your choices','Two enemy checkers block a point; a lone enemy is hit to the bar. Reenter all barred checkers before moving others. Doubles give four uses. Use the maximum number of dice; if only one is usable, use the higher one when legal. Every intermediate landing must be legal. Bearing off requires all remaining checkers in the final three-point home. Overshoot only from the farthest occupied home point. The offered moves are prefixes of complete legal maximum-use rolls.'],panelLog(s)]}}
};
