import {a,range,shuffle,finish,turnNote,panelLog} from './core.mjs';
const suits=['Spades','Hearts','Clubs','Diamonds'];
const card=c=>`${c.r===1?'A':c.r} ${suits[c.u]}`;
const ordered=(x,y)=>x.r===y.r+1&&x.u%2!==y.u%2;
function sources(s){const out=[];s.cols.forEach((col,i)=>col.forEach((c,j)=>{if(j<s.hidden[i])return;const tail=col.slice(j);if(tail.every((c,k)=>!k||ordered(tail[k-1],c)))out.push({id:`T${i}_${j}`,cs:tail,label:`Column ${i+1}: ${tail.map(card).join(' → ')}`});}));if(s.waste.length)out.push({id:'W',cs:[s.waste.at(-1)],label:'Waste: '+card(s.waste.at(-1))});s.found.forEach((f,i)=>{if(f.length)out.push({id:'F'+i,cs:[f.at(-1)],label:'Foundation '+card(f.at(-1))});});return out;}
function dest(s,src){if(!src)return [];const out=[];s.cols.forEach((col,i)=>{if(src.id.startsWith('T'+i+'_'))return;if(col.length?ordered(col.at(-1),src.cs[0]):src.cs[0].r===7)out.push(a('toT'+i,'Move to column '+(i+1),'Destination'));});if(src.cs.length===1){const c=src.cs[0];if(!src.id.startsWith('F')&&c.r===s.found[c.u].length+1)out.push(a('toF'+c.u,'Place on '+suits[c.u]+' foundation','Destination'));}return out;}
function movable(s){return sources(s).some(src=>dest(s,src).length);}
function check(s){if(s.found.every(f=>f.length===7))finish(s,'win','All twenty-eight cards reach their foundations. You finish the patience.');else if(!s.stock.length&&(!s.redeals||!s.waste.length)&&!movable(s))finish(s,'loss','The stock is exhausted and no legal card move remains. The columns are blocked.');}
export default {init(s){const d=shuffle(s,range(28).map(i=>({u:Math.floor(i/7),r:i%7+1})));s.cols=range(5).map(i=>d.splice(0,i+1));s.hidden=range(5);s.stock=d;s.waste=[];s.found=[[],[],[],[]];s.redeals=1;s.selected=null;s.note='Uncover the face-down cards. An empty column accepts only a 7; foundations may return to help a tableau chain.';},actions(s){const src=sources(s).find(x=>x.id===s.selected);return [...sources(s).map(x=>a('s'+x.id,x.label,'Choose cards',s.selected===x.id)),...dest(s,src),...(s.stock.length?[a('draw','Draw stock card')]:s.waste.length&&s.redeals?[a('redeal','Use the one redeal')]:[])];},move(s,c){if(c[0]==='s'){s.selected=c.slice(1);s.note='Selected '+sources(s).find(x=>x.id===s.selected).label+'. Choose a destination.';return;}if(c==='draw'){s.waste.push(s.stock.shift());s.selected=null;turnNote(s,'Drew '+card(s.waste.at(-1))+'.');check(s);return;}if(c==='redeal'){s.stock=s.waste;s.waste=[];s.redeals--;s.selected=null;s.note='Waste becomes stock in original draw order. No redeals remain.';check(s);return;}const src=sources(s).find(x=>x.id===s.selected);const cs=src.cs;if(src.id==='W')s.waste.pop();else if(src.id[0]==='F')s.found[+src.id[1]].pop();else{const [i,j]=src.id.slice(1).split('_').map(Number);s.cols[i].splice(j);if(s.cols[i].length&&s.hidden[i]>=s.cols[i].length)s.hidden[i]=s.cols[i].length-1;}if(c.startsWith('toT'))s.cols[+c.slice(3)].push(...cs);else s.found[+c.slice(3)].push(...cs);turnNote(s,`Moved ${cs.map(card).join(' → ')} to ${c.startsWith('toT')?'column '+(+c.slice(3)+1):suits[+c.slice(3)]+' foundation'}.`);s.selected=null;check(s);},view(s){return {stats:[`${s.found.reduce((n,f)=>n+f.length,0)}/28 founded`,`${s.stock.length} stock`,`${s.redeals} redeal`],panels:[['Foundations',s.found.map((f,i)=>suits[i]+': '+(f.length?card(f.at(-1)):'empty')).join('\n')],['Waste',s.waste.length?card(s.waste.at(-1))+' (top), '+s.waste.length+' cards total':'Empty'],...s.cols.map((col,i)=>['Column '+(i+1),`${s.hidden[i]} face-down\n`+col.slice(s.hidden[i]).map(card).join('\n')]),['Selection',s.selected?sources(s).find(x=>x.id===s.selected)?.label||'None':'Choose an exposed card or ordered suffix.'],panelLog(s)]};}};
