import {a,range,shuffle,random,compare,turnNote,panelLog} from './core.mjs';
const suits=['♠','♥','♣','♦'],rank=c=>c%13+2,name=c=>`${['','','2','3','4','5','6','7','8','9','10','J','Q','K','A'][rank(c)]}${suits[Math.floor(c/13)]}`;
function five(cs){const rs=cs.map(rank).sort((a,b)=>b-a),counts=[...new Set(rs)].map(r=>[rs.filter(x=>x===r).length,r]).sort((a,b)=>b[0]-a[0]||b[1]-a[1]),flush=cs.every(c=>Math.floor(c/13)===Math.floor(cs[0]/13));let straight=0;const uniq=[...new Set(rs)];for(let h=14;h>=5;h--)if(range(5).every(k=>uniq.includes(h-k)||(h===5&&k===4&&uniq.includes(14)))){straight=h;break;}let out;if(flush&&straight)out=[8,straight];else if(counts[0][0]===4)out=[7,counts[0][1],counts[1][1]];else if(counts[0][0]===3&&counts[1][0]===2)out=[6,counts[0][1],counts[1][1]];else if(flush)out=[5,...rs];else if(straight)out=[4,straight];else if(counts[0][0]===3)out=[3,counts[0][1],...counts.slice(1).map(x=>x[1]).sort((a,b)=>b-a)];else if(counts[0][0]===2&&counts[1][0]===2)out=[2,Math.max(counts[0][1],counts[1][1]),Math.min(counts[0][1],counts[1][1]),counts[2][1]];else if(counts[0][0]===2)out=[1,counts[0][1],...counts.slice(1).map(x=>x[1]).sort((a,b)=>b-a)];else out=[0,...rs];while(out.length<6)out.push(0);return out.reduce((v,n)=>v*15+n,0);}
function value(cs){if(cs.length<5)return 0;let v=0;for(let a=0;a<cs.length-4;a++)for(let b=a+1;b<cs.length-3;b++)for(let c=b+1;c<cs.length-2;c++)for(let d=c+1;d<cs.length-1;d++)for(let e=d+1;e<cs.length;e++)v=Math.max(v,five([cs[a],cs[b],cs[c],cs[d],cs[e]]));return v;}
const category=v=>['high card','pair','two pair','three of a kind','straight','flush','full house','four of a kind','straight flush'][Math.floor(v/15**5)];
function settle(s,winner){if(winner===null){const values=s.hands.map(h=>value([...h,...s.board]));winner=values[0]===values[1]?-1:values[0]>values[1]?0:1;s.reveal=true;turnNote(s,`Showdown: you ${category(values[0])}, house ${category(values[1])}.`);}if(winner===-1){s.cash[0]+=s.pot/2;s.cash[1]+=s.pot/2;}else s.cash[winner]+=s.pot;turnNote(s,(winner<0?'Split pot':winner===0?'You take the pot':'House takes the pot')+`: ${s.pot} chips.`);s.pot=0;s.phase='next';if(s.round===8||s.cash.some(c=>c<=0))compare(s,...s.cash,'Eight-hand chip stack');}
function closeStreet(s){if(s.street===3){settle(s,null);return;}if(s.cash.some(c=>c===0)){while(s.board.length<5)s.board.push(s.deck.pop());settle(s,null);return;}s.street++;s.board.push(...s.deck.splice(-1*(s.street===1?3:1)));s.bets=[0,0];s.acted=[false,false];s.raises=0;s.turn=1-s.dealer;turnNote(s,`${['Preflop','Flop','Turn','River'][s.street]}: ${s.board.map(name).join(' ')}.`);}
function doAction(s,p,c){const owed=Math.max(...s.bets)-s.bets[p],unit=s.street<2?2:4;if(c==='fold'){turnNote(s,(p?'House':'You')+' fold.');settle(s,1-p);return;}if(c==='raise'){const pay=owed+unit;s.cash[p]-=pay;s.bets[p]+=pay;s.pot+=pay;s.raises++;s.acted=[false,false];s.acted[p]=true;turnNote(s,`${p?'House':'You'} raise by ${unit}; total street contribution ${s.bets[p]}.`);}else{const pay=Math.min(owed,s.cash[p]);s.cash[p]-=pay;s.bets[p]+=pay;s.pot+=pay;s.acted[p]=true;if(pay<owed){const refund=s.bets[1-p]-s.bets[p];s.cash[1-p]+=refund;s.bets[1-p]-=refund;s.pot-=refund;turnNote(s,`${refund} unmatched chips refunded.`);}turnNote(s,`${p?'House':'You'} ${owed?'call '+pay:'check'}.`);}if(s.bets[0]===s.bets[1]&&s.acted.every(Boolean))closeStreet(s);else s.turn=1-p;}
function equity(s){const visible=[...s.hands[1],...s.board],pool=range(52).filter(c=>!visible.includes(c));let wins=0;for(let n=0;n<36;n++){const sample=shuffle(s,pool),other=sample.splice(0,2),board=[...s.board,...sample.slice(0,5-s.board.length)],v=value([...s.hands[1],...board]),w=value([...other,...board]);wins+=v>w?1:v===w?.5:0;}return wins/36;}
function bots(s){let guard=0;while(s.turn===1&&s.phase!=='next'&&!s.done&&guard++<8){const eq=equity(s),owed=Math.max(...s.bets)-s.bets[1],unit=s.street<2?2:4;let act='call';if(owed&&eq<owed/(s.pot+owed)*.9&&random(s)>.12)act='fold';else if(s.raises<3&&s.cash[1]>=owed+unit&&s.cash[0]>0&&(eq>.7||random(s)<.08))act='raise';doAction(s,1,act);}}
function deal(s){s.deck=shuffle(s,range(52));s.hands=[s.deck.splice(0,2),s.deck.splice(0,2)];s.board=[];s.street=0;s.dealer=(s.round-1)%2;s.bets=[0,0];s.pot=0;for(let p=0;p<2;p++){const n=Math.min(s.cash[p],p===s.dealer?1:2);s.cash[p]-=n;s.bets[p]=n;s.pot+=n;}s.acted=[false,false];s.raises=0;s.turn=s.dealer;s.phase='bet';s.reveal=false;s.note='Blinds paid. Review your private cards and the price of continuing.';bots(s);}
export default {init(s){s.cash=[40,40];s.round=1;deal(s);},actions(s){if(s.phase==='next')return[a('next','Deal hand '+(s.round+1))];const owed=Math.max(...s.bets)-s.bets[0],unit=s.street<2?2:4;return [a('call',owed?`Call ${Math.min(owed,s.cash[0])}${owed>s.cash[0]?' (all-in)':''}`:'Check'),...(owed?[a('fold','Fold; surrender this pot')]:[]),...(s.raises<3&&s.cash[0]>=owed+unit&&s.cash[1]>0?[a('raise',`Raise by ${unit}; pay ${owed+unit}`)]:[])];},move(s,c){if(c==='next'){s.round++;deal(s);return;}doAction(s,0,c);if(!s.done&&s.phase!=='next')bots(s);},view(s){return {stats:[`Hand ${s.round}/8`,`Cash ${s.cash.join(' : ')}`,`Pot ${s.pot}`,`${['Preflop','Flop','Turn','River'][s.street]}`,`Raises ${s.raises}/3`],panels:[['Your private cards',s.hands[0].map(name).join(' · ')+(s.board.length>=3?'\nCurrently '+category(value([...s.hands[0],...s.board])):'')],['Community',s.board.map(name).join(' · ')||'No cards revealed yet.'],['House cards',s.reveal?s.hands[1].map(name).join(' · '):'Two concealed cards. House samples unseen possibilities without reading your hand or future deck.'],['Betting ledger',`This street: you ${s.bets[0]}, house ${s.bets[1]}. Owed ${Math.max(...s.bets)-s.bets[0]}. Bets are2 preflop/flop,4 turn/river; at most three raises per street. Matching all-ins reveal the remaining board; unmatched excess is returned.`],['Rank order','High card < pair < two pair < trips < straight < flush < full house < four of a kind < straight flush. Best five of seven; ace may be low in A2345. Equal ranks compare remaining high cards; exact ties split.'],panelLog(s)]};}};
