import {a,range,shuffle,compare,sum,turnNote,panelLog} from './core.mjs';
const cards={copper:{name:'Copper',cost:0,coin:1},silver:{name:'Silver',cost:3,coin:2},gold:{name:'Gold',cost:6,coin:3},estate:{name:'Estate',cost:2,vp:1},duchy:{name:'Duchy',cost:5,vp:3},province:{name:'Province',cost:8,vp:6},village:{name:'Village',cost:3,text:'Draw 1; +2 actions.'},smith:{name:'Smith',cost:4,text:'Draw 3; uses your action.'},market:{name:'Market',cost:5,text:'Draw 1; +1 action, +1 buy, +1 coin.'},chapel:{name:'Chapel',cost:2,text:'Trash up to two cards permanently.'}};
const name=id=>cards[id].name;
function draw(s,p,n){for(let i=0;i<n;i++){if(!s.decks[p].length){s.decks[p]=shuffle(s,s.discards[p]);s.discards[p]=[];s.shuffles[p]++;}if(s.decks[p].length)s.hands[p].push(s.decks[p].pop());}}
const all=(s,p)=>[...s.decks[p],...s.discards[p],...s.hands[p],...s.played[p]];
const score=(s,p)=>sum(all(s,p).map(c=>cards[c].vp||0));
function resetTurn(s){s.actionsLeft=1;s.buys=1;s.money=0;s.phase='actions';s.trashSel=[];}
function action(s,p,id){s.hands[p].splice(s.hands[p].indexOf(id),1);s.played[p].push(id);s.actionsLeft--;if(id==='village'){draw(s,p,1);s.actionsLeft+=2;}if(id==='smith')draw(s,p,3);if(id==='market'){draw(s,p,1);s.actionsLeft++;s.buys++;s.money++;}if(id==='chapel')s.phase='trash';}
function treasures(s,p){s.hands[p]=s.hands[p].filter(id=>{if(cards[id].coin){s.money+=cards[id].coin;s.played[p].push(id);return false;}return true;});s.phase='buy';}
function buy(s,p,id){s.money-=cards[id].cost;s.buys--;s.stock[id]--;s.discards[p].push(id);turnNote(s,`${p?'House':'You'} acquire ${name(id)} into discard.`);}
function cleanup(s,p){s.discards[p].push(...s.hands[p],...s.played[p]);s.hands[p]=[];s.played[p]=[];draw(s,p,5);}
function ended(s){if(Object.values(s.stock).filter(n=>!n).length>=3||s.round>20){compare(s,score(s,0),score(s,1),'Victory cards');return true;}return false;}
function house(s){resetTurn(s);let guard=0;while(s.actionsLeft&&guard++<20){const h=s.hands[1],id=['village','market','smith','chapel'].find(c=>h.includes(c));if(!id)break;action(s,1,id);if(id==='chapel'){const trash=['estate','copper'].flatMap(c=>h.filter(x=>x===c)).slice(0,s.round<12?2:0);for(const c of trash)s.hands[1].splice(s.hands[1].indexOf(c),1);s.phase='actions';}}treasures(s,1);while(s.buys){let options=['province',...(s.round<12?['gold','market','village','smith','silver']:['duchy','gold','silver','estate'])];const total=all(s,1);if(s.round<6&&!total.includes('chapel'))options=['chapel',...options];const id=options.find(id=>s.stock[id]&&cards[id].cost<=s.money&&(id!=='village'||total.filter(c=>c==='village').length<2)&&(id!=='smith'||total.filter(c=>c==='smith').length<2));if(!id)break;buy(s,1,id);}cleanup(s,1);s.round++;resetTurn(s);ended(s);}
export default {init(s){s.decks=[[],[]];s.discards=[[],[]];s.hands=[[],[]];s.played=[[],[]];s.shuffles=[0,0];s.stock=Object.fromEntries(Object.keys(cards).map(id=>[id,cards[id].vp?6:10]));for(let p=0;p<2;p++){s.decks[p]=shuffle(s,[...Array(7).fill('copper'),...Array(3).fill('estate')]);draw(s,p,5);}s.round=1;resetTurn(s);s.note='Grow a deck, not just this hand. Purchased cards enter discard and arrive only after a reshuffle.';},actions(s){if(s.phase==='trash')return [...s.hands[0].map((id,i)=>a('t'+i,'Trash '+name(id),'Choose up to two',s.trashSel.includes(i))),a('trash','Confirm permanent removal')];return [...(s.phase==='actions'&&s.actionsLeft?s.hands[0].flatMap((id,i)=>cards[id].text?[a('p'+i,'Play '+name(id)+' — '+cards[id].text,'Action cards')]:[]):[]),...(s.phase==='actions'?[a('coins','Play all treasures; enter buy phase')]:[]),...(s.phase==='buy'&&s.buys?Object.keys(cards).filter(id=>s.stock[id]&&cards[id].cost<=s.money).map(id=>a('b'+id,`Buy ${name(id)} · ${cards[id].cost}`,'Market')):[]),a('end','End turn and draw five')];},move(s,c){if(c[0]==='t'&&c!=='trash'){const i=+c.slice(1);s.trashSel=s.trashSel.includes(i)?s.trashSel.filter(j=>j!==i):s.trashSel.length<2?[...s.trashSel,i]:[i];return;}if(c==='trash'){const ids=s.trashSel.map(i=>s.hands[0][i]);s.hands[0]=s.hands[0].filter((_,i)=>!s.trashSel.includes(i));turnNote(s,'Permanently trashed '+(ids.map(name).join(', ')||'nothing')+'.');s.trashSel=[];s.phase='actions';return;}if(c[0]==='p'){const id=s.hands[0][+c.slice(1)];action(s,0,id);turnNote(s,'Played '+name(id)+'.');return;}if(c==='coins'){treasures(s,0);s.note=`Treasures played; ${s.money} coins for ${s.buys} purchases.`;return;}if(c[0]==='b'){buy(s,0,c.slice(1));return;}cleanup(s,0);if(!ended(s))house(s);},view(s){const comp=all(s,0);return {stats:[`Round ${Math.min(s.round,20)}/20`,`Actions ${s.actionsLeft}`,`Buys ${s.buys}`,`Coins ${s.money}`,`Your VP ${score(s,0)}`],panels:[['Your hand',s.hands[0].map(id=>name(id)+(cards[id].vp?' (inert victory card)':cards[id].coin?' +'+cards[id].coin+' coin':'')).join('\n')||'Empty'],['Your library',`Draw ${s.decks[0].length}; discard ${s.discards[0].length}; reshuffles ${s.shuffles[0]}.\n`+Object.keys(cards).filter(id=>comp.includes(id)).map(id=>name(id)+' ×'+comp.filter(c=>c===id).length).join('\n')],['Market supply',Object.entries(cards).map(([id,c])=>`${c.name}: cost${c.cost}, ${s.stock[id]} left — ${c.text||(c.coin?c.coin+' coin':'victory card')}${c.vp?' '+c.vp+' VP':''}`).join('\n')],['House','Cards in deck '+all(s,1).length+'. Its hand and order remain hidden. Purchases are public in the log.'],panelLog(s)]};}};
