import {a,range,shuffle,pick,grid,coord,finish,turnNote,panelLog} from './core.mjs';
const names=['Acorn','Bell','Cloud','Drum','Elm','Fan','Gate','Harp','Iris','Jar','Kite','Leaf'];
const free=(s,i)=>{const t=s.tiles[i];if(!t.live)return false;const live=s.tiles.filter(t=>t.live);return !live.some(u=>u.x===t.x&&u.y===t.y&&u.z>t.z)&&(!live.some(u=>u.z===t.z&&u.y===t.y&&u.x===t.x-1)||!live.some(u=>u.z===t.z&&u.y===t.y&&u.x===t.x+1));};
const pairs=s=>{const f=s.tiles.flatMap((t,i)=>free(s,i)?[i]:[]);return f.flatMap((i,k)=>f.slice(k+1).filter(j=>s.tiles[i].kind===s.tiles[j].kind).map(j=>[i,j]));};
const label=t=>`${names[t.kind]} at ${String.fromCharCode(65+t.x)}${t.y+1}, layer ${t.z+1}`;
function check(s){if(s.tiles.every(t=>!t.live))finish(s,'win','All 24 pairs are clear. You opened every roof.');else if(!pairs(s).length&&!s.undos)finish(s,'loss','No matching free pair remains, and all three undo credits are spent. This roof is blocked.');else if(!pairs(s).length)s.note='No matching free pair. Undo your last removal to try another opening.';}
export default {init(s){s.tiles=[];for(let z=0;z<3;z++)for(let y=0;y<4;y++)for(let x=z;x<6-z;x++)s.tiles.push({x,y,z,kind:0,live:true});let accepted=null;
// Construct a legal removal witness first; reject asymmetric walks that strand a tile.
// Retain a deal only when ordinary alternative pair orders can actually block.
for(let attempt=0;attempt<600;attempt++){
 s.tiles.forEach(t=>t.live=true);const kinds=shuffle(s,range(12).flatMap(i=>[i,i]));let valid=true;
 for(const k of kinds){const f=s.tiles.flatMap((t,i)=>free(s,i)?[i]:[]);if(f.length<2){valid=false;break;}const i=pick(s,f),j=pick(s,f.filter(j=>j!==i));s.tiles[i].live=s.tiles[j].live=false;s.tiles[i].kind=s.tiles[j].kind=k;}
 if(!valid)continue;
 const candidate=s.tiles.map(t=>({...t,live:true}));let blocked=0;
 for(let trial=0;trial<16;trial++){s.tiles=candidate.map(t=>({...t}));while(true){const options=pairs(s);if(!options.length)break;const [i,j]=pick(s,options);s.tiles[i].live=s.tiles[j].live=false;}if(s.tiles.some(t=>t.live))blocked++;}
 if(blocked>=4){accepted=candidate;break;}
}
if(!accepted)throw new Error('Could not construct a consequential solvable roof');
s.tiles=accepted;s.selected=null;s.history=[];s.undos=3;s.layer=2;s.note='All faces are known. Remove equal free pairs; reserve copies that open useful side exits.';},actions(s){return [...range(3).map(z=>a('layer'+z,'View layer '+(z+1),'Layer',s.layer===z)),...s.tiles.flatMap((t,i)=>free(s,i)?[a('t'+i,label(t),'Free tiles',s.selected===i)]:[]),...(s.history.length&&s.undos?[a('undo',`Undo last pair (${s.undos} credits)`)]:[])];},move(s,c){if(c.startsWith('layer')){s.layer=+c.slice(5);return;}if(c==='undo'){const ids=s.history.pop();ids.forEach(i=>s.tiles[i].live=true);s.undos--;s.selected=null;s.note='Pair restored; one undo credit spent.';return;}const i=+c.slice(1);if(s.selected===i){s.selected=null;return;}if(s.selected===null){s.selected=i;s.note='Selected '+label(s.tiles[i])+'. Choose another free '+names[s.tiles[i].kind]+'.';return;}const j=s.selected;if(s.tiles[j].kind!==s.tiles[i].kind){s.selected=i;s.note='Different symbols; selection changed. No tile removed.';return;}s.tiles[i].live=s.tiles[j].live=false;s.history.push([j,i]);s.selected=null;turnNote(s,'Removed '+label(s.tiles[j])+' and '+label(s.tiles[i])+'.');check(s);},view(s){return {stats:[`${s.tiles.filter(t=>t.live).length}/48 tiles`,`${s.undos} undo credits`,`Layer ${s.layer+1}`],board:{n:6,cells:range(24).map(k=>{const i=s.tiles.findIndex(t=>t.z===s.layer&&t.x===k%6&&t.y===Math.floor(k/6)),t=s.tiles[i];return {text:!t||!t.live?'·':names[t.kind],label:coord(k,6)+': '+(!t||!t.live?'empty':label(t)+(free(s,i)?' · free':' · blocked')),action:t&&free(s,i)?'t'+i:null};})},panels:[['Selected',s.selected===null?'None':label(s.tiles[s.selected])],['Complete layer list',s.tiles.flatMap((t,i)=>!t.live?[]:[label(t)+(free(s,i)?' — FREE':' — blocked by cover or both sides')]).join('\n')],['Freedom rule','A tile must have nothing above its coordinate, and either left or right at the same layer must be open. Removing a pair can expose more than one layer. Three undo credits per deal.'],panelLog(s)]};}};
