import {range,sum,same,rng,shuffle,adj,connected,base,finish,cycle,cell,checkButton} from './core.mjs';
export function quietError(s,cells=s.cells){const dark=range(cells.length).filter(i=>cells[i]===1),white=range(cells.length).filter(i=>cells[i]!==1);if(dark.some(i=>adj(i,s.n).some(j=>dark.includes(j))))return'Shaded cells cannot share an edge.';if(!connected(white,s.n))return'All white cells must stay connected.';for(let k=0;k<s.count;k++)if(dark.filter(i=>s.regions[i]===k).length!==s.quotas[k])return`Room ${String.fromCharCode(65+k)} needs ${s.quotas[k]} shaded cells.`;for(const horizontal of [true,false])for(let line=0;line<s.n;line++){let rooms=[];for(let k=0;k<s.n;k++){const i=horizontal?line*s.n+k:k*s.n+line;if(dark.includes(i)){rooms=[];continue}const region=s.regions[i];if(rooms.at(-1)!==region)rooms.push(region);if(rooms.length>2)return`An uninterrupted white ${horizontal?'row':'column'} crosses more than two rooms.`}}return null}
const tileEdges=(s,k)=>{const a=s.tiles[k],r=s.turns[k];return range(4).map(d=>a[(d-r+4)%4])};
const windowCells=(i,n)=>range(n*n).filter(j=>Math.abs(j%n-i%n)<=1&&Math.abs(Math.floor(j/n)-Math.floor(i/n))<=1);
export const composition={
 'quiet-rooms':{
 init({stage,seed}){const r=rng(seed),n=5,topCuts=shuffle([[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]],r)[0],bottomCuts=shuffle([[1,2],[1,3],[1,4],[2,3],[2,4],[3,4]],r)[0],ycut=stage===0?2+Math.floor(r()*2):1+Math.floor(r()*4),regions=range(n*n).map(i=>{const bottom=Math.floor(i/n)>=ycut,cuts=bottom?bottomCuts:topCuts;return(bottom?3:0)+(i%n<cuts[0]?0:i%n<cuts[1]?1:2)});let dark,quotas;for(let attempt=0;;attempt++){dark=[];for(let y=0;y<n;y++){const valid=range(n).filter(x=>!dark.some(i=>Math.abs(i%n-x)+Math.abs(Math.floor(i/n)-y)===1));dark.push(y*n+shuffle(valid,r)[0])}if(stage>0)for(const i of shuffle(range(n*n),r)){if(dark.length>=6+Math.min(1,stage))break;if(!dark.includes(i)&&!adj(i,n).some(j=>dark.includes(j)))dark.push(i)}quotas=range(6).map(k=>dark.filter(i=>regions[i]===k).length);const cells=range(n*n).map(i=>dark.includes(i)?1:0);if(!quietError({n,count:6,regions,quotas,cells}))break;if(attempt>10000)throw Error('Room shading construction failed')}
 return base({n,count:6,regions,quotas,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check')finish(s,s.cells.some(v=>v<0)?'Assign every square as white or shaded.':quietError(s));else if(a.startsWith('cell:'))cycle(s,+a.split(':')[1])},
 render(ui,s){ui.p('A white straight run may pass through at most two rooms before a shaded square stops it.');ui.table(['Room','Shade quota','Current'],range(s.count).map(k=>[String.fromCharCode(65+k),s.quotas[k],s.cells.filter((v,i)=>v===1&&s.regions[i]===k).length]));ui.grid(s.n,'Room shading');s.cells.forEach((v,i)=>cell(ui,s,i,String.fromCharCode(65+s.regions[i])+(v===1?'■':v===0?'×':'·'),{region:s.regions[i],selected:v===1,label:`Cell ${i+1}, room ${String.fromCharCode(65+s.regions[i])}, ${v===1?'shade':v===0?'white':'unknown'}`}));checkButton(ui)}
 },
 'seam-quilt':{
 init({stage,seed}){const r=rng(seed),n=stage?3:2,vertical=range(n+1).map(()=>range(n).map(()=>1+Math.floor(r()*4))),horizontal=range(n).map(()=>range(n+1).map(()=>1+Math.floor(r()*4))),solution=range(n*n).map(i=>{const y=Math.floor(i/n),x=i%n;return[vertical[y][x],horizontal[y][x+1],vertical[y+1][x],horizontal[y][x]]}),tiles=shuffle(solution,r).map(a=>{const t=Math.floor(r()*4);return range(4).map(d=>a[(d-t+4)%4])}),boundary={N:vertical[0],S:vertical[n],W:horizontal.map(a=>a[0]),E:horizontal.map(a=>a[n])};return base({n,tiles,boundary,turns:Array(n*n).fill(0),placed:Array(n*n).fill(-1),selected:0})},
 act(s,a){if(a==='check'){if(s.placed.some(i=>i<0))return finish(s,'Every slot needs one tile.');for(let i=0;i<s.n*s.n;i++){const y=Math.floor(i/s.n),x=i%s.n,e=tileEdges(s,s.placed[i]);for(const[d,want]of [[0,y===0?s.boundary.N[x]:tileEdges(s,s.placed[i-s.n])[2]],[1,x===s.n-1?s.boundary.E[y]:tileEdges(s,s.placed[i+1])[3]],[2,y===s.n-1?s.boundary.S[x]:tileEdges(s,s.placed[i+s.n])[0]],[3,x===0?s.boundary.W[y]:tileEdges(s,s.placed[i-1])[1]]])if(e[d]!==want)return finish(s,`Tile in row ${y+1}, column ${x+1} has a mismatched ${['north','east','south','west'][d]} seam.`)}finish(s,null)}else if(a.startsWith('tile:')){const k=+a.split(':')[1],i=s.placed.indexOf(k);s.selected=k;if(i>=0){s.placed[i]=-1;s.edits++}s.note='Tile '+String.fromCharCode(65+k)+' selected; rotate if needed, then choose a slot.'}else if(a==='rotate'){s.turns[s.selected]=(s.turns[s.selected]+1)%4;const i=s.placed.indexOf(s.selected);if(i>=0)s.placed[i]=-1;s.edits++;s.note='Selected tile rotated clockwise and lifted.'}else if(a.startsWith('cell:')){const i=+a.split(':')[1],old=s.placed.indexOf(s.selected);if(old>=0)s.placed[old]=-1;s.placed[i]=s.selected;s.edits++;s.note=`Tile ${String.fromCharCode(65+s.selected)} placed in slot ${i+1}.`}},
 render(ui,s){ui.table(['Boundary','Labels'],[['North',s.boundary.N.join(' · ')],['East',s.boundary.E.join(' · ')],['South',s.boundary.S.join(' · ')],['West',s.boundary.W.join(' · ')]]);ui.grid(s.n,'Edge matching quilt');s.placed.forEach((k,i)=>{const e=k>=0?tileEdges(s,k):null;cell(ui,s,i,e?`${e[0]}\n${e[3]} ${String.fromCharCode(65+k)} ${e[1]}\n${e[2]}`:'Slot '+(i+1),{label:e?`Slot ${i+1}, tile ${String.fromCharCode(65+k)}, north${e[0]} east${e[1]} south${e[2]} west${e[3]}`:`Empty slot ${i+1}`})});ui.group('Tile tray');s.tiles.forEach((_,k)=>{const e=tileEdges(s,k);ui.button('tile:'+k,`${String.fromCharCode(65+k)}: ↑${e[0]} →${e[1]} ↓${e[2]} ←${e[3]}`,false,s.selected===k)});ui.group('Rotate selected tile');ui.button('rotate','Rotate '+String.fromCharCode(65+s.selected)+' clockwise');checkButton(ui)}
 },
 'exclusive-print':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage),target=range(n*n).map(()=>r()<.6?1:0);if(sum(target)<6)range(6).forEach(i=>target[i]=1);if(sum(target)===n*n)target[n*n-1]=0;const pending=shuffle(range(n*n).filter(i=>target[i]),r),cover=[];while(pending.length)cover.push(pending.splice(0,3+Math.floor(r()*2)));const plates=[...cover],budget=cover.length;while(plates.length<budget+4+Math.min(2,stage)){const p=shuffle(range(n*n),r).slice(0,3+Math.floor(r()*3));if(!plates.some(q=>same([...q].sort(),[...p].sort())))plates.push(p)}return base({n,target,budget,plates:shuffle(plates,r),chosen:Array(plates.length).fill(0)})},
 act(s,a){if(a==='check'){const coats=range(s.n*s.n).map(i=>sum(s.plates.map((p,k)=>s.chosen[k]&&p.includes(i)?1:0)));if(sum(s.chosen)>s.budget)return finish(s,`At most ${s.budget} plates may be used.`);const wrong=coats.findIndex((v,i)=>v!==s.target[i]);finish(s,wrong>=0?`Cell ${wrong+1} has ${coats[wrong]} coats; needs ${s.target[wrong]}.`:null)}else if(a.startsWith('plate:')){const k=+a.split(':')[1];s.chosen[k]=1-s.chosen[k];s.edits++;s.note=`Plate ${String.fromCharCode(65+k)} ${s.chosen[k]?'added':'lifted'}. Overlap produces extra coats.`}},
 render(ui,s){const coats=range(s.n*s.n).map(i=>sum(s.plates.map((p,k)=>s.chosen[k]&&p.includes(i)?1:0)));ui.p(`Choose at most ${s.budget} plates. Target squares need one coat; blank squares need zero.`);ui.grid(s.n,'Exact coat target');range(s.n*s.n).forEach(i=>cell(ui,s,i,`${s.target[i]?'■':'○'}\n${coats[i]} coat${coats[i]===1?'':'s'}`,{fixed:true,dark:coats[i]>1,label:`Cell ${i+1}, target ${s.target[i]} coats, current ${coats[i]}`}));ui.canvas('plate-patterns',480,Math.ceil(s.plates.length/4)*128,(ctx,state)=>{ctx.clearRect(0,0,480,ctx.canvas.height);const step=80/state.n;state.plates.forEach((p,k)=>{const x=k%4*120+12,y=Math.floor(k/4)*128+28;ctx.fillStyle='#244335';ctx.font='bold 16px system-ui';ctx.fillText(String.fromCharCode(65+k)+(state.chosen[k]?' selected':''),x,y-8);range(state.n*state.n).forEach(i=>{ctx.fillStyle=p.includes(i)?'#507a61':'#e7eddf';ctx.fillRect(x+i%state.n*step,y+Math.floor(i/state.n)*step,step-2,step-2)})})});ui.group('Printing plates');s.plates.forEach((p,k)=>ui.button('plate:'+k,String.fromCharCode(65+k)+' · '+p.length+' cells',false,!!s.chosen[k]));checkButton(ui)}
 },
 'window-tally':{
 init({stage,seed}){const r=rng(seed),n=stage>1?5:4,a=range(n*n).map(()=>r()<.45?1:0);if(sum(a)<4)range(4).forEach(i=>a[i]=1);const chosen=shuffle(range(n*n),r).slice(0,Math.ceil(n*n*(stage===0?1:.8))),clues=Object.fromEntries(chosen.map(i=>[i,sum(windowCells(i,n).map(j=>a[j]))]));return base({n,clues,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check'){if(s.cells.some(v=>v<0))return finish(s,'Mark every cell as filled or empty.');for(const[i,want]of Object.entries(s.clues)){const got=sum(windowCells(+i,s.n).map(j=>s.cells[j]));if(got!==want)return finish(s,`Window centered at cell ${+i+1} has ${got} filled cells; needs ${want}.`)}finish(s,null)}else if(a.startsWith('cell:'))cycle(s,+a.split(':')[1])},
 render(ui,s){ui.p('A clue counts filled squares in its clipped 3×3 window, including its own square.');ui.grid(s.n,'Local window count picture');s.cells.forEach((v,i)=>cell(ui,s,i,`${s.clues[i]!==undefined?s.clues[i]:'–'}\n${v<0?'·':v?'■':'×'}`,{selected:v===1,label:`Cell ${i+1}, ${s.clues[i]!==undefined?'local count '+s.clues[i]+', ':''}${v<0?'unknown':v?'filled':'empty'}`}));checkButton(ui)}
 },
 'weighted-weft':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage),a=range(n*n).map(()=>r()<(stage>1?.55:.4)?1:0);if(sum(a)<4)range(4).forEach(i=>a[i]=1);const rows=range(n).map(y=>sum(range(n).map(x=>a[y*n+x]*(x+1)))),cols=range(n).map(x=>sum(range(n).map(y=>a[y*n+x]*(y+1))));return base({n,rows,cols,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check'){if(s.cells.some(v=>v<0))return finish(s,'Mark every square as included or excluded.');for(let y=0;y<s.n;y++){const got=sum(range(s.n).map(x=>s.cells[y*s.n+x]*(x+1)));if(got!==s.rows[y])return finish(s,`Row ${y+1} weighted sum is ${got}; needs ${s.rows[y]}.`)}for(let x=0;x<s.n;x++){const got=sum(range(s.n).map(y=>s.cells[y*s.n+x]*(y+1)));if(got!==s.cols[x])return finish(s,`Column ${x+1} weighted sum is ${got}; needs ${s.cols[x]}.`)}finish(s,null)}else if(a.startsWith('cell:'))cycle(s,+a.split(':')[1])},
 render(ui,s){ui.table(['Line','Target','Current'],[...range(s.n).map(y=>['Row '+(y+1),s.rows[y],sum(range(s.n).map(x=>s.cells[y*s.n+x]===1?x+1:0))]),...range(s.n).map(x=>['Column '+(x+1),s.cols[x],sum(range(s.n).map(y=>s.cells[y*s.n+x]===1?y+1:0))])]);ui.p('Row contributions use column weights 1…'+s.n+'. Column contributions use row weights 1…'+s.n+'.');ui.grid(s.n,'Weighted binary inclusion grid');s.cells.forEach((v,i)=>cell(ui,s,i,v<0?'·':v?'■':'×',{selected:v===1,label:`Row ${Math.floor(i/s.n)+1}, column ${i%s.n+1}, ${v<0?'undecided':v?'included':'excluded'}, row contribution ${i%s.n+1}, column contribution ${Math.floor(i/s.n)+1}`}));checkButton(ui)}
 }
};
