import {range,sum,same,rng,shuffle,adj,connected,components,base,finish,cycle,cell,checkButton,squares} from './core.mjs';
export function diagonalEdges(cells,n){return cells.flatMap((v,i)=>{if(v<0)return[];const y=Math.floor(i/n),x=i%n,a=y*(n+1)+x;return[v===0?[a+1,a+n+1]:[a,a+n+2]]})}
export function forest(edges,count){const parent=range(count),root=a=>parent[a]===a?a:(parent[a]=root(parent[a]));for(const[a,b]of edges){const x=root(a),y=root(b);if(x===y)return false;parent[x]=y}return true}
function ray(i,d,n){const[dy,dx]=[[-1,0],[0,1],[1,0],[0,-1]][d],out=[];for(let k=1;k<n;k++){const y=Math.floor(i/n)+dy*k,x=i%n+dx*k;if(x<0||x>=n||y<0||y>=n)break;out.push(y*n+x)}return out}
function drawCellBoard(ctx,s){const n=s.n,w=360/n;ctx.clearRect(0,0,360,360);ctx.fillStyle='#f1f4e9';ctx.fillRect(0,0,360,360);for(let i=0;i<n*n;i++){const x=i%n*w,y=Math.floor(i/n)*w;ctx.strokeStyle='#adc4b7';ctx.strokeRect(x,y,w,w);if(s.cells[i]===1){ctx.fillStyle='#254139';ctx.fillRect(x+4,y+4,w-8,w-8)}if(s.clues[i]){ctx.fillStyle='#485349';ctx.fillRect(x+2,y+2,w-4,w-4);ctx.fillStyle='#fff';ctx.font=`bold ${Math.max(14,w*.3)}px system-ui`;ctx.textAlign='center';ctx.fillText(['↑','→','↓','←'][s.clues[i].d]+s.clues[i].want,x+w/2,y+w*.62)}}ctx.lineWidth=5;ctx.strokeStyle='#dc8c45';for(let k=0;k<s.edges.length;k++)if(s.links[k]){const[a,b]=s.edges[k];ctx.beginPath();ctx.moveTo((a%n+.5)*w,(Math.floor(a/n)+.5)*w);ctx.lineTo((b%n+.5)*w,(Math.floor(b/n)+.5)*w);ctx.stroke()}}
export const paths={
 'diagonal-grove':{
 init({stage,seed}){const r=rng(seed),n=3+Math.min(1,stage);let solution;for(let tries=0;;tries++){solution=Array(n*n).fill(-1);let fail=false;for(const i of shuffle(range(n*n),r)){const opts=shuffle([0,1],r);let chose=false;for(const v of opts){solution[i]=v;if(forest(diagonalEdges(solution,n),(n+1)**2)){chose=true;break}}if(!chose){fail=true;break}}if(!fail)break;if(tries>1000)throw Error('Diagonal construction failed')}
 const edges=diagonalEdges(solution,n),clues={};shuffle(range((n+1)**2),r).slice(0,Math.ceil((n+1)**2*(stage===0?1:stage===1?.8:.6))).forEach(v=>clues[v]=edges.filter(e=>e.includes(v)).length);return base({n,clues,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check'){if(s.cells.some(v=>v<0))return finish(s,'Every square needs a diagonal.');const edges=diagonalEdges(s.cells,s.n);for(const[v,want]of Object.entries(s.clues)){const got=edges.filter(e=>e.includes(+v)).length;if(got!==want)return finish(s,`Vertex row ${Math.floor(+v/(s.n+1))+1}, column ${+v%(s.n+1)+1} needs ${want} diagonals; has ${got}.`)}finish(s,!forest(edges,(s.n+1)**2)?'The diagonals contain a closed cycle.':null)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];s.cells[i]=s.cells[i]<0?0:1-s.cells[i];s.edits++;s.note='Diagonal turned. Match the neighboring vertex degrees.'}},
 render(ui,s){ui.canvas('diagonal-grove',360,360,(ctx,state)=>{ctx.clearRect(0,0,360,360);const gap=300/state.n,offset=30;ctx.strokeStyle='#d0dbcf';ctx.lineWidth=1;for(let k=0;k<=state.n;k++){ctx.beginPath();ctx.moveTo(offset+k*gap,offset);ctx.lineTo(offset+k*gap,offset+300);ctx.stroke();ctx.beginPath();ctx.moveTo(offset,offset+k*gap);ctx.lineTo(offset+300,offset+k*gap);ctx.stroke()}ctx.strokeStyle='#879b8d';ctx.lineWidth=3;for(const[a,b]of diagonalEdges(state.cells,state.n)){ctx.beginPath();ctx.moveTo(offset+a%(state.n+1)*gap,offset+Math.floor(a/(state.n+1))*gap);ctx.lineTo(offset+b%(state.n+1)*gap,offset+Math.floor(b/(state.n+1))*gap);ctx.stroke()}range((state.n+1)**2).forEach(i=>{const x=offset+i%(state.n+1)*gap,y=offset+Math.floor(i/(state.n+1))*gap;ctx.fillStyle='#f6f5e9';ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fill();ctx.fillStyle='#233e34';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(state.clues[i]===undefined?'·':state.clues[i],x,y+6)})});ui.table(['Vertex row','Counts left → right'],range(s.n+1).map(y=>[y+1,range(s.n+1).map(x=>s.clues[y*(s.n+1)+x]??'·').join(' · ')]));ui.grid(s.n,'Choose diagonals');s.cells.forEach((v,i)=>cell(ui,s,i,v<0?'?':v===0?'/':'\\',{label:`Square row ${Math.floor(i/s.n)+1} column ${i%s.n+1}, ${v<0?'unassigned':v===0?'slash':'backslash'}. Activate to turn.`}));checkButton(ui)}
 },
 'shade-detour':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage);let loop,shades,clues;for(let trial=0;;trial++){const start=Math.floor(r()*n*n),walk=[start];while(walk.length<n*n-3){const last=walk.at(-1);if(walk.length>=Math.floor(n*n*.5)&&adj(last,n).includes(start)&&r()<.7)break;const next=shuffle(adj(last,n).filter(i=>!walk.includes(i)),r);if(!next.length)break;walk.push(next[0])}if(walk.length<Math.floor(n*n*.5)||!adj(walk.at(-1),n).includes(start)){if(trial>10000)throw Error('Loop construction failed');continue}const out=range(n*n).filter(i=>!walk.includes(i));shades=[];for(const i of shuffle(out,r))if(shades.length<2+Math.min(1,stage)&&!adj(i,n).some(j=>shades.includes(j)))shades.push(i);if(shades.length<2||out.length===shades.length)continue;clues={};out.filter(i=>!shades.includes(i)).forEach(i=>{let options=range(4).filter(d=>ray(i,d,n).some(j=>shades.includes(j)));if(!options.length)options=range(4);const d=shuffle(options,r)[0];clues[i]={d,want:ray(i,d,n).filter(j=>shades.includes(j)).length}});loop=walk;break}
 const edges=range(n*n).flatMap(i=>adj(i,n).filter(j=>j>i&&!clues[i]&&!clues[j]).map(j=>[i,j]));return base({n,clues,edges,links:Array(edges.length).fill(0),cells:range(n*n).map(i=>clues[i]?0:-1),mode:'shade',selected:-1})},
 act(s,a){if(a==='check'){const dark=range(s.n*s.n).filter(i=>s.cells[i]===1);for(const[i,c]of Object.entries(s.clues)){const got=ray(+i,c.d,s.n).filter(j=>dark.includes(j)).length;if(got!==c.want)return finish(s,`Arrow at cell ${+i+1} sees ${got} shaded cells; needs ${c.want}.`)}if(dark.some(i=>adj(i,s.n).some(j=>dark.includes(j))))return finish(s,'Shaded cells cannot share an edge.');const edges=s.edges.filter((_,k)=>s.links[k]),nodes=range(s.n*s.n).filter(i=>!s.clues[i]&&s.cells[i]!==1);for(const i of range(s.n*s.n)){const degree=edges.filter(e=>e.includes(i)).length,want=nodes.includes(i)?2:0;if(degree!==want)return finish(s,`Cell ${i+1} needs ${want} loop edges; has ${degree}.`)}const seen=new Set([nodes[0]]),q=[nodes[0]];for(let k=0;k<q.length;k++)for(const[a,b]of edges){const v=a===q[k]?b:b===q[k]?a:-1;if(v>=0&&!seen.has(v)){seen.add(v);q.push(v)}}finish(s,seen.size!==nodes.length?'The drawn edges contain more than one loop.':null)}else if(a.startsWith('mode:')){s.mode=a.split(':')[1];s.selected=-1;s.note=s.mode==='shade'?'Choose cells to shade or mark white.':'Choose two neighboring cells to add/remove their loop edge.'}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(s.clues[i])return;if(s.mode==='shade'){if(s.edges.some((e,k)=>s.links[k]&&e.includes(i))){s.note='Remove this cell’s loop edges before shading it.';return}cycle(s,i)}else if(s.cells[i]===1){s.note='A shaded cell cannot carry the loop.'}else if(s.selected<0||s.selected===i){s.selected=s.selected===i?-1:i;s.note='Choose an edge-neighbor for the loop segment.'}else{const k=s.edges.findIndex(e=>e.includes(i)&&e.includes(s.selected));if(k<0){s.note='Loop segments must join edge-neighbor cells.';return}s.links[k]=1-s.links[k];s.selected=i;s.edits++;s.note=s.links[k]?'Loop edge added.':'Loop edge removed.'}}},
 render(ui,s){ui.canvas('shade-detour',360,360,drawCellBoard);ui.group('Editing tool');ui.button('mode:shade','Shade / white marks',false,s.mode==='shade');ui.button('mode:route','Draw loop edges',false,s.mode==='route');ui.grid(s.n,'Shade and loop controls');range(s.n*s.n).forEach(i=>{const c=s.clues[i],degree=s.edges.filter((e,k)=>s.links[k]&&e.includes(i)).length;cell(ui,s,i,c?['↑','→','↓','←'][c.d]+c.want:s.cells[i]===1?'■':degree?`${degree} links`:s.cells[i]===0?'×':'·',{fixed:!!c,dark:s.cells[i]===1,selected:s.selected===i,label:`Cell ${i+1}, ${c?'arrow '+['north','east','south','west'][c.d]+' counts '+c.want:s.cells[i]===1?'shaded':degree+' loop edges'}`})});checkButton(ui)}
 },
 'once-through':{
 init({stage,seed}){const r=rng(seed),n=6+Math.min(2,stage),edges=range(n).map(i=>[i,(i+1)%n].sort((a,b)=>a-b));for(let c=0;c<1+Math.min(2,stage);c++){let options=[];for(let a=0;a<n;a++)for(let b=a+1;b<n;b++)for(let d=b+1;d<n;d++){const tri=[[a,b],[b,d],[a,d]];if(tri.every(e=>!edges.some(x=>same(e,x))))options.push(tri)}if(options.length)edges.push(...shuffle(options,r)[0])}const candidates=range(edges.length).filter(k=>{const e=edges.filter((_,i)=>i!==k),seen=new Set([0]),q=[0];for(let i=0;i<q.length;i++)for(const[a,b]of e){const j=a===q[i]?b:b===q[i]?a:-1;if(j>=0&&!seen.has(j)){seen.add(j);q.push(j)}}return seen.size===n});const removed=edges.splice(shuffle(candidates,r)[0],1)[0],start=removed[Math.floor(r()*2)],exit=removed.find(i=>i!==start);return base({n,edges,start,exit,at:start,used:Array(edges.length).fill(0),route:[start]})},
 act(s,a){if(a.startsWith('node:')){const target=+a.split(':')[1];if(target===s.at){s.note='Choose another station connected by an unused bridge.';return}const k=s.edges.findIndex((e,k)=>e.includes(s.at)&&e.includes(target)&&!s.used[k]);if(k<0){s.note='That station has no unused bridge from your current station.';return}s.used[k]=1;s.at=target;s.route.push(target);s.edits++;if(s.used.every(Boolean))finish(s,s.at!==s.exit?'Every bridge is used, but you ended at the wrong exit.':null);else if(!s.edges.some((e,k)=>e.includes(s.at)&&!s.used[k]))finish(s,`Station ${s.at+1} has no unused bridge; ${s.used.filter(v=>!v).length} bridges remain.`);else s.note=`Arrived at station ${target+1}. ${s.used.filter(v=>!v).length} bridges remain.`}},
 render(ui,s){ui.p(`Station ${s.at+1} · Finish at ${s.exit+1} · Used ${sum(s.used)} / ${s.edges.length} bridges`);ui.canvas('bridge-map',400,360,(ctx,state)=>{ctx.clearRect(0,0,400,360);const pos=i=>[200+140*Math.cos(i/state.n*Math.PI*2-Math.PI/2),180+140*Math.sin(i/state.n*Math.PI*2-Math.PI/2)];state.edges.forEach(([a,b],k)=>{ctx.beginPath();ctx.moveTo(...pos(a));ctx.lineTo(...pos(b));ctx.strokeStyle=state.used[k]?'#bfcdc4':'#4b7461';ctx.lineWidth=state.used[k]?2:5;ctx.stroke()});range(state.n).forEach(i=>{const[x,y]=pos(i);ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.fillStyle=i===state.at?'#e5b15f':i===state.exit?'#bcd2bd':'#e9eddf';ctx.fill();ctx.fillStyle='#233e34';ctx.font='bold 18px system-ui';ctx.textAlign='center';ctx.fillText(i+1,x,y+6)})});ui.group('Cross an unused bridge');range(s.n).forEach(i=>ui.button('node:'+i,'Station '+(i+1),i===s.at||!s.edges.some((e,k)=>e.includes(s.at)&&e.includes(i)&&!s.used[k])));ui.table(['Bridge','State'],s.edges.map(([a,b],k)=>[`${a+1} ↔ ${b+1}`,s.used[k]?'used':'unused']));ui.p('Your route: '+s.route.map(i=>i+1).join(' → '))}
 },
 'cyclic-courtyard':{
 init({stage,seed}){const r=rng(seed),n=3,cells=range(9).map(i=>i+1),depth=4+Math.min(6,stage*2);let last='';for(let k=0;k<depth;k++){let action;do{action=[r()<.5?'row':'col',Math.floor(r()*n),r()<.5?-1:1]}while(action[0]===last);shift(cells,n,...action);last=action[0]}if(cells.every((v,i)=>v===i+1))shift(cells,n,'row',0,1);return base({n,cells,moves:0,budget:depth+6})},
 act(s,a){if(a.startsWith('shift:')){const[,type,index,d]=a.split(':');shift(s.cells,s.n,type,+index,+d);s.moves++;s.edits++;if(s.cells.every((v,i)=>v===i+1))finish(s,null);else if(s.moves>=s.budget)finish(s,'The line-shift allowance is used up.');else s.note=`${s.budget-s.moves} shifts remain. Rows and columns wrap around.`}},
 render(ui,s){ui.p(`Restore 1–9 in reading order · ${s.budget-s.moves} shifts left`);ui.grid(s.n,'Wrapping tile grid');s.cells.forEach((v,i)=>cell(ui,s,i,v,{fixed:true,label:`Row ${Math.floor(i/s.n)+1} column ${i%s.n+1}, tile ${v}, target ${i+1}`}));ui.group('Shift entire rows');range(s.n).forEach(y=>{ui.button(`shift:row:${y}:-1`,'Row '+(y+1)+' ←');ui.button(`shift:row:${y}:1`,'Row '+(y+1)+' →')});ui.group('Shift entire columns');range(s.n).forEach(x=>{ui.button(`shift:col:${x}:-1`,'Column '+(x+1)+' ↑');ui.button(`shift:col:${x}:1`,'Column '+(x+1)+' ↓')})}
 }
};
export function shift(a,n,type,index,d){const positions=range(n).map(k=>type==='row'?index*n+k:k*n+index),old=positions.map(i=>a[i]);positions.forEach((i,k)=>a[i]=old[(k-d+n)%n])}
