import {range,sum,same,rng,shuffle,adj,near,connected,components,squares,base,finish,cycle,cell,checkButton,transform} from './core.mjs';
const totals=(a,n,h=n)=>({rows:range(h).map(y=>sum(a.slice(y*n,y*n+n))),cols:range(n).map(x=>sum(range(h).map(y=>a[y*n+x]))) });
const margins=(ui,s)=>ui.table(['Axis','Required','Current'],[...s.rows.map((v,y)=>['Row '+(y+1),v,sum(s.cells.slice(y*s.n,y*s.n+s.n).map(v=>v===1?1:0))]),...s.cols.map((v,x)=>['Column '+(x+1),v,sum(range(s.h||s.n).map(y=>s.cells[y*s.n+x]===1?1:0))])]);
const marginError=(a,s)=>{const got=totals(a,s.n,s.h||s.n);for(let y=0;y<got.rows.length;y++)if(got.rows[y]!==s.rows[y])return `Row ${y+1} has ${got.rows[y]}; needs ${s.rows[y]}.`;for(let x=0;x<s.n;x++)if(got.cols[x]!==s.cols[x])return `Column ${x+1} has ${got.cols[x]}; needs ${s.cols[x]}.`;return null};
function poles(s){const a=Array(s.n*s.h).fill(0);s.slots.forEach(([i,j],k)=>{if(s.values[k]===1){a[i]=1;a[j]=-1}else if(s.values[k]===2){a[i]=-1;a[j]=1}});return a}
const dirs=[['N',-1,0],['E',0,1],['S',1,0],['W',0,-1]];
function cross(s,k){const hub=s.hubs[k][0],cells=[hub];s.arms[k].forEach((len,d)=>{for(let step=1;step<=len;step++)cells.push(hub+step*(dirs[d][1]*s.n+dirs[d][2]))});return cells}
export function tetromino(cells,n){if(cells.length!==4||!connected(cells,n))return null;const pts=cells.map(i=>[i%n,Math.floor(i/n)]);let forms=[];for(const flip of [1,-1]){let p=pts.map(([x,y])=>[x*flip,y]);for(let k=0;k<4;k++){const minx=Math.min(...p.map(p=>p[0])),miny=Math.min(...p.map(p=>p[1]));forms.push(p.map(([x,y])=>[x-minx,y-miny]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]).map(p=>p.join(',')).join(';'));p=p.map(([x,y])=>[-y,x])}}return forms.sort()[0]}
const forms=[[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[1,2]],[[0,0],[1,0],[2,0],[1,1]],[[1,0],[2,0],[0,1],[1,1]]];
const kindLabels=Object.fromEntries(forms.map((p,k)=>[tetromino(p.map(([x,y])=>y*5+x),5),['I','L','T','S'][k]]));
function shapePlacements(n){const out=[],seen=new Set;forms.forEach(p=>{for(let t=0;t<8;t++){let q=p.map(([x,y])=>[x,y]);if(t>=4)q=q.map(([x,y])=>[-x,y]);for(let k=0;k<t%4;k++)q=q.map(([x,y])=>[-y,x]);const minx=Math.min(...q.map(p=>p[0])),miny=Math.min(...q.map(p=>p[1]));q=q.map(([x,y])=>[x-minx,y-miny]);for(let y=0;y<n;y++)for(let x=0;x<n;x++){if(q.some(([dx,dy])=>x+dx>=n||y+dy>=n))continue;const cells=q.map(([dx,dy])=>(y+dy)*n+x+dx).sort((a,b)=>a-b),key=cells.join(',');if(!seen.has(key)){seen.add(key);out.push({cells,kind:tetromino(cells,n)})}}}});return out}
export const placement={
 'magnet-ledger':{
 init({stage,seed}){const r=rng(seed),n=stage>1?6:4,h=stage?6:4,slots=[];for(let y=0;y<h;y+=2)for(let x=0;x<n;x+=2){const i=y*n+x;if(r()<.5)slots.push([i,i+1],[i+n,i+n+1]);else slots.push([i,i+n],[i+1,i+n+1])}let values,a;for(let attempt=0;;attempt++){values=Array(slots.length).fill(0);a=Array(n*h).fill(0);for(const k of shuffle(range(slots.length),r)){if(r()<.25)continue;for(const v of shuffle([1,2],r)){const[i,j]=slots[k],p=v===1?1:-1;if(adj(i,n,h).some(t=>t!==j&&a[t]===p)||adj(j,n,h).some(t=>t!==i&&a[t]===-p))continue;values[k]=v;a[i]=p;a[j]=-p;break}}if(values.filter(Boolean).length>=3)break;if(attempt>1000)throw Error('Magnet construction failed')}
 const plus=totals(a.map(v=>v===1?1:0),n,h),minus=totals(a.map(v=>v===-1?1:0),n,h);return base({n,h,slots,plus,minus,values:Array(slots.length).fill(0)})},
 act(s,a){if(a==='check'){const p=poles(s),pos=totals(p.map(v=>v===1?1:0),s.n,s.h),neg=totals(p.map(v=>v===-1?1:0),s.n,s.h);for(const[type,got,want]of [['positive',pos,s.plus],['negative',neg,s.minus]])for(const axis of ['rows','cols'])for(let k=0;k<got[axis].length;k++)if(got[axis][k]!==want[axis][k])return finish(s,`${axis==='rows'?'Row':'Column'} ${k+1} needs ${want[axis][k]} ${type} poles; has ${got[axis][k]}.`);const i=p.findIndex((v,i)=>v&&adj(i,s.n,s.h).some(j=>p[j]===v));finish(s,i>=0?`Equal poles touch at cell ${i+1}.`:null)}else if(a.startsWith('slot:')){const k=+a.split(':')[1];s.values[k]=(s.values[k]+1)%4;s.edits++;s.note=`Slot ${k+1}: ${['empty','positive then negative','negative then positive','excluded'][s.values[k]]}.`}},
 render(ui,s){const p=poles(s);ui.table(['Line','+ quota','− quota'],[...range(s.h).map(y=>['Row '+(y+1),s.plus.rows[y],s.minus.rows[y]]),...range(s.n).map(x=>['Column '+(x+1),s.plus.cols[x],s.minus.cols[x]])]);ui.grid(s.n,'Paired magnet slots');range(s.n*s.h).forEach(i=>{const k=s.slots.findIndex(pair=>pair.includes(i)),b=ui.button('slot:'+k,`${k+1}${p[i]===1?' +':p[i]===-1?' −':s.values[k]===3?' ×':' ·'}`,false,s.values[k]===1||s.values[k]===2);b.classList.add('puzzle-cell');b.style.backgroundColor=k%2?'#dae7e2':'#ece0cb';b.dataset.cell=i;b.setAttribute('aria-label',`Cell ${i+1}, domino slot ${k+1}, ${p[i]===1?'positive':p[i]===-1?'negative':'empty'}`)});checkButton(ui)}
 },
 'thermometer-hall':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage),t=Math.floor(r()*8),path=range(n*n).map(i=>{const y=Math.floor(i/n),x=y%2?n-1-i%n:i%n;return transform(y*n+x,n,t)}),tubes=[];while(path.length){const len=Math.min(path.length,3+Math.floor(r()*3));tubes.push(path.splice(0,len))}const lengths=tubes.map(t=>1+Math.floor(r()*t.length)),a=Array(n*n).fill(0);tubes.forEach((tube,k)=>tube.slice(0,lengths[k]).forEach(i=>a[i]=1));return base({n,tubes,lengths:Array(tubes.length).fill(0),...totals(a,n)})},
 act(s,a){if(a==='check'){const values=Array(s.n*s.n).fill(0);s.tubes.forEach((t,k)=>t.slice(0,s.lengths[k]).forEach(i=>values[i]=1));finish(s,marginError(values,s))}else if(a.startsWith('tube:')){const[,k,len]=a.split(':').map(Number);s.lengths[k]=len;s.edits++;s.note=`Thermometer ${String.fromCharCode(65+k)} filled through segment ${len}.`}},
 render(ui,s){const values=Array(s.n*s.n).fill(0);s.tubes.forEach((t,k)=>t.slice(0,s.lengths[k]).forEach(i=>values[i]=1));margins(ui,{...s,cells:values});ui.grid(s.n,'Thermometer prefixes');range(s.n*s.n).forEach(i=>{const k=s.tubes.findIndex(t=>t.includes(i)),step=s.tubes[k].indexOf(i)+1,b=ui.button(`tube:${k}:${step}`,`${String.fromCharCode(65+k)}${step===1?'●':step}${values[i]?' ■':' ·'}`,false,values[i]===1);b.classList.add('puzzle-cell');b.dataset.cell=i;b.setAttribute('aria-label',`Thermometer ${String.fromCharCode(65+k)}, ${step===1?'bulb':'segment '+step}, ${values[i]?'filled':'empty'}. Fill through this segment.`)});ui.group('Drain a thermometer');s.tubes.forEach((t,k)=>ui.button(`tube:${k}:0`,'Drain '+String.fromCharCode(65+k)));checkButton(ui)}
 },
 'compass-estate':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage);let hubs;for(let trial=0;;trial++){const used=new Set;hubs=[];while(used.size<n*n){const options=range(n*n).filter(i=>!used.has(i));const reach=i=>dirs.map(([,dy,dx])=>{let out=[];for(let k=1;k<n;k++){const y=Math.floor(i/n)+dy*k,x=i%n+dx*k,j=y*n+x;if(x<0||x>=n||y<0||y>=n||used.has(j))break;out.push(j)}return out});options.sort((a,b)=>sum(reach(b).map(a=>a.length))-sum(reach(a).map(a=>a.length)));const hub=options[Math.floor(r()*Math.min(3,options.length))],rays=reach(hub);used.add(hub);let count=1;rays.forEach(ray=>{const len=Math.floor(r()*(ray.length+1));ray.slice(0,len).forEach(i=>used.add(i));count+=len});hubs.push([hub,count])}if(hubs.length<=8&&hubs.filter(h=>h[1]>=3).length>=3)break;if(trial>10000)throw Error('Cross partition construction failed')}return base({n,hubs,arms:hubs.map(()=>[0,0,0,0]),selected:0})},
 act(s,a){if(a==='check'){const all=s.hubs.flatMap((_,k)=>cross(s,k));for(let k=0;k<s.hubs.length;k++)if(cross(s,k).length!==s.hubs[k][1])return finish(s,`Hub ${String.fromCharCode(65+k)} owns ${cross(s,k).length}; needs ${s.hubs[k][1]}.`);if(new Set(all).size!==all.length)return finish(s,'Two estates overlap.');finish(s,new Set(all).size!==s.n*s.n?'Some land has no hub owner.':null)}else if(a.startsWith('hub:')){s.selected=+a.split(':')[1];s.note='Selected hub '+String.fromCharCode(65+s.selected)+'.'}else if(a.startsWith('cell:')){const i=+a.split(':')[1],hk=s.hubs.findIndex(h=>h[0]===i);if(hk>=0){s.selected=hk;s.note='Selected hub '+String.fromCharCode(65+hk)+'.';return}const h=s.hubs[s.selected][0],dy=Math.floor(i/s.n)-Math.floor(h/s.n),dx=i%s.n-h%s.n;if(dx&&dy){s.note='An arm must follow the same row or column as its hub.';return}const d=dy<0?0:dx>0?1:dy>0?2:3,len=Math.abs(dx+dy),old=s.arms[s.selected][d];s.arms[s.selected][d]=len;const ray=cross(s,s.selected);if(ray.some(j=>s.hubs.some(([q],k)=>k!==s.selected&&j===q)||s.hubs.some((_,k)=>k!==s.selected&&cross(s,k).includes(j)))){s.arms[s.selected][d]=old;s.note='That arm would cross another estate. Retract the blocking arm first.'}else{s.edits++;s.note=`Hub ${String.fromCharCode(65+s.selected)} ${dirs[d][0]} arm set to ${len}.`}}else if(a.startsWith('retract:')){s.arms[s.selected][+a.split(':')[1]]=0;s.edits++;s.note='Arm retracted.'}},
 render(ui,s){ui.group('Estate hubs');s.hubs.forEach(([i,v],k)=>ui.button('hub:'+k,`${String.fromCharCode(65+k)} needs ${v}, has ${cross(s,k).length}`,false,s.selected===k));ui.grid(s.n,'Straight cross estates');range(s.n*s.n).forEach(i=>{const k=s.hubs.findIndex(h=>h[0]===i),owner=s.hubs.findIndex((_,j)=>cross(s,j).includes(i));cell(ui,s,i,k>=0?String.fromCharCode(65+k)+s.hubs[k][1]:owner>=0?String.fromCharCode(65+owner):'·',{region:owner>=0?owner:undefined,selected:k===s.selected,label:`Cell ${i+1}, ${k>=0?'hub '+String.fromCharCode(65+k)+' area '+s.hubs[k][1]:owner>=0?'estate '+String.fromCharCode(65+owner):'unowned'}`})});ui.group('Retract selected arm');dirs.forEach(([label],d)=>ui.button('retract:'+d,'Retract '+label));checkButton(ui)}
 },
 'fleet-blueprint':{
 init({stage,seed}){const r=rng(seed),n=6,fleet=stage===0?[3,2,1]:stage===1?[3,2,2,1]:[4,3,2,1];let hull;for(let t=0;;t++){hull=[];let failed=false;for(const len of fleet){const options=[];for(let i=0;i<n*n;i++)for(const delta of [1,n]){const c=range(len).map(k=>i+k*delta);if(c.some(j=>j>=n*n)||(delta===1&&Math.floor(c.at(-1)/n)!==Math.floor(i/n)))continue;if(c.some(j=>hull.includes(j)||near(j,n).some(q=>hull.includes(q))))continue;options.push(c)}if(!options.length){failed=true;break}hull.push(...shuffle(options,r)[0])}if(!failed)break;if(t>5000)throw Error('Fleet construction failed')}const a=range(n*n).map(i=>hull.includes(i)?1:0),fixed={};shuffle(hull,r).slice(0,Math.max(1,2-stage)).forEach(i=>fixed[i]=1);shuffle(range(n*n).filter(i=>!hull.includes(i)),r).slice(0,3).forEach(i=>fixed[i]=0);return base({n,fleet,fixed,...totals(a,n),cells:range(n*n).map(i=>fixed[i]??-1)})},
 act(s,a){if(a==='check'){if(s.cells.some(v=>v<0))return finish(s,'Mark every square as hull or water.');const hull=range(s.n*s.n).filter(i=>s.cells[i]===1),groups=components(hull,s.n);let error=marginError(s.cells,s);if(!error)for(const g of groups){if(!g.every(i=>i%s.n===g[0]%s.n)&&!g.every(i=>Math.floor(i/s.n)===Math.floor(g[0]/s.n))){error=`Ship at cell ${g[0]+1} is bent.`;break}if(g.some(i=>near(i,s.n).some(j=>hull.includes(j)&&!g.includes(j)))){error='Separate ships cannot touch diagonally.';break}}if(!error&&!same(groups.map(g=>g.length).sort((a,b)=>a-b),[...s.fleet].sort((a,b)=>a-b)))error='The ship lengths do not match the fleet inventory.';finish(s,error)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(s.fixed[i]===undefined)cycle(s,i)}},
 render(ui,s){ui.p('Fleet lengths: '+s.fleet.join(' · ')+' · Ships are straight and separated in all eight directions.');margins(ui,s);ui.grid(s.n,'Fleet deduction');s.cells.forEach((v,i)=>cell(ui,s,i,v<0?'·':v?'■':'≈',{fixed:s.fixed[i]!==undefined,dark:v===1,label:`Cell ${i+1}, ${s.fixed[i]!==undefined?'fixed ':''}${v<0?'unknown':v?'hull':'water'}`}));checkButton(ui)}
 },
 'four-forms':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(2,stage),count=2+Math.min(2,stage),options=shapePlacements(n);let pieces;for(let attempt=0;;attempt++){pieces=[];for(let k=0;k<count;k++){const used=pieces.flatMap(p=>p.cells),valid=options.filter(p=>!p.cells.some(i=>used.includes(i))&&(!k||p.cells.some(i=>adj(i,n).some(j=>used.includes(j))))&&!squares(n).some(q=>q.every(i=>used.includes(i)||p.cells.includes(i)))&&!pieces.some(q=>q.kind===p.kind&&p.cells.some(i=>adj(i,n).some(j=>q.cells.includes(j)))));if(!valid.length)break;pieces.push(shuffle(valid,r)[0])}if(pieces.length===count)break;if(attempt>5000)throw Error('Tetromino construction failed')}const regions=Array(n*n).fill(-1);pieces.forEach((p,k)=>p.cells.forEach(i=>regions[i]=k));while(regions.includes(-1)){const options=range(n*n).filter(i=>regions[i]<0&&adj(i,n).some(j=>regions[j]>=0)),i=shuffle(options,r)[0];regions[i]=regions[shuffle(adj(i,n).filter(j=>regions[j]>=0),r)[0]]}return base({n,count,regions,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check'){const selected=range(s.n*s.n).filter(i=>s.cells[i]===1),kinds=[];for(let k=0;k<s.count;k++){const cells=selected.filter(i=>s.regions[i]===k),kind=tetromino(cells,s.n);if(!kindLabels[kind])return finish(s,`Region ${String.fromCharCode(65+k)} needs exactly one I, L, T or S tetromino.`);kinds.push(kind)}if(!connected(selected,s.n))return finish(s,'Selected tetrominoes must join into one connected group.');if(squares(s.n).some(q=>q.every(i=>selected.includes(i))))return finish(s,'A selected 2×2 block is forbidden.');if(selected.some(i=>adj(i,s.n).some(j=>selected.includes(j)&&s.regions[i]!==s.regions[j]&&kinds[s.regions[i]]===kinds[s.regions[j]])))return finish(s,'Touching regions cannot choose the same tetromino shape.');finish(s,null)}else if(a.startsWith('cell:'))cycle(s,+a.split(':')[1])},
 render(ui,s){ui.p('Choose four squares per region: I, L, T or S, including rotations/reflections. Touching pieces need different shapes.');ui.grid(s.n,'Tetromino selection regions');s.cells.forEach((v,i)=>cell(ui,s,i,String.fromCharCode(65+s.regions[i])+(v===1?'■':v===0?'×':'·'),{region:s.regions[i],selected:v===1,label:`Cell ${i+1}, region ${String.fromCharCode(65+s.regions[i])}, ${v===1?'selected':v===0?'excluded':'undecided'}`}));ui.table(['Region','Selected','Shape'],range(s.count).map(k=>{const c=range(s.n*s.n).filter(i=>s.regions[i]===k&&s.cells[i]===1);return[String.fromCharCode(65+k),c.length,kindLabels[tetromino(c,s.n)]||'incomplete']}));checkButton(ui)}
 },
 'domino-register':{
 init({stage,seed}){const r=rng(seed),max=stage?3:2,n=stage?5:4,h=stage?4:3,pairs=[];for(let a=0;a<=max;a++)for(let b=a;b<=max;b++)pairs.push([a,b]);let slots;for(let attempt=0;;attempt++){const left=new Set(range(n*h));slots=[];while(left.size){const i=[...left][0],options=shuffle(adj(i,n,h).filter(j=>left.has(j)),r);if(!options.length)break;const j=options[0];left.delete(i);left.delete(j);slots.push([i,j])}if(!left.size)break;if(attempt>5000)throw Error('Domino tiling construction failed')}const values=Array(n*h);shuffle(pairs,r).forEach((p,k)=>{p=r()<.5?p:[...p].reverse();values[slots[k][0]]=p[0];values[slots[k][1]]=p[1]});return base({n,h,max,pairs,values,joined:Array(n*h).fill(-1),selected:-1})},
 act(s,a){if(a==='check'){if(s.joined.some(j=>j<0))return finish(s,'Every numbered cell needs one domino partner.');const used=range(s.joined.length).filter(i=>s.joined[i]>i).map(i=>[s.values[i],s.values[s.joined[i]]].sort((a,b)=>a-b).join('-'));const duplicate=used.find((v,i)=>used.indexOf(v)!==i);finish(s,duplicate?`Domino ${duplicate} is used twice.`:null)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(s.joined[i]>=0){const j=s.joined[i];s.joined[i]=s.joined[j]=-1;s.selected=-1;s.edits++;s.note='Domino removed.'}else if(s.selected<0){s.selected=i;s.note=`Cell ${i+1} selected; choose an edge-neighbor.`}else if(i===s.selected){s.selected=-1;s.note='Selection canceled.'}else if(!adj(s.selected,s.n,s.h).includes(i)){s.note='Domino halves must share an edge.'}else{const j=s.selected;s.joined[i]=j;s.joined[j]=i;s.selected=-1;s.edits++;s.note=`Joined ${s.values[i]}–${s.values[j]}.`}}},
 render(ui,s){ui.p('Inventory: '+s.pairs.map(p=>p.join('–')).join(' · '));ui.grid(s.n,'Domino pairing board');s.values.forEach((v,i)=>cell(ui,s,i,String(v)+(s.joined[i]>=0?(s.joined[i]===i-1?'←':s.joined[i]===i+1?'→':s.joined[i]<i?'↑':'↓'):'·'),{selected:i===s.selected||s.joined[i]>=0,label:`Cell ${i+1}, number ${v}, ${s.joined[i]>=0?'paired with cell '+(s.joined[i]+1):'unpaired'}`}));checkButton(ui)}
 }
};
