import {range,sum,same,rng,shuffle,adj,near,connected,components,squares,base,finish,cycle,cell,markedGrid,checkButton,sight,ring,ringRuns} from './core.mjs';
const incomplete=s=>s.cells.some(v=>v<0)?'Assign every editable square first.':null;
const shade=s=>range(s.cells.length).filter(i=>s.cells[i]===1);
export const shading={
 'lamp-ward':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(2,stage);let walls,lamps;
 for(let attempt=0;;attempt++){walls=shuffle(range(n*n),r).slice(0,Math.floor(n*n*(.18+r()*.1)));lamps=[];for(const i of shuffle(range(n*n).filter(i=>!walls.includes(i)),r))if(!sight(i,n,walls).some(j=>lamps.includes(j)))lamps.push(i);if(lamps.length>=3&&walls.length>=3)break;if(attempt>200)throw Error('Lamp construction failed')}
 const clues=Object.fromEntries(walls.map(i=>[i,adj(i,n).filter(j=>lamps.includes(j)).length]));return base({n,walls,clues,cells:Array(n*n).fill(0)})},
 act(s,a){if(a==='check'){const lamps=shade(s),lit=new Set(lamps.flatMap(i=>sight(i,s.n,s.walls)));let error=lamps.find(i=>sight(i,s.n,s.walls).some(j=>j!==i&&lamps.includes(j)));if(error!==undefined)return finish(s,`Lamp at cell ${error+1} sees another lamp.`);const wall=s.walls.find(i=>adj(i,s.n).filter(j=>lamps.includes(j)).length!==s.clues[i]);if(wall!==undefined)return finish(s,`Wall at cell ${wall+1} needs exactly ${s.clues[wall]} adjacent lamps.`);const dark=range(s.n*s.n).find(i=>!s.walls.includes(i)&&!lit.has(i));finish(s,dark!==undefined?`Cell ${dark+1} is still unlit.`:null)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(!s.walls.includes(i)){s.cells[i]=(s.cells[i]+1)%3;s.edits++;s.note=s.cells[i]===1?'Lamp placed. Its rays stop at walls.':s.cells[i]===2?'Square excluded from lamps.':'Square cleared.'}}},
 render(ui,s){const lamps=shade(s),lit=new Set(lamps.flatMap(i=>sight(i,s.n,s.walls)));ui.p(`Lamps ${lamps.length} · Lit ${range(s.n*s.n).filter(i=>!s.walls.includes(i)&&lit.has(i)).length} / ${s.n*s.n-s.walls.length}`);ui.grid(s.n,'Lamp district');range(s.n*s.n).forEach(i=>cell(ui,s,i,s.walls.includes(i)?s.clues[i]:s.cells[i]===1?'☀':s.cells[i]===2?'×':lit.has(i)?'◦':'·',{fixed:s.walls.includes(i),dark:s.walls.includes(i),label:`Cell ${i+1}, ${s.walls.includes(i)?'wall, adjacent lamps required '+s.clues[i]:s.cells[i]===1?'lamp':lit.has(i)?'lit square':'unlit square'}`}));checkButton(ui)}
 },
 'star-charter':{
 init({stage,seed}){const r=rng(seed),n=6+Math.min(1,stage);let p;for(let t=0;;t++){p=shuffle(range(n),r);if(p.every((c,i)=>!i||Math.abs(c-p[i-1])>1))break;if(t>10000)throw Error('Star permutation failed')}
 const regions=Array(n*n).fill(-1);p.forEach((c,y)=>regions[y*n+c]=y);while(regions.includes(-1)){const frontier=range(n*n).filter(i=>regions[i]<0&&adj(i,n).some(j=>regions[j]>=0)),i=shuffle(frontier,r)[0];regions[i]=regions[shuffle(adj(i,n).filter(j=>regions[j]>=0),r)[0]]}return base({n,regions,cells:Array(n*n).fill(-1)})},
 act(s,a){if(a==='check'){const stars=shade(s);let error=null;for(let k=0;k<s.n&&!error;k++){if(stars.filter(i=>Math.floor(i/s.n)===k).length!==1)error=`Row ${k+1} needs exactly one star.`;else if(stars.filter(i=>i%s.n===k).length!==1)error=`Column ${k+1} needs exactly one star.`;else if(stars.filter(i=>s.regions[i]===k).length!==1)error=`Region ${String.fromCharCode(65+k)} needs exactly one star.`}const touch=stars.find(i=>near(i,s.n).some(j=>stars.includes(j)));finish(s,error||(touch!==undefined?`Star ${touch+1} touches another star.`:null))}else if(a.startsWith('cell:'))cycle(s,+a.split(':')[1])},
 render(ui,s){ui.p('One star per row, column and lettered region. Stars cannot touch, even diagonally.');ui.grid(s.n,'Star regions');s.cells.forEach((v,i)=>cell(ui,s,i,String.fromCharCode(65+s.regions[i])+(v===1?' ★':v===0?' ×':' ·'),{region:s.regions[i],selected:v===1,label:`Row ${Math.floor(i/s.n)+1} column ${i%s.n+1}, region ${String.fromCharCode(65+s.regions[i])}, ${v===1?'star':v===0?'excluded':'unknown'}`}));checkButton(ui)}
 },
 'region-census':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage);let labels,givens;for(let tries=0;;tries++){let groups=[],left=new Set(range(n*n));while(left.size){const first=shuffle([...left],r)[0],g=[first],want=2+Math.floor(r()*4);left.delete(first);while(g.length<want){const options=[...new Set(g.flatMap(i=>adj(i,n)).filter(i=>left.has(i)))];if(!options.length)break;const i=shuffle(options,r)[0];g.push(i);left.delete(i)}groups.push(g)}let changed=true;while(changed){changed=false;outer:for(let a=0;a<groups.length;a++)for(let b=a+1;b<groups.length;b++)if(groups[a].length===groups[b].length&&groups[a].some(i=>adj(i,n).some(j=>groups[b].includes(j)))){groups[a].push(...groups[b]);groups.splice(b,1);changed=true;break outer}}
 if(groups.length>=4&&groups.every(g=>g.length<=6)){labels=Array(n*n);givens={};groups.forEach(g=>{g.forEach(i=>labels[i]=g.length);givens[shuffle(g,r)[0]]=g.length;if(g.length>=5&&stage===0)givens[shuffle(g,r)[0]]=g.length});break}if(tries>5000)throw Error('Region construction failed')}
 return base({n,givens,max:6,selected:1,cells:range(n*n).map(i=>givens[i]||0)})},
 act(s,a){if(a==='check'){if(s.cells.some(v=>!v))return finish(s,'Every cell needs a size label.');for(let v=1;v<=s.max;v++)for(const g of components(range(s.n*s.n).filter(i=>s.cells[i]===v),s.n))if(g.length!==v)return finish(s,`The region containing cell ${g[0]+1} is labeled ${v} but has ${g.length} cells.`);finish(s,null)}else if(a.startsWith('size:')){s.selected=+a.split(':')[1];s.note=`Size ${s.selected} selected.`}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(!s.givens[i]){s.cells[i]=s.selected;s.edits++;s.note=`Cell ${i+1} labeled ${s.selected}.`}}},
 render(ui,s){ui.group('Size labels');range(7).forEach(v=>ui.button('size:'+v,v?String(v):'Erase',false,s.selected===v));ui.grid(s.n,'Connected size regions');s.cells.forEach((v,i)=>cell(ui,s,i,v||'·',{fixed:!!s.givens[i],region:v||undefined,label:`Cell ${i+1}, ${s.givens[i]?'fixed ':''}${v||'empty'}`}));checkButton(ui)}
 },
 'mosaic-ring':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage),dark=[Math.floor(r()*n*n)];for(let t=0;t<300&&dark.length<Math.floor(n*n*.43);t++){const options=[...new Set(dark.flatMap(i=>adj(i,n)).filter(i=>!dark.includes(i)&&!squares(n).some(q=>q.includes(i)&&q.every(j=>j===i||dark.includes(j)))))];if(!options.length)break;dark.push(shuffle(options,r)[0])}const light=range(n*n).filter(i=>!dark.includes(i)),chosen=shuffle(light,r).slice(0,Math.max(4,Math.ceil(light.length*.7))),clues=Object.fromEntries(chosen.map(i=>[i,ringRuns(ring(i,n).map(j=>dark.includes(j)?1:0))]));return base({n,clues,cells:range(n*n).map(i=>clues[i]?0:-1)})},
 act(s,a){if(a==='check'){let error=incomplete(s);const dark=shade(s);if(!error)for(const[i,clue]of Object.entries(s.clues))if(!same(ringRuns(ring(+i,s.n).map(j=>dark.includes(j)?1:0)),clue)){error=`Circular runs around clue cell ${+i+1} do not match ${clue.join('·')}.`;break}if(!error&&!connected(dark,s.n))error='Dark squares must form one connected mosaic.';if(!error&&squares(s.n).some(q=>q.every(i=>dark.includes(i))))error='A fully dark 2×2 square is forbidden.';finish(s,error)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(!s.clues[i])cycle(s,i)}},
 render(ui,s){ui.p('Ring clues list lengths of dark runs among the eight surrounding squares, in any cyclic order.');ui.grid(s.n,'Circular run mosaic');s.cells.forEach((v,i)=>cell(ui,s,i,s.clues[i]?s.clues[i].join('·'):v<0?'·':v?'■':'×',{fixed:!!s.clues[i],dark:v===1,label:`Cell ${i+1}, ${s.clues[i]?'ring clue '+s.clues[i].join(', '):v<0?'unknown':v?'dark':'light'}`}));checkButton(ui)}
 },
 'sight-garden':{
 init({stage,seed}){const r=rng(seed),n=4+Math.min(1,stage);let dark=[];for(const i of shuffle(range(n*n),r))if(dark.length<3+Math.min(3,stage)&&!adj(i,n).some(j=>dark.includes(j))&&connected(range(n*n).filter(j=>j!==i&&!dark.includes(j)),n))dark.push(i);const white=range(n*n).filter(i=>!dark.includes(i)),chosen=shuffle(white,r).slice(0,Math.max(4,Math.ceil(white.length*.35))),clues=Object.fromEntries(chosen.map(i=>[i,sight(i,n,dark).length]));return base({n,clues,cells:range(n*n).map(i=>clues[i]?0:-1)})},
 act(s,a){if(a==='check'){let error=incomplete(s);const dark=shade(s),white=range(s.cells.length).filter(i=>!dark.includes(i));if(!error)for(const[i,want]of Object.entries(s.clues))if(sight(+i,s.n,dark).length!==want){error=`Number ${want} at cell ${+i+1} sees ${sight(+i,s.n,dark).length} white squares.`;break}if(!error&&dark.some(i=>adj(i,s.n).some(j=>dark.includes(j))))error='Shaded squares cannot share an edge.';if(!error&&!connected(white,s.n))error='All white squares must stay connected.';finish(s,error)}else if(a.startsWith('cell:')){const i=+a.split(':')[1];if(!s.clues[i])cycle(s,i)}},
 render(ui,s){ui.p('Count the numbered square itself and every white square it can see in four straight directions. Shade stops sight.');markedGrid(ui,s,s.clues);checkButton(ui)}
 }
};
